### ISSUE TITLE
UnknownServerException: Session [(null externalkey)] not available and is not among the last 1000 terminated sessions. Active sessions are[ext. key 0e526d85-b3e9-4395-8961-02cbe5962dde]

### ISSUE THREAD

**Issue by liyuanzao** [SeleniumHQ/docker-selenium#651] opened 2018-01-13 05:47 UTC
## Meta -
Image(s):  
selenium/hub:latest
selenium/node-chrome-debug:latest
selenium/node-firefox-debug:latest
selenium/node-firefox-debug:3.7.1

Docker-Selenium Image Version(s):  
selenium/hub:latest
selenium/node-chrome-debug:latest
selenium/node-firefox-debug:latest
selenium/node-firefox-debug:3.7.1

Docker Version:  
15.05.0-0367

OS: 
LINUX

## Expected Behavior -
all should works with my simple test script.

## Actual Behavior -
chrome node works fine
firefox node not work, and error info is 

UnknownServerException: Session [(null externalkey)] not available and is not among the last 1000 terminated sessions.
Active sessions are[ext. key 0e526d85-b3e9-4395-8961-02cbe5962dde]

======

Here's my simple test script.

```
<?php

namespace Tests\Feature;

use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;
use RemoteWebDriver;

class UserTest extends TestCase
{

    /**
     * @var \RemoteWebDriver
     */
    
    protected $webDriver;

	public function setUp()
    {
        $capabilities = array(\WebDriverCapabilityType::BROWSER_NAME => 'firefox');
        $this->webDriver = RemoteWebDriver::create('http://192.168.2.165:4444/wd/hub', $capabilities, 50000, 50000);
    }

    protected $url = 'https://whoer.net';

    public function testGitHubHome()
    {
        $this->webDriver->get($this->url);
        // checking that page title contains word 'GitHub'
        $this->assertContains('IP', $this->webDriver->getTitle());
    }    
    
}

```

**Comment by diemol** [comment] 2018-01-13 11:38
Hi @liyuanzao,

Do you know if this also happens with the latest images (3.8.1-erbium)? 
And does this happen always or does one need to execute the script several times?

**Comment by liyuanzao** [comment] 2018-01-13 15:03
Hi @diemol 
I tested a whole day today, this issues happened all version I tested in Firefox Node ( both debug and non-debug, 3.7.1 and 3.8.1 version), and I tried on my Synology NAS system (Linux) and Centos 7.

it always happen, but only for firefox which I tested above, I haven't tested more version so far. 

if you need any test about it, feel free to let me know

**Comment by xMutaGenx** [comment] 2018-01-16 14:20
I was also able to replicate this issue with the following `docker-compose.yml`
```
version : '3'
services:
    selenium-hub:
      image: selenium/hub:3.8.1-erbium
      container_name: local-selenium-hub
      ports:
        - '4444:4444'
      environment:
        - SE_OPTS=-enablePassThrough false
    firefox:
      image: selenium/node-firefox:3.8.1-erbium
      environment:
        - HUB_PORT_4444_TCP_ADDR=local-selenium-hub
        - HUB_PORT_4444_TCP_PORT=4444
      depends_on:
        - selenium-hub
```

FF: v57.0.4
Gecko: v0.19.1.20171103

*Note*: SE_OPTS are there for our project, as Facebook Webdriver doesn't have support for W3C

Interestingly this doesn't seem to be failing when running the standalone version installed via `brew install selenium-server-standalone` (which runs Selenium v3.8.1)

**Comment by diemol** [comment] 2018-01-21 14:18
Hi @liyuanzao and @xMutaGenx,

I tried to reproduce the issue by creating a script, see https://github.com/diemol/docker-selenium-issues/tree/master/issue-651 (using docker since I don't want to install php on my laptop).

and I reached the point where I get an error that says:
```
Fatal error: Class 'Tests\TestCase' not found in /wd/src/SimpleTest.php on line 10
```

I have no clue on how to run tests with php, could you please help me out so I can reproduce the issue and see what's going on?

**Comment by diemol** [comment] 2018-01-22 07:18
As an additional comment, I was trying something with a different Framework (Serenity), and I got the error of `UnknownServerException: Session [(null externalkey)] not available and is not among the last 1000 terminated sessions.` when I used Firefox, with Chrome it worked well.

Then I tried with the Java and JavaScript bindings, and things worked out with both browsers.

Which makes me think, that the issue might be with the PHP bindings. 
@liyuanzao @xMutaGenx did you also post the issue in the PHP bindings repo?

**Comment by xMutaGenx** [comment] 2018-01-24 17:22
Hey @diemol it does seem like it's a problem with PHP bindings. The easiest way to replicate this is to start up your selenium server, and clone out facebook/php-webdriver community repo then just:

`composer install`
`php -f example.php`

I will raise an issue there as well when I find the time.

Thank you.

**Comment by diemol** [comment] 2018-01-24 21:53
Yeah @xMutaGenx, that is what thought because I was not able to reproduce with any of the other bindings. 

Since we see that it is an issue with the PHP bindings, I think we can close the issue here, right?

**Comment by diemol** [comment] 2018-01-24 22:37
Someone helped us an created an issue already https://github.com/facebook/php-webdriver/issues/523

**Comment by diemol** [comment] 2018-01-25 07:58
Hi @liyuanzao, @xMutaGenx 

Seems it gets solved by passing the flag `-enablePassThrough false` to hub and nodes. Check
https://github.com/facebook/php-webdriver/issues/523#issuecomment-360299646 

So it was identified that it is an issue with the bindings, so I'll close this one.

**Closed by diemol** 2018-01-25 07:58 UTC
Labels: R-awaiting-answer

**Comment by barancev** [comment] 2018-01-25 08:07
Note that -enablePassThrough option will be removed in selenium server 3.9, so the binding should be fixed to be able to work with the most revent server versions.

**Comment by diemol** [comment] 2018-01-25 08:19
Good point, I'll link your comment to the binding's repo @barancev

**Comment by xMutaGenx** [comment] 2018-01-29 17:37
@diemol I believe -enablePassThrough wasn't the actual issue, as seen I've used that in my examples. I've dug deeper into the php web-driver and I believe I found the culprit https://github.com/facebook/php-webdriver/issues/525
