### ISSUE TITLE
Hi , This is with reference to the issue 

### ISSUE THREAD

**Issue by arijitb1710** [SeleniumHQ/docker-selenium#848] opened 2018-11-23 15:47 UTC
Sorry for late reply. Was busy with work.
Please find the link of the GIT repo. Refer the README for running the test cases.
https://github.com/arijitb1710/nightwatch_automation

In the repo , there is a nightwatch.json file. This file file has a profile created as firefox which is run.
The exposed port of selenium hub is 4446 and the ip is that of the selenium hub

_Originally posted by @arijitb1710 in https://github.com/SeleniumHQ/docker-selenium/issue_comments#issuecomment-441271937_

**Comment by diemol** [comment] 2018-11-23 15:53
Duplicate of #839

**Closed by diemol** 2018-11-23 15:53 UTC
