### ISSUE TITLE
Unable to pass `-firefoxProfileTemplate` via SE_OPTS to standalone-selenium-firefox

### ISSUE THREAD

**Issue by dmitrygusev** [SeleniumHQ/docker-selenium#489] opened 2017-05-17 20:35 UTC
## Meta -
Image(s): 
standalone-firefox-debug

Docker-Selenium Image Version(s):  
2.53.1-beryllium

OS: 
macOS Sierra 10.12.4

## Docker compose configuration -
```yml
version: '2.1'
services:

    selenium:
      image: selenium/standalone-firefox-debug:2.53.1-beryllium
      ports:
        - 4444 # Selenium server
#        - 5900 # VNC for `standalone-firefox-debug`
      volumes:
        # Firefox profile templates dir for self-signed certificates
        - ${SELENIUM_DATA}:/data:ro
      environment:
        # https://github.com/SeleniumHQ/docker-selenium/issues/227
        no_proxy: localhost
        # There's a bug that prevents passing these options in debug mode,
        # with `standalone-firefox-debug` image
        SE_OPTS: "-firefoxProfileTemplate /data/${FF_PROFILE_TEMPLATE_DIR}"
```

## Expected Behavior -
`SE_OPTS` environment variable acknowledged and consumed by selenium.

## Actual Behavior -
Container fails to start with the following error in docker logs:
```
$ docker logs -f selenium_1
appending selenium options: -firefoxProfileTemplate /data/build/test/conf/ff_profile_template_filtered
-bash: /data/build/test/conf/ff_profile_template_filtered: Is a directory
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
```

The same configuration works as expected with `standalone-firefox`.

I suspect the error is somewhere in the `entry_point.sh` where some pre-processing of environment variables is happening: https://github.com/SeleniumHQ/docker-selenium/blob/2.53.1-beryllium/StandaloneDebug/entry_point.sh#L21-L29

**Comment by ddavison** [comment] 2017-05-17 22:53
have you tried with the latest versions?  since you are using version 2 of selenium, version 3 should be a pretty easy migration (shouldn't have to modify tests at all).

this waiting xvfb... was fixed since 3.1 i believe.

**Comment by dmitrygusev** [comment] 2017-05-18 10:31
Here's the output from version 3.4.0-bismuth:
```
appending selenium options: -firefoxProfileTemplate /data/build/test/conf/ff_profile_template_filtered
/opt/bin/entry_point.sh: line 27: : command not found
Waiting xvfb...
Exception in thread "main" com.beust.jcommander.ParameterException: Unknown option: -firefoxProfileTemplate
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:742)
	at com.beust.jcommander.JCommander.parse(JCommander.java:282)
	at com.beust.jcommander.JCommander.parse(JCommander.java:265)
	at com.beust.jcommander.JCommander.<init>(JCommander.java:210)
	at org.openqa.grid.selenium.GridLauncherV3$1.setConfiguration(GridLauncherV3.java:227)
	at org.openqa.grid.selenium.GridLauncherV3.buildLauncher(GridLauncherV3.java:155)
	at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:75)
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
```

As I understand it isn't possible to use the same `-firefoxProfileTemplate` flag for custom SSL certificates.

My test suite uses Selenium RC that's been deprecated if I understand this right, and in order to use Selenium 3 I need to migrate everything to WebDriver, right? I'd like to avoid that at the moment, if possible.

**Comment by ddavison** [comment] 2017-05-19 17:45
that's a true statement, yes.  RC has been deprecated and is no longer supported by the team.  i've never used the `-firefoxProfileTemplate` option personally.

If this was in Selenium 2 and now is not in Selenium 3, it must have been deprecated as well, or favored as another option.  perhaps since you have a general idea of what is going on, feel free to open a PR

**Comment by dmitrygusev** [comment] 2017-05-21 20:11
You can see the linked commit above that fixes the issue.

Problem was in a space contained in the value of `SE_OPTS` and it wasn't properly quoted when the script tried to compose its definition, i.e.:

```
SE_OPTS=-firefoxProfileTemplate /data/build/test/conf/ff_profile_template_filtered
```

That was already fixed in the master branch so I took the quote-fix from there, but it has another issue on [this line](https://github.com/SeleniumHQ/docker-selenium/blob/fe860cbcbf627a2e95d88bf073fdae4acd73888c/StandaloneDebug/entry_point.sh#L26):

    "$(for E in $(grep -vxFf asseluser asroot); do echo $E="'${!E}'" >> ~seluser/selenv; done)" \

it fails with this error:

    /opt/bin/entry_point.sh: line 26: : command not found


As I understand the `for` loop shouldn't be enclosed by the `$()` operator, as it doesn't return anything hence nothing to evaluate.

@ddavison not sure where should I target the fix? Is it possible to get a release with a fix based on the `2.53.1-beryllium` branch?

**Comment by diemol** [comment] 2017-05-28 16:27
@dmitrygusev, the error you mention:
`/opt/bin/entry_point.sh: line 26: : command not found`
should be gone when #477 gets merged.

**Comment by diemol** [comment] 2017-06-25 16:43
@dmitrygusev, #477 was merged and released some days ago. Could you please try again?

**Comment by diemol** [comment] 2017-09-26 21:22
Closing as we didn't get feedback. Feel free to reopen if the issue is still present.

**Closed by diemol** 2017-09-26 21:22 UTC
Labels: R-awaiting-answer
