### ISSUE TITLE
Connection selenium node

### ISSUE THREAD

**Issue by idan72** [SeleniumHQ/docker-selenium#607] opened 2017-11-07 12:57 UTC
Hi,

I have 2 EC2 machines called Server,Nodes.
To connect to Server (SSH) I connect to ServerIp.
To connect to Nodes I connect to NodesIp.

I installed on one selenium hub docker and run the following command : 
 docker run -d -p 4444:4444 --name selenium-hub selenium/hub

I see in the logs :   
 Nodes should register to http://172.17.0.2:4444/grid/register/

On the second machine I installed selenium chrome node docker  and try to run:
 docker run -d -e HUB_PORT_4444_TCP_ADDR=? -e HUB_PORT_4444_TCP_PORT=44444

What address should be put there ? is there something else to configure to make it works ?

Thanks

**Comment by diemol** [comment] 2017-11-07 17:27
Hi @idan72,

The short answer is; you would need to use the IP address of the instance that contains the hub here `HUB_PORT_4444_TCP_ADDR`, and also SE_OPTS like this when starting the node: 
```
SE_OPTS="-host yourNodeIP -port yourNodePort"
```
Check the [docs](https://github.com/SeleniumHQ/docker-selenium#se_opts-selenium-configuration-options)

Long answer; when you start the hub, then you need to create the node and give the IP address of the hub, (so you are telling the node where to find the hub), and in the case of your network, you need to tell the hub where to reach the node (this is done with the SE_OPTS). 
This is because the node will be able to reach the hub, but the hub also needs to reach the node to check its health status.
Something like:
```
# HUB
    docker run -d -p 4444:4444 \
        -e HUB_PORT_4444_TCP_ADDR=<ip_of_your_hub_instance> \
        -e HUB_PORT_4444_TCP_PORT=<opened_port_of_your_hub_instance> \ 
        --name selenium-hub selenium/hub:3.7.1-argon
# NODE
    docker run -d -p 4444:4444 \
        -e HUB_PORT_4444_TCP_ADDR=<ip_of_your_hub_instance> \
        -e HUB_PORT_4444_TCP_PORT=<opened_port_of_your_hub_instance> \ 
        -e SE_OPTS="-host <your_node_instance_ip> -port <your_node_instance_open_port" \
        --name selenium-chrome selenium/node-chrome:3.7.1-argon
```

**Comment by diemol** [comment] 2017-11-20 19:03
Closing this one as this was more a question than an issue. Feel free to reopen if any issue shows up.

**Closed by diemol** 2017-11-20 19:03 UTC
Labels: R-awaiting-answer

**Comment by jose-83** [comment] 2019-07-18 09:50
@diemol HI and sorry for tagging you.
I have the same issue as running Selenium-Hub on one EC2 instance and connecting nodes to this hub from other EC2 instances. <br>
I tried what you suggested several times with 3.141.59-selenium(and -oxygen) versionand I get the error: **ERROR [BaseServer.start] - Port 5555 is busy, please choose a free port and specify it using -port option**<br> I also tried to change the port number in the range of 5555-5559 and still I get the same error. Any idea how can I fix this?

Full log message when I try to connect the node and run this lines of code from node EC2:<br>
`2019-07-18 09:41:36,999 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
2019-07-18 09:41:37,002 INFO supervisord started with pid 7
2019-07-18 09:41:38,004 INFO spawned: 'xvfb' with pid 10
2019-07-18 09:41:38,006 INFO spawned: 'selenium-node' with pid 11
appending selenium options: -host 18.185.96.139 -port 5555
2019-07-18 09:41:38,274 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2019-07-18 09:41:38,275 INFO success: selenium-node entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
09:41:38.987 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
09:41:39.245 INFO [GridLauncherV3.lambda$buildLaunchers$7] - Launching a Selenium Grid node on port 5555
2019-07-18 09:41:39.439:INFO::main: Logging initialized @1124ms to org.seleniumhq.jetty9.util.log.StdErrLog
09:41:39.868 INFO [WebDriverServlet.<init>] - Initialising WebDriverServlet
09:41:40.002 ERROR [BaseServer.start] - Port 5555 is busy, please choose a free port and specify it using -port option
Exception in thread "main" java.lang.RuntimeException: java.net.BindException: Cannot assign requested address
	at org.openqa.selenium.grid.server.BaseServer.start(BaseServer.java:221)
	at org.openqa.selenium.remote.server.SeleniumServer.boot(SeleniumServer.java:131)
	at org.openqa.grid.internal.utils.SelfRegisteringRemote.startRemoteServer(SelfRegisteringRemote.java:119)
	at org.openqa.grid.selenium.GridLauncherV3.lambda$buildLaunchers$7(GridLauncherV3.java:284)
	at org.openqa.grid.selenium.GridLauncherV3.lambda$launch$0(GridLauncherV3.java:86)
	at java.util.Optional.map(Optional.java:215)
	at org.openqa.grid.selenium.GridLauncherV3.launch(GridLauncherV3.java:86)
	at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:70)
Caused by: java.net.BindException: Cannot assign requested address
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.seleniumhq.jetty9.server.ServerConnector.openAcceptChannel(ServerConnector.java:339)
	at org.seleniumhq.jetty9.server.ServerConnector.open(ServerConnector.java:307)
	at org.seleniumhq.jetty9.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at org.seleniumhq.jetty9.server.ServerConnector.doStart(ServerConnector.java:235)
	at org.seleniumhq.jetty9.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.seleniumhq.jetty9.server.Server.doStart(Server.java:395)
	at org.seleniumhq.jetty9.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.openqa.selenium.grid.server.BaseServer.start(BaseServer.java:202)
	... 7 more
`
