### ISSUE TITLE
quit() hangs while Firefox is at 100% CPU

### ISSUE THREAD

**Issue by tuxayo** [SeleniumHQ/docker-selenium#1146] opened 2020-11-24 15:07 UTC
## 💥 Regression Report

quit() can hang for around 60 seconds while Firefox is at 100% CPU before being closed.

## Working/non-working versions

Working: v2.53.1 (selenium/standalone-firefox:2.53.1-americium)
Non-working version: 3.141.59 (selenium/standalone-firefox:3)
In beetween: I could do more testing if requested

## To Reproduce

Run the script several times manually or automatically. The first times it quits in less than a second. But on a later run is take around 1min.
top in the container shows Firefox using 100% of a CPU core

## Expected behavior
With v2.53.1, it can be ran more than 50 times without issue.

## Test script reproducing this issue (when applicable)

```
#!/usr/bin/perl
use Modern::Perl;
eval { require Selenium::Remote::Driver; };

my $driver = Selenium::Remote::Driver->new(
    remote_server_addr => "selenium",
    port               => 4444,
);
$driver->get("https://example.org");
$driver->find_element("//*[contains(text(), 'Example Domain')]");
print "before quit\n";
$driver->quit();
print "end quit\n";
```

## Environment

OS: Linux
Docker-Selenium image version: selenium/standalone-firefox:3 782406a6c93f

Docker version: 19.03.13-ce
Docker-Compose version (if applicable): 1.27.4

### good run
```
selenium_1   | 14:29:52.014 INFO [ActiveSessionFactory.apply] - Capabilities are: {
selenium_1   |   "acceptSslCerts": true,
selenium_1   |   "browserName": "firefox",
selenium_1   |   "javascriptEnabled": true,
selenium_1   |   "version": ""
selenium_1   | }
selenium_1   | 14:29:52.016 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
selenium_1   | 1606228192066	geckodriver	INFO	Listening on 127.0.0.1:9987
selenium_1   | 1606228192415	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "--marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofileJ9atat"
selenium_1   | console.warn: SearchSettings: "get: No settings file exists, new profile?" (new Error("", "(unknown module)"))
selenium_1   | 1606228194730	Marionette	INFO	Listening on port 46599
selenium_1   | 14:29:54.913 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
selenium_1   | 14:29:54.987 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 370562e6-8c8a-456b-b75e-c2384b2df5b8 (org.openqa.selenium.firefox.GeckoDriverService)
selenium_1   | 1606228196117	Marionette	INFO	Stopped listening on port 46599
selenium_1   | console.warn: services.settings: main/partitioning-exempt-urls sync interrupted by shutdown
selenium_1   | console.error: services.settings: 
selenium_1   |   main/cfr-fxa Signature failed  TypeError: NetworkError when attempting to fetch resource.
selenium_1   | 14:29:56.929 INFO [ActiveSessions$1.onStop] - Removing session 370562e6-8c8a-456b-b75e-c2384b2df5b8 (org.openqa.selenium.firefox.GeckoDriverService)
```
### bad run
```
selenium_1   | 14:51:27.319 INFO [ActiveSessionFactory.apply] - Capabilities are: {
selenium_1   |   "acceptSslCerts": true,
selenium_1   |   "browserName": "firefox",
selenium_1   |   "javascriptEnabled": true,
selenium_1   |   "version": ""
selenium_1   | }
selenium_1   | 14:51:27.319 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
selenium_1   | 1606229487323	geckodriver	INFO	Listening on 127.0.0.1:5376
selenium_1   | 1606229487337	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "--marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofileqGTL3Q"
selenium_1   | console.warn: SearchSettings: "get: No settings file exists, new profile?" (new Error("", "(unknown module)"))
selenium_1   | 1606229489470	Marionette	INFO	Listening on port 44549
selenium_1   | 14:51:29.614 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
selenium_1   | 14:51:29.617 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 67372bfa-d9d3-4a5a-bd10-c9f1cd9eabba (org.openqa.selenium.firefox.GeckoDriverService)
selenium_1   | 1606229490318	Marionette	INFO	Stopped listening on port 44549
selenium_1   | console.warn: services.settings: main/message-groups sync interrupted by shutdown
selenium_1   | console.warn: services.settings: main/partitioning-exempt-urls sync interrupted by shutdown
selenium_1   | console.warn: services.settings: main/cfr-fxa sync interrupted by shutdown
selenium_1   | console.warn: SearchService: "_init: abandoning init due to shutting down"
selenium_1   | JavaScript error: , line 0: uncaught exception: 2147500036
selenium_1   | JavaScript error: , line 0: uncaught exception: 2147500036
selenium_1   | JavaScript error: , line 0: uncaught exception: 2147500036
selenium_1   | JavaScript error: , line 0: uncaught exception: 2147500036
selenium_1   | JavaScript error: , line 0: uncaught exception: 2147500036
selenium_1   | JavaScript error: , line 0: uncaught exception: 2147500036
selenium_1   | JavaScript error: , line 0: uncaught exception: 2147500036
selenium_1   | JavaScript error: , line 0: uncaught exception: 2147500036
selenium_1   | JavaScript error: , line 0: uncaught exception: 2147500036
selenium_1   | JavaScript error: , line 0: uncaught exception: 2147500036
selenium_1   | JavaScript error: , line 0: uncaught exception: 2147500036
selenium_1   | console.warn: services.settings: main/cfr sync interrupted by shutdown
selenium_1   | console.error: (new Error("Connection closed before committing the transaction.", "resource://gre/modules/Sqlite.jsm", 688))
selenium_1   | JavaScript error: resource://gre/modules/osfile/osfile_async_front.jsm, line 426: Error: OS.File has been shut down. Rejecting post to stat
selenium_1   | ExceptionHandler::GenerateDump cloned child ExceptionHandler::WaitForContinueSignal waiting for continue signal...
selenium_1   | 918
selenium_1   | ExceptionHandler::SendContinueSignalToChild sent continue signal to child
selenium_1   | 14:52:34.673 INFO [ActiveSessions$1.onStop] - Removing session 67372bfa-d9d3-4a5a-bd10-c9f1cd9eabba (org.openqa.selenium.firefox.GeckoDriverService)

```

## Comments
Not sure if it's firefox/geckodriver, selenium or the docker image, I hope I'm reporting in the right place. Thanks for you time reading this report :)

**Comment by diemol** [comment] 2020-11-27 10:55
@tuxayo, How can I reproduce this with Selenium WebDriver?
Other questions:
- Can you reproduce it when using Firefox directly?
- What happens if you start the session just using `curl`
- Are your Perl bindings compatible with the latest versions of Selenium Server? If not, have you upgraded them?

**Comment by tuxayo** [comment] 2020-12-08 17:55
> How can I reproduce this with Selenium WebDriver?

Do you mean without Selenium server? Or without any language bindings?

> Are your Perl bindings compatible with the latest versions of Selenium Server? If not, have you upgraded them?

IIUC yes as I have a test suite running on the latest Selenium Server 3.

> What happens if you start the session just using curl

Here is my attempt which failed
```
curl -XPOST http://localhost:4444/session -d ‘{“desiredCapabilities”:{“browserName”:”firefox”}}’
> Whoops! The URL specified routes to this help page.

#curl http://localhost:4444/session/MY_SESSION/url -d ‘{“url”:”https://example.org”}’
#curl -X DELETE http://localhost:4444/session/MY_SESSION

```


> Can you reproduce it when using Firefox directly?

What do you mean?

**Comment by dylanlive** [comment] 2020-12-08 18:11
For what it's worth, I am also investigating a Firefox delete session request taking 30+ seconds occasionally. This Grid is **not** within the docker images.

I think it's either something with Geckodriver 0.28.0 or Firefox 83. I should know more later today after experimenting.

**Comment by dylanlive** [comment] 2020-12-11 03:41
@tuxayo What Firefox version are you running in both your Working and Non-Working images?

I've experimented with different Firefox versions, and definitely see with Firefox 83.0.0, a huge increase in DELETE requests seeing 60 seconds or longer to close Firefox. It's not constantly reproducable, but it's pretty frequent (33 out of 360 times)

This happens on both Geckodriver 0.27 and 0.28 (I was surprised it wasn't geckodriver related).

Firefox 81 was working fine.
Firefox 82 had a bit more deletes taking 60+ seconds, but not too often (need to investigate 82 a little more)
Firefox 83 has a ton of deletes taking 60+ seconds

This is likely going to be a bug to file on the Mozilla side. I'm working on collecting more logs from geckodriver.

**Comment by dylanlive** [comment] 2020-12-11 03:45
Actually, this also looks related:
https://github.com/mozilla/geckodriver/issues/1811

**Comment by tuxayo** [comment] 2020-12-21 20:42
> @tuxayo What Firefox version are you running in both your Working and Non-Working images?

It was a hop from an old version (47) to the latest at the time (83).

**Comment by diemol** [comment] 2021-01-14 10:25
I'll close this since the linked GeckoDriver issue shows that it got solved in Firefox 84.

**Closed as completed by diemol** 2021-01-14 10:25 UTC
Labels: R-awaiting-answer

**Comment by tuxayo** [comment] 2021-02-26 12:38
Thanks a lot, have a nice day :)
