### ISSUE TITLE
WebDriverException: Message: Error forwarding the new session new session request for webdriver should contain a location header or an 'application/json;charset=UTF-8' response body with the session ID

### ISSUE THREAD

**Issue by jitesh43** [SeleniumHQ/docker-selenium#1350] opened 2021-07-30 08:32 UTC
## To Reproduce

Steps to reproduce the behavior (including the command to start the containers):

## Test script reproducing this issue (when applicable)

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: 
Docker-Selenium image version: 
Docker version: 
Docker-Compose version (if applicable):
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):

**Comment by diemol** [comment] 2021-07-30 20:20
Duplicate of #1348

**Closed as completed by diemol** 2021-07-30 20:20 UTC
