### ISSUE TITLE
Chrome / Firefox standalone crashes after a few hours 

### ISSUE THREAD

**Issue by frosty00** [SeleniumHQ/docker-selenium#816] opened 2018-10-20 23:22 UTC
OS: Debian 3.16.39
Docker: version 18.06.1-ce, build e68fc7a

---

After running a container for a while the firefox/chrome browser crashes (not the container) and upon trying to manipulate it in my python code I get the error: 

`selenium.common.exceptions.WebDriverException: Message: No active session with ID d133315f5be1a`

How can I mitigate this error / get better error logging so I can find out where the error is occuring?

Is there a way to filter the output of `docker logs -f` so it only shows the browser output and not any vncserver output? Is it possible to enable logging for chrome or firefox?

**Comment by frosty00** [comment] 2018-10-21 21:19
Did downgrading fix the issue for you?

**Comment by diemol** [comment] 2018-10-22 19:21
Hi @frosty00 and @yippeykeiyay,

As mentioned in #781, the only difference is the browser version. In a while, we are releasing the image with Chrome 70, which you can try after the release. 

The current version (and future ones, only output logs related to the Selenium and ChromeDriver/GeckoDriver activity). 

In the end, besides releasing the image with Chrome 70 (and tomorrow with Firefox 63), if we don't have a way to reproduce the issue, we cannot do anything about it, sorry.

I'll close this issue and please have a look in a few hours with the new release. If the issue is reproducible, please create an issue and fill the template completely.

**Closed by diemol** 2018-10-22 19:21 UTC

**Comment by tuomas2** [comment] 2019-02-13 13:16
I'm also experiencing this issue in our protractor e2e test stack. Tested with standalone-chrome-debug:3.141.59-gold.
