### ISSUE TITLE
Memory cleanup after quit()

### ISSUE THREAD

**Issue by grafa** [SeleniumHQ/docker-selenium#649] opened 2018-01-11 08:11 UTC
Hi folks,

Probably not the best place to ask but I will give it a try.

When I kick off container with Selenium, run a webdriver and quit with `quit()` it still keeps a lots of spawned threads and memory is not freed up.

My question is how can I run some kind of GC to free up the memory or how can I make `quit()` to do so (according docs it should close all threads). I run Selenium once a day and RAM is full of Selenium Java junk since I first kick off a webdriver.

Many thanks.

**Comment by diemol** [comment] 2018-01-12 17:57
Hi @grafa,

When using the docker-selenium images, the ideal approach is to benefit from the immutable infrastructure concept that docker offers. 
This means that it is preferred to have short-lived containers running the grid, and when you are done with your tests, throw them away. 
If you keep them running for a long time, you can end up with similar problems as a non-docker grid (spawned threads in memory caused by some crashed processes that were not cleaned).

I'd suggest you to try that approach, and if you still have questions, you can post them in the [Selenium Google Group](https://groups.google.com/forum/#!forum/selenium-users) and also join the community chat on [IRC/Slack](https://seleniumhq.herokuapp.com).

I'll close the issue, and we can continue the conversation in one of those channels.

**Closed by diemol** 2018-01-12 17:57 UTC
