### ISSUE TITLE
[🐛 Bug]:  EventBus stop working on AWS ECS Cluster

### ISSUE THREAD

**Issue by williammc2** [SeleniumHQ/docker-selenium#1427] opened 2021-10-20 16:41 UTC
### What happened?

My Selenium grid is stoping work after a hours in idle, when i send a task to grid, the task keep stuck in the concurrency, showing that process still working, but the  integration between  grid/nod  stop working.

I know that problem is in grid, because when i restart the task in AWS, the grid back to normal.

### Command used to start Selenium Grid with Docker

```shell
i'm only exposing the ports 4442-4444, no env are been used.
```

### Relevant log output

```shell
00:33:16.428 WARN [UnboundZmqEventBus$PollingRunnable.run] - Caught exception while polling for event bus messages: Unable to parse: ���k�m�O�φ\R��-�������
org.openqa.selenium.json.JsonException: Unable to parse: ���k�m�O�φ\R��-�������
	at org.openqa.selenium.json.Json.toType(Json.java:57)
	at org.openqa.selenium.json.Json.toType(Json.java:50)
	at org.openqa.selenium.events.zeromq.UnboundZmqEventBus$PollingRunnable.run(UnboundZmqEventBus.java:229)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.openqa.selenium.json.JsonException: Unable to determine type from: �. Last 1 characters read: �
Build info: version: '4.0.0', revision: '3a21814679'
System info: host: 'ip-10-0-191-34.ec2.internal', ip: '10.0.191.34', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.231-180.360.amzn2.x86_64', java.version: '11.0.11'
Driver info: driver.version: unknown
	at org.openqa.selenium.json.JsonInput.peek(JsonInput.java:126)
	at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:141)
	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:127)
	at org.openqa.selenium.json.Json.toType(Json.java:71)
	at org.openqa.selenium.json.Json.toType(Json.java:55)
	... 7 more
```

### Operating System

ECS Cluster

### Docker Selenium version (tag)

4.0.0-20211013

**Comment by williammc2** [comment] 2021-10-21 12:26
i'm getting the error below

`<html>
<body>


02:31:33.998 WARN [UnboundZmqEventBus$PollingRunnable.run] - Caught exception while polling for event bus messages: Unable to parse: node-heartbeat
--
org.openqa.selenium.json.JsonException: Unable to parse: node-heartbeat
at org.openqa.selenium.json.Json.toType(Json.java:57)
at org.openqa.selenium.json.Json.toType(Json.java:50)
at org.openqa.selenium.events.zeromq.UnboundZmqEventBus$PollingRunnable.run(UnboundZmqEventBus.java:229)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.openqa.selenium.json.JsonException: Unable to read null. Saw o at position 1. Last 2 characters read: no
Build info: version: '4.0.0', revision: '3a21814679'
System info: host: 'ip-10-0-124-249.ec2.internal', ip: '10.0.124.249', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.231-180.360.amzn2.x86_64', java.version: '11.0.11'
Driver info: driver.version: unknown
at org.openqa.selenium.json.JsonInput.read(JsonInput.java:338)
at org.openqa.selenium.json.JsonInput.nextNull(JsonInput.java:150)
at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:142)
at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:127)
at org.openqa.selenium.json.Json.toType(Json.java:71)
at org.openqa.selenium.json.Json.toType(Json.java:55)
... 7 more


</body>
</html>`

**Comment by sarvab123** [comment] 2021-10-22 08:01
Observed same issue in linux machine when we setup dockerized grid. We are getting above error message even scripts are running and it is in a loop.

After restart hub container, then it is working fine but again goes down after sometime.

**Comment by diemol** [comment] 2021-10-22 18:30
How can I reproduce the issue? How can I deploy this to ECS? Which component is showing that error?

**Comment by williammc2** [comment] 2021-10-22 18:44
I builded a CDK with selenium 4 , and deployed as ECS cluster autoscaled.

The grid task i have deployed with the env below

![image](https://user-images.githubusercontent.com/9258932/138505919-2c413888-230c-43f9-b436-d1ea27f75f6e.png)

If you prefer i can send to you the CDK AWS code...

The component that showing this error is grid hub ecs task, using the version selenium/hub:4.0.0-20211013, i already test with other selenium 4 version, and the same problem happen. 

"How can I reproduce the issue?"
This issue appear when the grid is in idle, look the log below, the error apear after hours in idle...

![image](https://user-images.githubusercontent.com/9258932/138506956-ddb1414e-4a43-4595-9f78-747808d39226.png)

**Comment by diemol** [comment] 2021-10-22 18:46
What about the Node? How is it deployed?

**Comment by williammc2** [comment] 2021-10-22 18:49
This Node was deployed using cloudformation, below you can see the  Hub's task definition json, where show all about the deployment...

```{
  "ipcMode": null,
  "executionRoleArn": "",
  "containerDefinitions": [
    {
      "dnsSearchDomains": [],
      "environmentFiles": null,
      "logConfiguration": {
        "logDriver": "awslogs",
        "secretOptions": null,
        "options": {
          "awslogs-group": "selenium-grid-stack-SeleniumHubClusterseleniumhubtaskdefseleniumhubcontainerLogGroupCD292309-o6CS6sR9u6hk",
          "awslogs-region": "us-east-1",
          "awslogs-stream-prefix": "selenium-hub-logs"
        }
      },
      "entryPoint": [
        "sh",
        "-c"
      ],
      "portMappings": [
        {
          "hostPort": 4444,
          "protocol": "tcp",
          "containerPort": 4444
        },
        {
          "hostPort": 4443,
          "protocol": "tcp",
          "containerPort": 4443
        },
        {
          "hostPort": 4442,
          "protocol": "tcp",
          "containerPort": 4442
        }
      ],
      "command": [
        "/opt/bin/entry_point.sh"
      ],
      "linuxParameters": null,
      "cpu": 1024,
      "environment": [
        {
          "name": "SE_NODE_POLLING",
          "value": "5000"
        },
        {
          "name": "SE_RELAX_CHECKS",
          "value": "true"
        },
        {
          "name": "SE_SESSION_REQUEST_TIMEOUT",
          "value": "300"
        },
        {
          "name": "SE_SESSION_RETRY_INTERVAL",
          "value": "5"
        }
      ],
      "resourceRequirements": null,
      "ulimits": null,
      "dnsServers": [],
      "mountPoints": [],
      "workingDirectory": null,
      "secrets": null,
      "dockerSecurityOptions": [],
      "memory": 2048,
      "memoryReservation": null,
      "volumesFrom": [],
      "stopTimeout": null,
      "image": "selenium/hub:4.0.0-20211013",
      "startTimeout": null,
      "firelensConfiguration": null,
      "dependsOn": null,
      "disableNetworking": null,
      "interactive": null,
      "healthCheck": null,
      "essential": true,
      "links": [],
      "hostname": null,
      "extraHosts": null,
      "pseudoTerminal": null,
      "user": null,
      "readonlyRootFilesystem": null,
      "dockerLabels": null,
      "systemControls": [],
      "privileged": null,
      "name": "selenium-hub-container"
    }
  ],
  "placementConstraints": [],
  "memory": "2048",
  "taskRoleArn": "",
  "compatibilities": [
    "EC2",
    "FARGATE"
  ],
  "taskDefinitionArn": "arn:aws:ecs:us-east-1:770967265766:task-definition/seleniumgridstackSeleniumHubClusterseleniumhubtaskdef5BD5FF9F:7",
  "family": "seleniumgridstackSeleniumHubClusterseleniumhubtaskdef5BD5FF9F",
  "requiresAttributes": [
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.logging-driver.awslogs"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "ecs.capability.execution-role-awslogs"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.docker-remote-api.1.19"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.docker-remote-api.1.17"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.task-iam-role"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.docker-remote-api.1.18"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "ecs.capability.task-eni"
    }
  ],
  "pidMode": null,
  "requiresCompatibilities": [
    "FARGATE"
  ],
  "networkMode": "awsvpc",
  "cpu": "1024",
  "revision": 7,
  "status": "ACTIVE",
  "inferenceAccelerators": null,
  "proxyConfiguration": null,
  "volumes": []
}`

**Comment by diemol** [comment] 2021-10-22 20:00
I think this is a duplicate of https://github.com/SeleniumHQ/selenium/issues/9959. Are you running some healthchecks or something similar?

**Comment by pujagani** [comment] 2021-10-25 06:14
Hey! The issue where a JSON parsing error prevents further messages from being processed is handled as part of 6bbafcd. The changes will be available in the next release.

**Comment by diemol** [comment] 2021-10-25 10:09
Closing as this got fixed in the linked issue.

**Closed as completed by diemol** 2021-10-25 10:09 UTC
Labels: R-awaiting-answer
