### ISSUE TITLE
[🚀 Feature]: Add a service option when running a chrome node

### ISSUE THREAD

**Issue by JonathonFord** [SeleniumHQ/docker-selenium#1659] opened 2022-08-18 15:37 UTC
### Feature and motivation

I am looking for a way to launch the chrome nodes authenticated as a certain user. It would be nice if I could do something like this:

docker run -d -p 4444:4444 -e SE_SERVICE="somefile.json" --name selenium-hub selenium/hub:4.4.0-20220812

Where it accepts a file of some sort to set the credentials for username password and a domain like in the Service class for the regular webdrivers

### Usage example

docker run -d -p 4444:4444 -e SE_SERVICE="somefile.json" --name selenium-hub selenium/hub:4.4.0-20220812

Where it accepts a file of some sort to set the credentials for username password and a domain like in the Service class for the regular webdrivers

**Comment by diemol** [comment] 2022-08-18 19:37
Duplicate of https://github.com/SeleniumHQ/selenium/issues/10957. We will understand better the feature request over there.

**Closed as completed by diemol** 2022-08-18 19:37 UTC
