### ISSUE TITLE
Standalone - Unable to create new session

### ISSUE THREAD

**Issue by TBurda** [SeleniumHQ/docker-selenium#812] opened 2018-10-18 13:23 UTC
Image(s):  selenium/standalone-chrome
Docker-Selenium Image Version(s):  latest
Docker Version:  18.06.1-ce
OS: Windows [10]

## Actual Behavior -
The latest version of the image shows error _Unable to create new session_. Last week, everything was all right. 

## Steps to reproduce -

1. docker pull selenium/standalone-chrome
2. docker run -d -p 4444:4444 selenium/standalone-chrome
3. Open url http://127.0.0.1:4444/
4. Click to Console
5. Create Session
6. Error: Unable to create new session
![error](https://user-images.githubusercontent.com/21170562/47156979-93e05b80-d2e8-11e8-9902-d462e7ec1b96.png)

**Comment by diemol** [comment] 2018-10-18 15:23
Hi @TBurda,

Can you please post the output of:

`docker images selenium/standalone-chrome`?

Also, what command do you use to start the container?

**Comment by TBurda** [comment] 2018-10-18 15:39
Hi @diemol 

PS C:\Users\tburd\Desktop\New folder> docker images selenium/standalone-chrome
REPOSITORY                   TAG                 IMAGE ID            CREATED             SIZE
selenium/standalone-chrome   latest              f29f963d1b0f        4 days ago          1.24GB

Command to run container: docker run -d -p 4444:4444 selenium/standalone-chrome

**Comment by diemol** [comment] 2018-10-18 19:44
Could you please start the container with the recommended command?

```
docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome:3.14.0-helium
```

I just tried it a few times and I was not able to reproduce.

**Comment by diemol** [comment] 2018-10-22 18:06
@TBurda I didn't get that, so did it work for you the following command?

```
docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome:3.14.0-helium
```

**Comment by diemol** [comment] 2018-11-04 21:59
Closing as we didn't get more info from the OP.

**Closed by diemol** 2018-11-04 21:59 UTC
Labels: R-awaiting-answer
