### ISSUE TITLE
Getting "session deleted because of page crash" error for some of the test cases while executing tests on chrome, firefox and edge browser. Also, execution time is very high around 5 minute for 6 tests.

### ISSUE THREAD

**Issue by sabya2020** [SeleniumHQ/docker-selenium#1307] opened 2021-06-02 03:32 UTC
## 🐛 Bug Report

Getting session deleted because of page crash for some of the test cases while executing tests on chrome, firefox and edge browser.
I am able to run 3 test cases parallel without any error. But while running 6 test cases or more I am getting " session deleted because of page crash" error.

## To Reproduce

Create 6 or more simple test cases as shown below. E.g. 2 for Edge, 2 for firefox and 2 for chrome
Start selenium grid using docker-compose file provided below.
Run those from testng.xml file in parallel.

## Expected behavior

Page should not crash during execution of tests. Also, time taken for executing simple test cases is very high.

## Test script reproducing this issue (when applicable)

I have created 6 simple tests like below for opening browser.
		DesiredCapabilities dc = new DesiredCapabilities();
		dc.setBrowserName("chrome");
		URL url =new URL("http://localhost:4444/wd/hub");
		RemoteWebDriver driver = new RemoteWebDriver(url,dc);
		driver.get("https://www.flipkart.com/");
		driver.quit();

## Environment

OS: macOS BigSur Version:11.4
Docker-Selenium image version: 4.0.0-beta-4-prerelease-20210527
Also provide the docker image id : 524c25ef95ae
-->
Docker version: 20.10.6
Docker-Compose version (if applicable): 1.29.1
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well): https://github.com/SeleniumHQ/docker-selenium/blob/trunk/docker-compose-v3-video.yml

**Comment by zzvara** [comment] 2021-06-07 19:49
I confirm the same problem with this version.

**Comment by diemol** [comment] 2021-07-30 21:08
Can you share a complete code to run this in parallel?  I was not able to reproduce it. If you are recording video please bear in mind that 1 extra CPU is needed for good performance.

For example, the docker compose file will start 3 browser containers (which need 3 CPUs, could be less or more depending on our application under test), and 3 containers recording video (3 CPUs more). And overall, around 6-8 GB of memory.

So, if you want to run 6 tests in paralell, I assume you are modifying the docker compose file to have 6 containers running browsers and 6 containers recording video. This is a setup that would need 12 CPUs (probably less, probably more, which depends on your app under test and the performace metrics you take).

**Comment by sabya2020** [comment] 2021-08-16 10:18
Hi @diemol,

Sorry for late reply. Please find attached simple project file to reproduce the issue in MacBook Pro. 
[Seleniumgrid4issue.zip](https://github.com/SeleniumHQ/docker-selenium/files/6991522/Seleniumgrid4issue.zip)

Steps: 1. Start grid by running docker compose command.
2. Open testng2.xml and run as testng suite.

**Comment by diemol** [comment] 2021-08-16 10:23
Before I check this, could you please share any comments about what I wrote above?
>So, if you want to run 6 tests in paralell, I assume you are modifying the docker compose file to have 6 containers running browsers and 6 containers recording video. This is a setup that would need 12 CPUs (probably less, probably more, which depends on your app under test and the performace metrics you take).

So, do you have a machine with 12CPUs to run those tests?

**Comment by sabya2020** [comment] 2021-08-16 10:43
I tried running those tests with a machine with 8 CPUs. First time those tests run successfully. But 2nd time when i tried again running those tests then tests got failed with error message as "org.openqa.selenium.WebDriverException: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed"

**Comment by diemol** [comment] 2021-08-16 11:14
8 CPUs is not the ideal amount if you want to run 6 concurrent tests with video recording. You can probably get a few successful executions, but for a consistent execution environment, resources cannot be overcommitted. 

With 8 CPUs you should be able to run 4 tests with video recording concurrently in a consitent way. I recommend you measure performance to find an adecuate amount of concurrent tests for your test suite. Also, please note that ideally nothing else should be competing for the CPU while tests are running.

**Comment by sabya2020** [comment] 2021-08-19 05:31
Hi @diemol 
I have 27 test cases to open a URL in browser. 9 for chrome browser, 9 for firefox browser, 9 for Edge browser. I want to run 3 parallel tests at a time per node with video recording. E.g. Running 3 chrome test cases in chrome node, 3 firefox test case in firefox node and 3 edge test cases in edge node in parallel. I am using attached docker-compose-v3-video.yml file and testng2.xml file. But getting failure with error message as "session deleted because of page crash" .
[Seleniumgrid4betadocker.zip](https://github.com/SeleniumHQ/docker-selenium/files/7011894/Seleniumgrid4betadocker.zip)
Can you please check yml file and testng file and let me know what needs to be modified to run 3 parallel tests.
**OS used :  MacBook pro, Memory-16GB, CPU-8**

**Find below error log**
org.openqa.selenium.WebDriverException: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: MicrosoftEdge=93.0.961.11)
Build info: version: '4.0.0-beta-3', revision: '5d108f9a67'
System info: host: '<systemname>.local', ip: '2405:201:d007:eaac:d90e:2ae:98ec:788d%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_231'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [fa749752834a12f01aac3d40feb1c66b, get {url=https://www.amazon.in/}]
Capabilities {acceptInsecureCerts: false, browserName: msedge, browserVersion: 93.0.961.11, javascriptEnabled: true, ms:edgeOptions: {debuggerAddress: localhost:38101}, msedge: {msedgedriverVersion: 93.0.961.11 (16419a32c7a83d..., userDataDir: /tmp/.com.microsoft.Edge.J2...}, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), se:cdp: ws://172.21.0.5:5555/sessio..., se:cdpVersion: 93.0.961.11, se:vnc: ws://172.21.0.5:5555/sessio..., se:vncEnabled: true, se:vncLocalAddress: ws://localhost:7900/websockify, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: fa749752834a12f01aac3d40feb1c66b

**Comment by diemol** [comment] 2021-09-06 16:13
@sabya2020 can you please provide the code in a GitHub repository with instructions showing how to execute the tests?

**Comment by diemol** [comment] 2021-09-23 08:52
I will close this issue but I am happy to reopen it when the GitHub repo with instuctions is provided.

**Closed as completed by diemol** 2021-09-23 08:52 UTC
Labels: R-awaiting-answer
