### ISSUE TITLE
can't connect to selenium at second time

### ISSUE THREAD

**Issue by shiratsu** [SeleniumHQ/docker-selenium#893] opened 2019-04-08 13:57 UTC
## 💬 Questions and Help
i would like to connect selenium which is created by docker-compose
docker-compose.yml is here
```
version: '2'

services:
  hub:
    image: selenium/hub:3.141.59-mercury
    container_name: 'selenium-hub'
    ports:
      - '4444:4444'
  chrome:
    image: selenium/node-chrome-debug:3.141.59-mercury
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    depends_on:
      - hub
    ports:
      - '5900:5900'

```

my program can connect at first
but at second time,it can't connect.

```
In HttpCommandExecutor.php line 292:

  Curl error thrown for http POST to /session with params: {"desiredCapabilities":{"browserName"
  :"chrome","platform":"linux","chromeOptions":{"binary":"","args":["--disable-notifications","-
  -headless","--no-sandbox"]}}}

  Operation timed out after 60001 milliseconds with 0 bytes received
```

How do i resolve?

**Comment by cgoldberg** [comment] 2019-04-08 14:17
@shiratsu 
please fill out the issue template and provide details on what you are attempting to run.

**Comment by shiratsu** [comment] 2019-04-08 14:42
@cgoldberg sorry,my question doesn’t follow template?
which point isn't enough?

my program is here.
```
$capabilities = DesiredCapabilities::chrome();

            $options = new ChromeOptions();
            $options->addArguments(
                array(
                    '--disable-notifications',
                    '--headless',
                    '--no-sandbox',
                )
            );
            $capabilities->setPlatform($this->argument('platform'));

            $capabilities->setCapability(ChromeOptions::CAPABILITY, $options);
            $this->_driver = RemoteWebDriver::create($host, $capabilities, 60 * 1000, 60 * 1000); 
```

then run a program.

the following error happend
```
In HttpCommandExecutor.php line 292:

  Curl error thrown for http POST to /session with params: {"desiredCapabilities":{"browserName"
  :"chrome","platform":"linux","chromeOptions":{"binary":"","args":["--disable-notifications","-
  -headless","--no-sandbox"]}}}

  Operation timed out after 60001 milliseconds with 0 bytes received
```

**Comment by diemol** [comment] 2019-04-08 14:53
@shiratsu Please submit a new issue with all the requested data, the template looks like this when you choose "Bug Report"

![image](https://user-images.githubusercontent.com/5992658/55733842-cdd02600-5a1e-11e9-9a72-d282717d3f9b.png)

Please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

**Comment by shiratsu** [comment] 2019-04-08 14:58
this is noted.
i will submit to a proper category
thank you.

**Comment by diemol** [comment] 2019-04-08 15:01
Ok, then I will close it and then you can sumbit an issue with all the required info. Thanks.

**Closed by diemol** 2019-04-08 15:01 UTC
Labels: R-awaiting-answer
