### ISSUE TITLE
InvocationTargetException received when trying to create new Selenium session

### ISSUE THREAD

**Issue by ddavison** [SeleniumHQ/docker-selenium#214] opened 2016-04-25 18:01 UTC
> Migrated from https://github.com/SeleniumHQ/selenium/issues/2008

@mariusioana wrote:
## Meta -

OS: CENTOS 7 docker image
Selenium Version: 2.53.0
Browser: Firefox
Browser Version: 45.0.2
## Expected Behavior -

No Exception should be raised when trying to create a new session
## Actual Behavior -

Stack trace is received:
`
12:36:44.301 INFO [26] org.openqa.selenium.remote.server.FirefoxDriverProvider - Creating a new session for Capabilities [{platform=ANY, acceptSslCerts=true, javascriptEnabled=true, browserName=firefox, name=M3 Script}]
12:37:29.507 WARN [14] org.openqa.selenium.remote.server.DriverServlet - Exception thrown
java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: '9bf0228b7c38', ip: '172.17.18.95', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-327.10.1.el7.x86_64', java.version: '1.7.0_99'
Driver info: driver.version: unknown
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:188)
    at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:183)
    at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:119)
    at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:95)
    at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:124)
    at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:59)
    at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:1)
    at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:111)
    at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:79)
    at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:204)
    at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:166)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:132)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at org.openqa.jetty.jetty.servlet.ServletHolder.handle(ServletHolder.java:428)
    at org.openqa.jetty.jetty.servlet.ServletHandler.dispatch(ServletHandler.java:680)
    at org.openqa.jetty.jetty.servlet.ServletHandler.handle(ServletHandler.java:571)
    at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1526)
    at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1479)
    at org.openqa.jetty.http.HttpServer.service(HttpServer.java:920)
    at org.openqa.jetty.http.HttpConnection.service(HttpConnection.java:820)
    at org.openqa.jetty.http.HttpConnection.handleNext(HttpConnection.java:986)
    at org.openqa.jetty.http.HttpConnection.handle(HttpConnection.java:837)
    at org.openqa.jetty.http.SocketListener.handleConnection(SocketListener.java:243)
    at org.openqa.jetty.util.ThreadedServer.handle(ThreadedServer.java:358)
    at org.openqa.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:537)
Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: '9bf0228b7c38', ip: '172.17.18.95', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-327.10.1.el7.x86_64', java.version: '1.7.0_99'
Driver info: driver.version: unknown
    at org.openqa.selenium.remote.server.FirefoxDriverProvider.callConstructor(FirefoxDriverProvider.java:101)
    at org.openqa.selenium.remote.server.FirefoxDriverProvider.newInstance(FirefoxDriverProvider.java:68)
    at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:60)
    at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:222)
    at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at org.openqa.selenium.remote.server.FirefoxDriverProvider.callConstructor(FirefoxDriverProvider.java:91)
    ... 9 more
`
## Steps to reproduce -

I am using Nightwatchjs selenium based testing framework. From time to time, I get this error when trying to create a new session and run a new test.

**Comment by bitliner** [comment] 2016-10-20 11:09
+1 - using docker image `selenium/standalone-chrome:2.45.0`

**Comment by GrayedFox** [comment] 2017-02-10 13:32
Getting the exact same error, but will post my log here in case it is helpful, I think it's from a timeout waiting for the chromedriver instance to be available. Tried increasing timeout to 30 seconds using `-timeout=30` option when starting selenium server but not yet sure that will work.

Log:
```
[acceptance-nemesis] java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
[acceptance-nemesis] Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
[acceptance-nemesis] System info: host: 'N/A', ip: 'N/A', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-59-generic', java.version: '1.8.0_121'
[acceptance-nemesis] Driver info: driver.version: unknown
[acceptance-nemesis] 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
[acceptance-nemesis] 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
[acceptance-nemesis] 	at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:183)
[acceptance-nemesis] 	at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:119)
[acceptance-nemesis] 	at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:95)
[acceptance-nemesis] 	at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:131)
[acceptance-nemesis] 	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:59)
[acceptance-nemesis] 	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:36)
[acceptance-nemesis] 	at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:111)
[acceptance-nemesis] 	at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:189)
[acceptance-nemesis] 	at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:222)
[acceptance-nemesis] 	at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:184)
[acceptance-nemesis] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
[acceptance-nemesis] 	at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:150)
[acceptance-nemesis] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
[acceptance-nemesis] 	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:808)
[acceptance-nemesis] 	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:587)
[acceptance-nemesis] 	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
[acceptance-nemesis] 	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:515)
[acceptance-nemesis] 	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
[acceptance-nemesis] 	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
[acceptance-nemesis] 	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
[acceptance-nemesis] 	at org.seleniumhq.jetty9.server.Server.handle(Server.java:499)
[acceptance-nemesis] 	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:310)
[acceptance-nemesis] 	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:257)
[acceptance-nemesis] 	at org.seleniumhq.jetty9.io.AbstractConnection$2.run(AbstractConnection.java:540)
[acceptance-nemesis] 	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
[acceptance-nemesis] 	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
[acceptance-nemesis] 	at java.lang.Thread.run(Thread.java:745)
[acceptance-nemesis] Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
[acceptance-nemesis] Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
[acceptance-nemesis] System info: host: 'N/A', ip: 'N/A', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-59-generic', java.version: '1.8.0_121'
[acceptance-nemesis] Driver info: driver.version: unknown
[acceptance-nemesis] 	at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:113)
[acceptance-nemesis] 	at org.openqa.selenium.remote.server.DefaultDriverProvider.newInstance(DefaultDriverProvider.java:97)
[acceptance-nemesis] 	at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:60)
[acceptance-nemesis] 	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:222)
[acceptance-nemesis] 	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:209)
[acceptance-nemesis] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[acceptance-nemesis] 	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
[acceptance-nemesis] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[acceptance-nemesis] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[acceptance-nemesis] 	... 1 more
[acceptance-nemesis] Caused by: java.lang.reflect.InvocationTargetException
[acceptance-nemesis] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[acceptance-nemesis] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[acceptance-nemesis] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[acceptance-nemesis] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[acceptance-nemesis] 	at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:103)
[acceptance-nemesis] 	... 9 more
[acceptance-nemesis] Caused by: org.openqa.selenium.WebDriverException: Timed out waiting for driver server to start.
[acceptance-nemesis] Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
[acceptance-nemesis] System info: host: 'N/A', ip: 'N/A', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-59-generic', java.version: '1.8.0_121'
[acceptance-nemesis] Driver info: driver.version: ChromeDriver
[acceptance-nemesis] 	at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:178)
[acceptance-nemesis] 	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:166)
[acceptance-nemesis] 	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:78)
[acceptance-nemesis] 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
[acceptance-nemesis] 	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:241)
[acceptance-nemesis] 	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:128)
[acceptance-nemesis] 	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:141)
[acceptance-nemesis] 	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:174)
[acceptance-nemesis] 	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:142)
[acceptance-nemesis] 	... 14 more
[acceptance-nemesis] Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://localhost:3394/status] to be available after 20000 ms
[acceptance-nemesis] 	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:107)
[acceptance-nemesis] 	at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:175)
[acceptance-nemesis] 	... 22 more
[acceptance-nemesis] Caused by: com.google.common.util.concurrent.UncheckedTimeoutException: java.util.concurrent.TimeoutException
[acceptance-nemesis] 	at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:143)
[acceptance-nemesis] 	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:80)
[acceptance-nemesis] 	... 23 more
[acceptance-nemesis] Caused by: java.util.concurrent.TimeoutException
[acceptance-nemesis] 	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
[acceptance-nemesis] 	at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:130)
[acceptance-nemesis] 	... 24 more
[acceptance-nemesis] 12:53:36.105 WARN - Exception: null
```

**Comment by diemol** [comment] 2017-09-08 14:36
@bitliner @GrayedFox is this still an issue for you guys? It would be nice if you can check it again with the latest releases.

**Comment by diemol** [comment] 2017-09-26 21:15
Closing as we didn't get any feedback. 

Please reopen in case the issue is still present.

**Closed by diemol** 2017-09-26 21:15 UTC
Labels: R-awaiting-answer
