### ISSUE TITLE
Browser hangs inside of browser after executed

### ISSUE THREAD

**Issue by derinbay** [SeleniumHQ/docker-selenium#456] opened 2017-04-14 12:46 UTC
## Meta -
Image(s):  
selenium/node-chrome:3.3.1-cesium
Docker Version:  
17.04.0-ce, build 4845c56
OS:
Ubuntu 16.04

When tests are executing with node-chrome container, some of the containers are hanging after open the browser, as far as I see from the logs. I'm experiencing this problem since 3.2.0-actinium.

But with node-chrome-debug this never happened.

docker logs 720a3571429d2d2aae6a31cf037c5a1a0b69db4b253bb24a9cdeb59a6755a961 -f
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
12:30:32.869 INFO - Selenium build info: version: '3.3.1', revision: '5234b32'
12:30:32.870 INFO - Launching a Selenium Grid node
2017-04-14 12:30:23.873:INFO::main: Logging initialized @1389ms to org.seleniumhq.jetty9.util.log.StdErrLog
12:30:23.934 INFO - Driver provider org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
 registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match the current platform LINUX
12:30:23.934 INFO - Driver provider org.openqa.selenium.edge.EdgeDriver registration is skipped:
 registration capabilities Capabilities [{browserName=MicrosoftEdge, version=, platform=WINDOWS}] does not match the current platform LINUX
12:30:23.934 INFO - Driver class not found: com.opera.core.systems.OperaDriver
12:30:23.935 INFO - Driver provider com.opera.core.systems.OperaDriver registration is skipped:
Unable to create new instances on this machine.
12:30:23.935 INFO - Driver class not found: com.opera.core.systems.OperaDriver
12:30:23.935 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
12:30:23.939 INFO - Driver provider org.openqa.selenium.safari.SafariDriver registration is skipped:
 registration capabilities Capabilities [{browserName=safari, version=, platform=MAC}] does not match the current platform LINUX
2017-04-14 12:30:24.011:INFO:osjs.Server:main: jetty-9.2.20.v20161216
2017-04-14 12:30:24.128:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@441772e{/,null,AVAILABLE}
2017-04-14 12:30:24.170:INFO:osjs.AbstractConnector:main: Started ServerConnector@6379eb{HTTP/1.1,[http/1.1]}{0.0.0.0:5555}
2017-04-14 12:30:24.171:INFO:osjs.Server:main: Started @1687ms
12:30:24.171 INFO - Selenium Grid node is up and ready to register to the hub
12:30:24.193 INFO - Starting auto registration thread. Will try to register every 5000 ms.
12:30:24.194 INFO - Registering the node to the hub: http://172.17.0.2:4444/grid/register
12:30:24.218 INFO - The node is registered to the hub and ready to use
12:30:29.397 INFO - SessionCleaner initialized with insideBrowserTimeout 300000 and clientGoneTimeout 720000 polling every 30000
12:30:48.641 INFO - Executing: [new session: Capabilities [{test_machine=web, browserName=chrome, version=}]])
12:30:48.655 INFO - Creating a new session for Capabilities [{test_machine=web, browserName=chrome, version=}]
Starting ChromeDriver 2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5) on port 32003
Only local connections are allowed.

**Comment by ddavison** [comment] 2017-04-14 16:42
can I see the command you're using to run the containers?

**Comment by derinbay** [comment] 2017-04-14 16:54
I'm using a docker-compose file to run the containers:
[gist link](https://gist.github.com/derinbay/b3ff9593752bb09d80eea1d31e9dd43d)

**Comment by ddavison** [comment] 2017-04-14 17:00
you're setting `GRID_BROWSER_TIMEOUT`, is it possible that it's hitting that timeout?  we default this to "0" (indefinite)

**Comment by derinbay** [comment] 2017-04-14 17:04
I'm setting that in case of some browser is hanged. In this case it's starting the browser as far as I saw from the logs and wait for 5 mins (grid_browser_timeout). If I don't set, isn't it going forever, since the default is 0?

**Comment by ddavison** [comment] 2017-04-14 17:08
when this starts happening, is it just a few tests, then it breaks? or..

**Comment by derinbay** [comment] 2017-04-14 17:17
Yes, just a few random tests are hanging, about %10.
When I work with chrome-node-debug, this never happened.

**Comment by testphreak** [comment] 2017-04-14 23:28
@ddavison I am seeing this issue as well, where after a few tests the run just hangs. I don't see this issue with 3.0.1. My meta information is is exactly the same as @derinbay

**Comment by testphreak** [comment] 2017-04-14 23:40
Please ignore me linking 447 above. Probably unrelated.

**Comment by diemol** [comment] 2017-04-15 21:44
@testphreak you could try using the debug image and see through VNC what happens when the browser hangs. Maybe it is not necessarily something related to the docker-selenium image but more to a newer Selenium, Chrome or Chromedriver version?

**Comment by testphreak** [comment] 2017-04-21 01:22
@diemol thanks for the suggestion. I find that my tests don't hang when running with node-chrome-debug. The test run hangs every time I use node-chrome. When I enable debugging for node-chrome container I see several errors related to `http-outgoing-129 << "[read] I/O error: Read timed out"`. I don't see anything else that might point to an issue.

I don't see any issues with my tests when using node-chrome 3.0.1.

**Comment by testphreak** [comment] 2017-04-21 23:20
@diemol the read timeout issue is probably a red herring. But my tests continue to hang with node-chrome 3.4.0-actinium. Tests run fine on node-chrome-debug.

**Comment by diemol** [comment] 2017-04-22 06:55
@testphreak 
I'll check it during the weekend, would it be possible for you to provide a test case to reproduce it?

**Comment by testphreak** [comment] 2017-04-22 18:18
@derinbay @ddavison spent a good deal of time last night trying to get to the bottom of the issue. It's related to this change https://github.com/SeleniumHQ/docker-selenium/commit/88584def77585863a226ca72bbce0f9dce561242 made by @a-k-g to resolve #358. 

Due to this change, none of the node-chrome images after 3.0.1 are working for me and the timeline of the commit confirms that. Would it be possible to add a fix that would work for all images - node-chrome, node-chrome-debug, standalone-chrome and standalone-chrome-debug images?

I passed in `DBUS_SESSION_BUS_ADDRESS=/dev/null` as an environment variable to node-chrome when starting the containers and all my tests now execute without random hangs with 3.4.0-actinium. It would be better if this variable is set in the image rather than us having to pass it in every time. 

I also found out that I am not alone in this issue and several including @pwaller and others have run into this issue recently https://github.com/SeleniumHQ/docker-selenium/issues/87#issuecomment-284238845.

**Comment by testphreak** [comment] 2017-04-22 22:21
@diemol I just realized this issue has nothing to do with the hang issues I was seeing with node-chrome. Opened a separate issue https://github.com/SeleniumHQ/docker-selenium/issues/465.

**Comment by diemol** [comment] 2017-04-28 10:03
Hi @derinbay,

I saw your [comment](https://github.com/SeleniumHQ/docker-selenium/issues/465#issuecomment-297957592). I would like to try to reproduce the error you get with the latest release, can you please help me with some test code you are using to get the error? Also the docker commands would be helpful.

**Comment by derinbay** [comment] 2017-04-28 13:22
Hello @diemol I've found out that, today's hangs were for another reason. I've checked that on my full suits and everything seems fine now. 

I can say that this issue was fixed on 3.4.0

Thanks for your efforts.

**Comment by diemol** [comment] 2017-04-28 13:28
How cool @derinbay, I'm glad it is working 👍 
Can you please close the issue?

**Closed** 2017-04-28 15:59 UTC
