### ISSUE TITLE
GRID_TIME doesn't change Node timeout

### ISSUE THREAD

**Issue by ronkorland** [SeleniumHQ/docker-selenium#784] opened 2018-09-12 09:30 UTC
## Meta
Image(s):  selenium/hub and selenium/node-chrome
Docker-Selenium Image Version(s):  3.14.0-dubnium
Docker Version: 18.06.0-ce
OS: Ubuntu 16 LTS

## Expected Behavior
Node timeout will be 10 sec

## Actual Behavior
Node timeout remained in default value 1800 sec

![image](https://user-images.githubusercontent.com/1866339/45416011-92879780-b687-11e8-9ac0-94135cc0030b.png)

![image](https://user-images.githubusercontent.com/1866339/45416022-9a473c00-b687-11e8-9e0f-912777627022.png)

## Steps to reproduce -
docker run -d -p 4444:4444 --name selenium-hub -e GRID_TIMEOUT=10 selenium/hub
docker run -d --link selenium-hub:hub -v /dev/shm:/dev/shm selenium/node-chrome

**Comment by ronkorland** [comment] 2018-09-12 09:31
Need to add GRID_TIMEOUT to node config json file ("timeout": GRID_TIMEOUT) or java command line (-timeout)

**Comment by diemol** [comment] 2018-09-13 08:33
This is a duplicate of https://github.com/SeleniumHQ/selenium/issues/5908, which was fixed in the upstream project and will be available in the next release.

**Closed by diemol** 2018-09-13 08:33 UTC
