### ISSUE TITLE
Some images are not rendered correctly

### ISSUE THREAD

**Issue by otodorov** [SeleniumHQ/docker-selenium#1376] opened 2021-08-27 20:23 UTC
## 🐛 Bug Report

Some of the images are not rendered correctly.

**This is how it is look:**
<img src="https://user-images.githubusercontent.com/26139666/131181825-a5cf1dcf-e950-4aeb-b7b9-fdfb4e6eb913.png" alt="alt text" width="500" height="500">

**This is how it should look:**
<img src="https://user-images.githubusercontent.com/26139666/131181690-c3dbe91a-8cd7-44c0-b013-b6b79ebfee09.png" alt="alt text" width="500" height="500">

## To Reproduce

_For the purpose of reproducing the issue, we were created a test account in our application._

1) Open Google Chrom inside the selenium container.
2) Go to this [URL](http://qa-selenium-cluster.gratowin.com:30080/#/lobby)
3) Login with username: `selenium` and password `selenium1`
<img src="https://user-images.githubusercontent.com/26139666/131182756-c6cf42a5-23c9-41b8-926e-09fa22871677.png" alt="3" width="500" height="500">
4) Once you are logged in click on the pirate in the bottom left corner
<img src="https://user-images.githubusercontent.com/26139666/131183068-4f0c20a4-a897-4355-97ed-0ff991b39eb9.png" alt="4" width="500" height="500">
5) You will see the image that is not rendered correctly
<img src="https://user-images.githubusercontent.com/26139666/131181825-a5cf1dcf-e950-4aeb-b7b9-fdfb4e6eb913.png" alt="5" width="500" height="500">

## Expected behavior

We are expecting to see the image the same way as it is displayed outside of the selenium container:
<img src="https://user-images.githubusercontent.com/26139666/131181690-c3dbe91a-8cd7-44c0-b013-b6b79ebfee09.png" alt="alt text" width="500" height="500">

## Environment

OS: Linux
Docker-Selenium image version: `selenium/standalone-chrome:4.0.0-rc-1-prerelease-20210804`, `selenium/standalone-chrome-debug:3.141.59-20210804` (We did test with different docker images)

The problem doesn't exist with `selenium/standalone-firefox:4.0.0-rc-1-prerelease-20210823`
We also test the same scenario outside of the selenium container while using the same google chrome and driver version used in the images above while executing the same command as it is used inside the container: `hrome --no-sandbox --disable-gpu-compositing --enable-crashpad`

**Comment by diemol** [comment] 2021-08-30 12:18
The difference between `selenium/standalone-chrome:4.0.0-rc-1-prerelease-20210804` and `selenium/standalone-firefox:4.0.0-rc-1-prerelease-20210823` is the Chrome version (92.0.4515.107 vs. 92.0.4515.159)

I just did an additional [release](https://github.com/SeleniumHQ/docker-selenium/releases/tag/3.141.59-20210830) to push 92.0.4515.159 also for Grid 3. 

Having said that, if the image looks fine in the most recent release, it indicates that it was an issue with Chrome directly. Also, both Grid 3 and 4 have now the version of Chrome that seems to work for your case. Therefore, I will close this issue.

**Comment by otodorov** [comment] 2021-08-30 13:10
We already tried with a bunch of different Chrome versions and we always got the same result -> When using Chrome inside the selenium container the image is always not rendered properly, but when we use exact same Chrome version outside the selenium container, everything is good.

**Comment by diemol** [comment] 2021-08-30 13:18
This is confusing. You mention above that the most recent tag works.

**Comment by otodorov** [comment] 2021-08-30 13:23
> This is confusing. You mention above that the most recent tag works.

Only when the Firefox browser is used. (Sorry if I didn't explain it well.)

I mean if you try that with `selenium/standalone-chrome:what_ever_version` it won't work
but if you try it with `selenium/standalone-firefox:what_ever_version` the problem doesn't exist.

**Comment by diemol** [comment] 2021-08-30 14:39
Apologies, I am the one who misread the report.

I think I know what the issue is, but I need some time to double check.

**Comment by diemol** [comment] 2021-08-30 14:58
I wanted to double check but I cannot load the site
![image](https://user-images.githubusercontent.com/5992658/131359589-85383256-24c4-4e9e-82f2-c8eed4664ce0.png)

Maybe what you can try is to use VNC to open manually Chrome and see how the website renders.

**Comment by otodorov** [comment] 2021-08-30 15:06
It seems we have some connectivity issues right now. 

> Maybe what you can try is to use VNC to open manually Chrome and see how the website renders.

I already did it, without any luck.

**Comment by diemol** [comment] 2021-08-30 15:23
To be honest, I am not sure what the issue could be. In the end, the container is using Ubuntu 20.04, XVFB, VNC, and a window manager to provide the view. You could try to replicate that setup on a real machine and see where the issue could be.

If you had the same issue while opening the browser manually, then my assumption is wrong, since I was thinking that `disable_gpu` was causing this.

Another question is, has this ever worked in any Chrome version inside our Docker images?

**Comment by otodorov** [comment] 2021-08-30 15:28
> You could try to replicate that setup on a real machine and see where the issue could be. 

This was replicated on Windows and Ubuntu

> If you had the same issue while opening the browser manually, then my assumption is wrong, since I was thinking that disable_gpu was causing this.

Opening the browser manually works fine. I also tried with and without `disable_gpu` option.

> Another question is, has this ever worked in any Chrome version inside our Docker images?

Do not remember if I did this test. Will test that tomorrow, we fix the URL.

**Comment by diemol** [comment] 2021-08-30 15:31
When you say:
>This was replicated on Windows and Ubuntu

It means that the website did not render properly on Windows and Ubuntu using Chrome?

Again, I am confused:
>Opening the browser manually works fine. I also tried with and without disable_gpu option.

Above you mentioned that you did not have any luck. 

So, when does it work, and when it does not?

**Comment by otodorov** [comment] 2021-08-30 15:45
When replicating the same scenario on Windows or Ubuntu (with or without disable_gpu) the issue doesn't exist.

When manually start Chrom with or without disable_gpu within a selenium container, the image is not rendered properly.

To summarize this:
- The image is not rendered properly only when we are using Chrome (whatever version) inside a selenium container (whatever version). It doesn't matter if we are using `disable_gpu` or not.

In all other cases, we do not have such an issue (for all these cases where we were using Chrom, we tried to open the browser from a CLI with this command `chrome --no-sandbox --disable-gpu-compositing --enable-crashpad` or this `chrome --no-sandbox  --enable-crashpad` and also open the Chrom as a normal user from the GUI):
- Using Firefox inside a selenium container 👉 no issue 
- Using Chrom from Windows VM 👉 no issue
- Using Chrom from Linux VM 👉 no issue

I did not tried (or at least do not remember) if I tried this from another container. Will do that tomorrow and will give you an update.

**Comment by diemol** [comment] 2021-08-30 15:57
Ok, please let us know when the url is accessible so we can have a look.

**Comment by otodorov** [comment] 2021-08-31 06:23
The [URL](http://qa-selenium-cluster.gratowin.com:30080/#/lobby) is accessible once again.

**Comment by otodorov** [comment] 2021-08-31 07:55
I just tested that from another container (not the Selenium's one) and if I remove the `--disable-gpu` option, it works fine.

**Comment by otodorov** [comment] 2021-09-03 06:44
Hey, @diemol did you had a chance to look at this?

**Comment by diemol** [comment] 2021-09-07 08:05
> I just tested that from another container (not the Selenium's one) and if I remove the `--disable-gpu` option, it works fine.

Yeah, that was my original question. 

The source of this is #1346, and it seems Chrome 93 is working fine. Therefore when https://github.com/SeleniumHQ/docker-selenium/pull/1382 gets merged and released, this issue should get fixed as well.

**Comment by diemol** [comment] 2021-09-07 13:06
This has been released https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.0.0-rc-2-prerelease-20210907

**Comment by otodorov** [comment] 2021-09-08 08:09
Hello @diemol 
We have the same issue after that release.

```bash
# docker ps
CONTAINER ID   IMAGE                                                       COMMAND                  CREATED        STATUS       PORTS                                                                                            NAMES
85eaccf76714   selenium/standalone-chrome:4.0.0-rc-2-prerelease-20210907   "/opt/bin/entry_poin…"   18 hours ago   Up 2 hours   0.0.0.0:4444->4444/tcp, :::4444->4444/tcp, 0.0.0.0:7900->7900/tcp, :::7900->7900/tcp, 5900/tcp   selenium-standalone-chrome-4.0.0-rc-2-prerelease-20210907
```

as I see from the `ps aux` output, the `/opt/google/chrome/chrome --no-sandbox --enable-crashpad` is without `--disable-gpu` option, but we still get the image that is not properly rendered.

```bash
seluser@85eaccf76714:/$ ps aux | grep chrome
seluser    156  0.0  0.0   2608   604 ?        Ss   06:59   0:00 /bin/sh -c /opt/google/chrome/google-chrome
seluser    157  6.1  1.7 17543344 233840 ?     Sl   06:59   4:02 /opt/google/chrome/chrome --no-sandbox --enable-crashpad
seluser    165  0.0  0.1 16825188 14072 ?      Sl   06:59   0:00 /opt/google/chrome/crashpad_handler --monitor-self --monitor-self-annotation=ptype=crashpad-handler --database=/home/seluser/.config/google-chrome/Crash Reports --metrics-dir=/home/seluser/.config/google-chrome --url=https://clients2.google.com/cr/report --annotation=channel= --annotation=lsb-release=Ubuntu 20.04.2 LTS --annotation=plat=Linux --annotation=prod=Chrome_Linux --annotation=ver=93.0.4577.63 --initial-client-fd=6 --shared-client-connection
seluser    168  0.0  0.0 16790500 2880 ?       Sl   06:59   0:00 /opt/google/chrome/crashpad_handler --no-periodic-tasks --monitor-self-annotation=ptype=crashpad-handler --database=/home/seluser/.config/google-chrome/Crash Reports --url=https://clients2.google.com/cr/report --annotation=channel= --annotation=lsb-release=Ubuntu 20.04.2 LTS --annotation=plat=Linux --annotation=prod=Chrome_Linux --annotation=ver=93.0.4577.63 --initial-client-fd=4 --shared-client-connection
seluser    172  0.0  0.4 17038680 57636 ?      S    06:59   0:00 /opt/google/chrome/chrome --type=zygote --no-zygote-sandbox --no-sandbox --enable-crashpad --crashpad-handler-pid=0 --enable-crash-reporter=54f6ca37-2ab9-4f07-bda9-6f5b191b0af2, --enable-crashpad
seluser    173  0.0  0.4 17038680 57656 ?      S    06:59   0:00 /opt/google/chrome/chrome --type=zygote --no-sandbox --enable-crashpad --crashpad-handler-pid=0 --enable-crash-reporter=54f6ca37-2ab9-4f07-bda9-6f5b191b0af2, --enable-crashpad
seluser    174  0.0  0.0 16790644 3500 ?       S    06:59   0:00 /opt/google/chrome/nacl_helper --no-sandbox
seluser    213  0.1  0.7 17089896 95012 ?      Sl   06:59   0:07 /opt/google/chrome/chrome --type=utility --utility-sub-type=network.mojom.NetworkService --field-trial-handle=10258228900781701481,8599180522043180220,131072 --lang=en-US --service-sandbox-type=none --no-sandbox --enable-crashpad --crashpad-handler-pid=0 --enable-crash-reporter=54f6ca37-2ab9-4f07-bda9-6f5b191b0af2, --shared-files=v8_context_snapshot_data:100 --enable-crashpad
seluser    222  0.0  0.3 17080088 42764 ?      Sl   06:59   0:00 /opt/google/chrome/chrome --type=utility --utility-sub-type=storage.mojom.StorageService --field-trial-handle=10258228900781701481,8599180522043180220,131072 --lang=en-US --service-sandbox-type=utility --no-sandbox --enable-crashpad --crashpad-handler-pid=0 --enable-crash-reporter=54f6ca37-2ab9-4f07-bda9-6f5b191b0af2, --shared-files=v8_context_snapshot_data:100
seluser    239 15.0  1.4 21452016 187260 ?     Sl   06:59   9:54 /opt/google/chrome/chrome --type=renderer --enable-crashpad --crashpad-handler-pid=0 --enable-crash-reporter=54f6ca37-2ab9-4f07-bda9-6f5b191b0af2, --no-sandbox --field-trial-handle=10258228900781701481,8599180522043180220,131072 --lang=en-US --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=6 --no-v8-untrusted-code-mitigations --shared-files=v8_context_snapshot_data:100
seluser    343  5.1  0.6 17131352 88628 ?      Sl   06:59   3:23 /opt/google/chrome/chrome --type=gpu-process --field-trial-handle=10258228900781701481,8599180522043180220,131072 --no-sandbox --enable-crashpad --crashpad-handler-pid=0 --enable-crash-reporter=54f6ca37-2ab9-4f07-bda9-6f5b191b0af2, --gpu-preferences=UAAAAAAAAAAgAAAQAAAAAAAAAAAAAAAAAABgAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAABgAAAAAAAAAGAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAACAAAAAAAAAA= --use-gl=disabled --shared-files
seluser    396  0.0  0.5 17069692 71668 ?      Sl   06:59   0:00 /opt/google/chrome/chrome --type=utility --utility-sub-type=audio.mojom.AudioService --field-trial-handle=10258228900781701481,8599180522043180220,131072 --lang=en-US --service-sandbox-type=none --no-sandbox --enable-crashpad --crashpad-handler-pid=0 --enable-crash-reporter=54f6ca37-2ab9-4f07-bda9-6f5b191b0af2, --shared-files=v8_context_snapshot_data:100 --enable-crashpad
seluser    676  1.1  1.6 21440296 216048 ?     Sl   07:07   0:41 /opt/google/chrome/chrome --type=renderer --enable-crashpad --crashpad-handler-pid=0 --enable-crash-reporter=54f6ca37-2ab9-4f07-bda9-6f5b191b0af2, --no-sandbox --field-trial-handle=10258228900781701481,8599180522043180220,131072 --disable-gpu-compositing --lang=en-US --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=28 --no-v8-untrusted-code-mitigations --shared-files=v8_context_snapshot_data:100
seluser    722  0.0  0.8 21392872 112628 ?     Sl   07:14   0:02 /opt/google/chrome/chrome --type=renderer --enable-crashpad --crashpad-handler-pid=0 --enable-crash-reporter=54f6ca37-2ab9-4f07-bda9-6f5b191b0af2, --no-sandbox --field-trial-handle=10258228900781701481,8599180522043180220,131072 --disable-gpu-compositing --lang=en-US --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=29 --no-v8-untrusted-code-mitigations --shared-files=v8_context_snapshot_data:100
seluser    740  0.0  0.4 21337624 58812 ?      Sl   07:14   0:00 /opt/google/chrome/chrome --type=renderer --enable-crashpad --crashpad-handler-pid=0 --enable-crash-reporter=54f6ca37-2ab9-4f07-bda9-6f5b191b0af2, --no-sandbox --field-trial-handle=10258228900781701481,8599180522043180220,131072 --disable-gpu-compositing --lang=en-US --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=30 --no-v8-untrusted-code-mitigations --shared-files=v8_context_snapshot_data:100
seluser    964  0.0  0.0   9032   724 pts/0    S+   08:05   0:00 grep --color=auto chrome
```

<img src="https://user-images.githubusercontent.com/26139666/131181825-a5cf1dcf-e950-4aeb-b7b9-fdfb4e6eb913.png" alt="alt text" width="500" height="500">

**Comment by diemol** [comment] 2021-09-08 11:23
That is not ideal, I really thought the flag removal should have fixed this.

I will reopen the issue and add a `help wanted` label, because I do not know what could be causing this. Hopefully you can give us a hand and help us find the root cause?

**Comment by otodorov** [comment] 2021-09-08 11:36
> Hopefully you can give us a hand and help us find the root cause?

Yes, of course. I already tried a bunch of scenarios even removing the `--disable-gpu` without any luck. Currently, I'm out of ideas, so please let me know if you have any.

I will summarize here again already tested scenarios, where that issue appears:
- removing the `--disable-gpu` flag
- Using a bunch of different versions of Selenium image
- Using a bunch of different versions of Google Chrome browsers + Chrome drivers inside Selenium container

**Comment by diemol** [comment] 2021-09-08 11:38
Maybe to add more details to this issue... Has this ever worked properly with Chrome inside a Docker image?

**Comment by otodorov** [comment] 2021-09-08 12:35
> Maybe to add more details to this issue... Has this ever worked properly with Chrome inside a Docker image?

Actually, I just noted that for some of the tests when I used another image instead the Selenium one, I used the `chromium-brower` instead 👉 [consol/ubuntu-xfce-vnc](https://hub.docker.com/r/consol/ubuntu-xfce-vnc/)
`chromium-browser 70.0.3538.67-0ubuntu0.16.04.1`
```bash
default@1c7a34fa97fc:~/Desktop$ dpkg -la | grep chrom
ii  chromium-browser                     70.0.3538.67-0ubuntu0.16.04.1              amd64        Chromium web browser, open-source version of Chrome
ii  chromium-browser-l10n                70.0.3538.67-0ubuntu0.16.04.1              all          chromium-browser language packages
ii  chromium-codecs-ffmpeg               70.0.3538.67-0ubuntu0.16.04.1              amd64        Free ffmpeg codecs for the Chromium Browser
```

So after removing that one and install `google-chrome-stable  93.0.4577.63-1`, the problem exists once again.
So this means the issue is in the chrome browser instead of the Selenium.

**Comment by diemol** [comment] 2021-09-09 12:49
Yeah, it is not something we do in this Docker images... Not sure if there is an additional package that needs to be installed to render things properly. But I would ask or raise an issue with the Chromium team, either at https://bugs.chromium.org/p/chromium or https://bugs.chromium.org/p/chromedriver.

**Comment by otodorov** [comment] 2021-09-10 12:46
A brief update:
I prepared 2 new docker images based on `selenium/node-base:4.0.0-rc-2-prerelease-20210907` and `dorowu/ubuntu-desktop-lxde-vnc:focal` as well (Both of them are Ubuntu 20.04.2 LTS (Focal Fossa)).After that, I installed the Chromium browser on top of them, by using the Ubuntu 16.04 repository. Chromium browser for Ubuntu 20.04 is supported only through snap, but snapd is not supported under docker, so that is the reason for adding an older Ubuntu repository.

In both cases, the image is not rendered properly. 

The previous image `consol/ubuntu-xfce-vnc` that I used and the test succeeded was based on `ubuntu:16.04`

**Comment by otodorov** [comment] 2021-09-16 07:36
Hey @diemol did you raise a ticket to chromium? Can you paste the link so I can follow it as well?

**Comment by diemol** [comment] 2021-09-16 07:39
I did not. I would need to give them something they can use to reproduce the issue and I do not have that. Perhaps you can do that?

**Comment by otodorov** [comment] 2021-09-16 07:43
Isn't the first comment enough [link](https://github.com/SeleniumHQ/docker-selenium/issues/1376#issue-98157218)?
The URL and the account still exist if they want to test anything.

**Comment by diemol** [comment] 2021-09-16 07:58
Yeah, maybe that is be enough. Feel free to post here the link of the issue so others can follow as well, thanks!

**Comment by otodorov** [comment] 2021-09-16 08:15
Here is the issue to Chromium https://bugs.chromium.org/p/chromium/issues/detail?id=1250214

**Comment by diemol** [comment] 2021-11-03 13:09
Closing as there is already an issue in the Chromium issue tracker for this, thank you for sharing the link!

**Closed as completed by diemol** 2021-11-03 13:09 UTC
