### ISSUE TITLE
Chrome crashing due to /dev/shm filesystem lacking execution permissions for Docker Desktop and the WSL2 setup.

### ISSUE THREAD

**Issue by theddub** [SeleniumHQ/docker-selenium#1309] opened 2021-06-03 15:10 UTC
## 🐛 Bug Report

Chrome crashing due to /dev/shm filesystem lacking execution permissions for Docker Desktop and the WSL2 setup.

![image](https://user-images.githubusercontent.com/14294692/120667922-31154180-c44b-11eb-9d70-6ebf311a8fef.png)

## To Reproduce

Do "Execution with Standalone roles": (or Execution with Hub & Node roles)
docker run --rm --name selenium-docker -p 4444:4444 \
    -v ${PWD}/config.toml:/opt/bin/config.toml \
    -v /path/on/your/host/machine:/opt/selenium/assets \
    selenium/standalone-docker:4.0.0-beta-4-prerelease-20210527

I wrote up an explanation here: 

I believe there is a defect/issue with the /dev/shm filesystem which causes Chrome(and Edge) to crash while in a Docker container AND executed from a WSL2 distro. This only happens in a Windows environment and Docker Desktop etc..
I say this because we get a message from the remote Selenium Grid Docker from the Dynamic Grid container(Execution with Standalone roles OR Execution with Hub & Node roles etc…) saying Chrome has crashed in the standalone Chrome container:

"Stopping driver service: Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: crashed.
(unknown error: DevToolsActivePort file doesn't exist)
(The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)"

Usually when we get a Chrome has “crashed” error it’s due to the /dev/shm filesystem. Either not in the right spot, not -v mounted in the container or not big enough. Obviously we have fixed this before doing the increasing the  --shm-size flag or -v /dev/shm:/dev/shm or -disable-dev-shm-usage etc.. However, when executing a standalone Chrome container from Selenium Grid 4, the Dynamic Grid feature to be exact, we encounter a new version of the Chrome has “crashed” error.
If we run the Dynamic Grid in Linux w/Selenium Grid 4 and Docker ….we do not have this or any errors. If we run the Dynamic Grid in Windows with Docker Desktop and Docker Engine using the Hyper-V backend and DockerDesktopVM….we do not have any errors. If we run the Dynamic Grid in Windows with Docker Desktop and Docker Engine using WSL2 backend(and the docker-desktop WSL2 distro)THEN we get this error and ONLY then do we get the above error. I can further elaborate on the error and what we discovered.
What we see is that the /dev/shm size exists and is sufficiently large enough for Chrome to startup in ALL cases. But what my coworker discovered is that the PERMISSIONS for the /dev/shm filesystem is different for the WSL2 setup versus the Hyper-V backend with Docker Desktop.
Obviously Chrome isn’t ready to start up in the small lifespan of the WSL2 supported container, but we tried it and received the information about the permissions to look into it further:

![image](https://user-images.githubusercontent.com/14294692/120668178-7174bf80-c44b-11eb-9fcc-d4786ea63c29.png)

 
“Caused by incorrect permission on /dev/shm” etc…
Compare the WSL2 supported Chrome container /dev/shm permissions to the Hyper-V supported Chrome container we get:
WSL2(Chrome crashes):
 
![image](https://user-images.githubusercontent.com/14294692/120668084-5c982c00-c44b-11eb-9cc6-d696f401184e.png)

Versus Hyper-V(Chrome works):

![image](https://user-images.githubusercontent.com/14294692/120668106-628e0d00-c44b-11eb-8178-dc5e3df29be8.png)

 
So where it work on Hyper-V, we have x(execute) permissions for all 3 User, Group and Other. Whereas we do not have execute permissions for any of the 3 categories in the WSL2 setup. 
I don’t think the issue lies with Selenium Grid 4(or Selenium Grid for that matter) as they are just executing Docker commands in their code and it works for Linux and Hyper-V supported Docker Desktop on Windows. Since we believe this is a permissions issue with the “Linux” backed WSL2, we are unsure if the root cause or issue lies with Docker Desktop and how it’s docker-desktop WSL2 distro interacts with the WSL2 or if this possible permissions issue lies with WSL2 in the same said interaction. I personally suspect it has to do more with the WSL2, but since I cannot log an issue with Microsoft for the WSL2-Linux-Kernel repository on GitHub, I’m trying to leave this information here in this repository. Thanks for any support and/or information.

## Expected behavior

Chrome standalone container not to crash
## Test script reproducing this issue (when applicable)

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: Windows 10 Pro
selenium/standalone-docker:4.0.0-beta-4-prerelease-20210527
&
"selenium/standalone-chrome:4.0.0-beta-4-prerelease-20210527"

-->
Docker version: 
Docker Desktop 3.3.3
Docker Engine v20.10.6
WSL2 based engine(This all works on "legacy Hyper-V backend"

**Comment by diemol** [comment] 2021-07-13 12:37
We have switched all examples and docs to use `shm_size` instead of mounting `/dev/shm`, please double check our README which shows how to do it, this works for all OS.

Fixed by https://github.com/SeleniumHQ/docker-selenium/commit/368081095edf40f2b087ca8cfcf9d40151de8c80

**Closed as completed by diemol** 2021-07-13 12:37 UTC

**Comment by theddub** [comment] 2021-07-15 14:58
So this works in legacy Hyper-V use for Docker Desktop on Windows, does not work in docker-desktop or Ubuntu WSL2 distros. I noticed that a regular and basic alpine-slim 3.5 docker image doesn't have this filesystem /dev/shm permission issue when launced from my modified config.toml for the standalone-docker for the Dynamic Grid such as:


(tester/tester is just a basic alpine-slim 3.5 container with openjdk)
configs = [
    "docker.io/tester/tester", "{\"browserName\": \"chrome\"}"
    ]

obviously this doesn't have Chrome and doesn't work with Remote Webdriver but as a test case I can see that the container has the correct executable filesystem privileges for /dev/shm. 

So I took that and added "RUN sudo chmod +x /dev/shm" to your Standalone\Dockerfile.txt and that fixed the issue for file permissions for /dev/shm for WSL2 and Docker Desktop and the Dynamic Grid.

My thoughts are that it's a combination of issues with your standalone-chrome (or others) Chrome container build and the WSL2 either WSL2 kernel or WSL2 distros when used by Docker Desktop. I say that because your standalone-chrome **currently** , as is, works(has correct execute /dev/shm file permissions) when used with the legacy Hyper-V vm for Docker Desktop. **However** Docker Desktop with WSL2 with your Dynamic Grid standalone-docker does have the /dev/shm executable permissions issue when NOT using your standalone-chrome image and I can get it to work with your standalone-chrome container **with the modification** to the Dockerfile.txt for it. So I'm not quite sure where the correct solution needs to be made. What I did feels more like a workaround. If you had access to the Docker Desktop code or distro code maybe something there instead. But at least what I did works for now although, like I mentioned, it doesn't feel like the correct fix.

**Comment by theddub** [comment] 2021-07-15 15:01
> We have switched all examples and docs to use `shm_size` instead of mounting `/dev/shm`, please double check our README which shows how to do it, this works for all OS.
> 
> Fixed by [3680810](https://github.com/SeleniumHQ/docker-selenium/commit/368081095edf40f2b087ca8cfcf9d40151de8c80)

That's not the issue. It's **not the SIZE of shm**...it's the **file permissions**. If you look at my screenshots and explanation.

**Comment by theddub** [comment] 2021-07-15 15:01
Please reopen this issue.

**Comment by theddub** [comment] 2021-07-15 15:03
@diemol Please reopen this issue.

It's not the **SIZE** of shm...it's the **file permissions**. If you look at my screenshots and explanation.

**Comment by theddub** [comment] 2021-07-15 15:04
My /dev/shm size is 2GB and still crashing due to file permissions.

**Comment by theddub** [comment] 2021-07-15 15:07
See my /dev/shm size is 4GB actually in your container spun up. I've dealt with /dev/shm size issues before.....it's 4GB at this time and it's not, this time, a /dev/shm file size issue. It's the file permissions this time. If the file permissions on the /dev/shm is changed in my case, it works, because it's already 4GB....ie...sufficient in size. From the beginning of my logged issue. my /dev/shm file system size has been 4GB that's why I didn't mention it as a problem, because the size is not the problem.

![image](https://user-images.githubusercontent.com/14294692/125819053-8ada261d-de3c-44cf-97c4-c77a42e6cb61.png)

**Comment by theddub** [comment] 2021-07-15 15:08
And it still crashes because of file permissions:

![image](https://user-images.githubusercontent.com/14294692/125811511-b3e36310-f3ba-46e0-811b-69775fc1d75e.png)

**Comment by theddub** [comment] 2021-07-15 15:13
@diemol Plus I fixed it with a "band-aid" fix by modifying your Dockerfile.txt with a chmod on /dev/shm for your standalone-chrome container....But, I don't think that's the right fix. Please read my original and follow up posts for clarification.

**Comment by theddub** [comment] 2021-07-15 15:52
@diemol @stigkj @jamesottaway @shs96c can someone reopen this issue? My /dev/shm filesystem size has always been 4GB which is why I didn't mention the file size originally...ie...it is not the problem.

**Comment by diemol** [comment] 2021-07-15 16:03
We never mentioned that the size of the shm was the issue, the issue was how it was being mounted. As we did not have time to dig into the root cause, we offer the alternative command to extend the shm size in the container. 

Now that you have dig into the root cause, would you like to provide a pull request to help us fix it?

**Comment by theddub** [comment] 2021-07-15 16:14
Yes I can. I just hesitated in doing so because I feel like it's a "band-aid" fix because I know the root cause is the file permissions for /dev/shm I just don't know if it's something to be fixed in(or a combination of)  :1)The Windows WSL2 kernel 2)All or any of the WSL2 distros(docker-desktop or ubuntu etc..) 3)Docker Desktop or 4)this repo(where I am able to provide my simple fix though not sure it belongs here). I'll go ahead and PR it though anyways.

**Comment by diemol** [comment] 2021-07-15 16:23
Me neither, that is why we updated the docs to show options that work in all operating systems when using any version of Docker. 
In addition, `/dev/shm` was confusing for some Windows users as they thought they had to adapt that `path` to something more Windows-ish. 

You are right, I guess it would be good to find out if the issue is with Docker Desktop or if each docker image needs to fix this on its own.

**Comment by theddub** [comment] 2021-07-15 16:29
Yeah, I'm not sure either. My gut tells me it's a combination of Docker Desktop with WSL2 and this repo. Because 1)This repo works with Docker Desktop and Hyper-V legacy(instead of WSL2) (with Dynamic Grid starting chrome standalone)  and otherwise, in the reverse direction: 2)Docker Desktop with WSL2 works(with Dynamic Grid starting another container) with a generic linux container not from this repo.

Here's is the PR: https://github.com/SeleniumHQ/docker-selenium/pull/1334

Thank you @diemol

**Comment by theddub** [comment] 2021-07-15 16:52
Oh in case I didn't mention it before. It works perfectly fine in Linux without any changes, ie...Docker Desktop with WSL2 only has the problem.
