### ISSUE TITLE
[🐛 Bug]: Deploying to Kubernetes, there are concurrent requests but the execution time is fixed by about 5 seconds

### ISSUE THREAD

**Issue by proQs** [SeleniumHQ/docker-selenium#1684] opened 2022-09-28 09:39 UTC
### What happened?

Deploying to Kubernetes, there are concurrent requests but the execution time is fixed by about 5 seconds
As shown below
[https://github.com/proQs/myConfig/blob/79a311c6a895d285cba8bdad4957e30bce09a924/4f7d-b33c-da5f68fa4509.png](url)
When k8s is not used, concurrent requests are basically executed at the same time

### Command used to start Selenium Grid with Docker

```shell
helm install selenium-grid docker-selenium/selenium-grid --version 0.8.0 --set isolateComponents=false --set ingress.enabled=false --set chromeNode.enabled=false --set firefoxNode.enabled=false --set edgeNode.enabled=false --set hub.serviceType=NodePort

docker run -d -p 5555:5555     -e SE_EVENT_BUS_HOST=     -e SE_EVENT_BUS_PUBLISH_PORT=30665     -e SE_EVENT_BUS_SUBSCRIBE_PORT=30384     -v /data/se/dockersel/config.toml:/opt/bin/config.toml     -v /data/se/dockersel/assets:/opt/selenium/assets     -v /var/run/docker.sock:/var/run/docker.sock -v /etc/localtime:/etc/localtime    selenium/node-docker:4.3.0-20220706
```

### Relevant log output

```shell
https://github.com/proQs/myConfig/blob/79a311c6a895d285cba8bdad4957e30bce09a924/4f7d-b33c-da5f68fa4509.png
```

### Operating System

ubuntu

### Docker Selenium version (tag)

4.3.0-20220706

**Comment by jamesmortensen** [comment] 2022-10-04 14:49
Hi @proQs sorry for the delay in getting back to you.  One of our core members is currently away, and I'm not sure what the solution would be or for what else you could try to get this to work, at least not at this time.  

In the meantime, if there's any additional information you'd like to provide to help us replicate the issue, maybe in a test GitHub repo, that would be helpful.

**Comment by diemol** [comment] 2022-10-14 07:42
I do not really understand what the issue is. There is not enough information provided, not a way to reproduce it, or even logs from the test execution and the Grid. I will leave this open for a couple of days but if no more information is provided, then it will be closed.

**Comment by diemol** [comment] 2022-10-18 10:09
I will close this since no more information was provided.

**Closed as completed by diemol** 2022-10-18 10:09 UTC
Labels: R-awaiting-answer
