### ISSUE TITLE
[🐛 Bug]: [Dynamic Grid] Cannot pass environment variables to the config.toml file

### ISSUE THREAD

**Issue by kirill-predkel-idf** [SeleniumHQ/docker-selenium#1548] opened 2022-04-14 15:28 UTC
### What happened?

Hi ! I have an issue with dynamic grid using. I was trying to create dynamic grid with standard Readme solution.
What I want is to run selenium/standalone-chrome instances with defined screen resolution.
I passed it as env variables like that:

[docker]
configs = ["selenium/standalone-chrome:4.1.3-20220405", "{\"browserName\": \"chrome\", \"browserVersion\": \"100\"}"]
environment = ["SCREEN_WIDTH=1600", "SCREEN_HEIGHT=1200"]
url = "http://127.0.0.1:2375"

but still got standard 1360x1020 (please find the evidence attached).
Is it correct way to pass env vars or is there any workarund ? 
Thanks in advance ! 

### Command used to start Selenium Grid with Docker

```shell
docker-compose -f docker-compose.yml up
```

### Relevant log output

```shell
Selenium Grid Standalone configuration: 
[network]
relax-checks = true
[node]
session-timeout = "300"
override-max-sessions = false
detect-drivers = false
max-sessions = 1
[[node.driver-configuration]]
display-name = "chrome"
stereotype = '{"browserName": "chrome", "browserVersion": "100.0", "platformName": "Linux"}'
max-sessions = 1
Starting Selenium Grid Standalone...
15:24:52.791 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
15:24:52.796 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
15:24:53.476 INFO [NodeOptions.getSessionFactories] - Detected 8 available processors
15:24:53.526 INFO [NodeOptions.report] - Adding chrome for {"browserVersion": "100.0","se:noVncPort": 7900,"browserName": "chrome","platformName": "Linux","se:vncEnabled": true} 1 times
15:24:53.543 INFO [Node.<init>] - Binding additional locator mechanisms: id, name, relative
15:24:53.571 INFO [GridModel.setAvailability] - Switching node 8b71f392-eb8d-4b6c-86e0-77b479856b99 (uri: http://172.21.0.6:4444) from DOWN to UP
15:24:53.572 INFO [LocalDistributor.add] - Added node 8b71f392-eb8d-4b6c-86e0-77b479856b99 at http://172.21.0.6:4444. Health check every 120s
15:24:53.729 INFO [Standalone.execute] - Started Selenium Standalone 4.1.3 (revision 7b1ebf28ef): http://172.21.0.6:4444
15:24:54.036 INFO [LocalDistributor.newSession] - Session request received by the distributor: 
 [Capabilities {acceptInsecureCerts: true, acceptSslCerts: true, browserName: chrome, goog:chromeOptions: {args: [--proxy-bypass-list=<-loopb..., --disable-dev-shm-usage, --no-sandbox], excludeSwitches: [enable-automation, load-extension], extensions: [], prefs: {credentials_enable_service: false, plugins.always_open_pdf_externally: true, profile.default_content_setting_values.automatic_downloads: 1, safebrowsing.enabled: true}}, handlesAlerts: true, javascriptEnabled: true, pageLoadStrategy: normal, takesScreenshot: true}, Capabilities {acceptInsecureCerts: true, browserName: chrome, goog:chromeOptions: {args: [--proxy-bypass-list=<-loopb..., --disable-dev-shm-usage, --no-sandbox], excludeSwitches: [enable-automation, load-extension], extensions: [], prefs: {credentials_enable_service: false, plugins.always_open_pdf_externally: true, profile.default_content_setting_values.automatic_downloads: 1, safebrowsing.enabled: true}}, pageLoadStrategy: normal}]
```

### Operating System

Windows 10

### Docker Selenium version (tag)

4.1.3-20220405

**Comment by diemol** [comment] 2022-04-14 15:34
Duplicate of #1319

**Closed as completed by diemol** 2022-04-14 15:34 UTC
