### ISSUE TITLE
[🐛 Bug]: Firefox - Invalid status code=400 text=Bad Request

### ISSUE THREAD

**Issue by xescuder** [SeleniumHQ/docker-selenium#1511] opened 2022-02-18 13:23 UTC
### What happened?

I am using your example **docker-compose-v3.yml**.

Using chrome everything works fine, but firefox is giving an error when trying to create a new session (see log output), so the tests are not being executed.

### Command used to start Selenium Grid with Docker

```shell
docker-compose -f docker-compose-v3.yml up
```

### Relevant log output

```shell
firefox_1       | 12:56:20.863 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
selenium-hub    | 12:56:20.911 INFO [LocalDistributor.newSession] - Session created by the distributor. Id: ddb23020-d244-4bfe-97ee-de7d6c2161ae, Caps: Capabilities {acceptInsecureCerts: false, browserName: firefox, browserVersion: 97.0.1, moz:accessibilityChecks: false, moz:buildID: 20220216172458, moz:geckodriverVersion: 0.30.0, moz:headless: false, moz:processID: 152, moz:profile: /tmp/rust_mozprofilekCVPjH, moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platformName: linux, platformVersion: 5.10.47-linuxkit, proxy: {}, se:cdp: ws://localhost:4444/session..., se:vnc: ws://localhost:4444/session..., se:vncEnabled: true, se:vncLocalAddress: ws://172.25.0.3:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
selenium-hub    | 12:56:21.156 WARN [ProxyWebsocketsIntoGrid$ForwardingListener.onError] - Error proxying websocket command
selenium-hub    | java.io.IOException: Invalid Status code=400 text=Bad Request
selenium-hub    |       at org.asynchttpclient.netty.handler.WebSocketHandler.abort(WebSocketHandler.java:92)
selenium-hub    |       at org.asynchttpclient.netty.handler.WebSocketHandler.handleRead(WebSocketHandler.java:118)
selenium-hub    |       at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:78)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
selenium-hub    |       at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
selenium-hub    |       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
selenium-hub    |       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314)
selenium-hub    |       at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435)
selenium-hub    |       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
selenium-hub    |       at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
selenium-hub    |       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
selenium-hub    |       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
selenium-hub    |       at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
selenium-hub    |       at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
selenium-hub    |       at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
selenium-hub    |       at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
selenium-hub    |       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
selenium-hub    |       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
selenium-hub    |       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
selenium-hub    |       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
selenium-hub    |       at java.base/java.lang.Thread.run(Thread.java:829)
selenium-hub    | 12:56:21.252 WARN [ProxyWebsocketsIntoGrid$ForwardingListener.onError] - Error proxying websocket command
selenium-hub    | java.io.IOException: Invalid Status code=400 text=Bad Request
selenium-hub    |       at org.asynchttpclient.netty.handler.WebSocketHandler.abort(WebSocketHandler.java:92)
selenium-hub    |       at org.asynchttpclient.netty.handler.WebSocketHandler.handleRead(WebSocketHandler.java:118)
selenium-hub    |       at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:78)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
selenium-hub    |       at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
selenium-hub    |       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
selenium-hub    |       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314)
selenium-hub    |       at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435)
selenium-hub    |       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
selenium-hub    |       at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
selenium-hub    |       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
selenium-hub    |       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
selenium-hub    |       at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
selenium-hub    |       at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
selenium-hub    |       at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
selenium-hub    |       at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
selenium-hub    |       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
selenium-hub    |       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
selenium-hub    |       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
selenium-hub    |       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
selenium-hub    |       at java.base/java.lang.Thread.run(Thread.java:829)
selenium-hub    | 12:56:21.417 WARN [ProxyWebsocketsIntoGrid$ForwardingListener.onError] - Error proxying websocket command
selenium-hub    | java.io.IOException: Invalid Status code=400 text=Bad Request
selenium-hub    |       at org.asynchttpclient.netty.handler.WebSocketHandler.abort(WebSocketHandler.java:92)
selenium-hub    |       at org.asynchttpclient.netty.handler.WebSocketHandler.handleRead(WebSocketHandler.java:118)
selenium-hub    |       at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:78)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
selenium-hub    |       at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
selenium-hub    |       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
selenium-hub    |       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314)
selenium-hub    |       at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435)
selenium-hub    |       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
selenium-hub    |       at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
selenium-hub    |       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
selenium-hub    |       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
selenium-hub    |       at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
selenium-hub    |       at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
selenium-hub    |       at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
selenium-hub    |       at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
selenium-hub    |       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
selenium-hub    |       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
selenium-hub    |       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
selenium-hub    |       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
selenium-hub    |       at java.base/java.lang.Thread.run(Thread.java:829)
selenium-hub    | 12:56:21.488 WARN [ProxyWebsocketsIntoGrid$ForwardingListener.onError] - Error proxying websocket command
selenium-hub    | java.io.IOException: Invalid Status code=400 text=Bad Request
selenium-hub    |       at org.asynchttpclient.netty.handler.WebSocketHandler.abort(WebSocketHandler.java:92)
selenium-hub    |       at org.asynchttpclient.netty.handler.WebSocketHandler.handleRead(WebSocketHandler.java:118)
selenium-hub    |       at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:78)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
selenium-hub    |       at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
selenium-hub    |       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
selenium-hub    |       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314)
selenium-hub    |       at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435)
selenium-hub    |       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
selenium-hub    |       at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
selenium-hub    |       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
selenium-hub    |       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
selenium-hub    |       at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
selenium-hub    |       at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
selenium-hub    |       at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
selenium-hub    |       at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
selenium-hub    |       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
selenium-hub    |       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
selenium-hub    |       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
selenium-hub    |       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
selenium-hub    |       at java.base/java.lang.Thread.run(Thread.java:829)
selenium-hub    | 12:56:21.584 WARN [ProxyWebsocketsIntoGrid$ForwardingListener.onError] - Error proxying websocket command
selenium-hub    | java.io.IOException: Invalid Status code=400 text=Bad Request
selenium-hub    |       at org.asynchttpclient.netty.handler.WebSocketHandler.abort(WebSocketHandler.java:92)
selenium-hub    |       at org.asynchttpclient.netty.handler.WebSocketHandler.handleRead(WebSocketHandler.java:118)
selenium-hub    |       at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:78)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
selenium-hub    |       at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
selenium-hub    |       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
selenium-hub    |       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314)
selenium-hub    |       at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435)
selenium-hub    |       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
selenium-hub    |       at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
selenium-hub    |       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
selenium-hub    |       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
selenium-hub    |       at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
selenium-hub    |       at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
selenium-hub    |       at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
selenium-hub    |       at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
selenium-hub    |       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
selenium-hub    |       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
selenium-hub    |       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
selenium-hub    |       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
selenium-hub    |       at java.base/java.lang.Thread.run(Thread.java:829)
selenium-hub    | 12:56:21.669 WARN [ProxyWebsocketsIntoGrid$ForwardingListener.onError] - Error proxying websocket command
selenium-hub    | java.io.IOException: Invalid Status code=400 text=Bad Request
selenium-hub    |       at org.asynchttpclient.netty.handler.WebSocketHandler.abort(WebSocketHandler.java:92)
selenium-hub    |       at org.asynchttpclient.netty.handler.WebSocketHandler.handleRead(WebSocketHandler.java:118)
selenium-hub    |       at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:78)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
selenium-hub    |       at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
selenium-hub    |       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
selenium-hub    |       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314)
selenium-hub    |       at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435)
selenium-hub    |       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
selenium-hub    |       at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
selenium-hub    |       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
selenium-hub    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
selenium-hub    |       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
selenium-hub    |       at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
selenium-hub    |       at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
selenium-hub    |       at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
selenium-hub    |       at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
selenium-hub    |       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
selenium-hub    |       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
selenium-hub    |       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
selenium-hub    |       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
selenium-hub    |       at java.base/java.lang.Thread.run(Thread.java:829)
```

### Operating System

macOS Catalina

### Docker Selenium version (tag)

4.1.2-20220217

**Comment by diemol** [comment] 2022-02-19 18:51
Duplicate of https://github.com/SeleniumHQ/selenium/issues/10348, there is a bug in Firefox 97 when using `Augmenter` or the CDP tools. Need to wait for Firefox 98 or use 96.

**Closed as completed by diemol** 2022-02-19 18:51 UTC

**Comment by xescuder** [comment] 2022-02-22 09:14
Tried with 96, same problem arises.

**Comment by diemol** [comment] 2022-02-22 09:31
How did you try it? Can you share the compose file and the test used?

**Comment by xescuder** [comment] 2022-02-22 09:39
My docker-compose:

```
version: "3"
services:
  firefox:
    image: selenium/node-firefox:96.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://localhost:4444

  selenium-hub:
    image: selenium/hub:4.1.2-20220208
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
```

I can't share the test used, as it's coupled with SerenityBDD, but it's not starting anything... It fails before opening the first url.

**Comment by diemol** [comment] 2022-02-22 09:41
Maybe you can share a reduced version of it?
