### ISSUE TITLE
[🐛 Bug]: Selenium Grid 4.20.0 not fetching node after some time 

### ISSUE THREAD

**Issue by Amanyadav12345** [SeleniumHQ/docker-selenium#2236] opened 2024-04-29 13:01 UTC
### What happened?

We can see 504 errors on the grid setup 

![image_2024_04_23T13_42_34_579Z](https://github.com/SeleniumHQ/docker-selenium/assets/86338519/a7a8da1a-763b-4eab-bf82-0b91d897a655)

and if we rerun the hub then it's coming to normal for some time and does the same thing again 
no logs are there for tracing in hub-nodes logs 

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
We use CLI commands
```

### Relevant log output

```shell
No log was seen on the grid setup
```

### Operating System

Windows server 2016 datacenter

### Docker Selenium version (image tag)

4.20.0

### Selenium Grid chart version (chart version)

4.20.0

**Comment by diemol** [comment] 2024-04-29 13:25
How can we reproduce the issue? You are sharing zero details on how you deploy the Grid.

**Comment by VietND96** [comment] 2024-05-03 03:58
@Amanyadav12345, have you deployed on K8s or docker compose?

**Comment by VietND96** [comment] 2024-09-20 04:22
I close this ticket since there is no input further

**Closed as not planned by VietND96** 2024-09-20 04:22 UTC
Labels: R-awaiting-answer
