### ISSUE TITLE
Error when generating screenshot from webUI

### ISSUE THREAD

**Issue by Akkarine** [SeleniumHQ/docker-selenium#969] opened 2019-10-04 22:12 UTC
## 🐛 Bug Report

Screenshot taken from webUI is send as blob in base64 with error

## To Reproduce

Start docker image, go to page:
http://127.0.0.1:4444/wd/hub/static/resource/hub.html
Run selenium tests with remote WebDriver, try take screenshot for ongoing tests.
Get error:
![image](https://user-images.githubusercontent.com/13115270/66242438-2001b380-e6f1-11e9-9905-7f6f222b1fef.png)

String in base64 could be succsessfully converted in image.

## Expected behavior

Screenshot should be visible without error

## Environment

OS: Virtual machine Ubuntu 18.04.03 in Virtual Box 6.0.8 r130520 (Qt5.6.2) at Windows 10 1903 (18362.387)
ports are forwarded by NAT

![image](https://user-images.githubusercontent.com/13115270/66242646-7ec72d00-e6f1-11e9-8f28-7b8e615346fe.png)

Docker image Digest: sha256:66b19bbc87c2d4cffe0c3478474daec3b9d101e6276c60c881e8b44a1c651a89
-->
Docker version 19.03.1, build 74b1e89

Docker command to start the container:
docker run -p 4444:4444 --shm-size=2g selenium/standalone-chrome:latest

**Comment by diemol** [comment] 2019-11-05 22:24
Duplicate of #858
Please accept my apologies which I wrote in this [comment](https://github.com/SeleniumHQ/docker-selenium/issues/858#issuecomment-513084839)

**Closed by diemol** 2019-11-05 22:24 UTC
