### ISSUE TITLE
[🐛 Bug]: /wd/hub/status return 000 in latest build , while it is working fine in 4.14

### ISSUE THREAD

**Issue by Vijayasok89** [SeleniumHQ/docker-selenium#2011] opened 2023-11-14 03:22 UTC
### What happened?

Bug Description:

Issue: The status check of the Selenium Hub using the provided curl command returns a status code of 000 instead of the expected 200.

Steps to Reproduce:

Execute the following curl command to check the status of the Selenium Hub: curl --write-out %{http_code} --silent --output /dev/null http://selenium-hub:4444/wd/hub/status
Expected Result: The curl command should return a status code of 200, indicating a successful connection to the Selenium Hub.

Actual Result: The curl command returns a status code of 000, which is unexpected and indicates a failure to establish a connection to the Selenium Hub.

Additional Information:

This issue is specific to the tag/version 4.15 of the Selenium server, as it worked fine with the previous version (4.14).

Impact:

Users relying on the curl command to check the status of the Selenium Hub are unable to accurately determine its connectivity and status.
Note:

The issue is reproducible consistently.

### Command used to start Selenium Grid with Docker

```shell
SELENIUM_COMPOSE_FILE='selenium_files/selenium-compose.yml'
docker compose -f ${SELENIUM_COMPOSE_FILE} up -d
```

### Relevant log output

```shell
checking hub status using below curl command  returns 000 
curl --write-out %{http_code} --silent --output /dev/null http://selenium-hub:4444/wd/hub/status
selenium server curl status code :000

The same worked fine with tag 4.14
 curl --write-out %{http_code} --silent --output /dev/null http://selenium-hub:4444/wd/hub/status
 selenium server curl status code :200
```

### Operating System

linux

### Docker Selenium version (tag)

4.15

**Comment by diemol** [comment] 2023-11-14 10:22
I cannot reproduce this, I used `docker-compose -f docker-compose-v3.yml up` from the repository. 

>gitpod /workspace/docker-selenium (diemol/bug-wd-hub-status-return-2011) $ curl --write-out %{http_code} --silent --output /dev/null http://localhost:4444/wd/hub/status
200
gitpod /workspace/docker-selenium (diemol/bug-wd-hub-status-return-2011) $

**Comment by Vijayasok89** [comment] 2023-11-14 12:10
@diemol Could you please try running the command from another container called "test container"? The "selenium-hub" container and the "test container" are in the same network called "pytest".

By running the command from the "test container" within the "pytest" network, we can ensure that both containers are properly connected and have network connectivity

**Comment by diemol** [comment] 2023-11-14 13:00
Why don't you provide the docker compose file I can use to reproduce this?

**Comment by Vijayasok89** [comment] 2023-11-15 07:37
[demo-selenium.zip](https://github.com/SeleniumHQ/docker-selenium/files/13361618/demo-selenium.zip)
@diemol please use the attached demo project 
To reproduce the issue, please follow these steps:

Navigate to the demo directory by running the command cd demo.

Build the Docker image using the command `docker` build -t pytest-app:v1 ..`

Start the Selenium Grid setup by running the command `docker-compose -f selenium-compose.yml up -d`

Start the pytest by running the command `docker-compose -f docker-compose.yml up`

**Comment by Vijayasok89** [comment] 2023-11-16 12:04
@diemol sorry for the delay in response 
It looks like this issue is reproducible in my Jenkins environment, where the agent is running on Ubuntu 18.04 with Docker client version : Docker version 20.10.24, build 297e128
Steps to reproduce:
1. in terminal goto demo folder build the image : docker build -f Dockerfile -t pytest-app:v1 .
2. create docker network : docker network create pytest-network
3. spin up the selenium containers : docker-compose -f selenium-compose.yml up -d  
4. spin up pytest container:  docker-compose -f docker-compose.yml up    

[demo-selenium 2.zip](https://github.com/SeleniumHQ/docker-selenium/files/13377357/demo-selenium.2.zip)

**Comment by VietND96** [comment] 2023-11-17 06:02
Hi @Vijayasok89, probably I reproduced the issue with your docker-compose file provided.
I think this config in compose file make the status returned `000`
```yaml
services:
  selenium-hub:
    ...
    networks:
        pytest-network:
            aliases:
                - hostname
```
When the alias is set, I think have to use `hostname` in the curl URL
```bash
curl --write-out %{http_code} --silent --output /dev/null http://selenium-hub:4444/wd/hub/status
000
```
```bash
curl --write-out %{http_code} --silent --output /dev/null http://$(hostname):4444/wd/hub/status
200
```

**Comment by diemol** [comment] 2023-11-17 10:14
Thanks for triaging, @vietnd96!

@Vijayasok89 this seems to be something in your setup, rather than something in Selenium. I will close this but feel free to continue the conversation.

**Closed as not planned by diemol** 2023-11-17 10:14 UTC
Labels: R-awaiting-answer

**Comment by luisfcorreia** [comment] 2023-11-17 10:16
I'm betting that "hostname" is a conflicting name, because it is a proper command that exist in most Unixes
