### ISSUE TITLE
3.3.1

### ISSUE THREAD

**Issue by bscheshirwork** [SeleniumHQ/docker-selenium#442] opened 2017-04-05 13:23 UTC
So... Its new release for hub.docker.com?
 7 days ago
3.3.1-arsenic 

3.3.0 version won't work properly with latest Firefox/Geckodriver.

**Comment by DerFlatulator** [comment] 2017-04-06 02:22
See #430

**Comment by tparikka** [comment] 2017-04-11 21:20
@bscheshirwork As said above, there's already an issue open for the 3.3.1 build issues. Are you looking for help specifically with 3.3.0 and Firefox/Geckodriver as well, or can this be closed as duplicate of issue 430?

**Comment by ddavison** [comment] 2017-04-11 21:31
duplicate of #430

**Closed by ddavison** 2017-04-11 21:31 UTC
