### ISSUE TITLE
Selenium Chrome tests are failing since the last 4 days

### ISSUE THREAD

**Issue by rajaraman-mahalingam** [SeleniumHQ/docker-selenium#629] opened 2017-12-06 16:22 UTC
## Meta -
Image(s):  

Docker-Selenium Image Version(s):  

Docker Version:  

OS: 

## Actual Behavior -
I have been using the selenium/standalone-chrome image for the browser based tests and running the same on Circleci. Everything was stable until recently, 4 days ago, all of the tests started failing with "Element not visible" or "stale element reference error" causing the build to a stand still. Looking at the the recent changes that have been made to this image and moving to selenium 3.8.1 may have caused this, although not able to conclude. Has anyone else seen a similar behaviour? All the tests, when run locally, seems to be OK.

**Comment by rajaraman-mahalingam** [comment] 2017-12-06 16:24
Image(s): selenium/standalone-chrome 

Docker-Selenium Image Version(s): 

Docker Version:

OS: Linux on Circleci 2

**Comment by diemol** [comment] 2017-12-06 16:51
Hi @rajaraman-mahalingam,

It is really hard to say what the cause might be. I'd suggest two things, go back in your CI to the latest 3.7.1 and on a separate machine try 3.8.1 to debug where the test fails and understand why. Second, use always a fixed tag in your CI, so you can control when the version is upgraded to avoid surprises.

I'll keep this open for a couple of days to see if you find an issue on the image, then please report back. Otherwise, we'll proceed to close it.

**Comment by rajaraman-mahalingam** [comment] 2017-12-10 18:27
Hello @diemol,

Thanks for your suggestion. I did your steps but with no luck. I have also updated the chromedriver version on my build but it is throwing up "invalid element state: Element is not currently interactable and may not be manipulated" for most cases. I have set the waits properly so wasn't expecting this at all. 
The issue is everything runs fine locally and they were running well until a week back on circleci too. 

FYI, mine is a maven project and in my pom file have set the dependencies for selenium-server to LATEST (which is 3.8.1). In circleci, I build the image and run my tests using mvn site command. 

 I am clue less as what could have caused to break the tests but happy to try out anything to get this fixed. 

Please suggest. Thanks

**Comment by dvarrazzo** [comment] 2017-12-11 13:26
I can confirm this issue. Some tests were working on my desktop using the image:

```
selenium/hub    latest    382bf96c8bde    3 weeks ago    296MB
```

and failed on our gitlab ci using the image:

```
selenium/hub    latest    059301140ded    8 days ago    297MB
```

after I refreshed the image on my desktop, tests started failing there too, so at least now I can debug them.

My tests start with `--window-size=1280,1024` but capturing a screenshot on the failing one the image size resuls 1050 x 895, which makes the tests fail because certain items cannot be reached on the right of the screen. Even trying with a smaller `--window-size` such as 1024 x 768, the screenshot size remains the same.

**Comment by dvarrazzo** [comment] 2017-12-11 13:33
Another note: the browser whose window is the wrong size is:

```
selenium/node-chrome    latest    62f850f3eb36    8 days ago    826MB
```

Connecting a real browser to the hub, the window appears right. tested using the hub node:

```
$ java -jar ~/Downloads/selenium-server-standalone-3.5.3.jar -role node -hub http:localhost:4444/grid/register
```

and Google Chrome 63.0.3239.52 beta on Ubuntu 16.04

**Comment by dvarrazzo** [comment] 2017-12-11 13:51
Using the image `selenium/hub:3.7.1` makes my tests pass. The regression is between 3.7.1 and 3.8.1.

**Comment by diemol** [comment] 2017-12-11 13:53
Thanks for debugging @dvarrazzo!
Do you know which tag specifically from 3.7.1 works? Is the issue with the hub or the node images? The original post was with the standalone image...

**Comment by dvarrazzo** [comment] 2017-12-11 15:35
The issue I've verified is with the docker image of selenium/hub version 3.8.1. Using a docker compose such as:

```yaml
services:
  selenium-hub:
    image: selenium/hub:3.8.1
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:3.8.1
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
    volumes:
      - /dev/shm:/dev/shm
```

the browser will not respect the desired initial size such as (Python):

```python
    caps['chromeOptions'] = {'args': ['--window-size=1280,1024']}
```

Using `image: selenium/hub:3.7.1` instead the initial size works as expected. The issue is revealed changing the hub version, not the node-chrome version. This is the minimal change in my deployment to reproduce the issue, sorry if I can't be more useful, I don't know much about selenium internals.

**Comment by rajaraman-mahalingam** [comment] 2017-12-11 16:36
@diemol @dvarrazzo as for my tests, i set them to use the kiosk mode in the chrome driver desired capabilities.

**Comment by diemol** [comment] 2017-12-12 16:55
@rajaraman-mahalingam when you mean "locally", you mean running the tests and having the docker-images running in your laptop?

Could someone please provide a script that reproduces the issue? This means, a small script that works on the 3.7.1 images and doesn't work on the 3.8.1 images. Please also point out the version of the bindings you are using.

**Comment by diemol** [comment] 2017-12-18 20:12
Hi @rajaraman-mahalingam @dvarrazzo 

Is it working for you now?

I tried to reproduce the issue in Java but I could not. I started a container like this:
```
docker run -d -p 4444:4444 -p 5900:5900 -v /dev/shm:/dev/shm selenium/standalone-chrome-debug:3.8.1-bohrium
```

and executed this [test](https://github.com/diemol/docker-selenium-issues/blob/master/issue-629/src/test/java/ChromeTest.java)... and it works for me.

Please note that I am using the 3.8.1 Java bindings, and the latest 3.8.1 image for Chrome.

It would be very helpful if you could post the docker commands used to start the images and a test script so we can reproduce the issue, otherwise it is kind of difficult to help.

**Comment by ajohnsen** [comment] 2017-12-20 12:58
I have found a similar problem with the newest version, it works if i downgrade to 3.7.1.

My issue happens when switching to an iFrame inside the site
It starts by doing this:
`  
// frameName is the name of the iFrame
getWebDriver().switchTo().frame(frameName);
`
and then it fails with element not found when trying to find something in the iFrame.
`
// xpath is the body of the iFrame (//body/embed)
getWebDriver().findElement(By.xpath(xpath));
`

**Comment by diemol** [comment] 2017-12-20 13:00
@ajohnsen is it possible for you to post a code example that can help us reproduce the issue? It is quite hard to check if there is a problem or not without ways to reproduce it.

**Comment by ddavison** [comment] 2018-01-02 16:53
I'm willing to bet all of these issues are stemming from static tagging issues.  

@all, don't use the `latest` tag if you can help it. issues like this will pop up very frequently if you do so.

Instead, you can use a fixed tag:  `:3.7.1` and update it when ready.  You can even use a specific version tag:  `:3.7.1-cadmium`.   if no script that can reproduce this issue can be provided, i'm going to close this issue

**Comment by ajohnsen** [comment] 2018-01-02 18:01
I changed to using the 3.7.1 in the build Pipeline and I think that fixed it, but will try to make a small script to reproduce it as soon as I have some free time.

**Comment by diemol** [comment] 2018-01-10 22:46
Hi all,

I will close this issue since we have not gotten feedback that can help us reproduce the issue and therefore act on it.

If someone has a way to provide the complete docker commands and a test script to reproduce the issue, feel free to post it here and we will happily reopen the issue to start investigating it.

**Closed by diemol** 2018-01-10 22:46 UTC
Labels: R-awaiting-answer

**Comment by dvarrazzo** [comment] 2018-01-12 17:45
Sorry but it was just trivial to test... whatevs. Here it is:

```yaml
# file: docker-compose.yml

version: '2'

services:
  selenium-hub:
    image: selenium/hub:3.8.1          # 3.7.1 works instead
    ports:
      - 14444:4444

  chrome:
    image: selenium/node-chrome:3.8.1
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
    volumes:
      - /dev/shm:/dev/shm
```

```python
# file: stest.py

from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

caps = DesiredCapabilities.CHROME
caps['chromeOptions'] = {'args': ['--window-size=1280,1024']}

r = webdriver.Remote(
	command_executor='http://localhost:14444/wd/hub',
	desired_capabilities=caps)
print r.get_window_size()
r.quit()
```

```
$ docker-compose up -d
Starting stest_chrome_1
Starting stest_selenium-hub_1
$ python stest.py 
{'width': 1050, 'height': 1000}
```

Using `selenium/hub:3.7.1` instead:

```
$ python stest.py 
{'width': 1280, 'height': 1024}
```

**Comment by dvarrazzo** [comment] 2018-01-12 20:13
Wouldn't it a good idea if `DesiredCapabilities.CHROME` addet it itself? I have noticed you quite like scope, but having two layers of scope to define the same thing seems a bit redundantly redundant. Also, you broke backward compatibility.

**Comment by diemol** [comment] 2018-01-12 21:15
I am sorry if something broke due to changes in the project. We basically put the grid in containers so it is also a good idea to keep an eye on the changelog for Selenium releases.

About the `DesiredCapabilities.CHROME`, it should actually do it. For example I use Java and the capability looks like that, so I don't need to handle any extra layer. Please double check that the most recent version of the bindings you are using also do the same. And if not, it'd be great if you can report that as a bug to the main project. 

In general, one should try to use the same version of the bindings on the client side as on the server side, so compatibility is maintained. But yes, maybe it could be a bug.
