### ISSUE TITLE
[🐛 Bug]: Unable to reach the Docker daemon at http://127.0.0.1:2375

### ISSUE THREAD

**Issue by LordPato** [SeleniumHQ/docker-selenium#1530] opened 2022-03-25 16:17 UTC
### What happened?

Starting Distributed Node on REL7.7 it gives the following error :

**Caused by: org.openqa.selenium.docker.DockerException: Unable to reach the Docker daemon at http://127.0.0.1:2375**

### Command used to start Selenium Grid with Docker

```shell
docker run -d -p 5555:5555 \
    -e SE_EVENT_BUS_HOST=******** \
    -e SE_EVENT_BUS_PUBLISH_PORT=4442 \
    -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 \
    -v ${PWD}/config.toml:/opt/bin/config.toml \
    -v ${PWD}/assets:/opt/selenium/assets \
    -v /var/run/docker.sock:/var/run/docker.sock \
    selenium/node-docker:4.1.2-20220317
```

### Relevant log output

```shell
2022-03-25 16:06:54,423 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-docker.conf" during parsing
2022-03-25 16:06:54,427 INFO supervisord started with pid 7
2022-03-25 16:06:55,429 INFO spawned: 'socat' with pid 9
2022-03-25 16:06:55,434 INFO spawned: 'selenium-grid-docker' with pid 10
Starting Selenium Grid Node Docker...
2022-03-25 16:06:55,452 INFO success: socat entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2022-03-25 16:06:55,452 INFO success: selenium-grid-docker entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
16:06:56.279 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
16:06:56.286 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
16:06:56.590 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://********:4442 and tcp://********:4443
16:06:56.704 INFO [UnboundZmqEventBus.<init>] - Sockets created
16:06:57.708 INFO [UnboundZmqEventBus.<init>] - Event bus ready
16:06:58.043 INFO [NodeServer.createHandlers] - Reporting self as: http://172.17.0.3:5555
16:06:58.113 INFO [NodeOptions.getSessionFactories] - Detected 1 available processors
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
        at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: org.openqa.selenium.grid.config.ConfigException: java.lang.reflect.InvocationTargetException
        at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:115)
        at org.openqa.selenium.grid.node.config.NodeOptions.getNode(NodeOptions.java:148)
        at org.openqa.selenium.grid.node.httpd.NodeServer.createHandlers(NodeServer.java:127)
        at org.openqa.selenium.grid.node.httpd.NodeServer.asServer(NodeServer.java:183)
        at org.openqa.selenium.grid.node.httpd.NodeServer.execute(NodeServer.java:230)
        at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:129)
        at org.openqa.selenium.grid.Main.launch(Main.java:83)
        at org.openqa.selenium.grid.Main.go(Main.java:57)
        at org.openqa.selenium.grid.Main.main(Main.java:42)
        ... 6 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.openqa.selenium.grid.config.ClassCreation.callCreateMethod(ClassCreation.java:50)
        at org.openqa.selenium.grid.config.MemoizedConfig.lambda$getClass$4(MemoizedConfig.java:100)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1737)
        at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:95)
        ... 14 more
**Caused by: org.openqa.selenium.docker.DockerException: Unable to reach the Docker daemon at http://127.0.0.1:2375**
        at org.openqa.selenium.grid.node.docker.DockerOptions.getDockerSessionFactories(DockerOptions.java:125)
        at org.openqa.selenium.grid.node.local.LocalNodeFactory.create(LocalNodeFactory.java:80)
        ... 22 more
Exception in thread "Thread-0" java.lang.NullPointerException
        at org.openqa.selenium.grid.node.httpd.NodeServer.lambda$new$0(NodeServer.java:79)
        at java.base/java.lang.Thread.run(Thread.java:829)
2022-03-25 16:06:59,647 INFO exited: selenium-grid-docker (exit status 1; not expected)
```

### Operating System

Redhat Enterprise Linux 7.7

### Docker Selenium version (tag)

4.1.2-20220317

**Comment by diemol** [comment] 2022-03-25 21:50
Do you get the same issue if you try Ubuntu? Also, can you share the container logs (found in `/var/log/supervisor/`)?.

**Comment by LordPato** [comment] 2022-03-26 00:27
It's not happening in Ubuntu 18.04.3 LTS. Same steps.

```
seluser@54237685dc42:/var/log/supervisor$ ls -la
total 16
drwxrwxrwx. 1 root    root    118 Mar 25 16:06 .
drwxr-xr-x. 1 root    root     23 Mar 17 21:33 ..
-rw-------. 1 seluser seluser   0 Mar 25 16:06 socat-stderr---supervisor-6cpxrtsf.log
-rw-------. 1 seluser seluser 385 Mar 25 16:06 socat-stdout---supervisor-3_oabpai.log
-rw-r--r--. 1 seluser seluser 652 Mar 25 16:06 supervisord.log
seluser@54237685dc42:/var/log/supervisor$ cat supervisord.log
2022-03-25 16:06:54,423 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-docker.conf" during parsing
2022-03-25 16:06:54,427 INFO supervisord started with pid 7
2022-03-25 16:06:55,429 INFO spawned: 'socat' with pid 9
2022-03-25 16:06:55,434 INFO spawned: 'selenium-grid-docker' with pid 10
2022-03-25 16:06:55,452 INFO success: socat entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2022-03-25 16:06:55,452 INFO success: selenium-grid-docker entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2022-03-25 16:06:59,647 INFO exited: selenium-grid-docker (exit status 1; not expected)
seluser@54237685dc42:/var/log/supervisor$ cat socat-stdout---supervisor-3_oabpai.log
  File: /var/run/docker.sock
  Size: 0               Blocks: 0          IO Block: 4096   socket
Device: 14h/20d Inode: 1274459846  Links: 1
Access: (0660/srw-rw----)  Uid: (    0/    root)   Gid: ( 1002/ UNKNOWN)
Access: 2022-03-25 16:06:53.882019022 +0000
Modify: 2022-03-25 16:01:49.052033231 +0000
Change: 2022-03-25 16:01:49.052033231 +0000
 Birth: -
Starting socat, docker.sock found.
```

**Comment by TheZekes** [comment] 2022-04-12 12:22
Exact same situation with Docker DIND:18(based on Alpine 3.9.4).
Logs are as same as above. 

UPDATE:

Fixed with DIND:20+ version. On this version it works fine.

**Comment by diemol** [comment] 2022-06-27 13:02
I was not able to reproduce this. I started Redhat Enterprise Linux 8 (no 7 available in AWS), installed docker and then things worked fine.

Probably the comment from above explains it.

![image](https://user-images.githubusercontent.com/5992658/175947822-a7113399-51ac-44af-90dd-fdd01e0940a6.png)

**Closed as completed by diemol** 2022-06-27 13:02 UTC

**Comment by william-sy** [comment] 2022-08-09 15:00
> Exact same situation with Docker DIND:18(based on Alpine 3.9.4). Logs are as same as above.
> 
> UPDATE:
> 
> Fixed with DIND:20+ version. On this version it works fine.

Install the latest docker-ce to fix this.

https://docs.docker.com/engine/install/centos/
