### ISSUE TITLE
 Windows Explorer Support

### ISSUE THREAD

**Issue by bcorner13** [SeleniumHQ/docker-selenium#1048] opened 2020-05-22 19:08 UTC
## 🚀 Feature Proposal

There is not a windows explorer option for docker-selenium

## Motivation

Explorer still maintains a sizeable number of clients out in the wild.  And a lot of companies still install Explorer on workstations.

## Example

Support a container for testing windows Explorer and / or other windows browser elements.

**Comment by diemol** [comment] 2020-05-22 20:03
This is a duplicate of #936. After many years, the status is the same, there are no official MS Windows docker images that support a UI.

**Closed by diemol** 2020-05-22 20:03 UTC
