### ISSUE TITLE
Headless container fails to maximize the window, works in debug container

### ISSUE THREAD

**Issue by DP19** [SeleniumHQ/docker-selenium#544] opened 2017-08-28 21:59 UTC
## Meta -
Image(s):  

Docker-Selenium Image Version(s):  latest

OS: os x 10.12

**Comment by JonasHavers** [comment] 2017-08-29 15:32
Same is true for Image Version 3.4.0 from Docker Hub
https://hub.docker.com/r/selenium/node-chrome/tags/

**Comment by westy92** [comment] 2017-08-29 16:26
I'm having the same issue.  Prior to yesterday's push I was using `selenium/node-chrome:latest` without issue.

**Comment by westy92** [comment] 2017-08-29 16:34
Related? 
https://github.com/angular/protractor/issues/4407
https://bugs.chromium.org/p/chromedriver/issues/detail?id=1901

**Comment by mMontu** [comment] 2017-08-31 18:03
Also related?
https://bugs.chromium.org/p/chromedriver/issues/detail?id=1946

**Comment by carlosmmelo** [comment] 2017-10-02 17:43
Just faced this issue when upgraded my NodeChrome from 3.4.0 to 3.6.0.

So whatever was updated in the dockerfile for 3.6.0 image its introducing this issue.

**Comment by carlosmmelo** [comment] 2017-10-02 18:24
https://github.com/SeleniumHQ/docker-selenium/issues/559

**Comment by carlosmmelo** [comment] 2017-10-02 18:28
so this is working on [node-chrome version 3.4.0-chromium](https://hub.docker.com/r/selenium/node-chrome/tags/)

However from `3.4.0-francium` and above, it started to fail when you try to maximize the browser's window size. (`self.driver.maximize_window()`)

**Comment by diemol** [comment] 2017-10-03 19:40
For Firefox see #575,

We'll investigate for Chrome.

**Comment by testphreak** [comment] 2017-10-05 06:04
@DP19 the way to maximize window for Chrome is to use the `--start-maximized` option. Do not use WebDriver to maximize.

```java
      DesiredCapabilities cap = DesiredCapabilities.chrome();
      ChromeOptions options = new ChromeOptions();
      options.addArguments("--start-maximized");
      cap.setCapability(ChromeOptions.CAPABILITY, options);
      webDriver = new RemoteWebDriver(hubUrl, cap);
```

**Comment by diemol** [comment] 2017-10-05 16:09
I've confirmed that this is a duplicate of #559, I'll close this issue and please follow that one.

**Closed by diemol** 2017-10-05 16:09 UTC
