### ISSUE TITLE
Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500 for edge 

### ISSUE THREAD

**Issue by rajgopalrajesh** [SeleniumHQ/docker-selenium#1306] opened 2021-06-01 19:29 UTC
## 🐛 Bug Report

Running DockerCompose grid 4 composefile    and running scripts with 
remote url   :http://localhost:4444
**getting below error** 
Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500 for edge 

## To Reproduce

Steps to reproduce the behavior (including the command to start the containers):
Running DockerCompose grid 4  and running scripts with remote url 
http://localhost:4444
getting below error 
Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500 for edge 

## Expected behavior
Scripts has to execute on docker machines 

## Test script reproducing this issue (when applicable)

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links are also OK.

```java
public WebDriver remoteEdgeDriver(){
EdgeOptions options = new EdgeOptions();
options.setCapability("platform", Platform.ANY);
return new RemoteWebDriver(this.url, options);
}
```
Issues without a reproduction script are likely to stall and eventually be closed.

## Environment
 Windows 10

OS: 
Docker-Selenium image version: 
Docker version: 3
Docker-Compose version (if applicable):
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well): `docker-compose docker-compose-v3-full-grid.yml up`

![error](https://user-images.githubusercontent.com/16475965/120379581-9713a300-c33d-11eb-9876-d962a2eb5a93.PNG)

https://github.com/SeleniumHQ/docker-selenium/blob/trunk/docker-compose-v3-full-grid.yml

**Comment by diemol** [comment] 2021-07-13 12:33
This is an issue in Windows envs these days, where (somehow) `/dev/shm/` fails to be mounted properly, I did not dig into the root cause. Switching to `shm_size: 2gb` in the docker-compose files fixes this.

Fixed by https://github.com/SeleniumHQ/docker-selenium/commit/368081095edf40f2b087ca8cfcf9d40151de8c80

Please refresh the docker compose file you are using with the one present in `trunk`.

**Closed as completed by diemol** 2021-07-13 12:33 UTC
Labels: S-investigating
