### ISSUE TITLE
 java.util.concurrent.TimeoutException 

### ISSUE THREAD

**Issue by mckinly** [SeleniumHQ/docker-selenium#1356] opened 2021-08-03 15:31 UTC
## 🐛 Bug Report

` java.util.concurrent.TimeoutException` surfaces in one of our 8 chrome node containers when running grid via docker-compose on 32GB RAM,  8 CPU linux machine in CircleCI causing the test run to fail. This issue started occurring about 1 month ago with no apparent changes to our configuration other than increasing the number of tests that get executed from 30 to 43.

I'm really stumped by this issue:
- It reproduces every 3-5 test runs
- I have increased the CircleCI machine executor size from xlarge (8CPU 16GB RAM), to 2xlarge (16CPU 32GB RAM) with no success at resolving the issue
- I added the `- SE_SESSION_REQUEST_TIMEOUT=120` to the chrome node containers with no success at resolving the issue

Any assistance would be greatly appreciated! I'm happy to provide any additional information upon request. 

## To Reproduce

Steps to reproduce the behavior (including the command to start the containers):

`docker-compose.yml`
```
version: "3"
services:

  aragog:
    image: aragog:${TAG}
    build: .

  chrome:
    image: selenium/node-chrome:4.0.0
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_CONCURRENT_SESSIONS=1
      # - SE_SESSION_REQUEST_TIMEOUT=60  # setting this value didn't resolve the issue
    networks:
      - grid

  selenium-hub:
    image: selenium/hub:4.0.0
    container_name: selenium-hub
    environment:
      - GRID_DEBUG=true
      - GRID_MAX_SESSION=8
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - grid
      
networks:
  grid:
```

1. Start selenium-hub container and scale up chrome nodes
`docker-compose -f docker-compose.yml up --scale chrome=8`
2. Script waits for the grid to come up and the nodes to register
```
while [[ `curl -s 'http://localhost:4444/status' | grep "UP" | wc -l` -ne 8 ]]; do
  echo "Not all nodes registered to grid, waiting one second..." >&2
 sleep 1
done | 
  until grep "UP" | wc -l; do
    echo "Waiting for selenium grid to be ready..."
    sleep 1
  done
echo "Selenium grid is up and running!"
```
3. Execute tests with container that contains webdriverio tests
`docker run --network=grid -t aragog:latest npm test -- --spec=${TEST_DIR} -- config/wdio.docker.conf.js`

## Expected behavior

All the tests execute.

## Environment

OS: Ubuntu 18.06 [machine xlarge](https://circleci.com/docs/2.0/executor-types/#available-docker-resource-classes) executor in CircleCI
Docker-Selenium image version: 4.0.0
Node chrome version: 4.0.0

## Stacktrace
```
org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)\n\tat java.base\u002fjava.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base\u002fjava.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base\u002fjava.lang.Thread.run(Thread.java:829)\nCaused by: java.util.concurrent.TimeoutException\n\tat java.base\u002fjava.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886)\n\tat java.base\u002fjava.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)\n\tat org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:206)\n\tat org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:66)\n\t... 35 more\n","exception.type": "org.openqa.selenium.TimeoutException","http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.router.HandleSession","http.host": "selenium-hub:4444","http.method": "GET","http.scheme": "HTTP","http.target": "\u002fsession\u002fbd65c60b77f0fbcbe8a08fec48cc06c5\u002furl","http.user_agent": "webdriver\u002f6.12.1","session.id": "bd65c60b77f0fbcbe8a08fec48cc06c5"}}
selenium-hub    | 
chrome_5        | 16:18:28.628 WARN [SpanWrappedHttpHandler.execute] - Unable to execute request: java.util.concurrent.TimeoutException
chrome_5        | Build info: version: '4.0.0-rc-1', revision: '74745cf081'
chrome_5        | System info: host: 'baa732c87611', ip: '172.19.0.9', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1021-gcp', java.version: '11.0.11'
chrome_5        | Driver info: driver.version: unknown
chrome_5        | org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException
chrome_5        | Build info: version: '4.0.0-rc-1', revision: '74745cf081'
chrome_5        | System info: host: 'baa732c87611', ip: '172.19.0.9', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1021-gcp', java.version: '11.0.11'
chrome_5        | Driver info: driver.version: unknown
chrome_5        | 	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:72)
chrome_5        | 	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
chrome_5        | 	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
chrome_5        | 	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:51)
chrome_5        | 	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
chrome_5        | 	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
chrome_5        | 	at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:116)
chrome_5        | 	at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55)
chrome_5        | 	at org.openqa.selenium.grid.web.ReverseProxyHandler.execute(ReverseProxyHandler.java:100)
chrome_5        | 	at org.openqa.selenium.grid.node.ProtocolConvertingSession.execute(ProtocolConvertingSession.java:75)
chrome_5        | 	at org.openqa.selenium.grid.node.local.SessionSlot.execute(SessionSlot.java:123)
chrome_5        | 	at org.openqa.selenium.grid.node.local.LocalNode.executeWebDriverCommand(LocalNode.java:385)
chrome_5        | 	at org.openqa.selenium.grid.node.ForwardWebDriverCommand.execute(ForwardWebDriverCommand.java:35)
chrome_5        | 	at org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:373)
chrome_5        | 	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
chrome_5        | 	at org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:86)
chrome_5        | 	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
chrome_5        | 	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
chrome_5        | 	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
chrome_5        | 	at org.openqa.selenium.grid.node.Node.execute(Node.java:240)
chrome_5        | 	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
chrome_5        | 	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
chrome_5        | 	at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)
chrome_5        | 	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
chrome_5        | 	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
chrome_5        | 	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
chrome_5        | 	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
chrome_5        | 	at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)
chrome_5        | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
chrome_5        | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
chrome_5        | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
chrome_5        | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
chrome_5        | 	at java.base/java.lang.Thread.run(Thread.java:829)
chrome_5        | Caused by: java.util.concurrent.TimeoutException
chrome_5        | 	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886)
chrome_5        | 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
chrome_5        | 	at org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:206)
chrome_5        | 	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:66)
chrome_5        | 	... 32 more
chrome_5        | 16:18:28.629 WARN [SeleniumSpanExporter$1.lambda$export$0] - {"traceId": "aa99b3dde6a096d910e4f0ebe6f86d06","eventTime": 1628007508627367148,"eventName": "exception","attributes": {"exception.message": "Unable to execute request: java.util.concurrent.TimeoutException\nBuild info: version: '4.0.0-rc-1', revision: '74745cf081'\nSystem info: host: 'baa732c87611', ip: '172.19.0.9', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1021-gcp', java.version: '11.0.11'\nDriver info: driver.version: unknown","exception.stacktrace": "org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException\nBuild info: version: '4.0.0-rc-1', revision: '74745cf081'\nSystem info: host: 'baa732c87611', ip: '172.19.0.9', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1021-gcp', java.version: '11.0.11'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:72)\n\tat org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)\n\tat org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)\n\tat org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:51)\n\tat org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)\n\tat org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)\n\tat org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:116)\n\tat org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55)\n\tat org.openqa.selenium.grid.web.ReverseProxyHandler.execute(ReverseProxyHandler.java:100)\n\tat org.openqa.selenium.grid.node.ProtocolConvertingSession.execute(ProtocolConvertingSession.java:75)\n\tat org.openqa.selenium.grid.node.local.SessionSlot.execute(SessionSlot.java:123)\n\tat org.openqa.selenium.grid.node.local.LocalNode.executeWebDriverCommand(LocalNode.java:385)\n\tat org.openqa.selenium.grid.node.ForwardWebDriverCommand.execute(ForwardWebDriverCommand.java:35)\n\tat org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:373)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:86)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.grid.node.Node.execute(Node.java:240)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)\n\tat java.base\u002fjava.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base\u002fjava.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base\u002fjava.lang.Thread.run(Thread.java:829)\nCaused by: java.util.concurrent.TimeoutException\n\tat java.base\u002fjava.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886)\n\tat java.base\u002fjava.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)\n\tat org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:206)\n\tat org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:66)\n\t... 32 more\n","exception.type": "org.openqa.selenium.TimeoutException","http.flavor": 1,"http.handler_class": "org.openqa.selenium.remote.http.Route$PredicatedRoute","http.host": "selenium-hub:4444","http.method": "GET","http.scheme": "HTTP","http.target": "\u002fsession\u002fbd65c60b77f0fbcbe8a08fec48cc06c5\u002furl","http.user_agent": "webdriver\u002f6.12.1"}}
chrome_5        | 
```

**Comment by mckinly** [comment] 2021-08-03 15:48
## Successful run logs
[successful_run.txt](https://github.com/SeleniumHQ/docker-selenium/files/6925416/successful_run.txt)

## Failed run logs
[failed_run.txt](https://github.com/SeleniumHQ/docker-selenium/files/6925624/failed_run.txt)
(see error at very bottom of the file)

**Comment by diemol** [comment] 2021-08-04 11:09
This is most likely a duplicate of https://github.com/SeleniumHQ/selenium/issues/9528, which we are having a hard time to replicate.

What happens when you use the latest full tag for Selenium Grid 4? Do you still see the issue?

**Comment by mckinly** [comment] 2021-08-04 15:22
> This is most likely a duplicate of [SeleniumHQ/selenium#9528](https://github.com/SeleniumHQ/selenium/issues/9528), which we are having a hard time to replicate.
> 
> What happens when you use the latest full tag for Selenium Grid 4? Do you still see the issue?

Yeah, that issue sounds like the same one to me. I'll try with the latest full tag and see if it reproduces.

**Comment by mckinly** [comment] 2021-08-04 16:19
@diemol I was able to run the tests 4 times before I hit this exception:
```
selenium-hub    | 16:04:17.994 WARN [UnboundZmqEventBus$PollingRunnable.lambda$notifyListeners$2] - Caught exception from listener: org.openqa.selenium.events.EventListener@26a2251c
selenium-hub    | java.io.UncheckedIOException: java.net.ConnectException: Connection refused: /172.19.0.7:5555
selenium-hub    | 	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:80)
selenium-hub    | 	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
selenium-hub    | 	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
selenium-hub    | 	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:51)
selenium-hub    | 	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
selenium-hub    | 	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
selenium-hub    | 	at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:116)
selenium-hub    | 	at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55)
selenium-hub    | 	at org.openqa.selenium.grid.node.remote.RemoteNode.getStatus(RemoteNode.java:207)
selenium-hub    | 	at org.openqa.selenium.grid.distributor.local.LocalDistributor.add(LocalDistributor.java:254)
selenium-hub    | 	at org.openqa.selenium.grid.distributor.local.LocalDistributor.register(LocalDistributor.java:243)
selenium-hub    | 	at org.openqa.selenium.grid.distributor.local.LocalDistributor.lambda$new$1(LocalDistributor.java:167)
selenium-hub    | 	at org.openqa.selenium.events.EventListener.accept(EventListener.java:43)
selenium-hub    | 	at org.openqa.selenium.events.EventListener.accept(EventListener.java:25)
selenium-hub    | 	at org.openqa.selenium.events.zeromq.UnboundZmqEventBus$PollingRunnable.lambda$notifyListeners$2(UnboundZmqEventBus.java:273)
selenium-hub    | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
selenium-hub    | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
selenium-hub    | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
selenium-hub    | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
```
Maybe I was running the tests too closely together and CircleCI provisioned the same linux machine to run the test and the hub was still up? I don't think so, because I'm always tearing down the grid at the end of the tests. 
The issue seems different. What do you think?

(see full failure logs here)
[failed_result.txt](https://github.com/SeleniumHQ/docker-selenium/files/6932784/failed_result.txt)

**Comment by mckinly** [comment] 2021-08-04 23:00
Ever since the failure I just reported above, the suite is running, but it takes about 20 minutes instead of 5 minutes to complete and the `java.util.concurrent.TimeoutException` still appears in the logs however the test suite is able to finish.

**Comment by diemol** [comment] 2021-08-05 21:16
Would it be possible to get a test suite to reproduce this? Having the logs you mention above can be helpful as well.

**Comment by mckinly** [comment] 2021-08-06 00:32
@diemol I unfortunately don't have an easy way to get you access to an example test suite at this time. Here are the logs of the case where all the tests execute, but we see the `java.util.concurrent.TimeoutException` .

Thanks so much for your diligence here!

[successful_run_with_java_exception.txt](https://github.com/SeleniumHQ/docker-selenium/files/6942281/successful_run_with_java_exception.txt)

**Comment by mckinly** [comment] 2021-08-06 15:05
If it helps with troubleshooting, I rolled back to grid 3 and the issue we see is the containers exit before all the tests finish _sometimes_. It happens at about the same rate as this bug in grid 4. 

[grid_3_torn_down_before_finish.txt](https://github.com/SeleniumHQ/docker-selenium/files/6946307/grid_3_torn_down_before_finish.txt)

**Comment by ghost** [comment] 2021-08-31 17:47
Not sure if it's exactly the same issue, but see https://github.com/SeleniumHQ/docker-selenium/issues/1375. I've got the same exception, added snippets + logs there.

**Comment by diemol** [comment] 2021-11-03 13:07
As this issue is a duplicate of https://github.com/SeleniumHQ/selenium/issues/9528, will close this one and follow up in the other one.

**Closed as completed by diemol** 2021-11-03 13:07 UTC
Labels: R-awaiting-answer
