### ISSUE TITLE
Memory leak on selenium/standalone-chrome

### ISSUE THREAD

**Issue by ezesculli** [SeleniumHQ/docker-selenium#513] opened 2017-06-30 15:32 UTC
## Meta -
Image(s):  
selenium/standalone-chrome

Docker-Selenium Image Version(s):  
lastest

OS: 
Linux (AWS EC2 Linux Image)

## Expected Behavior -
After running many test on different Chrome instances (> 2000), memory keeps stable on the Docker instance

## Actual Behavior -
After running many test on different Chrome instances (>2000), it seems there is a memory leak on the docker instance, because memory is at 5GB without any Chrome browser running on the Selenium Console (port 4444).
Also, it appears /opt/google/chrome/chrome and /opt/selenium/chromedriver-2.30 process are not close after each test run.

**Comment by ddavison** [comment] 2017-06-30 16:37
out of curiosity, why are you keeping instances open for that long?  docker containers are meant to be cheap and short-lived :)

really not sure what we can do about this, as this is very hard to replicate.   I'm assuming that the underlying problem is not docker - but chrome itself.

**Comment by ezesculli** [comment] 2017-06-30 17:23
On our production environment, we're not restarting docker instances, should we do that?

What docker images do you recommend for high throughput on production environment?

We're running 3 or 4 instances of Chrome browsers at the same time on a 8GB docker instance. But after a few days, it shows the described behaviour (memory leaks)

**Comment by ddavison** [comment] 2017-06-30 17:57
well, the ideal setup would be to spin up a container whenever you're running a test.

Test Startup -> Node Startup -> Node running test -> Node report result -> Node shutdown.

If that is unattainable right now, the best way would be to just use something like `docker-compose` for a quick win.

Have docker-compose spin up `n` amount of nodes, then shut them down, and spin up `n` amount of nodes after some specific time frame.  that'd be a quick-win

**Comment by ddavison** [comment] 2017-06-30 17:57
for high throughput, use the `selenium/hub` in conjunction with `selenium/node-chrome` and `selenium/node-firefox` and avoid the "debug" instances since those introduce superfluous programs like VNC

**Comment by philippe-granet** [comment] 2017-09-07 23:12
> well, the ideal setup would be to spin up a container whenever you're running a test.
Test Startup -> Node Startup -> Node running test -> Node report result -> Node shutdown.

You can take a look at this project, `an On-demand Grid prototype that spins off Docker based nodes on a "ask basis"` : https://github.com/RationaleEmotions/just-ask

**Comment by diemol** [comment] 2017-09-12 16:25
This [comment](https://github.com/SeleniumHQ/docker-selenium/issues/513#issuecomment-312333487) sums it all. It is not recommended to have nodes running for a long time, just take advantage of the docker performance by spinning new containers as needed.

On a side note, and following this [comment](https://github.com/SeleniumHQ/docker-selenium/issues/513#issuecomment-327952259), you can check that type of solutions, here are two examples more:

**Note: This projects are not official Selenium projects, and any support related to them should be addressed in their respective repos.**
- https://github.com/zalando/zalenium Enriched grid with several additional features
  - Disclosure: I have contributed to this project and it is developed where I work. 
- https://github.com/aerokube/selenoid New approach for Grids, good performance


Hopefully one some of this info can be helpful for you.

Closing as there is no direct action we can take.

**Closed by diemol** 2017-09-12 16:25 UTC

**Comment by ericrange** [comment] 2018-02-26 19:48
is this bug still relevant?

after 1 hours of endless looping (and correct .quit() and .close())
my cpu and ram cache explodes.

is this a known bug?

![image](https://user-images.githubusercontent.com/1785416/36691652-39c4702e-1b36-11e8-82cc-1efee169a800.png)

**Comment by cgoldberg** [comment] 2018-02-28 21:51
https://www.linuxatemyram.com/

**Comment by ericrange** [comment] 2018-03-01 10:41
the ram is not the problem. the cpu takes 100% and the whole process stuck.

**Comment by cgoldberg** [comment] 2018-03-01 15:48
> the ram is not the problem

well, the thread you hijacked *was* about memory (the issue is also closed)

**Comment by ericrange** [comment] 2018-03-01 15:52
i do not know where to put this. i found so many threads in stackoverflow, etc. where people complain about memory and cpu leaks but no single answer or fix so far.

**Comment by cgoldberg** [comment] 2018-03-01 15:55
if you have a new issue, then open a new issue.  (btw, there's no such thing as a cpu leak)
