### ISSUE TITLE
Unable to take a screenshot on selenium/standalone-firefox

### ISSUE THREAD

**Issue by extsoft** [SeleniumHQ/docker-selenium#858] opened 2019-01-01 15:57 UTC
## 🐛 Bug Report

Unable to take a screenshot for a session on http://localhost:4444/wd/hub/static/resource/hub.html.

## To Reproduce
1. `docker run -it --rm -p 4444:4444 selenium/standalone-firefox:3.141.59-dubnium`
2. Open a page. I use this snippet:
    ```python
    from selenium import webdriver
    from selenium.webdriver.firefox.options import Options
    options = Options()
    driver = webdriver.Remote(
       command_executor='http://localhost:4444/wd/hub',
       desired_capabilities=options.to_capabilities()
    )
    driver.get('http://google.com')
    ```
3. Open http://localhost:4444/wd/hub/static/resource/hub.html
4. Press "Take Screenshot" button

Error:
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/5806627/50574281-f7f5c480-0ded-11e9-9dc9-018089ab92ca.png">
Log: 
```
2019-01-01 15:47:11,514 WARN Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
2019-01-01 15:47:11,516 INFO supervisord started with pid 9
2019-01-01 15:47:12,521 INFO spawned: 'xvfb' with pid 12
2019-01-01 15:47:12,524 INFO spawned: 'selenium-standalone' with pid 13
15:47:13.101 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
2019-01-01 15:47:13,106 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2019-01-01 15:47:13,106 INFO success: selenium-standalone entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
15:47:13.310 INFO [GridLauncherV3.lambda$buildLaunchers$3] - Launching a standalone Selenium Server on port 4444
2019-01-01 15:47:13.439:INFO::main: Logging initialized @902ms to org.seleniumhq.jetty9.util.log.StdErrLog
15:47:14.044 INFO [WebDriverServlet.<init>] - Initialising WebDriverServlet
15:47:14.314 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 4444
15:47:21.265 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "acceptInsecureCerts": true,
  "browserName": "firefox",
  "marionette": true
}
15:47:21.271 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
1546357642108	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.Dyj5pqSq7mEC"
1546357643079	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid host permission: resource://pdf.js/
1546357643079	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid host permission: about:reader*
1546357645034	Marionette	INFO	Listening on port 34649
1546357645140	Marionette	WARN	TLS certificate errors will be ignored for this session
15:47:25.328 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
15:47:25.445 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 30f4de66-3a2a-4d89-95bf-e93f2407d714 (org.openqa.selenium.firefox.GeckoDriverService)
console.error: BroadcastService: 
  receivedBroadcastMessage: handler for
  remote-settings/monitor_changes
  threw error:
  Message: Error: Polling for changes failed: NetworkError when attempting to fetch resource..
  Stack:
    remoteSettingsFunction/remoteSettings.pollChanges@resource://services-settings/remote-settings.js:750:13
```

## Expected behavior

A screenshot is displayed.

## Environment

OS: macOS 10.14.2 (18C54)
Docker-Selenium image version: `3.141.59-dubnium`, `d2f37e55e704`
Docker version 18.09.0, build 4d60db4

**Comment by IsmaTeddy** [comment] 2019-02-14 17:08
Hi,
I have same error. I will wait solution ;)

**Comment by OneEyedSpaceFish** [comment] 2019-04-08 14:29
This could very well be related to https://github.com/facebook/php-webdriver/issues/469

**Comment by diemol** [comment] 2019-04-08 14:56
@extsoft 
Can you reproduce this withouth Docker? Using the Grid itself? Also, is it reproducible using only Firefox and taking a screenshot?

**Comment by extsoft** [comment] 2019-04-10 15:19
@diemol I can. Just please give me a hint what do I have to run? Standalone server via JAR file?

**Comment by diemol** [comment] 2019-04-14 20:17
@extsoft you can find the information here https://seleniumhq.github.io/docs/grid.html#setting_up_your_own_selenium_grid, setting it up for Standalone and try the same.

**Comment by extsoft** [comment] 2019-05-13 13:40
@diemol I have run
```bash
$ java -jar selenium-server-standalone-3.141.59.jar -role hub
$ java -jar selenium-server-standalone-3.141.59.jar -role node -hub http://localhost:4444
```

When I open <http://localhost:4444/wd/hub/static/resource/hub.html>, I see 
```
{
  "sessionId": null,
  "status": 13,
  "value": {
    "class": "org.openqa.grid.common.exception.GridException",
    "error": "unknown error",
    "message": "Session [(null externalkey)] not available and is not among the last 1000 terminated sessions.\nActive sessions are[ext. key 8ffc4de9-aca0-eb4b-9a5c-d0e8fa76d0a1]",
    "stackTrace": [
      {
        "className": "org.openqa.grid.internal.ActiveTestSessions",
        "fileName": "ActiveTestSessions.java",
        "lineNumber": 120,
        "methodName": "getExistingSession"
      },
      {
        "className": "org.openqa.grid.internal.DefaultGridRegistry",
        "fileName": "DefaultGridRegistry.java",
        "lineNumber": 387,
        "methodName": "getExistingSession"
      },
      {
        "className": "org.openqa.grid.web.servlet.handler.RequestHandler",
        "fileName": "RequestHandler.java",
        "lineNumber": 241,
        "methodName": "getSession"
      },
      {
        "className": "org.openqa.grid.web.servlet.handler.RequestHandler",
        "fileName": "RequestHandler.java",
        "lineNumber": 123,
        "methodName": "process"
      },
      {
        "className": "org.openqa.grid.web.servlet.DriverServlet",
        "fileName": "DriverServlet.java",
        "lineNumber": 85,
        "methodName": "process"
      },
      {
        "className": "org.openqa.grid.web.servlet.DriverServlet",
        "fileName": "DriverServlet.java",
        "lineNumber": 63,
        "methodName": "doGet"
      },
      {
        "className": "javax.servlet.http.HttpServlet",
        "fileName": "HttpServlet.java",
        "lineNumber": 687,
        "methodName": "service"
      },
      {
        "className": "javax.servlet.http.HttpServlet",
        "fileName": "HttpServlet.java",
        "lineNumber": 790,
        "methodName": "service"
      },
      {
        "className": "org.seleniumhq.jetty9.servlet.ServletHolder",
        "fileName": "ServletHolder.java",
        "lineNumber": 865,
        "methodName": "handle"
      },
      {
        "className": "org.seleniumhq.jetty9.servlet.ServletHandler",
        "fileName": "ServletHandler.java",
        "lineNumber": 535,
        "methodName": "doHandle"
      },
      {
        "className": "org.seleniumhq.jetty9.server.handler.ScopedHandler",
        "fileName": "ScopedHandler.java",
        "lineNumber": 146,
        "methodName": "handle"
      },
      {
        "className": "org.seleniumhq.jetty9.security.SecurityHandler",
        "fileName": "SecurityHandler.java",
        "lineNumber": 548,
        "methodName": "handle"
      },
      {
        "className": "org.seleniumhq.jetty9.server.handler.HandlerWrapper",
        "fileName": "HandlerWrapper.java",
        "lineNumber": 132,
        "methodName": "handle"
      },
      {
        "className": "org.seleniumhq.jetty9.server.handler.ScopedHandler",
        "fileName": "ScopedHandler.java",
        "lineNumber": 257,
        "methodName": "nextHandle"
      },
      {
        "className": "org.seleniumhq.jetty9.server.session.SessionHandler",
        "fileName": "SessionHandler.java",
        "lineNumber": 1595,
        "methodName": "doHandle"
      },
      {
        "className": "org.seleniumhq.jetty9.server.handler.ScopedHandler",
        "fileName": "ScopedHandler.java",
        "lineNumber": 255,
        "methodName": "nextHandle"
      },
      {
        "className": "org.seleniumhq.jetty9.server.handler.ContextHandler",
        "fileName": "ContextHandler.java",
        "lineNumber": 1340,
        "methodName": "doHandle"
      },
      {
        "className": "org.seleniumhq.jetty9.server.handler.ScopedHandler",
        "fileName": "ScopedHandler.java",
        "lineNumber": 203,
        "methodName": "nextScope"
      },
      {
        "className": "org.seleniumhq.jetty9.servlet.ServletHandler",
        "fileName": "ServletHandler.java",
        "lineNumber": 473,
        "methodName": "doScope"
      },
      {
        "className": "org.seleniumhq.jetty9.server.session.SessionHandler",
        "fileName": "SessionHandler.java",
        "lineNumber": 1564,
        "methodName": "doScope"
      },
      {
        "className": "org.seleniumhq.jetty9.server.handler.ScopedHandler",
        "fileName": "ScopedHandler.java",
        "lineNumber": 201,
        "methodName": "nextScope"
      },
      {
        "className": "org.seleniumhq.jetty9.server.handler.ContextHandler",
        "fileName": "ContextHandler.java",
        "lineNumber": 1242,
        "methodName": "doScope"
      },
      {
        "className": "org.seleniumhq.jetty9.server.handler.ScopedHandler",
        "fileName": "ScopedHandler.java",
        "lineNumber": 144,
        "methodName": "handle"
      },
      {
        "className": "org.seleniumhq.jetty9.server.handler.HandlerWrapper",
        "fileName": "HandlerWrapper.java",
        "lineNumber": 132,
        "methodName": "handle"
      },
      {
        "className": "org.seleniumhq.jetty9.server.Server",
        "fileName": "Server.java",
        "lineNumber": 503,
        "methodName": "handle"
      },
      {
        "className": "org.seleniumhq.jetty9.server.HttpChannel",
        "fileName": "HttpChannel.java",
        "lineNumber": 364,
        "methodName": "handle"
      },
      {
        "className": "org.seleniumhq.jetty9.server.HttpConnection",
        "fileName": "HttpConnection.java",
        "lineNumber": 260,
        "methodName": "onFillable"
      },
      {
        "className": "org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback",
        "fileName": "AbstractConnection.java",
        "lineNumber": 305,
        "methodName": "succeeded"
      },
      {
        "className": "org.seleniumhq.jetty9.io.FillInterest",
        "fileName": "FillInterest.java",
        "lineNumber": 103,
        "methodName": "fillable"
      },
      {
        "className": "org.seleniumhq.jetty9.io.ChannelEndPoint$2",
        "fileName": "ChannelEndPoint.java",
        "lineNumber": 118,
        "methodName": "run"
      },
      {
        "className": "org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill",
        "fileName": "EatWhatYouKill.java",
        "lineNumber": 333,
        "methodName": "runTask"
      },
      {
        "className": "org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill",
        "fileName": "EatWhatYouKill.java",
        "lineNumber": 310,
        "methodName": "doProduce"
      },
      {
        "className": "org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill",
        "fileName": "EatWhatYouKill.java",
        "lineNumber": 168,
        "methodName": "tryProduce"
      },
      {
        "className": "org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill",
        "fileName": "EatWhatYouKill.java",
        "lineNumber": 126,
        "methodName": "run"
      },
      {
        "className": "org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread",
        "fileName": "ReservedThreadExecutor.java",
        "lineNumber": 366,
        "methodName": "run"
      },
      {
        "className": "org.seleniumhq.jetty9.util.thread.QueuedThreadPool",
        "fileName": "QueuedThreadPool.java",
        "lineNumber": 765,
        "methodName": "runJob"
      },
      {
        "className": "org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2",
        "fileName": "QueuedThreadPool.java",
        "lineNumber": 683,
        "methodName": "run"
      },
      {
        "className": "java.lang.Thread",
        "fileName": "Thread.java",
        "lineNumber": 748,
        "methodName": "run"
      }
    ],
    "stacktrace": "org.openqa.grid.common.exception.GridException: Session [(null externalkey)] not available and is not among the last 1000 terminated sessions.\nActive sessions are[ext. key 8ffc4de9-aca0-eb4b-9a5c-d0e8fa76d0a1]\n\tat org.openqa.grid.internal.ActiveTestSessions.getExistingSession(ActiveTestSessions.java:120)\n\tat org.openqa.grid.internal.DefaultGridRegistry.getExistingSession(DefaultGridRegistry.java:387)\n\tat org.openqa.grid.web.servlet.handler.RequestHandler.getSession(RequestHandler.java:241)\n\tat org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:123)\n\tat org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:85)\n\tat org.openqa.grid.web.servlet.DriverServlet.doGet(DriverServlet.java:63)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:687)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:790)\n\tat org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:865)\n\tat org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)\n\tat org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:146)\n\tat org.seleniumhq.jetty9.security.SecurityHandler.handle(SecurityHandler.java:548)\n\tat org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)\n\tat org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)\n\tat org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)\n\tat org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)\n\tat org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)\n\tat org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)\n\tat org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)\n\tat org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)\n\tat org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)\n\tat org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1242)\n\tat org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:144)\n\tat org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)\n\tat org.seleniumhq.jetty9.server.Server.handle(Server.java:503)\n\tat org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:364)\n\tat org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:260)\n\tat org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)\n\tat org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:103)\n\tat org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)\n\tat org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)\n\tat org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)\n\tat org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)\n\tat org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)\n\tat org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)\n\tat org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)\n\tat org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)\n\tat java.lang.Thread.run(Thread.java:748)\n"
  }
}
```
And the node log 
```
16:29:22.701 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
16:29:22.815 INFO [GridLauncherV3.lambda$buildLaunchers$7] - Launching a Selenium Grid node on port 27297
2019-05-13 16:29:22.901:INFO::main: Logging initialized @426ms to org.seleniumhq.jetty9.util.log.StdErrLog
16:29:23.108 INFO [WebDriverServlet.<init>] - Initialising WebDriverServlet
16:29:23.195 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 27297
16:29:23.195 INFO [GridLauncherV3.lambda$buildLaunchers$7] - Selenium Grid node is up and ready to register to the hub
16:29:23.229 INFO [SelfRegisteringRemote$1.run] - Starting auto registration thread. Will try to register every 5000 ms.
16:29:23.599 INFO [SelfRegisteringRemote.registerToHub] - Registering the node to the hub: http://localhost:4444/grid/register
16:29:23.646 INFO [DefaultGridRegistry.add] - Registered a node http://10.131.169.111:27297
16:29:23.647 INFO [SelfRegisteringRemote.registerToHub] - The node is registered to the hub and ready to use
16:30:36.172 INFO [RequestHandler.process] - Got a request to create a new session: Capabilities {acceptInsecureCerts: true, browserName: firefox, marionette: true}
16:30:36.175 INFO [TestSlot.getNewSession] - Trying to create a new session on test slot {server:CONFIG_UUID=5993da87-bd6a-4364-9b7e-08779833368a, seleniumProtocol=WebDriver, marionette=true, browserName=firefox, maxInstances=5, platformName=MAC, platform=MAC}
16:30:36.235 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "acceptInsecureCerts": true,
  "browserName": "firefox",
  "marionette": true
}
16:30:36.237 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
1557754236836	mozrunner::runner	INFO	Running command: "/Applications/Firefox.app/Contents/MacOS/firefox-bin" "-marionette" "-foreground" "-no-remote" "-profile" "/var/folders/y0/11qh549977zdszd35r6tr6100000gn/T/rust_mozprofile.cr588FOETTYS"
1557754238303	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1557754238303	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1557754238303	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
mach_override: some instructions unknown! Need to update mach_override.c
Opcodes @ 0x7fff469909f5: 0x40 0xF6 0xC7 0x1 0x75 0x39 0x48 0x8B
err = f8000001 /Users/jenkins/build/workspace/Auto-AgentMac-7.5.1-hotfix/sasource/dgagent/agent/macosx/userspace/hooking/mach_override.c:224
err = f8000001 /Users/jenkins/build/workspace/Auto-AgentMac-7.5.1-hotfix/sasource/dgagent/agent/macosx/userspace/hooking/mach_override.c:237
err = f8000001 /Users/jenkins/build/workspace/Auto-AgentMac-7.5.1-hotfix/sasource/dgagent/agent/macosx/userspace/hooking/mach_override.c:243
err = f8000001 /Users/jenkins/build/workspace/Auto-AgentMac-7.5.1-hotfix/sasource/dgagent/agent/macosx/userspace/hooking/mach_override.c:257
err = f8000001 /Users/jenkins/build/workspace/Auto-AgentMac-7.5.1-hotfix/sasource/dgagent/agent/macosx/userspace/hooking/mach_override.c:262
mach_override: some instructions unknown! Need to update mach_override.c
Opcodes @ 0x7fff469909f5: 0x40 0xF6 0xC7 0x1 0x75 0x39 0x48 0x8B
err = f8000001 /Users/jenkins/build/workspace/Auto-AgentMac-7.5.1-hotfix/sasource/dgagent/agent/macosx/userspace/hooking/mach_override.c:224
err = f8000001 /Users/jenkins/build/workspace/Auto-AgentMac-7.5.1-hotfix/sasource/dgagent/agent/macosx/userspace/hooking/mach_override.c:237
err = f8000001 /Users/jenkins/build/workspace/Auto-AgentMac-7.5.1-hotfix/sasource/dgagent/agent/macosx/userspace/hooking/mach_override.c:243
err = f8000001 /Users/jenkins/build/workspace/Auto-AgentMac-7.5.1-hotfix/sasource/dgagent/agent/macosx/userspace/hooking/mach_override.c:257
err = f8000001 /Users/jenkins/build/workspace/Auto-AgentMac-7.5.1-hotfix/sasource/dgagent/agent/macosx/userspace/hooking/mach_override.c:262
1557754241503	Marionette	INFO	Listening on port 58502
1557754241588	Marionette	WARN	TLS certificate errors will be ignored for this session
mach_override: some instructions unknown! Need to update mach_override.c
Opcodes @ 0x7fff469909f5: 0x40 0xF6 0xC7 0x1 0x75 0x39 0x48 0x8B
err = f8000001 /Users/jenkins/build/workspace/Auto-AgentMac-7.5.1-hotfix/sasource/dgagent/agent/macosx/userspace/hooking/mach_override.c:224
err = f8000001 /Users/jenkins/build/workspace/Auto-AgentMac-7.5.1-hotfix/sasource/dgagent/agent/macosx/userspace/hooking/mach_override.c:237
err = f8000001 /Users/jenkins/build/workspace/Auto-AgentMac-7.5.1-hotfix/sasource/dgagent/agent/macosx/userspace/hooking/mach_override.c:243
err = f8000001 /Users/jenkins/build/workspace/Auto-AgentMac-7.5.1-hotfix/sasource/dgagent/agent/macosx/userspace/hooking/mach_override.c:257
err = f8000001 /Users/jenkins/build/workspace/Auto-AgentMac-7.5.1-hotfix/sasource/dgagent/agent/macosx/userspace/hooking/mach_override.c:262
16:30:41.964 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
16:30:41.988 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 8ffc4de9-aca0-eb4b-9a5c-d0e8fa76d0a1 (org.openqa.selenium.firefox.GeckoDriverService)
```

So, the "Sessions" page is not available.  Can I do something else to help in the investigation?

**Comment by extsoft** [comment] 2019-05-13 13:45
@diemol And with Chrome it works fine

Command: `docker run -it --rm -p 4444:4444 selenium/standalone-chrome:3.141.59-dubnium`

Screenshot: 
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/5806627/57626323-530aa580-759e-11e9-9dbc-6e3295ad7fd5.png">

**Comment by luizlohn** [comment] 2019-07-15 13:50
I got the same error on Standalone-chrome-debug, I can't take screenshot.

**Comment by diemol** [comment] 2019-07-19 04:22
OK, so I just saw that this is an issue in the Grid 3.x itself, not in `docker-selenium`, it is likely related to the fact that Firefox is working in W3C mode a while ago and recently Chrome is also working on W3C mode (based on @luizlohn's comment, where this is happening in Chrome as well).

Now the part where everyone will hate me, Grid 3.x won't be developed anymore because a new Grid is being written from scratch and it should be released when Selenium 4.0 is out (no date planned yet). This means that even if this is a bug, it won't be fixed due to the what I just wrote, and in addition that it is a low impact bug (in theory a few users are affected).

Therefore I will close this issue as a "won't fix", I truly apologise for not replying with a more helpful answer. If someone really needs this feature, please add a "feature request" for the new Grid in the Selenium repo.

**Closed by diemol** 2019-07-19 04:22 UTC
Labels: I-standalone-firefox, R-awaiting-answer

**Comment by sbabcoc** [comment] 2019-07-31 17:26
I'm able to capture screenshots from ChromeDriver 3.141.59 through Grid 3. To do this, I had to throw a `Hail Mary` by requesting a screenshot without being able to determine ahead of time that the remote driver I'm talking to will actually be able to fulfill this request. We need to add unit tests to the Grid project to confirm that capabilities are accurately reported.

**Comment by PavelShalahai** [comment] 2019-08-07 09:12
I had the same issue with a screenshot. I have used selenium/standalone-chrome-debug. 
An answer below helped me.

> @diemol And with Chrome it works fine

https://github.com/SeleniumHQ/docker-selenium/issues/858#issuecomment-491828505
