### ISSUE TITLE
Configured file download directory is ignored

### ISSUE THREAD

**Issue by breilly2** [SeleniumHQ/docker-selenium#628] opened 2017-12-05 20:04 UTC
## Meta -
Image(s):  node-chrome, node-chrome-debug

Docker-Selenium Image Version(s):  3.8.1

Docker Version:  17.09.0-ce

OS: OSX

## Expected Behavior -

Files should be downloaded to the directory specified by the "download.default_directory" chrome option. This worked in 3.7.1.

## Actual Behavior -

Files are downloaded to the default download directory of the selenium user (/home/seluser/Downloads).

Code (scala) is roughly as follows:
```
def startWebDriver(service: ChromeDriverService): RemoteWebDriver = {
    val downloadPath = "/app/downloads" // mapped volume in docker compose for selenium hub
    val options = new ChromeOptions
    options.setExperimentalOptions("prefs", Map(
      "download.default_directory" -> downloadPath,
      "download.prompt_for_download" -> "false").asJava)
    val capabilities = DesiredCapabilities.chrome
    capabilities.setCapability(ChromeOptions.CAPABILITY, options)
    new RemoteWebDriver(service.getUrl, capabilities)
}
```
I've confirmed that files are download and saved to /home/seluser/Downloads by connecting to the node (VNC with node-chrome-debug). /app/downloads is writable by seluser. This code works again when I revert to 3.7.1 images.

**Comment by diemol** [comment] 2017-12-06 16:47
Hi @breilly2,

That's weird, what version of the bindings are you using? 

Anyway, I tried to reproduce your issue based on your code and I could not, I created this small example [project](https://github.com/diemol/docker-selenium-issues/tree/master/issue-628). You can use this docker-compose [file](https://github.com/diemol/docker-selenium-issues/blob/master/issue-628/docker-compose.yaml) to run it, check it out and let us know if it worked.

**Comment by breilly2** [comment] 2017-12-06 19:57
Thanks for the follow-up and for creating the example project. I did run it and it passed. There must be something different in our project. I'll see about getting the example project into a state that fails in the way I described.

**Comment by breilly2** [comment] 2017-12-07 19:25
You had the right intuition. Looks like we were using 2.35.0 client libraries for some reason. Yikes! Switched to 3.8.1 and now it works.

So, if the intent was to not break this level of backwards compatibility going from 3.7 to 3.8 then this issue is still valid. Otherwise, I apologize for the false alarm and thank you for your help!

**Comment by diemol** [comment] 2017-12-07 23:18
Oh wow, 2.35.0! I am amazed that it was still working until 3.7.1
Selenium 2 not supported anymore, and people are encouraged to move to Selenium 3. 

And no, the same test works in 3.7.1, that's why I was wondering what the problem was.

I'll close the issue then, thanks for reporting back.

**Closed by diemol** 2017-12-07 23:18 UTC
Labels: R-awaiting-answer
