### ISSUE TITLE
[🐛 Bug]: Nodes hang when starting up

### ISSUE THREAD

**Issue by enivid** [SeleniumHQ/docker-selenium#1838] opened 2023-04-26 16:37 UTC
### What happened?

My grid has been running fine with 4.3.0-20220624 for a year but I've never been able to upgrade beyond that point. My grid consists of a selenium/hub and a couple selenium/node-chrome's. Starting with 4.3.0-20220628 and beyond, only the first node will start up. I enabled FINE logging on the nodes and the only log it has in the subsequent nodes is "INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing" and then nothing else. On the first node that does start up, I see the second log is "INFO RPC interface 'supervisor' initialized". In the changelog of 4.3.0-20220628, theres a change https://github.com/SeleniumHQ/docker-selenium/pull/1612 to the supervisord config. Could that be causing an issues with my env?

### Command used to start Selenium Grid with Docker

```shell
docker network create grid
docker run -d -p 4442-4444:4442-4444 --net grid --name hub selenium/hub:4.3.0-20220628
docker run -d --net grid --name chrome-node1 -e SE_EVENT_BUS_HOST=hub -e SE_EVENT_BUS_PUBLISH_PORT=4442 -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 -e selenium/node-chrome:4.3.0-20220628
docker run -d --net grid --name chrome-node2 -e SE_EVENT_BUS_HOST=hub -e SE_EVENT_BUS_PUBLISH_PORT=4442 -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 -e selenium/node-chrome:4.3.0-20220628
```

### Relevant log output

```shell
2023-04-26 15:58:21,968 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
```

### Operating System

Linux

### Docker Selenium version (tag)

4.3.0-20220628

**Comment by diemol** [comment] 2023-05-11 12:23
I am not sure what the issue is, if this was a common problem, we would have many many issues and comments about it. Please try on a different machine or using GitPod. 

I will leave this open for a bit in case you want to add more details, but with the provided information it is really hard to say what can be the problem in your environment.

**Comment by diemol** [comment] 2023-05-28 05:37
Closing as no more feedback was provided.

**Closed as completed by diemol** 2023-05-28 05:37 UTC
Labels: R-awaiting-answer
