### ISSUE TITLE
selenium/standalone-docker browsers should work inside docker-compose network  

### ISSUE THREAD

**Issue by josesa-xx** [SeleniumHQ/docker-selenium#1237] opened 2021-03-17 08:08 UTC
## 🚀 Feature Proposal

When using docker-compose for component self-test all container names act as DNS for host resolution automatically, so we can design our tests around that.

Using selenium/standalone-docker the browsers are started in docker-host not connected to the compose private network. This feature would provide some configuration option to allow the browsers instance to connect to the same network used in the compose.

## Motivation

The intention is to facilitate application testing in self-contained environment using dynamic grid option.

## Example

You can find a possible sample usage of the use case in (currently failing due to missing feature):
https://github.com/josesa-xx/selenium-tests/tree/master/standalone-docker

As alternative i also provide a sample using static browsers grid (working):
https://github.com/josesa-xx/selenium-tests/tree/master/selenium-grid

**Comment by diemol** [comment] 2021-03-17 10:30
Duplicate of #1147

**Closed as completed by diemol** 2021-03-17 10:30 UTC

**Comment by josesa-xx** [comment] 2021-03-17 11:26
Actually this is not the same issue as the standalone-docker starts and is able to deploy browser containers on demand.

The problem is connectivity to the test targets running inside the same compose (private network) that is not covered by current selenium docker config.

**Comment by diemol** [comment] 2021-03-17 11:43
Yes, that is one of the points of the linked ticket, have it working in docker-compose as well.
