### ISSUE TITLE
Content-Type header is missing -  4.0.0-alpha-7-20201119

### ISSUE THREAD

**Issue by StellarNero** [SeleniumHQ/docker-selenium#1148] opened 2020-11-25 13:52 UTC
## 🐛 Bug Report

During test execution we are getting following error; org.openqa.selenium.WebDriverException: Content-Type header is missing

Expected:

## To Reproduce

Automation Framework:  Selenium+Cucumber+java

## Expected behavior

 Web Driver should close

## Environment

OS: 
Docker-Selenium image version: selenium/node-chrome:4.0.0-alpha-7-20201119

-->
Docker version: 
Docker-Compose version (if applicable): 1.27.4
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well): https://github.com/SeleniumHQ/docker-selenium/blob/trunk/docker-compose-v3-video.yml

**Comment by NeginMn** [comment] 2020-11-26 11:11
Same here, I am also getting this error.

**Comment by diemol** [comment] 2020-11-27 21:53
Duplicate of #1145

**Closed as completed by diemol** 2020-11-27 21:53 UTC
Labels: needs-triaging
