### ISSUE TITLE
[🐛 Bug]: VNC viewer issue in Kubernetes with nginx ingress extra / in wss URL

### ISSUE THREAD

**Issue by amardeep2006** [SeleniumHQ/docker-selenium#2075] opened 2023-12-21 17:55 UTC
### What happened?

I upgraded to latest helm chart version 0.26.3 and NoVNC sessions have stopped working.
The selenium test cases and UI works fine without issues. Only problem is with VNC sessions. I am not using any subpaths.
I am using https setup (automatic with sectigo tls) .

I see blank screen if I click on the video icon to see session.
**Clue :** Interestingly I see one extra forward slash (/) in wss url before session. In browser console logs.
I have double checked INGRESS_DOMAIN env variable does not contain this extra slash.

wss://abc.com//session/d5b0aa9f497f46d9f4d6d27bdb82a08c/se/vnc

![image](https://github.com/SeleniumHQ/docker-selenium/assets/50517840/025f8ac8-f853-4ec4-85d6-efd8dbff8db5)
 
Here is my value file.

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
global:
  seleniumGrid:
    # Image registry for all selenium components
    imageRegistry: myinternalrepo/selenium-grid
    # Image tag for all selenium components
    imageTag: "4.16.1"
    # Image tag for browser's nodes
    nodesImageTag: "4.16.1"
    # Image tag for browser's video recorder
    videoImageTag: "ffmpeg-6.1"
    # Pull secret for all components, can be overridden individually
    imagePullSecret: ""
    # Log level for all components. Possible values describe here: https://www.selenium.dev/documentation/grid/configuration/cli_options/#logging
    logLevel: INFO
isolateComponents: $ISOLATE_COMPONENTS
# Basic auth settings for Selenium Grid
basicAuth:
  # Enable or disable basic auth
  enabled: $BASIC_AUTH_ENABLED
autoscaling:
  enabled: $AUTOSCALING_ENABLED
  scalingType: $SCALING_TYPE
  # Options for KEDA scaled resources (keep only common options used for both ScaledJob and ScaledObject)
  scaledOptions:
    minReplicaCount: 0
    maxReplicaCount: $MAX_REPLICAS_COUNT
    pollingInterval: 10
customLabels: {"app-id": "selgrid", "app-tier": "application"}
ingress:
  # Name of ingress class to select which controller will implement ingress resource
  # Custom annotations for ingress resource
  annotations: {"cert-manager.io/cluster-issuer": "ci-0-acme-sectigo","nginx.ingress.kubernetes.io/proxy-connect-timeout": "600","nginx.ingress.kubernetes.io/proxy-read-timeout": "600","nginx.ingress.kubernetes.io/proxy-send-timeout": "600"}
  # Default host for the ingress resource
  hostname: $INGRESS_DOMAIN
  tls:
    - secretName: sel-grid-tls-secret
      hosts:
        - $INGRESS_DOMAIN
router:
  imagePullPolicy: Always
distributor:
  imagePullPolicy: Always  
eventBus:
  imagePullPolicy: Always
sessionMap:
  imagePullPolicy: Always
sessionQueue:
  imagePullPolicy: Always    
hub:
  imagePullPolicy: Always
  # Resources for container
  resources:
    requests:
      memory: "2Gi"
      cpu: "2"
    limits:
      memory: "8Gi"
      cpu: "4"
  extraEnvironmentVariables:
    - name: SE_JAVA_OPTS
      value: "-Xms1024m -Xmx8192m"
chromeNode:
  enabled: true
  replicas: $CHROME_NODE_REPLICAS
  terminationGracePeriodSeconds: 2700
  imagePullPolicy: Always
  # /dev/shm volume
  dshmVolumeSizeLimit: "2Gi"
  # Resources for chrome-node container
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "2Gi"
      cpu: "2"
  extraEnvironmentVariables: 
    # - name: "SE_VNC_NO_PASSWORD"
    #   value: "1"
    - name: "SE_VNC_VIEW_ONLY"
      value: "1"      
edgeNode:
  # Enable edge nodes
  enabled: true
  replicas: $MSEDGE_NODE_REPLICAS
  imagePullPolicy: Always
  # /dev/shm volume
  dshmVolumeSizeLimit: "2Gi"
  # Resources for edge-node container
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "2Gi"
      cpu: "2"
  extraEnvironmentVariables: 
    # - name: "SE_VNC_NO_PASSWORD"
    #   value: "1"
    - name: "SE_VNC_VIEW_ONLY"
      value: "1"         
firefoxNode:
  # Enable firefox nodes
  enabled: true
  replicas: "$FIREFOX_NODE_REPLICAS" 
  imagePullPolicy: Always
  # /dev/shm volume
  dshmVolumeSizeLimit: "2Gi"
  # Resources for firefox-node container
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "2Gi"
      cpu: "2"
  extraEnvironmentVariables: 
    # - name: "SE_VNC_NO_PASSWORD"
    #   value: "1"
    - name: "SE_VNC_VIEW_ONLY"
      value: "1"         
keda:
  image:
    keda:
      # -- Image name of KEDA operator
      repository: myinternalrepo/kedacore/keda
      # -- Image tag of KEDA operator. Optional, given app version of Helm chart is used by default
      tag: "2.12.1"
    metricsApiServer:
      # -- Image name of KEDA Metrics API Server
      repository: myinternalrepo/kedacore/keda-metrics-apiserver
      # -- Image tag of KEDA Metrics API Server. Optional, given app version of Helm chart is used by default
      tag: "2.12.1"
    webhooks:
      # -- Image name of KEDA admission-webhooks
      repository: myinternalrepo/kedacore/keda-admission-webhooks
      # -- Image tag of KEDA admission-webhooks . Optional, given app version of Helm chart is used by default
      tag: "2.12.1"
    # -- Image pullPolicy for all KEDA components
  podLabels:
    # -- Pod labels for KEDA operator
    keda: {"app-id": "selgrid", "app-tier": "application"}
    # -- Pod labels for KEDA Metrics Adapter
    metricsAdapter: {"app-id": "selgrid", "app-tier": "application"}
    # -- Pod labels for KEDA Admission webhooks
    webhooks: {"app-id": "selgrid", "app-tier": "application"}
```

### Relevant log output

```shell
websock.js:231 WebSocket connection to 'wss://abc.com//session/d5b0aa9f497f46d9f4d6d27bdb82a08c/se/vnc' failed: Error during WebSocket handshake: Unexpected response code: 502
```

### Operating System

Kubernetes

### Docker Selenium version (image tag)

4.16.1

### Selenium Grid chart version (chart version)

0.26.3

**Comment by amardeep2006** [comment] 2023-12-21 19:20
Additional Troubleshooting :  I tried following combinations

Selenium grid Chart version 0.26.3 with Selenium-Server **4.15.0** : The NoVNC works fine without issues.

Selenium grid Chart version 0.26.3 with Selenium-Server **4.16.1** : The NoVNC have issues and appends extra slash in url.

**Comment by miguelsuddya** [comment] 2023-12-21 19:56
I think the issue roots come from here
https://github.com/SeleniumHQ/selenium/pull/13219.

this pull request was merged into trunk and delivered exactly in 4,16

**Comment by VietND96** [comment] 2023-12-22 04:09
I can confirm the issue comes from the chart itself, due to change #2073, `/` added to `SE_NODE_GRID_URL` always
In normal cases, e.g I run standalone, without subpath, the VNC URL is constructed correctly
```
docker run -d -p 4444:4444 --shm-size="2g" selenium/standalone-chrome:4.16.1-20231219
```
Also, upstream needs a fix to handle trailing slash, so users no longer have to worry about the slash.
I will fix both soon.

**Comment by VietND96** [comment] 2023-12-22 04:25
A workaround I think will help you continue with `0.26.3`, in chart, go to templates/_helpers.tpl (line 403), update it to
```
{{- $subPath := "" -}}
```

**Comment by amardeep2006** [comment] 2023-12-22 13:16
> A workaround I think will help you continue with `0.26.3`, in chart, go to templates/_helpers.tpl (line 403), update it to
> 
> ```
> {{- $subPath := "" -}}
> ```

I tried this workaround but unfortunately it did not seem to work. Still seeing extra / .

**Closed as completed** 2023-12-22 15:54 UTC
Labels: needs-triaging

**Comment by VietND96** [comment] 2023-12-22 15:56
More values need to be updated in background. Hence I have done the patch in chart 0.26.4

**Comment by amardeep2006** [comment] 2023-12-23 04:24
I am amazed by your work @vietnd96 . I tested with 0.26.4 and issue is fixed. Really appreciate.
