### ISSUE TITLE
[🐛 Bug]: Latest versions of Dynamic grid are not working  using the config provided in doc

### ISSUE THREAD

**Issue by victortanase** [SeleniumHQ/docker-selenium#1734] opened 2022-12-03 07:13 UTC
### What happened?

I'm not able to use the selenium dynamic grid starting from 4.6.0. 
Same configuration works for version older than 4.6.0.
Is this a bug in the grid or some step missing in the documentation ?

Error:
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: Could not start a new session. Could not start a new session. non-positive contentLength: 0 

Thank you in advance!

### Command used to start Selenium Grid with Docker

```shell
docker-compose up
docker compose file is almost same as the one provided in the documentation:

Docker host OS: Windows and Linux(ubuntu)

# To execute this docker-compose yml file use `docker-compose -f docker-compose-v3-dynamic-grid.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v3-dynamic-grid.yml down`
version: "3"
services:
  node-docker:
    image: selenium/node-docker:4.7.0-20221202
    volumes:
      - ./assets:/opt/selenium/assets
      - ./NodeDocker/config.toml:/opt/bin/config.toml
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    image: selenium/hub:4.7.0-20221202
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"   

config.toml:

[docker]
# Configs have a mapping between the Docker image to use and the capabilities that need to be matched to
# start a container with the given image.
configs = [
    "selenium/standalone-firefox:4.6.0-20221104", "{\"browserName\": \"firefox\"}",
    "selenium/standalone-chrome:4.6.0-20221104", "{\"browserName\": \"chrome\"}",
    "selenium/standalone-edge:4.6.0-20221104", "{\"browserName\": \"MicrosoftEdge\"}"
    ]

# URL for connecting to the docker daemon
# host.docker.internal works for macOS and Windows.
# Linux could use --net=host in the `docker run` instruction or 172.17.0.1 in the URI below.
# To have Docker listening through tcp on macOS, install socat and run the following command
# socat -4 TCP-LISTEN:2375,fork UNIX-CONNECT:/var/run/docker.sock
url = "http://host.docker.internal:2375"
# Docker imagee used for video recording
video-image = "selenium/video:ffmpeg-4.3.1-20221202"

# Uncomment the following section if you are running the node on a separate VM
# Fill out the placeholders with appropriate values
#[server]
#host = <ip-from-node-machine>
#port = <port-from-node-machine>

Sample code:
        RemoteWebDriver webDriver;
        String baseURL, nodeURL;
        baseURL = "http://demo.guru99.com/test/guru99home/";
        nodeURL = "http://localhost:4444";
        URL gridUrl = new URL(nodeURL);
        ChromeOptions chromeOptions = new ChromeOptions();
        chromeOptions.setCapability("se:name", "My simple test");
        //options.setCapability("se:screenResolution", "1920x1080");
        webDriver = new RemoteWebDriver(gridUrl, chromeOptions);
        System.out.println(chromeOptions.getCapabilityNames());
version:
 <dependency>
     <groupId>org.seleniumhq.selenium</groupId>
     <artifactId>selenium-java</artifactId>
     <version>4.6.0</version>
  </dependency>
-tried with latest python library too with same error
```

### Relevant log output

```shell
selenium-hub            | 07:08:08.742 WARN [SeleniumSpanExporter$1.lambda$export$1] - Unable to create session: Could not start a new session. Could not start a new session. non-positive contentLength: 0
selenium-hub            | Host info: host: 'b576219d97d7', ip: '172.18.0.3'
selenium-hub            | Build info: version: '4.7.0', revision: '52e3a49ea2'
selenium-hub            | System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.16.3-microsoft-standard-WSL2', java.version: '11.0.17'
selenium-hub            | Driver info: driver.version: unknown
selenium-hub            | Build info: version: '4.7.0', revision: '52e3a49ea2'
selenium-hub            | System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.16.3-microsoft-standard-WSL2', java.version: '11.0.17'
selenium-hub            | Driver info: driver.version: unknown
selenium-hub            | 07:08:08.747 WARN [SeleniumSpanExporter$1.lambda$export$1] - org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Could not start a new session. non-positive contentLength: 0
selenium-hub            | Host info: host: 'b576219d97d7', ip: '172.18.0.3'
selenium-hub            | Build info: version: '4.7.0', revision: '52e3a49ea2'
selenium-hub            | System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.16.3-microsoft-standard-WSL2', java.version: '11.0.17'
selenium-hub            | Driver info: driver.version: unknown
selenium-hub            | Build info: version: '4.7.0', revision: '52e3a49ea2'
selenium-hub            | System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.16.3-microsoft-standard-WSL2', java.version: '11.0.17'
selenium-hub            | Driver info: driver.version: unknown
selenium-hub            |       at org.openqa.selenium.grid.node.remote.RemoteNode.newSession(RemoteNode.java:150)
selenium-hub            |       at org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession(LocalDistributor.java:645)
selenium-hub            |       at org.openqa.selenium.grid.distributor.local.LocalDistributor.newSession(LocalDistributor.java:564)
selenium-hub            |       at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest(LocalDistributor.java:818)
selenium-hub            |       at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.lambda$run$1(LocalDistributor.java:779)
selenium-hub            |       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
selenium-hub            |       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
selenium-hub            |       at java.base/java.lang.Thread.run(Thread.java:829)
selenium-hub            |
selenium-hub            | 07:08:08.748 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "39f3208e910ec779401bbae454299448","eventTime": 1670051288732849846,"eventName": "exception","attributes": {"exception.message": "Unable to create session: Could not start a new session. Could not start a new session. non-positive contentLength: 0 \nHost info: host: 'b576219d97d7', ip: '172.18.0.3'\nBuild info: version: '4.7.0', revision: '52e3a49ea2'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.16.3-microsoft-standard-WSL2', java.version: '11.0.17'\nDriver info: driver.version: unknown\nBuild info: version: '4.7.0', revision: '52e3a49ea2'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.16.3-microsoft-standard-WSL2', java.version: '11.0.17'\nDriver info: driver.version: unknown","exception.stacktrace": "org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Could not start a new session. non-positive contentLength: 0 \nHost info: host: 'b576219d97d7', ip: '172.18.0.3'\nBuild info: version: '4.7.0', revision: '52e3a49ea2'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.16.3-microsoft-standard-WSL2', java.version: '11.0.17'\nDriver info: driver.version: unknown\nBuild info: version: '4.7.0', revision: '52e3a49ea2'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.16.3-microsoft-standard-WSL2', java.version: '11.0.17'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.grid.node.remote.RemoteNode.newSession(RemoteNode.java:150)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession(LocalDistributor.java:645)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor.newSession(LocalDistributor.java:564)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest(LocalDistributor.java:818)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.lambda$run$1(LocalDistributor.java:779)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base\u002fjava.lang.Thread.run(Thread.java:829)\n","exception.type": "org.openqa.selenium.SessionNotCreatedException","logger": "org.openqa.selenium.grid.distributor.local.LocalDistributor","request.payload": "[Capabilities {browserName: chrome, goog:chromeOptions: {args: [], extensions: []}, se:name: My simple test}]"}}
selenium-hub            |
selenium-hub            | 07:08:08.770 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "39f3208e910ec779401bbae454299448","eventTime": 1670051288765454413,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueue","http.host": "localhost:4444","http.method": "POST","http.request_content_length": "435","http.scheme": "HTTP","http.status_code": 500,"http.target": "\u002fsession","http.user_agent": "selenium\u002f4.6.0 (java windows)"}}
```

### Operating System

Ubuntu,Windows

### Docker Selenium version (tag)

4.7.0-20221202

**Comment by diemol** [comment] 2022-12-03 07:35
Duplicate of https://github.com/SeleniumHQ/selenium/issues/11342

**Closed as completed by diemol** 2022-12-03 07:35 UTC
