### ISSUE TITLE
Container keeps running after Selenium is killed by OOM killer (code 137)

### ISSUE THREAD

**Issue by elciok** [SeleniumHQ/docker-selenium#1133] opened 2020-11-09 17:25 UTC
## 🐛 Bug Report

Selenium standalone container is not killed after Java Selenium process is killed by host due to memory limit settings. 

## To Reproduce

1. Start a Selenium container with enough memory for it to boot but not enough to keep running. In my tests, using the docker-compose.yml file below, with memory limited to 15 MB, is the easiest way to reproduce this problem.

```
version: "3.8"

services:
  selenium:
    image: selenium/standalone-chrome:3.141.59
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 15m
    volumes:
      - /dev/shm:/dev/shm
    environment:
      START_XVFB: 'false'
      GRID_DEBUG: 'true'
    healthcheck:
      test: /opt/bin/check-grid.sh --host 0.0.0.0 --port 4444
      interval: 10s
      timeout: 30s
      retries: 5
```

2. Wait a few seconds and you will see the process error after being killed.

```
selenium_1  | /opt/bin/start-selenium-standalone.sh: line 6:    12 Killed                  java ${JAVA_OPTS} -cp ${JAVA_CLASSPATH:-"/opt/selenium/*:."} org.openqa.grid.selenium.GridLauncherV3 ${SE_OPTS}
selenium_1  | 2020-11-09 16:52:52,884 INFO exited: selenium-standalone (exit status 137; not expected)
```

3. System logs shows this was indeed caused by the OOM killer.

```
Nov 09 13:52:52 elcio-ideapad kernel: Memory cgroup out of memory: Kill process 5758 (java) score 811 or sacrifice child
Nov 09 13:52:52 elcio-ideapad kernel: oom_reaper: reaped process 5758 (java), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

4. docker ps output still shows container is up and running (with unhealthy status). It's still possible to docker exec into the container but Selenium won't accept any connections because it's not running.

## Expected behavior

Container should stop running when Selenium process is killed.

## Test script reproducing this issue (when applicable)

See above in steps to reproduce.

## Environment

OS: Linux Ubuntu 16.04.7 LTS (kernel 4.15.0-120-generic)
Docker-Selenium image version: selenium/standalone-chrome:3.141.59 (image ID: 85071b633f11)

Docker version: 19.03.13, build 4484c46d9d
Docker-Compose version (if applicable): 1.27.4
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well): docker-compose up

**Comment by diemol** [comment] 2020-11-27 10:50
Thank you for opening this issue!

The approach we take when running the docker containers is to have `supervisor` as the process that oversees everything, we do it this way in order to avoid situations where a container dies and there is no way to debug it to find out why it happened.

Therefore, the behavior you are seeing is exactly what we expect, which is what helped you to get those logs and understand why the Selenium Server died.

I will close this because the containers are behaving in the way we expect, process wise. 

Feel free to add more comments or suggest ideas, we can keep the conversation going even if the issue is closed.

**Closed as completed by diemol** 2020-11-27 10:50 UTC

**Comment by elciok** [comment] 2020-11-27 12:34
Thank you for your explanation, @diemol .

I understand how that behavior can be useful when you are debugging an issue. But I think there are some pretty common cases where it would be great if the container would die when Selenium is killed so the cluster could just spawn a new one.

For example, when you have a long running set of tests that you can't wait around until they finish because they just take a long time. Another case could be when Selenium is used to do something other than normal testing where it would need to be kept running all the time as a service.

At least it would be useful to have some way to change the current behavior and let the container die.
