### ISSUE TITLE
WebDriverError: Content-Type header is missing

### ISSUE THREAD

**Issue by MarkyC** [SeleniumHQ/docker-selenium#1105] opened 2020-09-03 19:33 UTC
## 🐛 Bug Report

When running `selenium/standalone-chrome:4.0.0-alpha-7-prerelease-20200826`, using `driver.getCurrentUrl()` throws an error `WebDriverError: Content-Type header is missing`. The same thing also happens when `driver.quit()` is called

## To Reproduce

```
await driver.get("https://google.com"); // since there's no age gate on this page
await driver.findElement(By.name("q")).sendKeys("test\n");
console.log(await driver.getCurrentUrl()); // WebDriverError: Content-Type header is missing
```

## Expected behavior

`driver.getCurrentUrl()` should return the URL in the browser instead of an error message

## Test script reproducing this issue (when applicable)

I was able to reproduce it in GitHub Actions:
* https://github.com/MarkyC/selenium-standalone-chrome-content-type-bug/runs/1068586385?check_suite_focus=true#step:6:14

## Environment

OS: Linux, OSX
Docker-Selenium image version: selenium/standalone-chrome:4.0.0-alpha-7-prerelease-20200826

**Comment by diemol** [comment] 2020-09-03 20:59
We were able to reproduce it, I will close this issue since it was reported here
https://github.com/SeleniumHQ/selenium/issues/8655

**Closed as completed by diemol** 2020-09-03 20:59 UTC
Labels: needs-triaging
