### ISSUE TITLE
Helm Chart, Node cannot connect to Hub[🐛 Bug]: 

### ISSUE THREAD

**Issue by sourcestl** [SeleniumHQ/docker-selenium#2016] opened 2023-11-21 11:51 UTC
### What happened?

https://groups.google.com/g/selenium-users/c/elbAEGnpX2o
Getting selenuim-hub host could not be found on any Browser node Pods.

### Command used to start Selenium Grid with Docker

```shell
Helm chart any command, not working. ( happening with any chart Version )
```

### Relevant log output

```shell
11:41:19.472 WARN [UnboundZmqEventBus.lambda$new$3] - Connecting to tcp://selenium-hub:4442 and tcp://selenium-hub:4443 failed
11:41:26.917 WARN [UnboundZmqEventBus.lambda$new$4] - Failure #4. Retrying.
11:41:46.928 WARN [UnboundZmqEventBus.isSubAddressIPv6] - Could not determine if the address tcp://selenium-hub:4442 is IPv6 or IPv4
java.net.UnknownHostException: selenium-hub: Temporary failure in name resolution
        at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
        at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:930)
        at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1543)
        at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1533)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1386)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1307)
        at java.base/java.net.InetAddress.getByName(InetAddress.java:1257)
        at org.openqa.selenium.events.zeromq.UnboundZmqEventBus.isSubAddressIPv6(UnboundZmqEventBus.java:180)
        at org.openqa.selenium.events.zeromq.UnboundZmqEventBus.lambda$new$6(UnboundZmqEventBus.java:136)
        at dev.failsafe.Functions.lambda$toCtxSupplier$9(Functions.java:228)
        at dev.failsafe.Functions.lambda$get$0(Functions.java:46)
        at dev.failsafe.internal.RetryPolicyExecutor.lambda$apply$0(RetryPolicyExecutor.java:74)
        at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:187)
        at dev.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
        at dev.failsafe.FailsafeExecutor.run(FailsafeExecutor.java:220)
        at org.openqa.selenium.events.zeromq.UnboundZmqEventBus.<init>(UnboundZmqEventBus.java:133)
        at org.openqa.selenium.events.zeromq.ZeroMqEventBus.create(ZeroMqEventBus.java:51)
        at org.openqa.selenium.events.zeromq.ZeroMqEventBus.create(ZeroMqEventBus.java:91)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.openqa.selenium.grid.config.ClassCreation.callCreateMethod(ClassCreation.java:51)
        at org.openqa.selenium.grid.config.MemoizedConfig.lambda$getClass$4(MemoizedConfig.java:104)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
        at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:99)
        at org.openqa.selenium.grid.server.EventBusOptions.createBus(EventBusOptions.java:51)
        at org.openqa.selenium.grid.server.EventBusOptions.getEventBus(EventBusOptions.java:41)
        at org.openqa.selenium.grid.node.httpd.NodeServer.createHandlers(NodeServer.java:116)
        at org.openqa.selenium.grid.node.httpd.NodeServer.asServer(NodeServer.java:184)
        at org.openqa.selenium.grid.node.httpd.NodeServer.execute(NodeServer.java:246)
        at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:122)
        at org.openqa.selenium.grid.Main.launch(Main.java:83)
        at org.openqa.selenium.grid.Main.go(Main.java:56)
        at org.openqa.selenium.grid.Main.main(Main.java:41)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
        at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
11:41:46.929 WARN [UnboundZmqEventBus.lambda$new$3] - Connecting to tcp://selenium-hub:4442 and tcp://selenium-hub:4443 failed
11:41:46.929 WARN [UnboundZmqEventBus.lambda$new$5] - Connection aborted.
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
        at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: org.openqa.selenium.grid.config.ConfigException: java.lang.reflect.InvocationTargetException
        at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:119)
        at org.openqa.selenium.grid.server.EventBusOptions.createBus(EventBusOptions.java:51)
        at org.openqa.selenium.grid.server.EventBusOptions.getEventBus(EventBusOptions.java:41)
        at org.openqa.selenium.grid.node.httpd.NodeServer.createHandlers(NodeServer.java:116)
        at org.openqa.selenium.grid.node.httpd.NodeServer.asServer(NodeServer.java:184)
        at org.openqa.selenium.grid.node.httpd.NodeServer.execute(NodeServer.java:246)
        at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:122)
        at org.openqa.selenium.grid.Main.launch(Main.java:83)
        at org.openqa.selenium.grid.Main.go(Main.java:56)
        at org.openqa.selenium.grid.Main.main(Main.java:41)
        ... 6 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.openqa.selenium.grid.config.ClassCreation.callCreateMethod(ClassCreation.java:51)
        at org.openqa.selenium.grid.config.MemoizedConfig.lambda$getClass$4(MemoizedConfig.java:104)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
        at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:99)
        ... 15 more
Caused by: org.zeromq.ZMQException: selenium-hub : Address not available
        at zmq.io.net.tcp.TcpAddress.resolve(TcpAddress.java:161)
        at zmq.io.net.tcp.TcpAddress.<init>(TcpAddress.java:39)
        at zmq.io.net.NetProtocol$2.zresolve(NetProtocol.java:61)
        at zmq.io.net.Address.resolve(Address.java:103)
        at zmq.io.net.NetProtocol$2.resolve(NetProtocol.java:55)
        at zmq.SocketBase.connectInternal(SocketBase.java:646)
        at zmq.SocketBase.connect(SocketBase.java:461)
        at org.zeromq.ZMQ$Socket.connect(ZMQ.java:3190)
        at org.openqa.selenium.events.zeromq.UnboundZmqEventBus.lambda$new$6(UnboundZmqEventBus.java:137)
        at dev.failsafe.Functions.lambda$toCtxSupplier$9(Functions.java:228)
        at dev.failsafe.Functions.lambda$get$0(Functions.java:46)
        at dev.failsafe.internal.RetryPolicyExecutor.lambda$apply$0(RetryPolicyExecutor.java:74)
        at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:187)
        at dev.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
        at dev.failsafe.FailsafeExecutor.run(FailsafeExecutor.java:220)
        at org.openqa.selenium.events.zeromq.UnboundZmqEventBus.<init>(UnboundZmqEventBus.java:133)
        at org.openqa.selenium.events.zeromq.ZeroMqEventBus.create(ZeroMqEventBus.java:51)
        at org.openqa.selenium.events.zeromq.ZeroMqEventBus.create(ZeroMqEventBus.java:91)
        ... 23 more
Caused by: java.net.UnknownHostException: selenium-hub
        at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1533)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1386)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1307)
        at zmq.io.net.tcp.TcpAddress.resolve(TcpAddress.java:138)
        ... 40 more
Exception in thread "Thread-0" java.lang.NullPointerException
        at org.openqa.selenium.grid.node.httpd.NodeServer.lambda$new$0(NodeServer.java:78)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

### Operating System

Centos 7

### Docker Selenium version (tag)

4.15.0-20231110

**Comment by VietND96** [comment] 2023-11-21 17:18
```bash
11:41:46.928 WARN [UnboundZmqEventBus.isSubAddressIPv6] - Could not determine if the address tcp://selenium-hub:4442 is IPv6 or IPv4
```
Hi @sourcestl, can you please share which K8s version is used in this setup?

**Comment by diemol** [comment] 2023-11-21 17:26
Thanks for troubleshooting, @vietnd96!

That error shows that the Hub ports cannot receive TCP connections. Please double check your configuration is allowing that.

**Comment by diemol** [comment] 2023-11-21 17:26
I will close this and treat it as a question, but feel free to continue the conversation.

**Closed as completed** 2023-11-21 17:27 UTC
Labels: I-question

**Comment by sourcestl** [comment] 2023-11-22 14:50
@vietnd96 , it is 1.28

@diemol We have used Default Helm chart, where should be change to allow TCP connections. The Nodes could not access tcp://selenium-hub:4442 < this is exposed as service within Kubernetes.

**Comment by VietND96** [comment] 2023-11-22 15:06
I guess current Service definition is not compatible with K8s version v1.28.
Let me try to reproduce with this version and get back to you.

**Comment by sourcestl** [comment] 2023-11-23 13:08
Thank you! @vietnd96

**Comment by VietND96** [comment] 2023-11-27 05:01
Hi @sourcestl, I could not reproduce the issue with the same K8s version.
Can you please provide more info about the environment, e.g K8s cluster on cloud or on-premise? You are using default chart to deploy, any extra configs are set, e.g ingress, load balancer?
You can attach your custom YAML was used, or use `helm template` to get the output of all K8s manifest files generated. Then we can look into what's wrong.

**Comment by sourcestl** [comment] 2023-11-27 09:45
Hi, I have used Minikube, if that helps.
Default template, no custom change.

Regards,
Venod
