### ISSUE TITLE
selenium/standalone-firefox-debug xvfb unable to start

### ISSUE THREAD

**Issue by istinspring** [SeleniumHQ/docker-selenium#309] opened 2016-10-17 17:12 UTC
## Meta -
standalone-firefox
Docker Version:  

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64

## Expected Behavior -

Expected to run docker container at least.

## Actual Behavior -

Docker container stop shortly after start.

```
docker run -p 4444:4444 -p 5901:5900 selenium/standalone-firefox-debug             Waiting xvfb...
-bash: 169.254/16: No such file or directory
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
```

**Comment by ddavison** [comment] 2016-10-17 17:26
closing as duplicate of #227

**Closed by ddavison** 2016-10-17 17:26 UTC
