### ISSUE TITLE
ChromeDriver throws error during startup causing no session created at node

### ISSUE THREAD

**Issue by praveen4463** [SeleniumHQ/docker-selenium#774] opened 2018-08-26 16:28 UTC
Image(s):  
selenium/hub:3.14.0-arsenic
selenium/node-chrome:3.14.0-arsenic

Docker-Selenium Image Version(s):  
3.14.0-arsenic

Docker Version:  
18.06.0-ce

OS: 
Mac 10.13.6 used for running the images

_Note - I am not assuming it as a chromedriver issue cause the chromedriver is failing to start on the port inside docker during session creation which i believe must be working for image builders (contributors).
**Expected Behavior** -ChromeDriver should start inside docker and a new session created._

**Actual Behavior** -ChromeDriver is failing to start with error - 
```
[1535293492.630][SEVERE]: bind() returned an error, errno=99: Cannot assign requested address (99)

```

*Steps to reproduce -**
1) My docker-compose.yaml

```
version: "3.7"
  services:
    selenium-hub:
      image: selenium/hub:3.14.0-arsenic
      container_name: selenium-hub
      ports:
        - "4444:4444"
    chrome:
      image: selenium/node-chrome:3.14.0-arsenic
      build:
        context: .
        shm_size: '2gb'
      depends_on:
        - selenium-hub
      environment: 
        - HUB_HOST=selenium-hub
        - HUB_PORT=4444
        - SE_OPTS="-debug"
```

2) Please run `docker-compose up`

3) Simple test in node:

```
const webdriver = require('selenium-webdriver');

let driver = new webdriver.Builder()
	.forBrowser('chrome')
	.usingServer('http://localhost:4444/wd/hub')
	.build();

driver.manage().window().maximize()
	.then(_ =>  driver.get('http://www.google.com/ncr'))
	.then(_ => driver.findElement(webdriver.By.name('q')).sendKeys('webdriver', webdriver.Key.RETURN))
	.then(_ => driver.wait(webdriver.until.titleIs('webdriver - Google Search'), 1000))
	.then(_ => driver.quit())
	.catch(_err => console.log(_err));
```
4) Run the above test and the container will log following messages:

```
chrome_1        | 14:24:52.619 DEBUG [UrlChecker.waitUntilAvailable] - Waiting for [http://localhost:13939/status]
chrome_1        | 14:24:52.621 DEBUG [UrlChecker.lambda$waitUntilAvailable$1] - Polling http://localhost:13939/status
chrome_1        | Starting ChromeDriver 2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706) on port 13939
chrome_1        | Only local connections are allowed.
chrome_1        | [1535293492.630][SEVERE]: bind() returned an error, errno=99: Cannot assign requested address (99)
chrome_1        | 14:24:52.648 DEBUG [HttpURLConnection.writeRequests] - sun.net.www.MessageHeader@51fa825f5 pairs: {GET /status HTTP/1.1: null}{User-Agent: Java/1.8.0_181}{Host: localhost:13939}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
chrome_1        | 14:24:52.651 DEBUG [HttpURLConnection.getInputStream0] - sun.net.www.MessageHeader@14f816043 pairs: {null: HTTP/1.1 200 OK}{Content-Length: 136}{Content-Type: application/json; charset=utf-8}
chrome_1        | 14:24:53.520 INFO [ProtocolHandshake.createSession] - Detected dialect: OSS
```

5) Node app will raise error 

`WebDriverError: unknown error: failed to change window state to maximized, current state is normal`

If the test doesn't run 'window maximize' and directly go to the url, the node process hangs on the doesn't get anything back.

**Comment by anto-ac** [comment] 2018-08-29 12:26
@praveen4463 I have always had `[SEVERE]: bind() returned an error, errno=99` in my logs, but the session end up being created ok and my tests always run successfully afterwards. It's interesting that's not the case for you. What do the logs say after the last line you've pasted above?

@diemol I guess that #772 may fix also the SEVERE error the `bind() returned an error, errno=99` chrome problem.

**Comment by praveen4463** [comment] 2018-08-29 14:38
Hi @anto-ac,
It just hangs up at that point and nothing happens afterwards. So i believe since the chromedriver/geckodriver server was unable to bind to the port the process freezes up.

I've not yet seen the logs of chromedriver, are you referring that?

**Comment by diemol** [comment] 2018-09-09 17:14
@praveen4463 can you please try with the node-chrome-debug image instead?

**Comment by praveen4463** [comment] 2018-09-15 16:36
@diemol Thanks very much for responding on this. Apologies for the delay, i tried node-chrome-debug images and it worked well. 
I noticed the error "bind() returned an error, errno=99: Cannot assign ..." is still there but the node was able to take request with debug images. I was also able to connect to VNC server and viewed the browser.

I'll try to find differences in 'normal' vs 'debug' images to know why the normal ones are failing for me, if you know something from top of your mind please let me know.

Thanks again!

**Comment by diemol** [comment] 2018-09-16 08:58
Depending on the browser, sometimes the window maximise fails using the "normal" images because they don't have fluxbox, which is a window manager that is installed only in debug images (together with VNC). 
Eventually we will merge both images to avoid this type of issues and to simplify maintenance. 

About the :99 error, I have also seen it but I haven't found the root cause, nevertheless, this is not affecting any test execution.

I'll close this issue since it has been solved.

**Closed by diemol** 2018-09-16 08:58 UTC
Labels: R-awaiting-answer

**Comment by praveen4463** [comment] 2018-09-16 11:28
@diemol Gotcha, but as i wrote in the issue description it failed even if i don't set window-maximize, It just didn't work and hung but i'll investigate myself being one of the images are working correctly.

Thank you!

**Comment by Shuchita009** [comment] 2019-01-16 04:01
@praveen4463 I am learning to execute on docker. I have used following line of code
                ChromeOptions options = new ChromeOptions();
                options.AddArguments("--start-maximized");
                driver = new RemoteWebDriver(new Uri("http://localhost:4446/wd/hub"), options.ToCapabilities());

but I am getting below error Starting ChromeDriver 2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5) on port 21952
Only local connections are allowed.
[1547609611.071][SEVERE]: bind() failed: Cannot assign requested address (99)
03:33:34.220 INFO [ProtocolHandshake.createSession] - Detected dialect: OSS

Please suggest how to overcome it.
I have seen in your answer you have tried  "node-chrome-debug images and it worked well" , how you used it?

**Comment by praveen4463** [comment] 2019-01-17 07:02
@Shuchita009 I just used the same docker-compose and the same code described initially in this issue and just changed the image name to 'debug' one. i suggest you use that and see if it runs.
