### ISSUE TITLE
org.openqa.selenium.TimeoutException after using using Firefox in headless mode from Selenium.

### ISSUE THREAD

**Issue by a527859** [SeleniumHQ/docker-selenium#984] opened 2019-11-11 07:24 UTC
## 🐛 Bug Report

When I am trying to run my selenium tests at firefox headless mode, all the test cases are failing with the exception **org.openqa.selenium.TimeoutException: Timeout loading page after 30000ms**
I am running this docker image on gitlab runner using docker-compose. While all tests are successfull  in the normal mode. 
--

## To Reproduce

Adding Headless mode

## Expected behavior

timeout exception

## Test script reproducing this issue (when applicable)

```java
        private static Capabilities initCapabilities() {
		FirefoxOptions options = new FirefoxOptions();
		FirefoxProfile profile = new FirefoxProfile();
		boolean headless = false;
		if(seleniumProps.getProperty("headless")!=null) {
			String headlessProp = seleniumProps.getProperty("headless").toLowerCase();
			if(headlessProp.equals("true") || headlessProp.equals("false")) {
				headless = Boolean.parseBoolean(headlessProp);
			}
		}
		options.setHeadless(headless);
		profile.setPreference("browser.helperApps.neverAsk.saveToDisk","application/msword, application/csv,application/xml, application/ris, text/csv,text/xml, image/png, application/pdf, text/html, text/plain, application/zip, application/x-zip, application/x-zip-compressed, application/download, application/octet-stream");
		options.setCapability("browser.sessionstore.resume_from_crash", false);
		options.setCapability("browser.safebrowsing.enabled", false);
		options.setCapability("toolkit.startup.max_resumed_crashes", -1);

		options.setCapability("network.proxy.no_proxies_on", "localhost");
		options.setCapability("browser.download.folderList", 2);
		options.setCapability("browser.download.manager.showWhenStarting", false);
		options.setCapability("browser.helperApps.neverAsk.saveToDisk",
				"application/pdf, application/zip, text/zip, text/csv, text/pdf");
		options.setCapability("intl.accept_languages", "en,en-us,fr");

		// allow page with untrusted content (does not work with out firefox version)
		options.setCapability("acceptInsecureCerts", true);
		options.setCapability("assume_untrusted_certificate_issuer", false);
		options.setAcceptInsecureCerts(true);

		
		profile.setAcceptUntrustedCertificates(true);
		options.setProfile(profile);

		return options;
	}
```

## Environment

OS: S name: "linux", version: "3.10.0-693.21.1.el7.x86_64", arch: "amd64", family: "unix"
Docker-Selenium image version: selenium/standalone-firefox-debug:latest
image id :-1580ae50ae77
Docker version: 18.09.0
Docker-Compose version (if applicable):1.23.2

**Comment by conradolega** [comment] 2019-11-29 10:51
This is also happening to us, but intermittently

**Comment by ddavison** [comment] 2019-12-03 18:44
Could you also share the command(s) you used to spin up your containers?

**Comment by a527859** [comment] 2019-12-04 05:20
> Could you also share the command(s) you used to spin up your containers?
In docker-compose.yml file as below:-

services:
  firefox:
    image: selenium/standalone-firefox-debug:latest
    ports:
    - 30011:4444/tcp
    - 30028:5900/tcp
    shm_size: 1g
    environment:
      - SCREEN_WIDTH=1500
      - SCREEN_HEIGHT=1500
      - TZ=Europe/Paris
    volumes:
      - ${linux.project.basedir}/target/test-classes/test-data/psp:/data


The driver is being initialized in  java from docker container as below:

public static RobustRemoteWebDriver getBrowserDriver() {
		try {
			return driver == null ? getBrowserDriver(new URL("http://127.0.0.1:30011/wd/hub")) : driver;
		} catch (MalformedURLException e) {
			throw new RuntimeException(e);
		}
	}

**Comment by andrewnicols** [comment] 2019-12-06 02:21
Also seeing this intermittently. I found that rebooting the hosts which are experiencing this 'cured' the issue.

Simple bash testcase attached with logs
```
docker run --rm -d  --name selenium  -p 4444:4444 selenium/standalone-firefox:3
sleep 4

echo "Creating session:"
SESSIONID=`curl -d '{"capabilities": {"firstMatch": [{"acceptInsecureCerts": false, "browserName": "firefox", "moz:firefoxOptions": {"args": [ "-headless"], "log": {"level": "trace"}}}]}}' http://localhost:4444/wd/hub/session | python3 -c "import sys, json; print(json.load(sys.stdin)['value']['sessionId'])"`
echo
echo
echo "Got a session with id '${SESSIONID}"

echo "Deleting cookies:"
curl -X DELETE "http://localhost:4444/wd/hub/session/${SESSIONID}/cookie"
echo
echo

echo "Fetching user agent:"
curl -d '{"script":"return navigator.userAgent;", "args": []}' "http://localhost:4444/wd/hub/session/${SESSIONID}/execute/sync"
echo
echo

echo "Setting windowrect:"
curl -d '{"width":1366, "height":768}' "http://localhost:4444/wd/hub/session/${SESSIONID}/window/rect"
echo
echo

echo "Setting URL:"
curl -d '{"url":"http:\/\/google.com\/"}' "http://localhost:4444/wd/hub/session/${SESSIONID}/url"
echo

echo "Deleting cookies:"
curl -X DELETE "http://localhost:4444/wd/hub/session/${SESSIONID}/cookie"
echo
echo

echo "Deleting window:"
curl -X DELETE "http://localhost:4444/wd/hub/session/${SESSIONID}/window"
echo
echo

docker stop selenium
```

On those examples which fail, the testcase hangs at the setting URL stage.
It will very occasionallyl eventually succeed on a server which is experiencing fails.

I've attached log counts from the same server. The success one hung for a considerable time whilst setting the URL before eventually succeeding whilst the fail hung for a significant amount of time before eventually failing, and then triggering a shutdown.

[984_fail.txt](https://github.com/SeleniumHQ/docker-selenium/files/3930081/984_fail.txt)
[984_slow_success.txt](https://github.com/SeleniumHQ/docker-selenium/files/3930082/984_slow_success.txt)

**Comment by andrewnicols** [comment] 2019-12-06 02:34
Confirmed that this also happens when using geckodriver directly in the same selenium image.

Removing the -headless option allows things to run.

The main stall seems to be between the following two log lines:
```
  1575597993766 Marionette  TRACE [14] Received observer notification outer-window-destroyed
  1575597994693 Marionette  TRACE [14] Received DOM event pageshow for https://www.google.com/?gws_rd=ssl
```

On passing tests we see the pageshow log, on failing tests we do not see it, and on the same node after a restart there is no hang and it all works well.

**Comment by andrewnicols** [comment] 2019-12-06 02:58
Gist demonstrating failure when using Geckodriver directly: https://gist.github.com/15f03ecccdc160db9a9de3e18e4ef1d1

**Comment by diemol** [comment] 2020-06-14 12:40
Sorry for the late reply, I just read the linked issue and I see that this was a Firefox issue. 
Closing the issue here then.

**Closed by diemol** 2020-06-14 12:40 UTC
Labels: I-firefox-debug, R-awaiting-answer
