### ISSUE TITLE
[🐛 Bug]: Intermittent "System.Net.Sockets.SocketException (125): Operation canceled" error while launching browser on AKS Selenium grid

### ISSUE THREAD

**Issue by chandupranayp** [SeleniumHQ/docker-selenium#1829] opened 2023-04-17 19:55 UTC
### What happened?

While executing scripts on AKS Selenium grid using the command "driver = new RemoteWebDriver(new Uri("https://selenium.dev.in.nbfc.dev/wd/hub"), options.ToCapabilities(), TimeSpan.FromDays(1))", we are encountering an intermittent error "System.Net.Sockets.SocketException (125): Operation canceled". This error causes our scripts to fail, even when Browser PODs are idle. 

Note: Sometimes we have a long queue and scripts need to wait in the queue for a longer time. To handle this, we are using the queue wait-TimeSpan as 1 day.

### Command used to start Selenium Grid with Docker

```shell
Below are my configuration files
###########  kedaSeleniumTriggers ########### 
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: selenium-grid-chrome-scaledobject
  namespace: selenium-dev
  labels:
    deploymentName: selenium-chrome-node
spec:
  maxReplicaCount: 15
  scaleTargetRef:
    name: selenium-chrome-node
  triggers:
    - type: selenium-grid
      metadata:
        url: 'https://selenium.dev.in.nbfc.dev/graphql'
        browserName: 'chrome'
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: selenium-grid-firefox-scaledobject
  namespace: selenium-dev
  labels:
    deploymentName: selenium-firefox-node
spec:
  maxReplicaCount: 5
  scaleTargetRef:
    name: selenium-firefox-node
  triggers:
    - type: selenium-grid
      metadata:
        url: 'https://selenium.dev.in.nbfc.dev/graphql'
        browserName: 'firefox'
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: selenium-grid-edge-scaledobject
  namespace: selenium-dev
  labels:
    deploymentName: selenium-edge-node
spec:
  maxReplicaCount: 10 
  scaleTargetRef:
    name: selenium-edge-node
  triggers:
    - type: selenium-grid
      metadata:
        url: 'https://selenium.dev.in.nbfc.dev/graphql'
        browserName: 'MicrosoftEdge'
        sessionBrowserName: 'msedge'

 ###########  values-dev.yaml ########### 
global:
  seleniumGrid:
    imageTag: 4.8.0-20230131
    nodesImageTag: 4.8.0-20230131
    imagePullSecret: ""

isolateComponents: false

ingress:
  enabled: true
  className: ""
  annotations: {}
  hostname: selenium-grid.local
  tls: []

busConfigMap:
  name: selenium-event-bus-config
  annotations: {}

components:

  router:
    imageName: selenium/router

    imagePullPolicy: IfNotPresent
    imagePullSecret: ""

    annotations: {}
    port: 4444
    livenessProbe:
      enabled: true
      path: /readyz
      initialDelaySeconds: 10
      failureThreshold: 10
      timeoutSeconds: 10
      periodSeconds: 10
      successThreshold: 1
    readinessProbe:
      enabled: true
      path: /readyz
      initialDelaySeconds: 12
      failureThreshold: 10
      timeoutSeconds: 10
      periodSeconds: 10
      successThreshold: 1
    resources: {}
    serviceType: ClusterIP
    loadBalancerIP: ""
    serviceAnnotations: {}
    tolerations: []
    nodeSelector: {}
    priorityClassName: ""

  distributor:
    imageName: selenium/distributor

    imagePullPolicy: IfNotPresent
    imagePullSecret: ""

    annotations: {}
    port: 5553
    resources: {}
    serviceType: ClusterIP
    serviceAnnotations: {}
    tolerations: []
    nodeSelector: {}
    priorityClassName: ""

  eventBus:
    imageName: selenium/event-bus

    imagePullPolicy: IfNotPresent
    imagePullSecret: ""

    annotations: {}
    port: 5557
    publishPort: 4442
    subscribePort: 4443
    resources: {}
    serviceType: ClusterIP
    serviceAnnotations: {}
    tolerations: []
    nodeSelector: {}
    priorityClassName: ""

  sessionMap:
    imageName: selenium/sessions

    imagePullPolicy: IfNotPresent
    imagePullSecret: ""

    annotations: {}
    port: 5556
    resources: {}
    serviceType: ClusterIP
    serviceAnnotations: {}
    tolerations: []
    nodeSelector: {}
    priorityClassName: ""

  sessionQueue:
    imageName: selenium/session-queue

    imagePullPolicy: IfNotPresent
    imagePullSecret: ""

    annotations: {}
    port: 5559
    resources: {}
    serviceType: ClusterIP
    serviceAnnotations: {}
    tolerations: []
    nodeSelector: {}
    priorityClassName: ""

  extraEnvironmentVariables:

  extraEnvFrom:

hub:
  imageName: selenium/hub
  imagePullPolicy: IfNotPresent
  imagePullSecret: ""

  annotations: {}
  labels: {}
  publishPort: 4442
  subscribePort: 4443
  port: 4444
  livenessProbe:
    enabled: true
    path: /readyz
    initialDelaySeconds: 10
    failureThreshold: 10
    timeoutSeconds: 10
    periodSeconds: 10
    successThreshold: 1
  readinessProbe:
    enabled: true
    path: /readyz
    initialDelaySeconds: 12
    failureThreshold: 10
    timeoutSeconds: 10
    periodSeconds: 10
    successThreshold: 1
  extraEnvironmentVariables:
    - name: SE_SESSION_REQUEST_TIMEOUT
      value: "86400"
    - name: SE_NODE_SESSION_TIMEOUT
      value: "600"
  extraEnvFrom:
  resources: {}
  serviceType: ClusterIP
  loadBalancerIP: ""
  serviceAnnotations: {}
  tolerations: []
  nodeSelector: {}
  priorityClassName: ""

chromeNode:
  enabled: true

  deploymentEnabled: true

  replicas: 0
  imageName: selenium/node-chrome
  imagePullPolicy: IfNotPresent
  imagePullSecret: ""

  ports:
    - 5555
  seleniumPort: 5900
  seleniumServicePort: 6900
  annotations: {}
  labels: {}
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "2Gi"
      cpu: "1"
  tolerations: []
  nodeSelector: {}
  hostAliases:
  extraEnvironmentVariables:
    - name: SE_SCREEN_WIDTH
      value: "1920"
    - name: SE_SCREEN_HEIGHT
      value: "1080"
    - name: SE_SESSION_REQUEST_TIMEOUT
      value: "86400"
    - name: SE_NODE_SESSION_TIMEOUT
      value: "600"
  extraEnvFrom:
  service:
    enabled: true
    type: ClusterIP
    annotations: {}
  dshmVolumeSizeLimit: 2Gi
  priorityClassName: ""

  startupProbe: {}
  terminationGracePeriodSeconds: 300
  lifecycle:
    preStop:
      exec:
        command: ["/bin/sh", "-c", "curl --request POST 'localhost:5555/se/grid/node/drain' --header 'X-REGISTRATION-SECRET;'; tail --pid=$(pgrep -f '[n]ode --bind-host false --config /opt/selenium/config.toml') -f /dev/null; sleep 30s"]

  extraVolumeMounts: []

  extraVolumes: []

firefoxNode:
  enabled: true

  deploymentEnabled: true

  replicas: 0
  imageName: selenium/node-firefox
  imagePullPolicy: IfNotPresent
  imagePullSecret: ""

  ports:
    - 5555
  seleniumPort: 5900
  seleniumServicePort: 6900
  annotations: {}
  labels: {}
  tolerations: []
  nodeSelector: {}
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "2Gi"
      cpu: "1"
  hostAliases:
  extraEnvironmentVariables:
    - name: SE_SCREEN_WIDTH
      value: "1920"
    - name: SE_SCREEN_HEIGHT
      value: "1080"
    - name: SE_SESSION_REQUEST_TIMEOUT
      value: "86400"
    - name: SE_NODE_SESSION_TIMEOUT
      value: "600"
  extraEnvFrom:
  service:
    enabled: true
    type: ClusterIP
    annotations: {}
  dshmVolumeSizeLimit: 2Gi
  priorityClassName: ""

  startupProbe: {}
  terminationGracePeriodSeconds: 300
  lifecycle:
    preStop:
      exec:
        command: ["/bin/sh", "-c", "curl --request POST 'localhost:5555/se/grid/node/drain' --header 'X-REGISTRATION-SECRET;'; tail --pid=$(pgrep -f '[n]ode --bind-host false --config /opt/selenium/config.toml') -f /dev/null; sleep 30s"]

  extraVolumeMounts: []

  extraVolumes: []

edgeNode:
  enabled: true

  deploymentEnabled: true

  replicas: 0
  imageName: selenium/node-edge
  imagePullPolicy: IfNotPresent
  imagePullSecret: ""

  ports:
    - 5555
  seleniumPort: 5900
  seleniumServicePort: 6900
  annotations: {}
  labels: {}
  tolerations: []
  nodeSelector: {}
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "2Gi"
      cpu: "1"
  hostAliases:
  extraEnvironmentVariables:
    - name: SE_SCREEN_WIDTH
      value: "1920"
    - name: SE_SCREEN_HEIGHT
      value: "1080"
    - name: SE_SESSION_REQUEST_TIMEOUT
      value: "86400"
    - name: SE_NODE_SESSION_TIMEOUT
      value: "600"
  extraEnvFrom:
  service:
    enabled: true
    type: ClusterIP
    annotations:
      hello: world
  dshmVolumeSizeLimit: 2Gi
  priorityClassName: ""

  startupProbe: {}
  terminationGracePeriodSeconds: 300
  lifecycle:
    preStop:
      exec:
        command: ["/bin/sh", "-c", "curl --request POST 'localhost:5555/se/grid/node/drain' --header 'X-REGISTRATION-SECRET;'; tail --pid=$(pgrep -f '[n]ode --bind-host false --config /opt/selenium/config.toml') -f /dev/null; sleep 30s"]

  extraVolumeMounts: []

  extraVolumes: []

customLabels: {}

########## We use the following helm command to deploy Selenium ##########

helm upgrade --install selenium-grid docker-selenium/selenium-grid --set isolateComponents=false --set ingress.enabled=false -n selenium-dev --values values-dev.yaml
```

### Relevant log output

```shell
System.Net.Sockets.SocketException (125): Operation canceled
```

### Operating System

Ubuntu

### Docker Selenium version (tag)

Selenium Grid 4.8.3. Chrome & Edge version 111.0

**Comment by diemol** [comment] 2023-04-18 07:48
How can I reproduce the issue? Can you share a test script I can execute against a deployed Grid?

**Comment by chandupranayp** [comment] 2023-04-21 15:33
Hello Diemol, This issue occurs intermittently and has no fixed steps to reproduce. 
Unfortunately, I cannot share my scripts as they are restricted.

**Comment by diemol** [comment] 2023-04-21 15:35
Without a way to reproduce it, the issue will likely stall. It does not need to be the exact same code you use internally, any code that helps reproduce the issue is enough.

**Comment by chandupranayp** [comment] 2023-04-25 17:23
Hi Diemol, I have created a workaround for this issue. 
By changing the "SE_SESSION_REQUEST_TIMEOUT" setting to 360 seconds and with the below custom logic, I have been able to overcome the "System.Net.Sockets.SocketException" the issue which is holding my batch execution waiting for 1-day timeout to happen.
Now I am recurringly trying to establish the connection for every 5 mins.

Custom log

public void CreateWebDriverWithRetry(TimeSpan commandTimeout, int maxRetries, int retryDelaySeconds)
        {
            int retries = 0;
            
            while (retries < maxRetries)
            {
                try
                {
                    if (browser.Equals("Chrome"))
                    {
                        ChromeOptions options = new ChromeOptions();
                        driver = new RemoteWebDriver(new Uri("https://selenium.qa.in.XYZ.dev/wd/hub"), options.ToCapabilities(), commandTimeout);
                        log.PassedTestMethod("", browser+" browser launched");
                        break;
                    }
                    else
                    {
                        EdgeOptions options = new EdgeOptions();
                        driver = new RemoteWebDriver(new Uri("https://selenium.qa.in.XYZ.dev/wd/hub"), options.ToCapabilities(), commandTimeout);
                        log.PassedTestMethod("", browser + " browser launched");
                        break;
                    }
                }
             
                catch (Exception ex)
                {
                    if (ex.GetBaseException().ToString().Contains("System.Net.Sockets.SocketException"))
                    {
                        retries++;

                        if (retries >= maxRetries)
                        {
                            log.FailedTestMethod("",$"Failed to create RemoteWebDriver after {maxRetries} attempts: {ex.Message}");
                            throw;
                        }

                        log.InfoTestMethod("",$"Operation canceled (attempt {retries}/{maxRetries}), retrying in {retryDelaySeconds} seconds...");
                        Thread.Sleep(retryDelaySeconds * 1000); // Sleep for the specified number of seconds
                    }
                }
            }

        }

**Comment by diemol** [comment] 2023-04-26 08:43
Looks like the issue is due to the large amount of tests requests you put in the queue which not all of them get processed before the session request timeout is triggered. By adjusting the timeout you will get better results, not sure if retrying to create sessions is the way to go but you know your environment better than I do.

Please also check the different configuration options for the queue https://www.selenium.dev/documentation/grid/configuration/cli_options/#sessionqueue

I will close this since it was a matter of properly configuring the Grid.

**Closed as completed by diemol** 2023-04-26 08:43 UTC
Labels: R-awaiting-answer
