### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by vranjithreddy** [SeleniumHQ/docker-selenium#1518] opened 2022-03-01 04:17 UTC
### What happened?

I see this charts working similar to selenium3. It could be useful if we have documentation relates to how to auto scale, add own ingress  and set max sessions using theses charts

https://github.com/SeleniumHQ/docker-selenium/tree/trunk/chart/selenium-grid

### Command used to start Selenium Grid with Docker

```shell
I am using helm charts from https://github.com/SeleniumHQ/docker-selenium/tree/trunk/chart/selenium-grid
```

### Relevant log output

```shell
Expecting to auto scale, helm chart that supported add own ingress, and set max sessions to 200
```

### Operating System

suse linux

### Docker Selenium version (tag)

4.1.1

**Comment by diemol** [comment] 2022-03-01 09:26
This is a duplicate of #1517, please follow https://github.com/SeleniumHQ/selenium/issues/9845 for updates.

**Closed as completed by diemol** 2022-03-01 09:26 UTC
