### ISSUE TITLE
Chrome browser crashes. 

### ISSUE THREAD

**Issue by gireinvent** [SeleniumHQ/docker-selenium#1081] opened 2020-07-13 19:59 UTC
## 🐛 Bug Report

Chrome Browser crash when run on [docker.](url)

## To Reproduce

Steps to reproduce the behavior (including the command to start the containers):

## Expected behavior
Chrome browser should not crash.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS:  Windows 10
Docker-Selenium image version: 3.141.59-20200525
Also provide the docker image id : 845cb7d30dec
-->
Docker version: 
Docker-Compose version (if applicable): 3.7
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):

**Comment by diemol** [comment] 2020-07-13 22:08
I will close this issue since there is no clear description of what the issue is or how to reproduce it.

**Closed by diemol** 2020-07-13 22:08 UTC
Labels: needs-triaging
