### ISSUE TITLE
[🚀 Feature]: Support file downloads on the nodes

### ISSUE THREAD

**Issue by xZero707** [SeleniumHQ/docker-selenium#1813] opened 2023-03-23 14:45 UTC
### Feature and motivation

Right now, the [suggested solution](https://github.com/SeleniumHQ/docker-selenium#mounting-volumes-to-retrieve-downloaded-files) for downloading files is mounting a volume, but this is not practical when the grid is running as a remote service. 

Selenium provides an API for fetching remote files, and this feature had a recent revamp (see: PR SeleniumHQ/selenium#11277 and SeleniumHQ/selenium#11702). <br/>

Unfortunately, it seems like nothing of this is implemented in Selenium Docker, the place where this feature is very much needed. 

Here are my unsuccessful attempts:

**Chrome node**
```
GET /session/:sessionId:/se/files
curl -X GET "http://172.17.53.2:4444/session/98473aa8661fc256bf7c0de98861005e/se/file?filename=100MB.bin"
Result = Unknown command
```

**Firefox node**
```
GET /session/:sessionId:/se/files
curl -X GET "http://172.17.53.2:4444/session/98473aa8661fc256bf7c0de98861005e/se/file?filename=100MB.bin"
Result = Unsupported method - expect POST for file upload
```

**I also tried running this using PHP driver:**
```php
$file = $driver->executeCustomCommand('/session/:sessionId/se/file?filename=100MB.bin');
```

Result:
```
Facebook\WebDriver\Exception\UnknownCommandException : unknown command: unknown command: session/41d161b598c0fd3f85a4e09b1f5f5a1f/se/file?filename=100MB.bin`
```

This feature is [documented](https://www.selenium.dev/documentation/grid/configuration/cli_options/#specifying-path-from-where-downloaded-files-can-be-retrieved), yet cannot be used.

I defined `--downloads-path /usr/downloads` using env `SE_OPTS` and nothing. Chrome is still downloading to `/home/seluser/Downloads` and ignoring the path I defined. 

Version: Selenium 4.8.1 (revision 8ebccac989)

### Usage example

Calling API like this would return JSON response with base64 encoded file data.

```
curl -X GET "http://172.17.53.2:4444/session/98473aa8661fc256bf7c0de98861005e/se/file?filename=100MB.bin"
```

Expected response:
```json
{
    "filename": "100MB.bin",
    "contents": "ZXhhbXBsZSBiaW5hcnkgZGF0YQ=="
}
```

**Comment by patilsha** [comment] 2023-04-18 14:52
Can someone please take this issue to include the fix in selenium-docker?
Thanks

**Comment by diemol** [comment] 2023-04-18 14:56
This is already working https://www.selenium.dev/documentation/grid/configuration/cli_options/#enabling-managed-downloads-by-the-node

You can pass the flag via `SE_OPTS` or send us a PR to set the flag via an environment variable.

**Comment by xZero707** [comment] 2023-04-19 17:15
@diemol With Selenium 4.8.1, this flag was not recognized by node. As of 4.8.2 it works, but there is no reference to commit that fixed this. Anyway, now that I have it running, I'll test it, and get back with the results.

**Comment by xZero707** [comment] 2023-04-20 12:41
I can confirm that this is working as intended, although making it work was challenging. This is what it takes to enable this with [php-webdriver/php-webdriver](https://github.com/php-webdriver/php-webdriver) on Chrome.

```php
<?php

use Facebook\WebDriver\Chrome\ChromeOptions;
use Facebook\WebDriver\Remote\DesiredCapabilities;

$desiredCapabilities = DesiredCapabilities::chrome();
$desiredCapabilities->setCapability('se:downloadsEnabled', true);
$desiredCapabilities->setCapability(ChromeOptions::CAPABILITY_W3C, [
    'prefs' => [
        'se:downloadsEnabled' => true
    ]
 ]);
```
Without `ChromeOptions::CAPABILITY_W3C`, `GET` would return empty array of files and `POST` would fail saying that file doesn't exist.

Without `$desiredCapabilities->setCapability('se:downloadsEnabled', true);` I would get error:
```
Cannot find downloads file system for session id: XXXXXXXXXXXX
```

Documentation doesn't state that `ChromeOptions::CAPABILITY_W3C` is required too. 

---
And this is how to implement it since [php-webdriver/php-webdriver](https://github.com/php-webdriver/php-webdriver) has no implemented methods for this:
```php
<?php

/**
* List downloaded files
* Example: {"names":["1MB.bin","5MB.bin"]}
*/
$driver->executeCustomCommand('/session/:sessionId/se/files');

/**
* Download desired file
* Eg. {"filename":"1MB.bin","contents":"UEsDBBQACAgIAEFN..."}
* Eg. {"filename":"5MB.bin","contents":"UEsDBBQACAgIAMpNl..."}
*/
$driver->executeCustomCommand('/session/:sessionId/se/files', 'POST', [
    'name' => '1MB.bin'
]);

```

Anyhow guys, well done. Very glad to finally have this working.

**Comment by patilsha** [comment] 2023-04-20 14:56
I am still getting error as below

 **"message\":\"unknown command: unknown command: session/87c6bf631786eb72a16b3a152d0afa93/se/files\**

I tried the same scenario to list downloaded files with below detail
I am using C# code to run our selenium scripts on Selenium Grid on Docker
WebDriver version = 4.8.2
Selenium Grid version = 4.8.3
Chrome version = 104
Below are the settings for Chrome Options (There is no DesiredCapability class available to set the capabilities in C# WebDriver)
ChromeOptions options = new ChromeOptions(); 
options.AddUserProfilePreference("se:downloadsEnabled", true)

I am making a HTTP Get call to list down the all downloaded files on particular node.
http://{HubIPAddress}:4444/session/87c6bf631786eb72a16b3a152d0afa93/se/files

Can someone please help how can I use this download functionality in C# Selenium Grid on Docker?
I'm suspecting the capability has not been selected correctly. 
Thanks

**Comment by diemol** [comment] 2023-04-20 14:59
I will close this issue since the main requirement is completed. @patilsha please open a new one with enough information to reproduce the issue.

**Closed as completed by diemol** 2023-04-20 14:59 UTC
Labels: help wanted

**Comment by patilsha** [comment] 2023-04-20 15:07
Thanks @diemol I've raised a new issue as below 
https://github.com/SeleniumHQ/docker-selenium/issues/1831
