### ISSUE TITLE
[🐛 Bug]: Selenium4 Node chrome not getting registered with Hub

### ISSUE THREAD

**Issue by sharigitpersonal** [SeleniumHQ/docker-selenium#1441] opened 2021-10-28 02:15 UTC
### What happened?

While running Hub and node-chrome (4.0) in kubernetes cluster. The node is not able to get registered, It keeps on sending the registration event. 
I tried Standalone chrome and it is working ,though.

Can someone help ? 

[seleniumerrorlog.txt](https://github.com/SeleniumHQ/docker-selenium/files/7430528/seleniumerrorlog.txt)

### Command used to start Selenium Grid with Docker

```shell
Selenium Hub and Node was created using Kubernetes deployment yaml. 
The file attached has the service,deployment contents.
```

### Relevant log output

```shell
[events]
publish = "tcp://selenium-hub:4442"
subscribe = "tcp://selenium-hub:4443"

[server]
host = "selenium-chrome-node"
port = "5555"
[node]
grid-url = "http://selenium-hub:4444"
session-timeout = "300"
override-max-sessions = true
detect-drivers = false
max-sessions = 10

[[node.driver-configuration]]
display-name = "chrome"
stereotype = '{"browserName": "chrome", "browserVersion": "95.0", "platformName": "Linux"}'
max-sessions = 10
.
.
.
17:00:27.549 INFO [NodeServer$1.start] - Starting registration process for node id d6a68bf5-e5b4-483a-9e71-408b3c158c0b
17:00:27.609 INFO [NodeServer.execute] - Started Selenium node 4.0.0 (revision 3a21814679): http://selenium-chrome-node:5555
17:00:27.621 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
17:00:37.629 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
17:00:47.636 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
17:00:57.641 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
17:01:07.646 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
17:01:17.650 INFO [NodeServer$1.lambda$start$1] - Sending registration event...

````
This registration never happens

Logs of hub pod:

```
4443, advertising as tcp://100.106.0.5:4443]
17:00:25.242 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://100.106.0.5:4442 and tcp://100.106.0.5:4443
17:00:25.324 INFO [UnboundZmqEventBus.<init>] - Sockets created
17:00:26.333 INFO [UnboundZmqEventBus.<init>] - Event bus ready
17:00:27.621 INFO [Hub.execute] - Started Selenium Hub 4.0.0 (revision 3a21814679): http://100.106.0.5:4444
```

### Operating System

Ubuntu

### Docker Selenium version (tag)

4.0

**Comment by woosyume** [comment] 2021-10-28 08:40
Hi.
Hub allows access from the node?
I mean the node can see 100.106.0.5 and 4444 is opened?
Hub and node should be able to see each other.

**Comment by sharigitpersonal** [comment] 2021-10-28 09:48
> Hi. Hub allows access from the node? I mean the node can see 100.106.0.5 and 4444 is opened? Hub and node should be able to see each other.
    
The GirdURL is mentioned as http://selenium-hub:4444 where 'selenium-hub' is the service abstracting the hub from the pod running in the same cluster. 
Getting into the chrome Pod and doing a curl to the http://selenium-hub:4444/status was showing results. 

I think that means there is traffic flowing ! @woosyume  Can you elaborate if I overlooked anything ?
. 
The

**Comment by woosyume** [comment] 2021-10-28 13:28
- How about the opposite side?
Can the selenium-hub can see 'http://selenium-chrome-node:5555' as well?

- In my understanding, the request from node is transferred by EventBus which is opened with 4442 and 4443.
And they're in selenium-hub as you may know.
The ports can be accessible from node as well, not only 4444?

**Comment by namilkimfree** [comment] 2021-11-03 02:01
dynamic grid node same issue 

https://github.com/SeleniumHQ/docker-selenium/issues/1408

**Comment by diemol** [comment] 2021-11-03 15:27
This [comment](https://github.com/SeleniumHQ/docker-selenium/issues/1403#issuecomment-959134307) should help. If the issue is still happening, please create a new one with all the requested details (lots were left out).

**Closed as completed** 2021-11-03 15:27 UTC
