### ISSUE TITLE
[🐛 Bug]: Azure Kubernetes Services and Keda Selenium Grid scaler:org.openqa.selenium.NoSuchSessionException: Unable to execute request for an existing session

### ISSUE THREAD

**Issue by abhitrivedi2006** [SeleniumHQ/docker-selenium#1726] opened 2022-11-14 20:58 UTC
### What happened?

We are using AKS with Keda Selenium auto scaler for our tests ..Keda scaler seems to be working fine. We are seeing issues when we are running  75 tests with thread count 50.. every-time we see 50 jobs are successful and remaining 25 tests fail with below error    

Unable to execute request for an existing session: Unable to find session with ID: 

### Command used to start Selenium Grid with Docker

```shell
Instruction were followed from https://github.com/SeleniumHQ/docker-selenium#deploying-to-kubernetes
```

### Relevant log output

```shell
org.openqa.selenium.NoSuchSessionException: Unable to execute request for an existing session: Unable to find session with ID: 5a69294737d508d189cf0f1759dbcfa8
Build info: version: '4.5.0', revision: 'fe167b119a'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1094-azure', java.version: '11.0.16'
Driver info: driver.version: unknown
Build info: version: '4.5.0', revision: 'fe167b119a'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-372.19.1.el8_6.x86_64', java.version: '17'
Driver info: org.openqa.selenium.remote.RemoteWebDriver$ByteBuddy$JZkTlmlV
Command: [5a69294737d508d189cf0f1759dbcfa8, getElementText {id=97ae1603-c5ba-4953-bb2d-955782e62b0e}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 106.0.5249.91, chrome: {chromedriverVersion: 106.0.5249.61 (511755355844..., userDataDir: /tmp/.com.google.Chrome.Hv7AYt}, goog:chromeOptions: {debuggerAddress: localhost:34253}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: LINUX, proxy: Proxy(), se:cdp: ws://20.81.3.213:4444/sessi..., se:cdpVersion: 106.0.5249.91, se:vnc: ws://20.81.3.213:4444/sessi..., se:vncEnabled: true, se:vncLocalAddress: ws://10.250.0.221:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Element: [[RemoteWebDriver$ByteBuddy$JZkTlmlV: chrome on LINUX (5a69294737d508d189cf0f1759dbcfa8)] -> xpath: //table[@class = 'recentsList']//a[@data-refid = 'recordId']]
Session ID: 5a69294737d508d189cf0f1759dbcfa8
	at jdk.internal.reflect.GeneratedConstructorAccessor93.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
	at java.base/java.util.function.Function.lambda$andThen$1(Function.java:88)
	at org.openqa.selenium.remote.RemoteWebDriverBuilder.lambda$createExecutor$12(RemoteWebDriverBuilder.java:450)
	at org.openqa.selenium.remote.RemoteWebDriverBuilder.lambda$createExecutor$13(RemoteWebDriverBuilder.java:456)
	at org.openqa.selenium.remote.RemoteWebDriverBuilder.lambda$createExecutor$14(RemoteWebDriverBuilder.java:460)
	at org.openqa.selenium.remote.RemoteWebDriverBuilder.lambda$createExecutor$15(RemoteWebDriverBuilder.java:469)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:547)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:257)
	at org.openqa.selenium.remote.RemoteWebElement.getText(RemoteWebElement.java:207)
	at grid.pages.connected.RecentRecordsPage.recordsNames(RecentRecordsPage.java:67)
	at grid.tests.connected.SalesforceTests12.salesforceTest(SalesforceTests12.java:55)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Operating System

Azure Kubernetes Services/ Chrome

### Docker Selenium version (tag)

4.5.0-20221004 and 4.6.0-20221104

**Comment by abhitrivedi2006** [comment] 2022-11-14 20:59
[hub4.6.log](https://github.com/SeleniumHQ/docker-selenium/files/10007015/hub4.6.log)

**Comment by abhitrivedi2006** [comment] 2022-11-14 21:05
Hub Config

kind: Deployment
apiVersion: apps/v1
metadata:
  name: selenium-hub
  namespace: abhi
  uid: 244de8f7-4bef-4974-911e-a99eac420223
  resourceVersion: '20385781'
  generation: 2
  creationTimestamp: '2022-11-11T21:08:28Z'
  labels:
    app: selenium-hub
    app.kubernetes.io/component: selenium-grid-4.6.0-20221104
    app.kubernetes.io/instance: selenium-grid
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: selenium-hub
    app.kubernetes.io/version: 4.6.0-20221104
    helm.sh/chart: selenium-grid-0.13.1
  annotations:
    deployment.kubernetes.io/revision: '2'
    meta.helm.sh/release-name: selenium-grid
    meta.helm.sh/release-namespace: abhi
  managedFields:
    - manager: helm
      operation: Update
      apiVersion: apps/v1
      time: '2022-11-11T21:08:28Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
        f:spec:
          f:progressDeadlineSeconds: {}
          f:replicas: {}
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:strategy:
            f:rollingUpdate:
              .: {}
              f:maxSurge: {}
              f:maxUnavailable: {}
            f:type: {}
          f:template:
            f:metadata:
              f:labels:
                .: {}
                f:app: {}
                f:app.kubernetes.io/component: {}
                f:app.kubernetes.io/instance: {}
                f:app.kubernetes.io/managed-by: {}
                f:app.kubernetes.io/name: {}
                f:app.kubernetes.io/version: {}
                f:helm.sh/chart: {}
            f:spec:
              f:containers:
                k:{"name":"selenium-hub"}:
                  .: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:livenessProbe:
                    .: {}
                    f:failureThreshold: {}
                    f:httpGet:
                      .: {}
                      f:path: {}
                      f:port: {}
                      f:scheme: {}
                    f:initialDelaySeconds: {}
                    f:periodSeconds: {}
                    f:successThreshold: {}
                    f:timeoutSeconds: {}
                  f:name: {}
                  f:ports:
                    .: {}
                    k:{"containerPort":4442,"protocol":"TCP"}:
                      .: {}
                      f:containerPort: {}
                      f:protocol: {}
                    k:{"containerPort":4443,"protocol":"TCP"}:
                      .: {}
                      f:containerPort: {}
                      f:protocol: {}
                    k:{"containerPort":4444,"protocol":"TCP"}:
                      .: {}
                      f:containerPort: {}
                      f:protocol: {}
                  f:readinessProbe:
                    .: {}
                    f:failureThreshold: {}
                    f:httpGet:
                      .: {}
                      f:path: {}
                      f:port: {}
                      f:scheme: {}
                    f:initialDelaySeconds: {}
                    f:periodSeconds: {}
                    f:successThreshold: {}
                    f:timeoutSeconds: {}
                  f:resources: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
              f:dnsPolicy: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:terminationGracePeriodSeconds: {}
    - manager: Mozilla
      operation: Update
      apiVersion: apps/v1
      time: '2022-11-11T22:06:27Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:template:
            f:spec:
              f:containers:
                k:{"name":"selenium-hub"}:
                  f:env:
                    .: {}
                    k:{"name":"SE_OPTS"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"SE_SESSION_REQUEST_TIMEOUT"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"SE_SESSION_RETRY_INTERVAL"}:
                      .: {}
                      f:name: {}
                      f:value: {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2022-11-12T00:54:52Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:deployment.kubernetes.io/revision: {}
        f:status:
          f:availableReplicas: {}
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Progressing"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updatedReplicas: {}
      subresource: status
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-hub
      app.kubernetes.io/instance: selenium-grid
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: selenium-hub
        app.kubernetes.io/component: selenium-grid-4.6.0-20221104
        app.kubernetes.io/instance: selenium-grid
        app.kubernetes.io/managed-by: helm
        app.kubernetes.io/name: selenium-hub
        app.kubernetes.io/version: 4.6.0-20221104
        helm.sh/chart: selenium-grid-0.13.1
    spec:
      containers:
        - name: selenium-hub
          image: selenium/hub:4.6.0-20221104
          ports:
            - containerPort: 4444
              protocol: TCP
            - containerPort: 4442
              protocol: TCP
            - containerPort: 4443
              protocol: TCP
          env:
            - name: SE_OPTS
              value: '--log-level FINE'
            - name: SE_SESSION_REQUEST_TIMEOUT
              value: '3600'
            - name: SE_SESSION_RETRY_INTERVAL
              value: '20'
          resources: {}
          livenessProbe:
            httpGet:
              path: /readyz
              port: 4444
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 4444
              scheme: HTTP
            initialDelaySeconds: 12
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 2
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2022-11-11T22:06:47Z'
      lastTransitionTime: '2022-11-11T21:08:28Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "selenium-hub-5b6dc98bcf" has successfully progressed.
    - type: Available
      status: 'True'
      lastUpdateTime: '2022-11-12T00:54:52Z'
      lastTransitionTime: '2022-11-12T00:54:52Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.

**Comment by diemol** [comment] 2022-11-15 09:10
Not sure what the cause might be. The error means that you are trying to interact with a session that does not exist anymore. The log does not provide any information. You should probably scan the logs and see what happened with session `5a69294737d508d189cf0f1759dbcfa8`, or whatever ID you get in the logs.

**Comment by abhitrivedi2006** [comment] 2022-11-15 20:46
Thanks @diemol We tried to trace ID 98200fbbefec27e2a93631ed57b337db ... but couldn't understand as what could be causing the issue...

to me it sounds like it could be an issue with scaling down the chrome node( using Keda selenium scaler) because when I keep all the Pods available same test works fine .

1- 75 tests with thread count 75 -- it works
2- 75 tests with thread count 50 -- it doesn't work ( first 50 tests pass and other 25 test fails with rg.openqa.selenium.NoSuchSessionException: Unable to find session with ID)

Here is the logs based on the 98200fbbefec27e2a93631ed57b337db ID .
_______________________________________________________________________________________________________
17:20:21.469 DEBUG [RequestConverter.channelRead0] - Incoming message: DefaultHttpRequest(decodeResult: success, version: HTTP/1.1)
POST /session/98200fbbefec27e2a93631ed57b337db/elements HTTP/1.1
User-Agent: selenium/4.5.0 (java unix)
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
host: 20.81.3.213:4444
accept: */*
content-length: 114
17:20:21.469 DEBUG [RequestConverter.channelRead0] - Start of http request: DefaultHttpRequest(decodeResult: success, version: HTTP/1.1)
POST /session/98200fbbefec27e2a93631ed57b337db/elements HTTP/1.1
User-Agent: selenium/4.5.0 (java unix)
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
host: 20.81.3.213:4444
accept: */*
content-length: 114
17:20:21.469 DEBUG [RequestConverter.channelRead0] - Incoming message: DefaultLastHttpContent(data: PooledSlicedByteBuf(ridx: 0, widx: 114, cap: 114/114, unwrapped: PooledUnsafeDirectByteBuf(ridx: 352, widx: 352, cap: 384)), decoderResult: success)
17:20:21.469 DEBUG [RequestConverter.channelRead0] - Closing input pipe.
17:20:21.469 DEBUG [HttpTracing.inject] - Injecting (POST) /session/98200fbbefec27e2a93631ed57b337db/elements into OpenTelemetrySpan{traceId=850b72a7144bc1130a98076c7c56f68a,spanId=71d661fb6b377b7a} at org.openqa.selenium.grid.router.HandleSession:121
17:20:21.470 DEBUG [SeleniumSpanExporter$1.lambda$export$4] - SpanData{spanContext=ImmutableSpanContext{traceId=850b72a7144bc1130a98076c7c56f68a, spanId=71d661fb6b377b7a, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, parentSpanContext=ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}, resource=Resource{schemaUrl=https://opentelemetry.io/schemas/1.13.0, attributes={service.name="unknown_service:java", telemetry.sdk.language="java", telemetry.sdk.name="opentelemetry", telemetry.sdk.version="1.19.0"}}, instrumentationScopeInfo=InstrumentationScopeInfo{name=default, version=null, schemaUrl=null, attributes={}}, name=router.handle_session, kind=INTERNAL, startEpochNanos=1668532821469000000, endEpochNanos=1668532821469440180, attributes=AttributesMap{data={http.target=/session/98200fbbefec27e2a93631ed57b337db/elements, error=true, http.method=POST, session.id=98200fbbefec27e2a93631ed57b337db}, capacity=128, totalAddedValues=4}, totalAttributeCount=4, events=[ImmutableEventData{name=exception, attributes={exception.message="Unable to execute request for an existing session: Unable to find session with ID: 98200fbbefec27e2a93631ed57b337db
Build info: version: '4.6.0', revision: '79f1c02ae20'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1094-azure', java.version: '11.0.16'
Driver info: driver.version: unknown", exception.stacktrace="org.openqa.selenium.NoSuchSessionException: Unable to find session with ID: 98200fbbefec27e2a93631ed57b337db
Build info: version: '4.6.0', revision: '79f1c02ae20'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1094-azure', java.version: '11.0.16'
Driver info: driver.version: unknown
	at org.openqa.selenium.grid.sessionmap.local.LocalSessionMap.get(LocalSessionMap.java:129)
	at org.openqa.selenium.grid.router.HandleSession.lambda$loadSessionId$4(HandleSession.java:159)
	at io.opentelemetry.context.Context.lambda$wrap$2(Context.java:224)
	at org.openqa.selenium.grid.router.HandleSession.execute(HandleSession.java:122)
	at org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:373)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
	at org.openqa.selenium.grid.router.Router.execute(Router.java:91)
	at org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
	at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)
	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
", exception.type="org.openqa.selenium.NoSuchSessionException", http.flavor=1, http.handler_class="org.openqa.selenium.grid.router.HandleSession", http.host="20.81.3.213:4444", http.method="POST", http.request_content_length="114", http.scheme="HTTP", http.target="/session/98200fbbefec27e2a93631ed57b337db/elements", http.user_agent="selenium/4.5.0 (java unix)", session.id="98200fbbefec27e2a93631ed57b337db"}, epochNanos=1668532821469353040, totalAttributeCount=12}], totalRecordedEvents=1, links=[], totalRecordedLinks=0, status=ImmutableStatusData{statusCode=ERROR, description=Kind: CANCELLED Description:}, hasEnded=true}
17:20:21.470 WARN [SeleniumSpanExporter$1.lambda$export$1] - Unable to execute request for an existing session: Unable to find session with ID: 98200fbbefec27e2a93631ed57b337db
Build info: version: '4.6.0', revision: '79f1c02ae20'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1094-azure', java.version: '11.0.16'
Driver info: driver.version: unknown
17:20:21.470 WARN [SeleniumSpanExporter$1.lambda$export$1] - org.openqa.selenium.NoSuchSessionException: Unable to find session with ID: 98200fbbefec27e2a93631ed57b337db
Build info: version: '4.6.0', revision: '79f1c02ae20'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1094-azure', java.version: '11.0.16'
Driver info: driver.version: unknown
	at org.openqa.selenium.grid.sessionmap.local.LocalSessionMap.get(LocalSessionMap.java:129)
	at org.openqa.selenium.grid.router.HandleSession.lambda$loadSessionId$4(HandleSession.java:159)
	at io.opentelemetry.context.Context.lambda$wrap$2(Context.java:224)
	at org.openqa.selenium.grid.router.HandleSession.execute(HandleSession.java:122)
	at org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:373)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
	at org.openqa.selenium.grid.router.Router.execute(Router.java:91)
	at org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
	at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)
	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)

**Comment by abhitrivedi2006** [comment] 2022-11-16 01:35
thanks @diemol  here is what we found

1. run selenium java tests using a testng.xml file
2. there are 75 test classes, each with 1 test method
3. the thread count from the testng.xml count is 50, tests are executed in parallel by class
4. the first 50 tests pass after being executed in parallel
5. most of the remaining 25 tests fail
6. this is an example:
   test starts ok
    
        15-Nov-2022 12:14:45    grid.tests.connected.SalesforceTests22.salesforceTest STARTED
        15-Nov-2022 12:14:45    SalesforceTests22 - session id = 1b019875f3829d4409b4613450ffbc45
        
    test fails due to missing session
    
        15-Nov-2022 12:20:20    grid.tests.connected.SalesforceTests22.salesforceTest FAILED in 335 seconds
        15-Nov-2022 12:20:20    
        15-Nov-2022 12:20:20    
        15-Nov-2022 12:20:20     exception:
        15-Nov-2022 12:20:20    
        15-Nov-2022 12:20:20    Unable to execute request for an existing session: Unable to find session with ID: 1b019875f3829d4409b4613450ffbc45
        15-Nov-2022 12:20:20    Build info: version: '4.6.0', revision: '79f1c02ae20'
        15-Nov-2022 12:20:20    System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1094-azure', java.version: '11.0.16'
        15-Nov-2022 12:20:20    Driver info: driver.version: unknown
        15-Nov-2022 12:20:20    Build info: version: '4.5.0', revision: 'fe167b119a'
        15-Nov-2022 12:20:20    System info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-372.19.1.el8_6.x86_64', java.version: '17'
        15-Nov-2022 12:20:20    Driver info: org.openqa.selenium.remote.RemoteWebDriver$ByteBuddy$at5LYqNV
        15-Nov-2022 12:20:20    Command: [1b019875f3829d4409b4613450ffbc45, findElements {using=xpath, value=//div[@class = 'board']/div[@class = 'board-header']/span}]
        
        15-Nov-2022 12:20:20    Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 107.0.5304.87, chrome: {chromedriverVersion: 107.0.5304.62 (1eec40d3a576..., userDataDir: /tmp/.com.google.Chrome.ywf13j}, goog:chromeOptions: {debuggerAddress: localhost:41935}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: LINUX, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://20.81.3.213:4444/sessi..., se:cdpVersion: 107.0.5304.87, se:vnc: ws://20.81.3.213:4444/sessi..., se:vncEnabled: true, se:vncLocalAddress: ws://10.250.0.65:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}



       15-Nov-2022 12:20:20    Session ID: 1b019875f3829d4409b4613450ffbc45
        
    the above details are taken from the attached log of the bamboo build.
    
7. searching through the grid hub log, it is clear that the grid releases the session during the execution of the test (see attached screenshot)

8. what are possible causes for the grid to release and delete the session while the test is still being executed?

![grid releases the sessionf88f9b1c6c39e3286d8884db32033ff73de00f69ee134c38d2ee1387c12b4a8b](https://user-images.githubusercontent.com/60986284/202061551-f014945d-6a50-458b-8ea3-6ead570f6797.png)

**Comment by abhitrivedi2006** [comment] 2022-11-16 01:39
attached the bamboo job 
[plan-155681183-JOB1-35a8fb862f18f308d5ad901a376cb6434df8443ee1f70b3cb898977e5e7fa0299d.log](https://github.com/SeleniumHQ/docker-selenium/files/10017367/plan-155681183-JOB1-35a8fb862f18f308d5ad901a376cb6434df8443ee1f70b3cb898977e5e7fa0299d.log)

**Comment by diemol** [comment] 2022-11-16 09:03
A session is release because it times out or because the client stops the session. 

I cannot see much about that session ID in the logs you provided. Feel free to provide the full log for the Node and Hub where the session was stopped/released.

**Comment by abhitrivedi2006** [comment] 2022-11-16 18:45
[Logs.zip](https://github.com/SeleniumHQ/docker-selenium/files/10024766/Logs.zip)

uploading the logs.

**Comment by diemol** [comment] 2022-11-17 15:02
I do not see the logs of the Node, which is what would tell us what happened with session ID 1b019875f3829d4409b4613450ffbc45.

**Comment by abhitrivedi2006** [comment] 2022-11-17 15:37
> 
Hi @diemol as I mentioned .. we are using Keda Selenium scalar which brings down the Pods so its easy to collect node logs .. so pls let me know if there is anything we can do to collects those logs.

Also if we disable Keda selenium scalar and make to the pods available then this problem goes away.

**Comment by diemol** [comment] 2022-11-17 15:46
Not sure, maybe you can check if there is a way to tell Kubernetes to store logs.

**Comment by abhitrivedi2006** [comment] 2022-11-17 18:31
Please track session ID 397ce9a0018f3032667601d1ce209564 
Here are the logs from Hub, Node and Bamboo plan
[Hub.csv](https://github.com/SeleniumHQ/docker-selenium/files/10034513/Hub.csv)
[Node.csv](https://github.com/SeleniumHQ/docker-selenium/files/10034514/Node.csv)
[plan-155681183-JOB1-85.log](https://github.com/SeleniumHQ/docker-selenium/files/10034526/plan-155681183-JOB1-85.log)

**Comment by abhitrivedi2006** [comment] 2022-11-17 22:43
Please track the session ID as fb481374a9c7769e366c2d178795c6c4 


[hub log for session3febc8daa3c3109c20be9e33727cd78f2c79e19ca84998b6e815ef522ee5bf10.xlsx](https://github.com/SeleniumHQ/docker-selenium/files/10036253/hub.log.for.session3febc8daa3c3109c20be9e33727cd78f2c79e19ca84998b6e815ef522ee5bf10.xlsx)
[node log latest68391575b627cc45e7e87a354f82ea377d510fa65d27f2a227fd1e553505e8c0.xlsx](https://github.com/SeleniumHQ/docker-selenium/files/10036257/node.log.latest68391575b627cc45e7e87a354f82ea377d510fa65d27f2a227fd1e553505e8c0.xlsx)
[bamboo log latest52c55ffc58fbd5a1b4d9ec7c27a210bc981ed42df15aefcd9500271c058b7c6e.log](https://github.com/SeleniumHQ/docker-selenium/files/10036258/bamboo.log.latest52c55ffc58fbd5a1b4d9ec7c27a210bc981ed42df15aefcd9500271c058b7c6e.log)

**Comment by diemol** [comment] 2022-11-21 16:01
I cannot really see the whole session in the Node log. I cannot see when the session starts and when it ends. Also, there is no need to have the log in debug more, there is a lot of unneeded noise for this case.

**Comment by abhitrivedi2006** [comment] 2022-11-22 23:10
Here are the fresh logs .. pls track the session ID -  d94ded3d155a38290523f8fddf96326a

[Hub.csv](https://github.com/SeleniumHQ/docker-selenium/files/10071709/Hub.csv)
[Node.csv](https://github.com/SeleniumHQ/docker-selenium/files/10071710/Node.csv)

**Comment by abhitrivedi2006** [comment] 2022-12-07 18:36
@diemol do you have any update on this ?

**Comment by Wolfe1** [comment] 2023-03-01 16:16
@abhitrivedi2006 This may be helpful: https://www.selenium.dev/blog/2022/scaling-grid-with-keda/

When I wrote this I was not using the helm chart and configuring KEDA myself but your error here looks like a classic issue of the keda scale-down terminating running pods at random. I would suggest making some of the changes listed here to allow your sessions to terminate gracefully when they are asked to scale down.

**Comment by diemol** [comment] 2023-07-13 12:58
Closing as Keda is now part of the chart and due to the lack of input from the OP.

**Closed as completed by diemol** 2023-07-13 12:58 UTC
Labels: R-awaiting-answer
