### ISSUE TITLE
Usage of disc space on Selenium 3

### ISSUE THREAD

**Issue by mr-raptor** [SeleniumHQ/docker-selenium#633] opened 2017-12-10 14:23 UTC
Hello!

I have a question about Selenium 3.
When I run a lot of tests (app. 500 testcases) with Selenium 2.53.1 (on Firefox), docker consume small disc space.
But after upgrade my autotests project to Selenium 3.8.1 when I run the same tests, the disc space on server ends. I have 10gb of free space and for Selenium 2.53.1 it was enough.
So I just curious, is it normal behavior for new Selenium version? Or I need to search for a memory leakage in my project? 
Thanks.

**Comment by diemol** [comment] 2017-12-12 16:13
Hi @mr-raptor, if you check inside the container, does it look like what is mentioned in #329?

**Comment by mr-raptor** [comment] 2017-12-13 11:01
It doesn't seems to be the same issue. I have no extra data in /home directory, 
But here is content of /tmp in selenium-hub container: http://prntscr.com/hmw0ot
And it grows very fast. In 5 minutes it reached 4gb.
I also checked another selenium versions and it looks like this issue is specific to 3.8.*

**Comment by diemol** [comment] 2017-12-13 11:10
@mr-raptor could you please give us a script that we can run and then reproduce the issue? Thanks!

**Comment by barancev** [comment] 2017-12-13 11:20
It must be related to https://github.com/SeleniumHQ/selenium/issues/5209
Just fixed, to be released in 3.9

**Comment by mr-raptor** [comment] 2017-12-13 11:31
That's nice. Thank you very much!

**Comment by diemol** [comment] 2017-12-13 12:06
Thanks @barancev!

**Comment by diemol** [comment] 2017-12-22 10:08
I'll close this one since it will be released in 3.9 and we release the images shortly afterwards.

**Closed by diemol** 2017-12-22 10:08 UTC
