### ISSUE TITLE
New selenium/standalone-firefox images have trouble loading Google maps

### ISSUE THREAD

**Issue by ryandingap** [SeleniumHQ/docker-selenium#948] opened 2019-07-16 19:05 UTC
Our Webdriver test loads the following Google maps URL:

https://www.google.com/maps/embed?pb=!1m10!1m8!1m3!1d1304.4392286268862!2d-77.35878071289632!3d38.958322144715694!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sus!4v1512613798596

The test failed yesterday because the map is not loaded. This is because the latest standalone-firefox image that was updated 2 days ago (7/14) does not work well with Google maps. When using 3.141.59-radium that was updated a month ago, the test passed.

**Comment by cgoldberg** [comment] 2019-07-16 19:32
@ryandingap 
"does not work well" is really vague...  Can you clarify?

**Comment by ryandingap** [comment] 2019-07-16 19:52
The Webdriver does not load the Google maps page (with the URL in the original issue description). By.className("google-maps-link") could not be found on the page.

**Comment by diemol** [comment] 2019-07-20 01:32
The difference between the image you refer as working and the one as non-working is the Firefox version, the most recent image has Firefox 68.

I will close this issue since the template has been completely ignored and the OP has not provided a way to reproduce the issue in a way that clearly reflects that it is an issue happening only when using the `docker-selenium` images. Please consider opening an issue in the Mozilla issue tracker if you can verify that the issue is related to Firefox itself.

**Closed by diemol** 2019-07-20 01:32 UTC
