### ISSUE TITLE
Selenium Hub 3.14.0 will not start VMware VIC

### ISSUE THREAD

**Issue by Reedler01** [SeleniumHQ/docker-selenium#811] opened 2018-10-15 16:08 UTC
## Meta -

Image(s):  
Selenium Hub 3.14.0 node-firefox 3.14.0 node-chrome 3.14.0

Docker Version:  
VMware VIC 1.4.3
OS: 
Photon

## Expected Behavior -
The grid hub container starts
## Actual Behavior -
The grid hub errors out with 
2018-10-15 14:26:45,435 WARN Included extra file "/etc/supervisor/conf.d/selenium-hub.conf" during parsing
2018-10-15 14:26:45,439 INFO supervisord started with pid 355
2018-10-15 14:26:46,440 INFO spawnerr: unknown error making dispatchers for 'selenium-hub': EACCES
2018-10-15 14:26:47,442 INFO gave up: selenium-hub entered FATAL state, too many start retries too quickly

**Comment by diemol** [comment] 2018-10-15 16:16
Hi @Reedler01,

What is the exact tag of the image you are using?

**Comment by Reedler01** [comment] 2018-10-15 16:50
3.14.0
Aaron Reed
Senior Systems and DevOps Engineer
areed74@gmail.com
540-354-6500

**Comment by Reedler01** [comment] 2018-10-15 16:50
3.14.0

**Comment by diemol** [comment] 2018-10-15 16:53
Is it 3.14.0-helium? Can you please paste the docker image id?

**Comment by diemol** [comment] 2018-10-15 23:32
Not really, what is the output of this command?
`docker images selenium/hub`

**Comment by Reedler01** [comment] 2018-10-16 13:16
selenium/hub        3.14.0 This is the output of that command. Here is one for an inspect. "RepoTags": [
            "selenium/hub:3.14.0"
Also this seem to be a file permission error. Here is the log trace from the VMware VCH. 
I am guessing something with the permissions changed somewhere which is causing the EACCES message. 

Checking the permissions of the entry point seems okay. Also running hub as root works okay, well I didn't test attaching nodes but did get past the eacces error.
root@b24552e55126:/etc# ls -l /opt/bin/entry_point.sh
-rwxrwxr-x 1 root root 776 Oct 13 22:47 /opt/bin/entry_point.sh
root@b24552e55126:/etc# /opt/bin/entry_point.sh
2018-10-15 23:32:40,433 CRIT Supervisor running as root (no user in config file)
2018-10-15 23:32:40,433 WARN Included extra file "/etc/supervisor/conf.d/selenium-hub.conf" during parsing
2018-10-15 23:32:40,435 INFO supervisord started with pid 386
2018-10-15 23:32:41,437 INFO spawned: 'selenium-hub' with pid 389
Starting Selenium Hub with configuration:
2018-10-15 23:32:41,453 INFO success: selenium-hub entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
{
  "host": "0.0.0.0",
  "port": 4444,
  "role": "hub",
  "maxSession": 250,
  "newSessionWaitTimeout": 180000,
  "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
  "throwOnCapabilityNotPresent": true,
  "jettyMaxThreads": -1,
  "cleanUpCycle": 180000,
  "browserTimeout": 300,
  "timeout": 320,
  "debug": false
}
23:32:42.706 INFO [GridLauncherV3.launch] - Selenium build info: version: '3.14.0', revision: 'aacccce0'
23:32:42.710 INFO [GridLauncherV3$2.launch] - Launching Selenium Grid hub on port 4444
2018-10-15 23:32:43.258:INFO::main: Logging initialized @1605ms to org.seleniumhq.jetty9.util.log.StdErrLog
23:32:43.598 INFO [Hub.start] - Selenium Grid hub is up and running
23:32:43.604 INFO [Hub.start] - Nodes should register to http://172.17.0.2:4444/grid/register/
23:32:43.611 INFO [Hub.start] - Clients should connect to http://172.17.0.2:4444/wd/hub

If I run the entry_point as the seluser I reproduce the issue. 
root@b24552e55126:/etc# sudo -u seluser /opt/bin/entry_point.sh
2018-10-15 23:42:37,910 WARN Included extra file "/etc/supervisor/conf.d/selenium-hub.conf" during parsing
2018-10-15 23:42:37,919 INFO supervisord started with pid 456
2018-10-15 23:42:38,920 INFO spawnerr: unknown error making dispatchers for 'selenium-hub': EACCES
2018-10-15 23:42:39,922 INFO gave up: selenium-hub entered FATAL state, too many start retries too quickly

The dockerfile builds the hub to run with seluser and has been this way for a while now. However I noticed from 3.14.0-francium and forward the entry_point.sh is no longer started with "CMD" in the dockerfile used to build the container. I will need to do more checking if this would change how the entry point is ran enough to cause these issues.

**Comment by diemol** [comment] 2018-10-16 13:18
The output of that command should be something similar to:

```
docker images selenium/hub                                                                                
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
selenium/hub        latest              5dbe41cbcbfd        2 days ago          321MB
```

Can you please post that? Also, what is the command being used to start the images?

**Comment by Reedler01** [comment] 2018-10-16 13:45
I was able to fix adding the root user in the compose file for the hub and chrome containers. FF container already had it in there. I noticed last night I was getting the same error on the chrome containers. So my question is, was this a new change by design or will we go back to using the seluser?

  hub:
    user: root
    image: selenium/hub:$SEL_VERSION

**Comment by diemol** [comment] 2018-10-22 20:59
@Reedler01, yes, I met them during SeleniumConf.

Going back to the topic, the images were built so they work in any sudo-less environment, but that also depends of course on the host environment configuration. It is hard for me to say why it is not working on that environment, but somehow it seems that your docker-compose file was changed before to use `root` for some reason.

In the end, if you are fine using the `root` user, you can set it up with it.

**Comment by hyunil-shin** [comment] 2018-11-01 01:04
I got the same problem.
I think host OS is related.

host OS Cent 6.8 + 3.14.0 : the same problem ( unknown error making dispatchers for 'selenium-node': EACCES)
host OS Cent 6.8 + 3.11.0: it works.
host OS Cent 7.1 + 3.14.0: it works.

**Comment by kkucera** [comment] 2019-02-11 15:55
I'm experiencing this same issue. 
It started with 3.14.0-francium and every version since then will not run for me. 
I can use the --user root option to get the hub and nodes running, but it still doesn't work.
Everything seems to come up but the nodes display the message: 
"Running Firefox as root in a regular user's session is not supported.  ($HOME is /home/seluser which is owned by seluser.)"
Attempting to run against the grid fails with an error: "WebDriverException: invalid argument: can't kill an exited process".

host OS Cent 7.2.1511
java version: 1.8.0_181

I'm starting the containers with the cli:

docker run -d -p 4444:4444 --name selenium-hub -e GRID_TIMEOUT=125000 -e GRID_UNREGISTER_IF_STILL_DOWN_AFTER=125000 -e TZ=US/Arizona selenium/hub:3.14.0

docker run -d -P -v /dev/shm:/dev/shm --name firefox-0 --link selenium-hub:hub -e TZ=US/Arizona selenium/node-firefox-debug:3.14.0

**Comment by diemol** [comment] 2020-03-26 16:33
Is this still happening with the latest releases?
Could someone please provide reproduction steps in case it is still happening?

**Comment by shankarkc** [comment] 2020-05-18 13:48
@diemol Here is the repro steps. Its still happening
```
docker exec -it <hub-docker-container-id-here> bash
 sudo su seluser
/usr/bin/supervisord --configuration /etc/supervisord.conf &
```

**Comment by diemol** [comment] 2020-05-18 16:11
I will close this issue because it is getting different operating systems mixed and the comments are not related to the original issue.

For the original one, the OP reported that the workaround of using `root` solves the issue for them. For any other issue, please open a new one with all the information filled out and a way to reproduce it.

**Closed by diemol** 2020-05-18 16:11 UTC
Labels: R-awaiting-answer
