### ISSUE TITLE
Time out error from selenium-router when using Selenium grid 4 fully distributed on top of k8s

### ISSUE THREAD

**Issue by itaymelamed** [SeleniumHQ/docker-selenium#1299] opened 2021-05-25 19:55 UTC
``## 🐛 Bug Report
When running a suite of 300 parallel tests on 300 chrome nodes on top of selenium 4 fully distributed grid deployed in k8s, all the tests fail due to an error #1222". The same amount of tests are passing when running with 150 parallel on 90 chrome nodes.

## To Reproduce
1. Set up a k8s cluster of 20 nodes with 32G ram each.
2. Deploy k8s-deployment-full-grid.yaml.
3. Scale chrome nodes to 300 (1G ram and 1000Mi CPU for each)
3. Run 300 parallel tests.

## Expected behavior
All tests should pass.

## Environment

OS: Kubernetes on top of aws linux.
Docker-Selenium image version: 4.0.0-beta-4-prerelease-20210517

Deployment yaml:
[https://raw.githubusercontent.com/FTBpro/mmservices/master/tests/ui_tests/selenium-grid.yaml?token=AHYFTAFZJ6QGIVYXPB2GC53AW2I24](url)

**Comment by diemol** [comment] 2021-05-25 20:34
Can you please provide the logs of the components? This issue is very abstract and has almost no information that can be used to understand what the issue might be. 

What happens if you use a smaller amount of Nodes? Does the issue still happen? How can the Distributor access the Nodes? 

Please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

**Comment by itaymelamed** [comment] 2021-05-26 18:51
@diemol
1. When running a smaller amount of parallel tests(100 tests) on 100 nodes, all tests pass.
2. When running 300 parallel tests on 100 nodes, the first tests are passing and then start to fail.
3. When running 300 parallel tests on 200 nodes, the first tests are passing and then start to fail.
4. We have tried to increase the resources request for the selenium-router component to 20G but it didn't help. Is there any best practice for resource requests for the components same as a request for 1Giga ram for each node?
5. "How can the Distributor access the Nodes?", Sorry but I'm not sure I understood What does it mean?
6. This is the deployment we are using: [https://github.com/SeleniumHQ/docker-selenium/blob/trunk/k8s-deployment-full-grid.yaml](https://github.com/SeleniumHQ/docker-selenium/blob/trunk/k8s-deployment-full-grid.yaml) and then scale chrome nodes to 300.
7. Logs:
**selenium-router**
```
21:04:18.972 WARN [SpanWrappedHttpHandler.execute] - Unable to execute request: java.util.concurrent.TimeoutException
Build info: version: '4.0.0-beta-3', revision: '5d108f9a67'
System info: host: 'selenium-router-deployment-7bc8ff6948-xzkz9', ip: '175.0.160.171', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.95-42.163.amzn2.x86_64', java.version: '1.8.0_282'
Driver info: driver.version: unknown
org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException
Build info: version: '4.0.0-beta-3', revision: '5d108f9a67'
System info: host: 'selenium-router-deployment-7bc8ff6948-xzkz9', ip: '175.0.160.171', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.95-42.163.amzn2.x86_64', java.version: '1.8.0_282'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:71)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:51)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:103)
	at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55)
	at org.openqa.selenium.grid.sessionqueue.remote.RemoteNewSessionQueuer.addToQueue(RemoteNewSessionQueuer.java:93)
	at org.openqa.selenium.grid.sessionqueue.NewSessionQueuer.lambda$new$0(NewSessionQueuer.java:71)
	at org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle(Route.java:192)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
	at org.openqa.selenium.grid.sessionqueue.NewSessionQueuer.execute(NewSessionQueuer.java:112)
	at org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:86)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
	at org.openqa.selenium.grid.router.Router.execute(Router.java:91)
	at org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
	at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)
	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1784)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
	at org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:206)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:65)
	... 34 more


21:04:18.972 WARN [SeleniumSpanExporter$1.lambda$export$0] - {"traceId": "859ba4c7e4253cd5c4004d5e414edd13","spanId": "c5f05c1e944225b8","spanKind": "INTERNAL","eventTime": 1622063058972051722,"eventName": "exception","attributes": {"exception.message": "Unable to execute request: java.util.concurrent.TimeoutException\nBuild info: version: '4.0.0-beta-3', revision: '5d108f9a67'\nSystem info: host: 'selenium-router-deployment-7bc8ff6948-xzkz9', ip: '175.0.160.171', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.95-42.163.amzn2.x86_64', java.version: '1.8.0_282'\nDriver info: driver.version: unknown","exception.stacktrace": "org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException\nBuild info: version: '4.0.0-beta-3', revision: '5d108f9a67'\nSystem info: host: 'selenium-router-deployment-7bc8ff6948-xzkz9', ip: '175.0.160.171', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.95-42.163.amzn2.x86_64', java.version: '1.8.0_282'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:71)\n\tat org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)\n\tat org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)\n\tat org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:51)\n\tat org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)\n\tat org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)\n\tat org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:103)\n\tat org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55)\n\tat org.openqa.selenium.grid.sessionqueue.remote.RemoteNewSessionQueuer.addToQueue(RemoteNewSessionQueuer.java:93)\n\tat org.openqa.selenium.grid.sessionqueue.NewSessionQueuer.lambda$new$0(NewSessionQueuer.java:71)\n\tat org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle(Route.java:192)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.grid.sessionqueue.NewSessionQueuer.execute(NewSessionQueuer.java:112)\n\tat org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:86)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.grid.router.Router.execute(Router.java:91)\n\tat org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: java.util.concurrent.TimeoutException\n\tat java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1784)\n\tat java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)\n\tat org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:206)\n\tat org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:65)\n\t... 34 more\n","exception.type": "org.openqa.selenium.TimeoutException","http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.sessionqueue.remote.RemoteNewSessionQueuer","http.host": "10.100.106.8:4444","http.method": "POST","http.request_content_length": "862","http.scheme": "HTTP","http.target": "\u002fsession","http.user_agent": "selenium\u002f3.141.0 (python linux)"}}
``

**Comment by diemol** [comment] 2021-05-27 13:24
>When running a smaller amount of parallel tests(100 tests) on 100 nodes, all tests pass.

Expected as all Nodes are available for the same amount of tests.

>When running 300 parallel tests on 100 nodes, the first tests are passing and then start to fail.

100 tests will get executed, 200 will be in the queue. If tests need a long time, tests in the queue will hit a timeout (which is what you see in the Router request). Default timeout is 300 seconds, it can be increased through this [option](https://github.com/SeleniumHQ/docker-selenium#grid-url-and-session-timeout).

>When running 300 parallel tests on 200 nodes, the first tests are passing and then start to fail.

Same case as the previous one.

>We have tried to increase the resources request for the selenium-router component to 20G but it didn't help. Is there any best practice for resource requests for the components same as a request for 1Giga ram for each node?

The Nodes get registered to the Distributor via the EventBus. Check if those two components are having enough resources by monitoring their CPU and RAM, also checking the logs could give you good hints. The Router's job is to forward information, so its resource usage should not be that high. We do not have a set of best practices yet as we have not tested the Grid with 300 nodes, so far we have only tried it with 60 tops.

>"How can the Distributor access the Nodes?", Sorry but I'm not sure I understood What does it mean?

When the Node registers to the Distributor through the EventBus, the Distributor pings the Node via http to double check it is there and complete the registration process. So you should check that all Nodes are registered (you can quickly see it on the Grid UI), and also inspect the logs of the Nodes, Distributor and EventBus for possible pointers on what is going wrong.



As a last comment, I see you are using an "old" set of Docker images, please check the most recent pre-release and use that one for your tests.

**Comment by itaymelamed** [comment] 2021-05-30 13:35
@diemol 
Thanks, seems like increasing the session timeout parameter and adding more resources to the distributor service (1000Gi of ram) has solved the issue.

> So you should check that all Nodes are registered (you can quickly see it on the Grid UI)

What is the UI route for selenium grid 4? same as /wd/hub/status?

**Comment by zzvara** [comment] 2021-05-30 16:02
This issue is strange since we only observed it in distributed mode. The same parallelism, resource dimensions, and application, only that we changed compact/distributed mode. In distributed mode, we saw timeouts after the first few sessions go through.

**Comment by diemol** [comment] 2021-05-30 17:49
Thanks for letting us know, @itaymelamed.

>What is the UI route for selenium grid 4? same as /wd/hub/status?

The path for the UI is root, as in `/`, no  ` /wd/hub/status` needed.

**Closed as completed by diemol** 2021-05-30 17:49 UTC
Labels: R-awaiting-answer
