### ISSUE TITLE
Arm support for all the selenium docker images

### ISSUE THREAD

**Issue by ubertidavide** [SeleniumHQ/docker-selenium#1179] opened 2021-01-18 19:03 UTC
## 🚀 Feature Proposal

Arm arch support for all selenium docker images.

## Motivation

In order to run the docker images on arm devices, like Raspberry Pi 4 that have the arm64/v8 arch is important to have in docker hub the multi arch container...

## Example
buildx docker tools enable the possibility to compile a container for more arch in one container build.

**Comment by diemol** [comment] 2021-01-19 08:55
Duplicate of #1076

I also have not had the time to look into this, any PRs are welcome.

**Closed as completed by diemol** 2021-01-19 08:55 UTC
Labels: needs-triaging
