### ISSUE TITLE
Dynamic Grid video timeout, add record options. http://gridhub:4444/session timed out after 60 seconds.'

### ISSUE THREAD

**Issue by namilkimfree** [SeleniumHQ/docker-selenium#1325] opened 2021-07-05 05:34 UTC
## 🐛 Bug Report

[1625465509.749][SEVERE]: bind() failed: Cannot assign requested address (99)

Add option record option (se:*)  and connect remote hub ( url:4444) 
then throw timeout.

but don't add record options , success.

## To Reproduce

1. start dynamic grid docker-compose: https://github.com/SeleniumHQ/docker-selenium#configuration-example
2. add record video option
3. connect docker dynamic hub
4. throw timeout exception

Detailed steps to reproduce the behavior:

1. start dynamic grid docker-compose: https://github.com/SeleniumHQ/docker-selenium#configuration-example
2. drvier add options
3. driverOptions.AddAdditionalOption("se:recordVideo", true); 
4. driverOptions.AddAdditionalOption("se:timeZone", "US/Pacific");
5. driverOptions.AddAdditionalOption("se:screenResolution", "1920x1080");
6. connect remote webdriver
7. driver = new RemoteWebDriver(new Uri("http://dockerUrl"), driverOptions);

Steps to reproduce the behavior (including the command to start the containers):

## Expected behavior
https://github.com/namilkimfree/SeleniumDynamicissueTest

don't throw timeout exception, 
 (OpenQA.Selenium.WebDriverException: 'The HTTP request to the remote WebDriver server for URL http://gridhub:4444/session timed out after 60 seconds.'

## Test script reproducing this issue (when applicable)

```

private IWebDriver GetChromeDriver()
{
      var driverOptions = new ChromeOptions();

      driverOptions.AddAdditionalOption("se:recordVideo", true);
      driverOptions.AddAdditionalOption("se:timeZone", "US/Pacific");
      driverOptions.AddAdditionalOption("se:screenResolution", "1920x1080");

      var driver = new RemoteWebDriver(new Uri("http://172.27.6.37:4444"), driverOptions)
      {
      };

      return driver;
  }

```
```

private void Test()
{

      var driver = GetChromeDriver();    -> throw timeout 
      driver.Navigate().GoToUrl("anything url");

  }

```

```
*[dynamic grid docker.yml]

version: "3"
services:
  node-docker:
    image: selenium/node-docker:4.0.0-rc-1-prerelease-20210618
    volumes:
      - ./assets:/opt/selenium/assets
      - ./NodeDocker/config.toml:/opt/bin/config.toml
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    image: selenium/hub:4.0.0-rc-1-prerelease-20210618
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
```

```

*[confing.toml]

[docker]

configs = [
    "selenium/standalone-chrome:4.0.0-rc-1-prerelease-20210618", "{\"browserName\": \"chrome\"}"
    ]
url = "http://host.docker.internal:2375"
video-image = "selenium/video:ffmpeg-4.3.1-20210426"

```

## Environment

OS: Windows 10 
Docker-Selenium image version:  https://github.com/SeleniumHQ/docker-selenium/blob/trunk/docker-compose-v3-dynamic-grid.yml 
Also provide the docker image id 
-->
Docker version:  Docker version 20.10.7, build f0df350
Docker-Compose version (if applicable): docker-compose version 1.29.2, build 5becea4c
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well): docker-compose -f .\docker-compose-v3-dynamic-grid.yml up -d
in powersehll

**Comment by namilkimfree** [comment] 2021-07-05 06:48
```
06:45:56.384 INFO [DockerSessionFactory.apply] - Waiting for server to start (container id: e1fd0f0828e80b597406ec568ffb101abeb92ae6f2e66a7d6792ba90466a7b83, url http://172.18.0.4:4444/wd/hub)


06:46:56.605 INFO [Container.stop] - Stopping container e1fd0f0828e80b597406ec568ffb101abeb92ae6f2e66a7d6792ba90466a7b83


06:47:01.264 WARN [DockerSessionFactory.apply] - Unable to connect to docker server (container id: e1fd0f0828e80b597406ec568ffb101abeb92ae6f2e66a7d6792ba90466a7b83)


06:47:01.265 WARN [SeleniumSpanExporter$1.lambda$export$0] - {"traceId": "343f64261dd256a3d8742fa4bf9468ba","eventTime": 1625467616605897400,"eventName": "exception","attributes": {"container.id": "e1fd0f0828e80b597406ec568ffb101abeb92ae6f2e66a7d6792ba90466a7b83","container.ip": "172.18.0.4","container.port": 4444,"docker.browser.image": "Image{summary=org.openqa.selenium.docker.internal.ImageSummary@245a26e1}","docker.server.url": "http:\u002f\u002f172.18.0.4:4444\u002fwd\u002fhub","exception.message": "Unable to connect to docker server. Stopping container: Expected condition failed: waiting for org.openqa.selenium.grid.docker.DockerSessionFactory$$Lambda$490\u002f0x00000008402f6040@1adf8c5e (tried for 60 second(s) with 500 milliseconds interval)\nBuild info: version: '4.0.0-beta-4', revision: '29f46d02dd'\nSystem info: host: '1776cf1c8ee1', ip: '172.18.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.25-linuxkit', java.version: '11.0.11'\nDriver info: driver.version: unknown","exception.stacktrace": "org.openqa.selenium.TimeoutException: Expected condition failed: waiting for org.openqa.selenium.grid.docker.DockerSessionFactory$$Lambda$490\u002f0x00000008402f6040@1adf8c5e (tried for 60 second(s) with 500 milliseconds interval)\nBuild info: version: '4.0.0-beta-4', revision: '29f46d02dd'\nSystem info: host: '1776cf1c8ee1', ip: '172.18.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.25-linuxkit', java.version: '11.0.11'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.support.ui.FluentWait.timeoutException(FluentWait.java:263)\n\tat org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:231)\n\tat org.openqa.selenium.grid.docker.DockerSessionFactory.waitForServerToStart(DockerSessionFactory.java:391)\n\tat org.openqa.selenium.grid.docker.DockerSessionFactory.apply(DockerSessionFactory.java:165)\n\tat org.openqa.selenium.grid.docker.DockerSessionFactory.apply(DockerSessionFactory.java:85)\n\tat org.openqa.selenium.grid.node.local.SessionSlot.apply(SessionSlot.java:143)\n\tat org.openqa.selenium.grid.node.local.LocalNode.newSession(LocalNode.java:325)\n\tat org.openqa.selenium.grid.node.NewNodeSession.execute(NewNodeSession.java:52)\n\tat org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle(Route.java:192)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.grid.security.RequiresSecretFilter.lambda$apply$0(RequiresSecretFilter.java:64)\n\tat org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:86)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.grid.node.Node.execute(Node.java:240)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)\n\tat java.base\u002fjava.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base\u002fjava.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base\u002fjava.lang.Thread.run(Thread.java:829)\nCaused by: java.io.UncheckedIOException: java.net.ConnectException: Connection refused: \u002f172.18.0.4:4444\n\tat org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:79)\n\tat org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)\n\tat org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)\n\tat org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:51)\n\tat org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)\n\tat org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)\n\tat org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:105)\n\tat org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55)\n\tat org.openqa.selenium.grid.docker.DockerSessionFactory.lambda$waitForServerToStart$3(DockerSessionFactory.java:392)\n\tat org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)\n\t... 27 more\nCaused by: java.net.ConnectException: Connection refused: \u002f172.18.0.4:4444\n\tat org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:179)\n\tat org.asynchttpclient.netty.channel.NettyChannelConnector$1.onFailure(NettyChannelConnector.java:108)\n\tat org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:28)\n\tat org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)\n\tat io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)\n\tat io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)\n\tat io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)\n\tat io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)\n\tat io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)\n\tat io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)\n\tat io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)\n\tat io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321)\n\tat io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\t... 1 more\nCaused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: \u002f172.18.0.4:4444\nCaused by: java.net.ConnectException: Connection refused\n\tat java.base\u002fsun.nio.ch.SocketChannelImpl.checkConnect(Native Method)\n\tat java.base\u002fsun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)\n\tat io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)\n\tat io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat java.base\u002fjava.lang.Thread.run(Thread.java:829)\n","exception.type": "org.openqa.selenium.TimeoutException","logger": "org.openqa.selenium.grid.docker.DockerSessionFactory"}}
```

**Comment by namilkimfree** [comment] 2021-07-14 08:03
Hi, @diemol  

Running multiple tests, One or two tests occur.

 The HTTP request to the remote WebDriver server for URL http://172.27.6.37:4444/session timed out after 60 seconds. -> The operation was canceled. -> Unable to read data from the transport connection


how to change timeout ??

Can I use SE_NODE_SESSION_TIMEOUT? in docker-compose-v3-dynamic-grid.yml

      - SE_NODE_SESSION_TIMEOUT = 300 

thank you

**Comment by diemol** [comment] 2021-08-05 20:36
@namilkimfree I was not able to reproduce this issue (I used Firefox because there is a problem with Chrome which will be fixed in the next prerelease).

I took you example and updated the images, here you can see the whole [solution](https://github.com/diemol/selenium-issues/tree/master/docker-selenium/issue-1325/SeleniumDynamicissueTest/SeleniumDynamicissueTest).

Make sure you are exposing the Docker endpoint via tcp in Windows:
![image](https://user-images.githubusercontent.com/5992658/128417400-fd276c44-7aa3-4350-977f-1f0e72a12764.png)

The video recorded in the test can be seen [here](https://github.com/diemol/selenium-issues/tree/master/docker-selenium/issue-1325/SeleniumDynamicissueTest/SeleniumDynamicissueTest/assets/b5645a73-8b87-4545-a787-c0732c89cb32).

Please check the updated code and let us know if it also works. It does seem to be a configuration issue. If you are bumping still into an issue, please attach the complete logs of the docker-compose execution.

**Comment by diemol** [comment] 2021-08-18 19:40
Closing as we did not get any more information.

**Closed as completed by diemol** 2021-08-18 19:40 UTC
Labels: R-awaiting-answer
