### ISSUE TITLE
RemoteWebDriver fails to respect flags when using selenium/standalone-chrome

### ISSUE THREAD

**Issue by modevxen** [SeleniumHQ/docker-selenium#1016] opened 2020-01-10 23:09 UTC
## 🐛 Bug Report

Using a RemoteWebDriver class with selenium/standalone-chrome will cause certain chrome 
options to not be respected.

The flags in question will work when using a regular ChromeDriver class, but upon using selenium's standalone-chrome docker image, will either silently fail or be completely ignored. These include:
--use-fake-ui-for-media-stream
--use-fake-device-for-media-stream
--use-file-for-fake-audio-capture

**May be a regression** if the code claiming to work on the following webpage is accurate: 
https://www.browserstack.com/automate/handle-popups-alerts-prompts-in-automated-tests

## To Reproduce

Detailed steps to reproduce the behaviour:

This was reproduced by running the test script twice, once with a local ChromeDriver, and the second with a RemoteWebDriver. The test script navigates to a website where an audiograph will show if a sound it being played (wavy lines) or if there is no sound (straight line) or microphone acmes isn't granted. A screenshot is taken some time after and analyzed post test.

During the first iteration, isRemote is set to false. The script is run, and completes. The screenshot shows the audio graph with spiky lines, showing that microphone access was granted and chrome's getUserMedia can use the playing audio file. 

During the second iteration, isRemote is set to true. A selenium standalone chrome docker image is run using "docker run -d -p 4444:4444 -v /desv/shm:/dev/shm selenium/standalone-chrome". After the test completes, the screenshot shows that microphone access was not even granted.

## Expected behavior

What is expected is that both iterations show audio graph activity, because the same flags are used for both and so both sets of flags should be honoured. (i.e. microphone access granted for both, both use the same audio file to simulate audio)

## Test script or set of commands reproducing this issue

Test Script attached in text file, ran using testng on IntelliJ.
[MicTest.txt](https://github.com/SeleniumHQ/selenium/files/4048517/MicTest.txt)

## Environment

OS: Ubuntu 5.0.0-37-generic 
Browser: Chrome 
Browser version: 79 
Browser Driver version: RemoteWebDriver (selenium/standalone-chrome:latest) 
Language Bindings version: Java 11  
Selenium Grid version (if applicable): N/A

**Comment by ketanbijwe** [comment] 2020-06-12 16:33
is there any update on this issue, I am facing the same

**Comment by diemol** [comment] 2020-06-14 21:23
Putting the attached script as part of this comment:

```java
package com.company;

import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.io.FileHandler;
import org.testng.annotations.*;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.remote.DesiredCapabilities;

import java.io.File;
import java.net.URL;
import java.util.logging.Level;


public class MainTest {
    private ChromeOptions options;
    private WebDriver driver;
    private WebDriverWait wait;
    private URL remoteURL;
    private boolean isRemote = true;


    public void customSleep(double time) {
        try {
            Thread.sleep((int) (time * 1000));
        } catch (InterruptedException e) {
            e.printStackTrace();
        };
    }

    public void getScreenshot() {
        File screenshot = ((TakesScreenshot)driver).getScreenshotAs(OutputType.FILE);

        try
        {
            FileHandler.copy(screenshot, new File(System.getProperty("user.dir") + "/screenshot.png"));
            System.out.println("Saved screenshot");

        }
        catch (Exception e)
        {
            System.out.println("Did not save screenshot: " + e.getMessage());

        }
    }


    @BeforeTest
    public void beforeTest() {
        java.util.logging.Logger.getLogger("org.openqa.selenium").setLevel(Level.ALL);

        File fakeAudioFile = new File(System.getProperty("user.dir") + "/src/rickcut.wav");
        System.out.println("The audio file was found to " + (fakeAudioFile.exists() ? "exist." : "not exist."));

        options = new ChromeOptions();
        options
                .addArguments("--allow-file-access-from-files")
                .addArguments("--enable-local-file-accesses")
                .addArguments("--enable-media-stream")
                .addArguments("--use-fake-ui-for-media-stream")
                .addArguments("--use-fake-device-for-media-stream")
                .addArguments("--use-file-for-fake-audio-capture=" + fakeAudioFile.getAbsolutePath());

        if (isRemote)
        {
            try
            {
                remoteURL = new URL("http://localhost:4444/wd/hub");
            }
            catch (Exception e)
            {
                System.out.println("Could not instatiate docker connection. Exiting...");
                System.exit(0);
            }

            options
                    .addArguments("--disable-dev-shm-usage");

            DesiredCapabilities capabilties = new DesiredCapabilities();
            capabilties.setCapability(ChromeOptions.CAPABILITY, options);

            driver = new RemoteWebDriver(remoteURL, capabilties);
        }
        else
        {
            System.setProperty("webdriver.chrome.driver", System.getProperty("user.dir") + "/src/chromedriver79");
            driver = new ChromeDriver(options);
        }

        wait = new WebDriverWait(driver, 10);
        driver.manage().window().maximize();
    }

    @Test
    public void testMic() {
        driver.get("https://www.onlinemictest.com/");
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("audio-start")));
        driver.findElement(By.id("audio-start")).click();
        customSleep(1);
        getScreenshot();
        customSleep(3);
    }

    @AfterTest
    public void afterTest() {
        driver.quit();
    }

}
```

**Comment by diemol** [comment] 2020-06-14 21:35
Apologies for the late reply.

First, this part of the code:
```java
File fakeAudioFile = new File(System.getProperty("user.dir") + "/src/rickcut.wav");
        System.out.println("The audio file was found to " + (fakeAudioFile.exists() ? "exist." : "not exist."));
```
has the `fakeAudioFile` as a local file, which is why it is used when the script runs locally. When you use the docker container, this file is not present in the container, therefore Chrome won't be able to use a file that cannot be found. You need to share/copy/make available the file to the container. Please check the Docker documentation for that.

Second, there was no good support for audio/video in the docker images. This PR added better support for audio and video to the images, so probably after the file is available inside the container, you should be able to have it working.

I'll close this issue since it is not a bug/problem in the docker images.

**Closed by diemol** 2020-06-14 21:35 UTC
Labels: needs-triaging
