### ISSUE TITLE
Test is not able to open Chrome browser inside its container

### ISSUE THREAD

**Issue by diegoquirino** [SeleniumHQ/docker-selenium#1276] opened 2021-05-06 13:22 UTC
## 🐛 Bug Report

Chrome browser does not open to execute tests inside chrome container. If using firefox, test works perfectly.

## To Reproduce

Steps to reproduce the behavior (including the command to start the containers):

1. Download [Robot Edge project, branch 20210501_chrome-keyerror-status](https://gitlab.com/diegoquirino/robot-edge/-/tree/20210501_chrome-keyerror-status) and install its python dependencies `pip install robotframework robotframework-seleniumlibrary docker`.
2. Execute command `python main.py` into its base path.

If you inform into `locators.py` project file variable >> BROWSER='firefox' << instead of 'chrome', the test runs as expected (without failure).

## Expected behavior

Chrome browser should open and google home page showed.

## Test script reproducing this issue (when applicable)

Here is the code to reproduce bug [Robot Edge project, branch 20210501_chrome-keyerror-status](https://gitlab.com/diegoquirino/robot-edge/-/tree/20210501_chrome-keyerror-status).

## Environment

OS: Windows 10
Docker-Selenium image version: 4.0.0-beta-3-20210426
Docker version: 20.10.5
Docker-Compose version (if applicable): (none)
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well): 

1. `docker network create my_selenium_network`
2. `docker run -d --privileged --name selenium --network my_selenium_network -p 4444:4444 -p 6900:5900 -v /dev/shm:/dev/shm selenium/standalone-chrome:4.0.0-beta-3-20210426`

**Comment by diemol** [comment] 2021-05-07 12:15
Can you please provide the logs from the docker containers? What operating system are you using?

**Comment by diegoquirino** [comment] 2021-05-07 15:39
Hi @diemol 

I'm using Windows 10, and here cames the log:

```
2021-05-07 15:36:36,127 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
2021-05-07 15:36:36,130 INFO supervisord started with pid 9
2021-05-07 15:36:37,132 INFO spawned: 'xvfb' with pid 11
2021-05-07 15:36:37,133 INFO spawned: 'vnc' with pid 12
2021-05-07 15:36:37,135 INFO spawned: 'novnc' with pid 13
2021-05-07 15:36:37,136 INFO spawned: 'selenium-standalone' with pid 14
2021-05-07 15:36:37,152 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2021-05-07 15:36:37,152 INFO success: vnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2021-05-07 15:36:37,152 INFO success: novnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2021-05-07 15:36:37,152 INFO success: selenium-standalone entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
15:36:37.886 INFO [LogManager$RootLogger.log] - Using the system default encoding
15:36:37.890 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
15:36:38.412 INFO [NodeOptions.getSessionFactories] - Detected 12 available processors
15:36:38.438 INFO [NodeOptions.discoverDrivers] - Discovered 1 driver(s)
15:36:38.464 INFO [NodeOptions.report] - Adding Chrome for {"browserName": "chrome","platformName": "LINUX"} 1 times
15:36:38.488 INFO [Node.<init>] - Binding additional locator mechanisms: id, name
15:36:38.500 INFO [LocalDistributor.add] - Added node ead4deeb-7d37-434f-be86-4bf9fddd69e1 at http://172.18.0.2:4444.
15:36:38.504 INFO [GridModel.setAvailability] - Switching node ead4deeb-7d37-434f-be86-4bf9fddd69e1 (uri: http://172.18.0.2:4444) from DOWN to UP
15:36:38.675 INFO [Standalone.execute] - Started Selenium Standalone 4.0.0-beta-3 (revision 5d108f9a67): http://172.18.0.2:4444
15:36:43.116 INFO [Distributor.newSession] - Session request received by the distributor: 
 [Capabilities {browserName: chrome, version: }, Capabilities {browserName: chrome}]
Starting ChromeDriver 90.0.4430.24 (4c6d850f087da467d926e8eddb76550aed655991-refs/branch-heads/4430@{#429}) on port 7039
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[1620401803.187][SEVERE]: bind() failed: Cannot assign requested address (99)
ChromeDriver was started successfully.
15:36:44.045 WARN [SeleniumSpanExporter$1.lambda$export$0] - {"traceId": "72648c27a7eaea803c1172ac36d89c6b","spanId": "5da29c3e0ae9a21c","spanKind": "INTERNAL","eventTime": 1620401804028111500,"eventName": "exception","attributes": {"driver.url": "http:\u002f\u002flocalhost:7039","exception.message": "Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: crashed.\n (unknown error: DevToolsActivePort file doesn't exist)\n (The process started from chrome location \u002fusr\u002fbin\u002fgoogle-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nBuild info: version: '4.0.0-beta-3', revision: '5d108f9a67'\nSystem info: host: '28813976f850', ip: '172.18.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.72-microsoft-standard-WSL2', java.version: '1.8.0_282'\nDriver info: driver.version: unknown","exception.stacktrace": "org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: crashed.\n (unknown error: DevToolsActivePort file doesn't exist)\n (The process started from chrome location \u002fusr\u002fbin\u002fgoogle-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nBuild info: version: '4.0.0-beta-3', revision: '5d108f9a67'\nSystem info: host: '28813976f850', ip: '172.18.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.72-microsoft-standard-WSL2', java.version: '1.8.0_282'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:84)\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:62)\n\tat org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:128)\n\tat org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:63)\n\tat org.openqa.selenium.grid.node.local.SessionSlot.apply(SessionSlot.java:143)\n\tat org.openqa.selenium.grid.node.local.LocalNode.newSession(LocalNode.java:325)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor.reserve(LocalDistributor.java:356)\n\tat org.openqa.selenium.grid.distributor.Distributor.newSession(Distributor.java:219)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest(LocalDistributor.java:426)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.run(LocalDistributor.java:399)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n","exception.type": "org.openqa.selenium.SessionNotCreatedException","logger": "org.openqa.selenium.grid.node.config.DriverServiceSessionFactory","session.capabilities": "{\"browserName\": \"chrome\",\"version\": \"\"}\n"}}


15:36:44.056 WARN [SeleniumSpanExporter$1.lambda$export$0] - {"traceId": "2b80cd4ac8e02290e1a5480e63d0fd8d","spanId": "43ce5d0e2637cd13","spanKind": "INTERNAL","eventTime": 1620401804054032200,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueuer","http.host": "172.26.96.1:4444","http.method": "POST","http.request_content_length": "187","http.scheme": "HTTP","http.status_code": 500,"http.target": "\u002fsession","http.user_agent": "selenium\u002f3.141.0 (python windows)"}}
```

**Comment by diemol** [comment] 2021-05-09 19:02
Seems there is an issue with mounting `dev/shm` on Windows due to a Docker release. This is a duplicate of #1267, check the last comment for the solution.

**Closed as completed by diemol** 2021-05-09 19:02 UTC
Labels: R-awaiting-answer

**Comment by diegoquirino** [comment] 2021-05-12 00:01
Thanks @diemol for your time. Unfortunately, upgrading to 2gb didn't solve the problem (#1267). But, deleting this volume was the workarround applied that effectively did work in my project. My best regards.
