### ISSUE TITLE
Selenium Chrome Nodes Often Failing to Connect to Hub When Started

### ISSUE THREAD

**Issue by IanDT** [SeleniumHQ/docker-selenium#1270] opened 2021-04-22 14:12 UTC
## 🐛 Bug Report

Selenium is being run using Docker containers.  It is running on AWS EC2 instances with the Hub on one instance and each node, of which there are up to 30, running on a separate EC2 instance.

Often, when chrome nodes are started they fail to connect to the hub.  When they do connect successfully, they work and can be used to run tests.  The only difference in the node's Docker log between a node that connects successfully and one that does not is that the last line is missing - 

`11:45:41.964 INFO [NodeServer.lambda$createHandlers$1] - Node has been added`

In the hub's log, there is a connection timeout error message - 

```
11:46:12.526 WARN [UnboundZmqEventBus.lambda$notifyListeners$10] - Caught exception from listener: org.openqa.selenium.events.EventListener@276a5ae6
java.io.UncheckedIOException: java.net.ConnectException: connection timed out: selenium-chrome-node13.test.com.sss.int/172.25.154.136:5555
```
Full docker logs are attached for the hub, for a node that successfully connects and for one that fails to connect.  The hub log is from when it was started.  18 nodes were started; 12 connected successfully and 6 did not.

[Hub Docker Log.txt](https://github.com/SeleniumHQ/selenium/files/6358400/Hub.Docker.Log.txt)
[Node Successful Connection Docker Log.txt](https://github.com/SeleniumHQ/selenium/files/6358406/Node.Successful.Connection.Docker.Log.txt)
[Node Failed Connection Docker Log.txt](https://github.com/SeleniumHQ/selenium/files/6358408/Node.Failed.Connection.Docker.Log.txt)

I've also attached the results of curling the nodes from the hub's Docker container, both for one with a successful connection and one with a failed connection.  They are the same.

`curl http://selenium-chrome-node13.test.com.sss.int:5555/status`

[Node Successful Connection Curl.txt](https://github.com/SeleniumHQ/selenium/files/6358465/Node.Successful.Connection.Curl.txt)
[Node Failed Connection Curl.txt](https://github.com/SeleniumHQ/selenium/files/6358467/Node.Failed.Connection.Curl.txt)

For the frequency with which the problem occurs, yesterday I tried to start 30 nodes several times and got 2, 9, 5, 4 and 5 failures respectively.  Today, I've tried to start 18 nodes twice and got 3 failures the first time and 6 failures the second time.

## To Reproduce

- Start the hub by running the Docker command:

`docker run -d -p 4442-4444:4442-4444 selenium/hub:4.0.0-beta-3-prerelease-20210422`

- Wait until the hub is running (so going to http://selenium4.test.com.sss.int:4444/ui/index.html#/ works)

- Start a node by running the Docker command:

`docker run -d -p 5555:5555 -p 5900:5900 -e SE_EVENT_BUS_HOST=selenium-hub.test.com.sss.int -e SE_EVENT_BUS_PUBLISH_PORT=4442 -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 -e SE_NODE_HOST=selenium-chrome-node13.test.com.sss.int -v /dev/shm:/dev/shm selenium/node-chrome:90.0-20210422`

## Expected behavior

When a node is started it always appears on the Hub's Overview page (http://selenium4.test.com.sss.int:4444/ui/index.html#/) as an available node and does not fail to connect with an error message.

## Test script or set of commands reproducing this issue

See "To Reproduce" section.  The only steps required are to have a running Hub and then to start up a new node to connect to it.

## Environment

OS: Docker 19.03.13-ce running on Amazon Linux release 2
Browser: Chrome
Browser version: selenium/node-chrome:90.0-20210422
Browser Driver version: N/A
Language Bindings version: N/A 
Selenium Grid version (if applicable): selenium/hub:4.0.0-beta-3-prerelease-20210422

**Comment by AutomatedTester** [comment] 2021-04-27 13:12
Transfered from the main selenium repo as it looks docker related

**Comment by avinashs15** [comment] 2021-04-29 13:35
Even I've been getting this error specifically with  chrome node but the Firefox node works just fine.

**Comment by diemol** [comment] 2021-05-10 17:19
@IanDT, are all the nodes running on the same EC2 instance or each node is running on its own E2C instance?

**Comment by IanDT** [comment] 2021-05-10 20:05
@diemol The Hub is on one EC2 instance and each node is running on its own EC2 instance.

**Comment by diemol** [comment] 2021-05-13 19:20
@IanDT, I was not able to reproduce this. I used the tags you mentioned and also this one https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.0.0-beta-3-20210426, but I did not get any `WARN` messages.

I suspect there might be an issue with the host names you are using, could it be that the DNS is not resolving things properly. In my scripts I only used IPs. Please double check your setup.

Just for the sake of sharing the details of how I tried to reproduce it, please check the info below.

I used Terraform to create the EC2 infrastructure for a Hub and 60 Nodes. I was able to registed them succesfully. Please check the video:


https://user-images.githubusercontent.com/5992658/118175365-50164a00-b430-11eb-930b-56501f7551e1.mp4

Here are the terraform files I used:

`main.tf`
```
terraform {
  backend "remote" {
    organization = "diemol"
    workspaces {
      name = "Selenium-Grid"
    }
    
  }
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.27"
    }
  }

  required_version = ">= 0.14.9"
}

provider "aws" {
  profile = "default"
  region  = "eu-central-1"
}

resource "aws_security_group" "grid_security_group" {
  name        = "grid_security_group"
  description = "Open ports for Grid & inbound traffic"

  ingress {
    description      = "Hub ports"
    from_port        = 4442
    to_port          = 4444
    protocol         = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
    ipv6_cidr_blocks = ["::/0"]
  }

  ingress {
    description      = "Node ports"
    from_port        = 5555
    to_port          = 5555
    protocol         = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
    ipv6_cidr_blocks = ["::/0"]
  }

  ingress {
    description      = "SSH"
    from_port        = 22
    to_port          = 22
    protocol         = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
    ipv6_cidr_blocks = ["::/0"]
  }

  egress {
    from_port        = 0
    to_port          = 0
    protocol         = "-1"
    cidr_blocks      = ["0.0.0.0/0"]
    ipv6_cidr_blocks = ["::/0"]
  }

  tags = {
    Name = "grid_security_group"
  }
}

data "template_file" "user_data_node" {
  template = "${file("${path.module}/node.sh")}"
  vars = {
    hub_ip_address = "${aws_instance.grid_hub.public_ip}"
  }
}

resource "aws_instance" "grid_hub" {
  ami           = "ami-05f7491af5eef733a"
  instance_type = "t3a.xlarge"
  vpc_security_group_ids = [aws_security_group.grid_security_group.id]
  user_data_base64 = filebase64("${path.module}/hub.sh")
  tags = {
    Name = "Grid Hub"
  }
}

resource "aws_launch_template" "grid_node_template" {
  name_prefix   = "grid"
  image_id      = "ami-05f7491af5eef733a"
  instance_type = "t2.micro"
  vpc_security_group_ids = [aws_security_group.grid_security_group.id]  
  user_data = "${base64encode(data.template_file.user_data_node.rendered)}"  
}

resource "aws_autoscaling_group" "grid_node_scale_group" {
  availability_zones = ["eu-central-1a"]
  desired_capacity   = 60
  max_size           = 70
  min_size           = 1

  launch_template {
    id      = aws_launch_template.grid_node_template.id
    version = aws_launch_template.grid_node_template.latest_version
  }

  depends_on = [aws_instance.grid_hub]
}
```

`node.sh`
```bash
#!/bin/bash -xe

curl -fsSL https://get.docker.com -o get-docker.sh

sudo sh get-docker.sh

export node_ip_address=$(curl http://169.254.169.254/latest/meta-data/public-ipv4)

sudo docker run -p 5555:5555 \
    -e SE_EVENT_BUS_HOST=${hub_ip_address} \
    -e SE_EVENT_BUS_PUBLISH_PORT=4442 \
    -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 \
    -e SE_NODE_HOST=$${node_ip_address} \
    -v /dev/shm:/dev/shm \
    selenium/node-chrome:4.0.0-beta-3-20210426
```

`hub.sh`
```bash
#!/bin/bash -xe

curl -fsSL https://get.docker.com -o get-docker.sh

sudo sh get-docker.sh

sudo docker run -p 4442-4444:4442-4444 selenium/hub:4.0.0-beta-3-20210426
```

**Comment by diemol** [comment] 2021-05-28 08:32
@IanDT, I will close this for now as we did not see any issues, but if you have more information that helps point an issue in Grid, please comment and we will be happy to reopen this.

**Closed as completed by diemol** 2021-05-28 08:32 UTC
Labels: R-awaiting-answer

**Comment by IanDT** [comment] 2021-07-20 08:03
See issue https://github.com/SeleniumHQ/docker-selenium/issues/1337 for what may well be the same problem when running Selenium using EKS.

I continue to experience the problem using the latest Docker images (4.0.0-rc-1-prerelease-20210713 and 91.0-20210713).

I have tried the workaround suggested in Issue 1337 and found that it works for me as well.  I have further found that if all the nodes are started first, left to run for a couple of minutes, and then the hub is started, all nodes successfully connect to the hub.

This is an improvement on what I had, but not a solution, because I still can't reliably scale up the number of nodes after starting the hub.
