### ISSUE TITLE
Chrome hangs executing new session

### ISSUE THREAD

**Issue by rferreira** [SeleniumHQ/docker-selenium#89] opened 2015-08-19 09:39 UTC
```
02:27:55.226 INFO - Executing: [get alert text])
02:27:55.233 INFO - Done: [get alert text]
02:27:55.237 INFO - Executing: [get alert text])
02:27:55.241 INFO - Done: [get alert text]
02:27:55.244 INFO - Executing: [accept alert])
02:27:55.249 INFO - Done: [accept alert]
02:27:55.252 INFO - Executing: [close window])
02:27:55.386 INFO - Done: [close window]
02:27:55.390 INFO - Executing: [delete session: b2dbb4e9-8eb7-42b5-ac53-f8407eac1434])
02:27:55.909 INFO - Done: [delete session: b2dbb4e9-8eb7-42b5-ac53-f8407eac1434]
02:27:56.919 INFO - Executing: [new session: Capabilities [{platform=ANY, browserName=chrome, chromeOptions={args=[--no-sandbox, --disable-impl-side-painting, --disable-setuid-sandbox, --disable-breakpad, --disable-client-side-phishing-detection, --disable-cast, --disable-cast-streaming-hw-encoding, --disable-cloud-import, --disable-popup-blocking, --ignore-certificate-errors, --disable-background-networking, --allow-http-screen-capture], extensions=[]}, version=}]])
02:27:56.921 INFO - Creating a new session for Capabilities [{platform=ANY, browserName=chrome, chromeOptions={args=[--no-sandbox, --disable-impl-side-painting, --disable-setuid-sandbox, --disable-breakpad, --disable-client-side-phishing-detection, --disable-cast, --disable-cast-streaming-hw-encoding, --disable-cloud-import, --disable-popup-blocking, --ignore-certificate-errors, --disable-background-networking, --allow-http-screen-capture], extensions=[]}, version=}]
Starting ChromeDriver 2.16.333243 (0bfa1d3575fc1044244f21ddb82bf870944ef961) on port 25028
Only local connections are allowed.
02:30:40.060 INFO - Executing: org.openqa.selenium.remote.server.handler.GetAllSessions@7daa2420)
02:30:40.060 INFO - Done: org.openqa.selenium.remote.server.handler.GetAllSessions@7daa2420
02:30:40.521 INFO - Executing: org.openqa.selenium.remote.server.handler.GetAllSessions@1ca2d8f6)
02:30:40.521 INFO - Done: org.openqa.selenium.remote.server.handler.GetAllSessions@1ca2d8f6

```

OS Ubuntu linux, docker: 

```
# docker --version
Docker version 1.5.0, build a8a31ef
root@synthetics-test-02:/etc# docker info
Containers: 10
Images: 262
Storage Driver: btrfs
Execution Driver: native-0.2
Kernel Version: 3.13.0-61-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 6
Total Memory: 7.798 GiB
Name: kkjkj
ID: 3NRD:CIDI:R7AQ:XIV4:24DX:J26Y:NCYY:DB3D:WCIJ:DI7H:O2MH:ZJJO
WARNING: No swap limit support
```

docker-selenium version 2.47.1  

This is happening very consistently during CI tests that start/stop many chrome instances.

**Comment by rubytester** [comment] 2015-08-28 21:07
This could be the issue with Chrome crashing per #79 . Start chrome with `-v /dev/shm:/dev/shm` as pointed to workaround. 

Are you using the standalone image?

**Comment by rubytester** [comment] 2015-08-28 21:12
see #87

**Comment by rferreira** [comment] 2015-08-30 02:27
hey folks I'll give the work around a shot here and report back, cheers!

**Comment by kingkevin** [comment] 2015-09-01 19:27
This work around solved our issue.

**Comment by pwaller** [comment] 2015-09-02 17:58
I'm also having this problem as @kingkevin. Also using `-v /dev/shm:/dev/shm`. No defunct processes. Just gets stuck.

**Comment by rferreira** [comment] 2015-09-07 01:37
yeah using  ```-v /dev/shm:/dev/shm``` did not work for me as well.

**Comment by hmcgowan** [comment] 2015-09-28 14:35
We were seeing this too. The -v /dev/shm:/dev/shm made things better but we still got hangs starting a new browser after a slave was up for some time. Testing browser.close() vs. browser.quit() locally I noticed that browser.close() closed out the chrome browser fine but left a zombie process of chromeDriver while browser.quit() cleaned everything up. After making sure we were stopping everything with a browser.quit() the issue went away.

**Comment by hmcgowan** [comment] 2015-09-29 14:32
Not out of the woods yet. Saw another hang starting chrome (though much less prevalent). Will let y'all know if I find anything else

**Comment by rubytester** [comment] 2015-09-29 15:55
With Chrome 44 and Chrome 45 (with chromedriver 2.18) I see lots of timeouts when running on CentOS 7.1 with Docker 1.7.1 

On Ubuntu hosts with docker 1.8.2 the same chrome images run without any timeouts for me. 

I use /dev/shm mount for both test scenarios.

**Comment by hmcgowan** [comment] 2015-09-29 17:13
Interesting. I'm using Amazon Linux AMI release 2014.03 with the /dev/shm mount and Docker version 1.8.2, build 0a8c2e3

**Comment by uhef** [comment] 2015-12-07 21:54
This still seems to be an issue with the latest docker image.

I'm getting following on `selenium/standalone-chrome-debug:latest` with `-v /dev/shm:/dev/shm` work around. Notice that in the beginning we request generation of two sessions but we receive a *Done* message on only one of them. At the end only the one which got created gets deleted.

Sorry for the long log dump. Interesting parts are right in the beginning and at the end.

```
13:36:49.306 INFO - Executing: [new session: Capabilities [{rotatable=true, locationContextEnabled=true, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@445fb0fb, browserName=chrome, javascriptEnabled=true, handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=3.2.4, url=http://webdriver.io}}]])
13:36:49.306 INFO - Executing: [new session: Capabilities [{rotatable=true, locationContextEnabled=true, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@68dee62d, browserName=chrome, javascriptEnabled=true, chromeOptions={args=[user-agent=Mozilla/5.0 (Linux; Android 4.3; Nexus 10 Build/JSS15Q) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2307.2 Mobile Safari/537.36]}, handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=3.2.4, url=http://webdriver.io}}]])
13:36:49.306 INFO - Creating a new session for Capabilities [{rotatable=true, locationContextEnabled=true, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@68dee62d, browserName=chrome, javascriptEnabled=true, chromeOptions={args=[user-agent=Mozilla/5.0 (Linux; Android 4.3; Nexus 10 Build/JSS15Q) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2307.2 Mobile Safari/537.36]}, handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=3.2.4, url=http://webdriver.io}}]
13:36:49.307 INFO - Creating a new session for Capabilities [{rotatable=true, locationContextEnabled=true, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@445fb0fb, browserName=chrome, javascriptEnabled=true, handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=3.2.4, url=http://webdriver.io}}]
Starting ChromeDriver 2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b) on port 13718
Only local connections are allowed.
Starting ChromeDriver 2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b) on port 15975
Only local connections are allowed.
13:36:50.041 INFO - Done: [new session: Capabilities [{rotatable=true, locationContextEnabled=true, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@68dee62d, browserName=chrome, javascriptEnabled=true, chromeOptions={args=[user-agent=Mozilla/5.0 (Linux; Android 4.3; Nexus 10 Build/JSS15Q) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2307.2 Mobile Safari/537.36]}, handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=3.2.4, url=http://webdriver.io}}]]
13:36:50.043 INFO - Executing: [get: http://10.96.4.162:8090/1369530?autoplay=true&embedded=false&init=true])
13:36:50.262 INFO - Done: [get: http://10.96.4.162:8090/1369530?autoplay=true&embedded=false&init=true]
13:36:50.270 INFO - Executing: [set script timeout: 15000])
13:36:50.275 INFO - Done: [set script timeout: 15000]
13:36:50.280 INFO - Executing: [execute async script: return (function waitForPausedState(state, done) {
    setInterval(function () {
        if (window.player && window.player.videoElementAvailable && window.player.isPaused() === state) {
            done(state);
        }
    }, 100);
}).apply(null, arguments);, [false]])
13:36:50.393 INFO - Done: [execute async script: return (function waitForPausedState(state, done) {
    setInterval(function () {
        if (window.player && window.player.videoElementAvailable && window.player.isPaused() === state) {
            done(state);
        }
    }, 100);
}).apply(null, arguments);, [false]]
13:36:50.402 INFO - Executing: [find elements: By.cssSelector: .__player-controls])
13:36:50.415 INFO - Done: [find elements: By.cssSelector: .__player-controls]
13:36:50.419 INFO - Executing: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]])
13:36:50.430 INFO - Done: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]]
13:36:50.689 INFO - Executing: [find elements: By.cssSelector: .__player-controls])
13:36:50.705 INFO - Done: [find elements: By.cssSelector: .__player-controls]
13:36:50.708 INFO - Executing: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]])
13:36:50.719 INFO - Done: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]]
13:36:50.982 INFO - Executing: [find elements: By.cssSelector: .__player-controls])
13:36:50.988 INFO - Done: [find elements: By.cssSelector: .__player-controls]
13:36:50.991 INFO - Executing: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]])
13:36:50.998 INFO - Done: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]]
13:36:51.255 INFO - Executing: [find elements: By.cssSelector: .__player-controls])
13:36:51.265 INFO - Done: [find elements: By.cssSelector: .__player-controls]
13:36:51.268 INFO - Executing: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]])
13:36:51.273 INFO - Done: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]]
13:36:51.529 INFO - Executing: [find elements: By.cssSelector: .__player-controls])
13:36:51.534 INFO - Done: [find elements: By.cssSelector: .__player-controls]
13:36:51.537 INFO - Executing: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]])
13:36:51.543 INFO - Done: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]]
13:36:51.799 INFO - Executing: [find elements: By.cssSelector: .__player-controls])
13:36:51.805 INFO - Done: [find elements: By.cssSelector: .__player-controls]
13:36:51.808 INFO - Executing: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]])
13:36:51.814 INFO - Done: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]]
13:36:52.070 INFO - Executing: [find elements: By.cssSelector: .__player-controls])
13:36:52.076 INFO - Done: [find elements: By.cssSelector: .__player-controls]
13:36:52.078 INFO - Executing: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]])
13:36:52.084 INFO - Done: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]]
13:36:52.341 INFO - Executing: [find elements: By.cssSelector: .__player-controls])
13:36:52.346 INFO - Done: [find elements: By.cssSelector: .__player-controls]
13:36:52.349 INFO - Executing: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]])
13:36:52.354 INFO - Done: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]]
13:36:52.611 INFO - Executing: [find elements: By.cssSelector: .__player-controls])
13:36:52.617 INFO - Done: [find elements: By.cssSelector: .__player-controls]
13:36:52.620 INFO - Executing: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]])
13:36:52.627 INFO - Done: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]]
13:36:52.883 INFO - Executing: [find elements: By.cssSelector: .__player-controls])
13:36:52.890 INFO - Done: [find elements: By.cssSelector: .__player-controls]
13:36:52.893 INFO - Executing: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]])
13:36:52.898 INFO - Done: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]]
13:36:53.155 INFO - Executing: [find elements: By.cssSelector: .__player-controls])
13:36:53.163 INFO - Done: [find elements: By.cssSelector: .__player-controls]
13:36:53.166 INFO - Executing: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]])
13:36:53.171 INFO - Done: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]]
13:36:53.428 INFO - Executing: [find elements: By.cssSelector: .__player-controls])
13:36:53.434 INFO - Done: [find elements: By.cssSelector: .__player-controls]
13:36:53.438 INFO - Executing: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]])
13:36:53.445 INFO - Done: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]]
13:36:53.702 INFO - Executing: [find elements: By.cssSelector: .__player-controls])
13:36:53.711 INFO - Done: [find elements: By.cssSelector: .__player-controls]
13:36:53.714 INFO - Executing: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]])
13:36:53.720 INFO - Done: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]]
13:36:53.983 INFO - Executing: [find elements: By.cssSelector: .__player-controls])
13:36:53.988 INFO - Done: [find elements: By.cssSelector: .__player-controls]
13:36:53.992 INFO - Executing: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]])
13:36:53.996 INFO - Done: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]]
13:36:54.000 INFO - Executing: [find element: By.cssSelector: video, object])
13:36:54.013 INFO - Done: [find element: By.cssSelector: video, object]
13:36:54.016 INFO - Executing: [click: 1 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: video, object]])
13:36:54.041 INFO - Done: [click: 1 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: video, object]]
13:36:54.047 INFO - Executing: [find elements: By.cssSelector: .__player-controls])
13:36:54.052 INFO - Done: [find elements: By.cssSelector: .__player-controls]
13:36:54.055 INFO - Executing: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]])
13:36:54.062 INFO - Done: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]]
13:36:54.319 INFO - Executing: [find elements: By.cssSelector: .__player-controls])
13:36:54.327 INFO - Done: [find elements: By.cssSelector: .__player-controls]
13:36:54.329 INFO - Executing: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]])
13:36:54.334 INFO - Done: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]]
13:36:54.339 INFO - Executing: [find elements: By.cssSelector: .__player-controls])
13:36:54.348 INFO - Done: [find elements: By.cssSelector: .__player-controls]
13:36:54.351 INFO - Executing: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]])
13:36:54.360 INFO - Done: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]]
13:36:54.615 INFO - Executing: [find elements: By.cssSelector: .__player-controls])
13:36:54.621 INFO - Done: [find elements: By.cssSelector: .__player-controls]
13:36:54.624 INFO - Executing: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]])
13:36:54.631 INFO - Done: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]]
13:36:54.886 INFO - Executing: [find elements: By.cssSelector: .__player-controls])
13:36:54.894 INFO - Done: [find elements: By.cssSelector: .__player-controls]
13:36:54.896 INFO - Executing: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]])
13:36:54.901 INFO - Done: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]]
13:36:55.157 INFO - Executing: [find elements: By.cssSelector: .__player-controls])
13:36:55.165 INFO - Done: [find elements: By.cssSelector: .__player-controls]
13:36:55.168 INFO - Executing: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]])
13:36:55.172 INFO - Done: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]]
13:36:55.428 INFO - Executing: [find elements: By.cssSelector: .__player-controls])
13:36:55.434 INFO - Done: [find elements: By.cssSelector: .__player-controls]
13:36:55.437 INFO - Executing: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]])
13:36:55.443 INFO - Done: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]]
13:36:55.699 INFO - Executing: [find elements: By.cssSelector: .__player-controls])
13:36:55.705 INFO - Done: [find elements: By.cssSelector: .__player-controls]
13:36:55.707 INFO - Executing: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]])
13:36:55.715 INFO - Done: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]]
13:36:55.971 INFO - Executing: [find elements: By.cssSelector: .__player-controls])
13:36:55.976 INFO - Done: [find elements: By.cssSelector: .__player-controls]
13:36:55.979 INFO - Executing: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]])
13:36:55.984 INFO - Done: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]]
13:36:56.240 INFO - Executing: [find elements: By.cssSelector: .__player-controls])
13:36:56.245 INFO - Done: [find elements: By.cssSelector: .__player-controls]
13:36:56.248 INFO - Executing: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]])
13:36:56.253 INFO - Done: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]]
13:36:56.509 INFO - Executing: [find elements: By.cssSelector: .__player-controls])
13:36:56.514 INFO - Done: [find elements: By.cssSelector: .__player-controls]
13:36:56.517 INFO - Executing: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]])
13:36:56.522 INFO - Done: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]]
13:36:56.778 INFO - Executing: [find elements: By.cssSelector: .__player-controls])
13:36:56.783 INFO - Done: [find elements: By.cssSelector: .__player-controls]
13:36:56.786 INFO - Executing: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]])
13:36:56.794 INFO - Done: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]]
13:36:57.050 INFO - Executing: [find elements: By.cssSelector: .__player-controls])
13:36:57.057 INFO - Done: [find elements: By.cssSelector: .__player-controls]
13:36:57.086 INFO - Executing: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]])
13:36:57.093 INFO - Done: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]]
13:36:57.349 INFO - Executing: [find elements: By.cssSelector: .__player-controls])
13:36:57.356 INFO - Done: [find elements: By.cssSelector: .__player-controls]
13:36:57.359 INFO - Executing: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]])
13:36:57.364 INFO - Done: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]]
13:36:57.620 INFO - Executing: [find elements: By.cssSelector: .__player-controls])
13:36:57.628 INFO - Done: [find elements: By.cssSelector: .__player-controls]
13:36:57.631 INFO - Executing: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]])
13:36:57.636 INFO - Done: [is displayed: 0 [[ChromeDriver: chrome on LINUX (f36aead622658a7530d0ae8f81f7a043)] -> css selector: .__player-controls]]
13:36:57.639 INFO - Executing: [delete session: 12e5ad61-cc37-4948-bcb1-bc30931b3675])
13:36:58.195 INFO - Done: [delete session: 12e5ad61-cc37-4948-bcb1-bc30931b3675]
```

`docker --version` says `Docker version 1.9.1, build a34a1d5`.

Any work arounds (or an actual fix) are highly appreciated. We are contemplating on retrying on session creation in the tests. Any thoughts on whether that's a good idea or not?

**Comment by SpencerMalone** [comment] 2015-12-14 16:35
Are you using ubuntu or centos? Also, try using release 2.46.0. For some reason, that works a little better for me.

**Comment by hmcgowan** [comment] 2015-12-14 17:25
We're using Java and decided to start the browser in a thread with a re-try if we saw it hang. Code in the gist, below. We've been using this work-around for over a month and have not seen an issue. 

https://gist.github.com/hmcgowan/2272e0546964417d2163

**Comment by uhef** [comment] 2015-12-16 13:51
I managed to get sessions started up with a retry logic similar to @hmcgowan.

However now I get
```
Uncaught Error: socket hang up
      at createHangUpError (_http_client.js:215:15)
      at Socket.socketCloseListener (_http_client.js:247:23)
      at TCP.close (net.js:485:12)
```
On multiple tests (these do not occur when running the tests against selenium server running on localhost.

We are using Node.js (v0.12.2) to run selenium tests on mocha (2.2.5) through webdriverio (3.2.4).

Any ideas what could be at play?

**Comment by hmcgowan** [comment] 2015-12-16 14:13
I'm assuming you mean that it's intermittent and you get some tests to run and then it fails with the socket error right? If you could provide a gist to the full stack trace I'm happy to take a look. We're on a totally different stack than you are but there might be a clue in there. 

One thing we noticed  with Chrome - if you don't call driver.quit() then it leaves a chrome process running and those can pile up every time you start the browser. The other thing is that before each suite we restart the docker container since it's so fast and that seems to keep things stable.

**Comment by gabriel-sagula-hs** [comment] 2016-02-24 23:43
Any update on this. Selenium hangs on Jenkins slaves (ubuntu), but never hangs on boot2docker. Thoughts?

selenium v. 2.52
chrome driver v. 2.21 (same happens with 2.20)

Here is my configuration:

selenium:
  image:  selenium/node-chrome-debug:2.52.0
  ports:
    - "4444:4444"
    - "5900:5900"
  expose:
    - "5900"
    - "4444"
  environment:
    - JAVA_OPTS=-Xmx1024M
    - SCREEN_WIDTH=1152
    - SCREEN_HEIGHT=864
    - SCREEN_DEPTH=16
  volumes:
    - /dev/urandom/:/dev/random
    - /dev/shm:/dev/shm
  privileged: true

**Comment by pwaller** [comment] 2016-02-25 08:14
This may be a duplicate of #87. There is a preliminary workaround of setting `DBUS_SESSION_BUS_ADDRESS=/dev/null` on the chrome container.

**Comment by gabriel-sagula-hs** [comment] 2016-02-25 19:46
@pwaller Thanks Peter, you nailed. Works now!

**Comment by Meju121093** [comment] 2016-08-09 13:15
Hi guys,
In Docker cloud terminal tab of the container, I couldn't type command in shell. Can you please help me to do in running container?

**Comment by diemol** [comment] 2017-09-07 19:53
Closing this issue since it has been solved in the referenced one and also with the help of the community.

**Closed by diemol** 2017-09-07 19:53 UTC
