### ISSUE TITLE
Reinstate tags with truncated version numbers

### ISSUE THREAD

**Issue by nickgaya** [SeleniumHQ/docker-selenium#1369] opened 2021-08-23 04:23 UTC
## 💥 Regression Report

Issue #1360 is invalid as it is based on the false notion that tags are intended to be immutable in Docker.

There is no need to try to make tags immutable, as Docker already provides immutable identifiers in the form of [image digests](https://docs.docker.com/engine/reference/commandline/pull/#pull-an-image-by-digest-immutable-identifier).  In contrast to tags, specifying an image digest ensures that the exact same image is pulled each time.

The change to remove rolling tags breaks workflows for users that want to constrain the image version without fully specifying it.  (For example, in my use case, I want to pull the latest selenium-hub image with version 4.x, so I would specify the tag `4`.)

Please revert commit 169dc4a.

**Comment by fkrivsky** [comment] 2021-08-25 15:57
@diemol [commented ](https://github.com/SeleniumHQ/docker-selenium/issues/1365#issuecomment-898546372) on this topic under #1365 ... 

I agree with you, the rolling tags are a standard way of managing updates. If people need stable versions they can use a stable tag.

**Comment by diemol** [comment] 2021-08-30 12:20
Duplicate of #1365

**Closed as completed by diemol** 2021-08-30 12:20 UTC
