### ISSUE TITLE
Error connecting node-chrome to hub

### ISSUE THREAD

**Issue by anjunatl** [SeleniumHQ/docker-selenium#553] opened 2017-09-05 21:53 UTC
## Meta -
**Image(s):** 
node-chrome
hub

**Docker-Selenium Image Version(s):**  
3.4.0-einsteinium

**OS:** 
OS X

## Expected Behavior - 

Using the following docker-compose config, when I run spin up my test container I should be able to run my Protractor tests using the `hub` and `node-chrome` images.

`docker-compose.yml` snippet:

```
  hub:
    image: selenium/hub:3.4.0-einsteinium
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:3.4.0-einsteinium
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
    expose:
      - "5555"
    ports:
      - "5900:5900"
    volumes:
      - /dev/shm:/dev/shm
    links:
      - hub

  web:
    <<: *npm
    ports:
      - "3001"
    entrypoint: ["bash"]
    command: ["/opt/project/web.sh"]

  test:
    build: test-env
    depends_on:
      - chrome
      - bbtserver
      - hub
    volumes:
      - ./test-env:/app/test
    entrypoint: ["/app/test/bin/run.sh"]
```

`test` container's `Dockerfile`:

```
FROM node:6
RUN apt-get update && apt-get upgrade -y --no-install-recommends && apt-get dist-upgrade -y

# Replace shell with bash so we can source files
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

RUN npm install --no-optional  underscore \
    protractor-jasmine2-screenshot-reporter \
    jasmine-spec-reporter 

WORKDIR /tmp

RUN npm install -g --no-optional gulp protractor@5.1.2

RUN apt-get update -y --no-install-recommends

# Fix for the issue with Selenium, as described here:
# https://github.com/SeleniumHQ/docker-selenium/issues/87
ENV DBUS_SESSION_BUS_ADDRESS=/dev/null

WORKDIR /app/blackbox-test
```

`test` container's entrypoint `run.sh`:

```
#!/bin/bash
test_dir=$(dirname $(dirname $0))
set -e
cd ${test_dir}
mkdir -p test-reports
sleep 15s
echo "Starting Blackbox-Test Execution"
echo "Protractor version:"
protractor --version
$test_dir/bin/wait-for-it.sh hub:4444 --timeout=200 -- \
$test_dir/bin/wait-for-it.sh bbtserver:3001 --timeout=200 -- \
protractor protractor.config.js --disableChecks --verbose --stackTrace
sleep 2
```

Protractor config:

```
// timing
var thirtySeconds = 30000;

// allow https self-signed
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

// screenshot reporter
var htmlScreenshotReporter = require('protractor-jasmine2-screenshot-reporter');
var screenshotReporter = new htmlScreenshotReporter({
  dest: 'test-reports/jasmine-screenshots',
  filename: 'my-report.html',
  ignoreSkippedSpecs: true,
  captureOnlyFailedSpecs: true
});

// spec reporter
var specReporter = require('jasmine-spec-reporter').SpecReporter;

// export configuration
exports.config = {
  framework: 'jasmine',
  getPageTimeout: thirtySeconds,
  allScriptsTimeout: thirtySeconds,
  rootElement: 'html',
  seleniumAddress: 'http://hub:4444/wd/hub',
  capabilities: {
    browserName: 'chrome'
  },

  // Setup the report before any tests start
  beforeLaunch: function() {
    return new Promise(function(resolve) {
      screenshotReporter.beforeLaunch(resolve);
    });
  },

  // Assign the test reporter to each running instance
  onPrepare: function() {
    jasmine.getEnv().addReporter(screenshotReporter);
    jasmine.getEnv().addReporter(new specReporter({
      spec: {
        displayStacktrace: true
      },
      summary: {
        displayPending: false
      }
    }));
  },

  // Close the report after all tests finish
  afterLaunch: function(exitCode) {
    return new Promise(function(resolve){
      screenshotReporter.afterLaunch(resolve.bind(this, exitCode));
    });
  },

  baseUrl: "http://web:3001/",
  specs: ['jasmine/specs/**/*.spec.js']

  // NOTE: Uncomment this and use it to filter which specs to run (by name)
  // https://jasmine.github.io/2.6/node.html#section-20
  //
  // jasmineNodeOpts: {
  //   filter: ''
  // }
};
```

## Actual Behavior -

The tests do not run and show an error instead. Googling the error message got me to the same answer from several locations, [to remove `-role hub`](https://github.com/angular/protractor/issues/1226#issuecomment-53930736) from [the command that starts it](https://github.com/SeleniumHQ/docker-selenium/blob/master/Hub/entry_point.sh#L23). I'm really not sure if that's what I should be doing in this case, as I'd like to set up an environment that can run several Chrome instances with a hub, so I figured I'd ask here.

Error log while running `test` container:

```
Starting redactedappname_npmdata_1
Creating redactedappname_hub_1
Creating redactedappname_web_1
Creating redactedappname_chrome_1
Starting Test Execution
Protractor version:
Version 5.1.2
wait-for-it.sh: waiting 15 seconds for hub:4444--timeout=200
wait-for-it.sh: timeout occurred after waiting 15 seconds for hub:4444--timeout=200
wait-for-it.sh: waiting 200 seconds for web:3001
wait-for-it.sh: web:3001 is available after 9 seconds
Report destination:   test-reports/jasmine-screenshots/my-report.html
[21:18:20] I/launcher - Running 1 instances of WebDriver
[21:18:20] I/hosted - Using the selenium server at http://hub:4444/wd/hub
[21:18:20] E/launcher - Error forwarding the new session Empty pool of VM for setup Capabilities [{count=1, browserName=chrome}]
[21:18:20] E/launcher - WebDriverError: Error forwarding the new session Empty pool of VM for setup Capabilities [{count=1, browserName=chrome}]
    at WebDriverError (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:27:5)
    at Object.checkLegacyResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:505:15)
    at parseHttpResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:440:13)
    at process._tickCallback (internal/process/next_tick.js:109:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:777:24)
    at Function.createSession (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/chrome.js:709:29)
    at createDriver (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/index.js:167:33)
    at Builder.build (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/index.js:623:16)
    at Hosted.getNewDriver (/usr/local/lib/node_modules/protractor/lib/driverProviders/driverProvider.ts:60:29)
    at Runner.createBrowser (/usr/local/lib/node_modules/protractor/lib/runner.ts:225:39)
    at q.then.then (/usr/local/lib/node_modules/protractor/lib/runner.ts:391:27)
    at _fulfilled (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:796:13)
[21:18:20] E/launcher - Process exited with error code 199
Killing redactedappname_chrome_1 ... done
Killing redactedappname_web_1 ... done
Killing redactedappname_hub_1 ... done
ERRO[0043] exit status 199                              
ERRO[0043] command failed. use --debug to see full stacktrace 
```

**Comment by diemol** [comment] 2017-10-03 19:28
Hi @anjunatl,

I think the problem is here:
```
$test_dir/bin/wait-for-it.sh hub:4444 --timeout=200
```
Because you are just checking that the hub is up and listening on the port 4444, but this does not mean that the Chrome container has already registered and is ready to receive requests.

Maybe you can check for the hub status at `http://hub:4444/wd/hub/status`, and you will see that the json will have a `ready` key which is `true` when the hub has already a node registered. That is what we do with the [tests we run in this project via python](https://github.com/SeleniumHQ/docker-selenium/blob/3.6.0-americium/tests/SmokeTests/__init__.py#L20), you could take that approach and adapt it.

**Comment by diemol** [comment] 2017-10-17 20:08
I'll close this issue since we didn't get feedback from the OP.

**Closed by diemol** 2017-10-17 20:08 UTC
Labels: R-awaiting-answer
