### ISSUE TITLE
User permissions error in non-debug images (Chrome and Firefox)

### ISSUE THREAD

**Issue by gael-wogenstahl** [SeleniumHQ/docker-selenium#405] opened 2017-03-07 04:02 UTC
## Meta -
Image(s): `node-chrome` and `node-firefox` 3.1.0-astatine

Docker Version:  1.13.1

OS: Ubuntu 14.04

## Expected Behavior -
First running a Selenium `hub` container and then running a new container with any `node-chrome`, `node-chrome-debug`, `node-firefox` or `node-firefox-debug` image should connect the node to the hub and be available in the grid.
## Actual Behavior -
Trying to run a new container with the `node-chrome` or `node-firefox` images version `3.1.0` results in container exiting right away with the following error :
```
/opt/bin/entry_point.sh: line 4: /opt/selenium/config.json: Permission denied
No Selenium Node configuration file, the node-base image is not intended to be run directly.
```
While running a new container with the debug images `node-chrome-debug` or `node-firefox-debug` version `3.1.0` everything works fine.

While changing the entrypoint and starting a bash inside the containers I noticed the user is different between the images. User is `seluser` in the non-debug images while it's `root` in the debug images.
Also I noticed the `/opt/selenium` directory belongs to `root` despite the Dockerfile line :
```
RUN chown -R seluser:seluser /opt/selenium
```
This prevents user `seluser` from accessing the configuration and thus running the node.

I'm not feeling confident enough to fix the Dockerfile myself. Can anyone help me with this ?

**Comment by ddavison** [comment] 2017-03-13 19:24
we need to see your run commands in order to help you out, here.

> Trying to run a new container

how are you trying to run these?

**Comment by gael-wogenstahl** [comment] 2017-03-14 00:13
Here are the commands I used to start my grid with the 2 nodes failing :
```console
username@machine:~$ docker run -d -p 4444:4444 --name selenium-hub selenium/hub:3.1.0
267a1fb6ff14ae664f8a4e104ec47778e2dc9e9b74b2ac2f98b237e4eb64361b
username@machine:~$ docker run -d --link selenium-hub:hub --name selenium-node-firefox selenium/node-firefox:3.1.0
a7e91d8b53e34b1d0e18c38ec970dd786e5aeea195db8f7e8edce58408ee3d3c
username@machine:~$ docker run -d --link selenium-hub:hub --name selenium-node-chrome selenium/node-chrome:3.1.0
a58e9511a89e59026bf437a26516ed5f6601fb7653ffbb1a239590ba724ef455
username@machine:~$ docker run -d --link selenium-hub:hub --name selenium-node-firefox-debug selenium/node-firefox-debug:3.1.0
f0dafbdcd866b1534e27782ee345e10fbdf17a9f327a7823c229972f7451287c
username@machine:~$ docker run -d --link selenium-hub:hub --name selenium-node-chrome-debug selenium/node-chrome-debug:3.1.0
1e98d1ac534a544ecd4408dc77df504f982ab64d6f877a79b5c9abe89d06fd1d
username@machine:~$ docker ps -a
CONTAINER ID        IMAGE                               COMMAND                  CREATED              STATUS                      PORTS                    NAMES
1e98d1ac534a        selenium/node-chrome-debug:3.1.0    "/opt/bin/entry_po..."   7 seconds ago        Up 6 seconds                5900/tcp                 selenium-node-chrome-debug
f0dafbdcd866        selenium/node-firefox-debug:3.1.0   "/opt/bin/entry_po..."   17 seconds ago       Up 16 seconds               5900/tcp                 selenium-node-firefox-debug
a58e9511a89e        selenium/node-chrome:3.1.0          "/opt/bin/entry_po..."   28 seconds ago       Exited (1) 28 seconds ago                            selenium-node-chrome
a7e91d8b53e3        selenium/node-firefox:3.1.0         "/opt/bin/entry_po..."   41 seconds ago       Exited (1) 40 seconds ago                            selenium-node-firefox
267a1fb6ff14        selenium/hub:3.1.0                  "/opt/bin/entry_po..."   About a minute ago   Up About a minute           0.0.0.0:4444->4444/tcp   selenium-hub
username@machine:~$ docker logs selenium-node-firefox
/opt/bin/entry_point.sh: line 4: /opt/selenium/config.json: Permission denied
No Selenium Node configuration file, the node-base image is not intended to be run directly.
username@machine:~$ docker logs selenium-node-chrome
/opt/bin/entry_point.sh: line 4: /opt/selenium/config.json: Permission denied
No Selenium Node configuration file, the node-base image is not intended to be run directly.
```

And here are what I did to check the user permissions inside the images :
```console
username@machine:~$ docker run --link selenium-hub:hub --name selenium-node-firefox -it --entrypoint /bin/bash selenium/node-firefox:3.1.0
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

seluser@0217ccd94bca:/$ id
uid=1000(seluser) gid=1000(seluser) groups=1000(seluser),27(sudo)
seluser@0217ccd94bca:/$ ls -al /opt/selenium
total 20712
drwxr-xr-x 2 root root     4096 Feb 24 19:09 .
drwxr-xr-x 8 root root     4096 Feb 24 19:09 ..
-rwxrwxr-x 1 root root      480 Feb 24 19:06 generate_config
-rw-r--r-- 1 root root 21190292 Feb 16 16:16 selenium-server-standalone.jar
seluser@0217ccd94bca:/$ exit
exit
username@machine:~$ docker run --link selenium-hub:hub --name selenium-node-firefox-debug -it --entrypoint /bin/bash selenium/node-firefox-debug:3.1.0
root@f3f4f5f25668:/# id
uid=0(root) gid=0(root) groups=0(root)
root@f3f4f5f25668:/# ls -al /opt/selenium
total 20712
drwxr-xr-x  2 root root     4096 Feb 24 19:09 .
drwxr-xr-x 10 root root     4096 Feb 24 19:11 ..
-rwxrwxr-x  1 root root      480 Feb 24 19:06 generate_config
-rw-r--r--  1 root root 21190292 Feb 16 16:16 selenium-server-standalone.jar
root@f3f4f5f25668:/# exit
exit
```

**Comment by diemol** [comment] 2017-04-18 15:56
@gael-wogenstahl I tried to reproduce the issue based on your commands and I was not able to see the error.

Maybe the images were updated for 3.1.0 after you posted this? Could you try again for 3.3.1?

**Comment by diemol** [comment] 2017-07-09 17:45
I'll close this issue since we didn't get feedback from the OP. Feel free to reopen when more accurate info is provided.

**Closed by diemol** 2017-07-09 17:45 UTC

**Comment by gael-wogenstahl** [comment] 2017-08-10 05:21
Hello,

Sorry I've been busy on other matters and couldn't try again what you asked.

I'm upgrading Selenium to 3.4.0 and tried to run the new docker images and got stuck in the same kind of problem.

Image(s): selenium/hub:3.4.0-einsteinium
Docker Version: 17.05.0-ce
OS: Ubuntu 14.04

I tried to start the hub following the documentation with that result :
```console
username@machine:~/git/scenarios$ docker run -d -p 4444:4444 --name selenium-hub selenium/hub:3.4.0-einsteinium
a04cf62774c4cf57346791a209e9086ef7444b6dc461151ca78156fabbf98546
username@machine:~/git/scenarios$ docker ps -a
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS                     PORTS               NAMES
a04cf62774c4        selenium/hub:3.4.0-einsteinium   "/opt/bin/entry_po..."   4 seconds ago       Exited (1) 3 seconds ago                       selenium-hub
username@machine:~/git/scenarios$ docker logs selenium-hub 
/opt/bin/entry_point.sh: line 6: /opt/selenium/config.json: Permission denied
starting selenium hub with configuration:
{
  "host": null,
  "port": 4444,
  "role": "hub",
  "maxSession": ,
  "newSessionWaitTimeout": ,
  "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
  "throwOnCapabilityNotPresent": ,
  "jettyMaxThreads": ,
  "cleanUpCycle": ,
  "browserTimeout": ,
  "timeout": ,
  "debug": 
}
Exception in thread "main" org.openqa.grid.common.exception.GridConfigurationException: Wrong format for the JSON input : com.google.gson.stream.MalformedJsonException: Unexpected value at line 1 column 65 path $.maxSession
	at org.openqa.grid.common.JSONConfigurationUtils.loadJSON(JSONConfigurationUtils.java:81)
	at org.openqa.grid.internal.utils.configuration.GridHubConfiguration.loadFromJSON(GridHubConfiguration.java:147)
	at org.openqa.grid.selenium.GridLauncherV3$2.setConfiguration(GridLauncherV3.java:249)
	at org.openqa.grid.selenium.GridLauncherV3.buildLauncher(GridLauncherV3.java:155)
	at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:75)
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unexpected value at line 1 column 65 path $.maxSession
	at com.google.gson.internal.Streams.parse(Streams.java:60)
	at com.google.gson.JsonParser.parse(JsonParser.java:84)
	at com.google.gson.JsonParser.parse(JsonParser.java:59)
	at com.google.gson.JsonParser.parse(JsonParser.java:45)
	at org.openqa.grid.common.JSONConfigurationUtils.loadJSON(JSONConfigurationUtils.java:79)
	... 4 more
Caused by: com.google.gson.stream.MalformedJsonException: Unexpected value at line 1 column 65 path $.maxSession
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:564)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:716)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714)
	at com.google.gson.internal.Streams.parse(Streams.java:48)
	... 8 more
```

**Comment by rakeshnambiar** [comment] 2017-09-10 11:08
@diemol ..  I am facing this issue on OpenShift. May I know which environment variable I should pass to resolve this issue?

**Comment by gael-wogenstahl** [comment] 2017-09-10 20:31
@rakeshnambiar as stated in #535 the issue for me is linked to user namespace being activated in Docker. Once I deactivated it everything was working fine although this isn't the right option since user namespaces do have a purpose.

**Comment by rakeshnambiar** [comment] 2017-09-10 20:38
@gael-wogenstahl .. It's working for me when I run sudo permission on docker. But in the cloud openshift I don't have sudo permission and facing the stated issue. Since it's not a pure docker installation I couldn't find the folder which you mentioned to deactivate the namespace.

**Comment by gael-wogenstahl** [comment] 2017-09-10 20:44
@rakeshnambiar you might want to get in touch with your cloud provider to check which Docker options are activated or not. Depending on their setup user namespaces might be activated.

But as I already stated the problem is in the docker itself since docker container should be runnable without root privileges. There might be some user permissions fixing to do but I don't know Selenium docker setup enough to be able to contribute.
Maybe @diemol can help me with that ?
