### ISSUE TITLE
Standalone Container Firefox broken?

### ISSUE THREAD

**Issue by AumCoin** [SeleniumHQ/docker-selenium#718] opened 2018-04-06 01:34 UTC
Not sure where to begin.  I downloaded firefox-standalone-debug or whatever and spent some good time (12hrs+) working with it.  It runs Selenium but eventually throws an error on driver.get, which seems to be linked to the FF version.  I manually downgraded FF in the container and wound up with some other issue.

I originally tried these containers because somewhere between Selenium, Firefox, and Geckodriver versions, there are bugs in the dozen or so implementations I have tried.  Ironically, I have been using Selenium standalone with FF for years and -never- had a problem until recently.  I don't understand how something that worked so perfectly up to 2 years ago can now be impossible to get working 100% of the time.

I guess this is a bit of a rant.  I'm just hoping that this git actually supplies something useful, like a working combination of the above-mentioned software versions.  Can anyone recommend any combination of (docker containers, software versions, etc.) that will allow me to run Selenium tests successfully?  I have spend hundreds of hours trying to work around all this BS ChromeDriver/GeckoDriver crap.  It almost seems like these two new parts of Selenium were designed to break Selenium.  Do people still use Selenium?  I assume there is still some way in the world of producing a working Selenium implementation?  Or did Selenium just cease to exist?

I realize I'm not providing much information but this is surely some kind of known "issue" (more like 20 issues).  Selenium standalone has never worked for me under ChromeDriver or GeckoDriver, and I tried the server last night with a Docker container and am still encountering issues.  I have given up on this.  Can anyone provide a plan of action for producing a working Selenium environment, that does not have huge issues involving Geckodriver or Chromedriver, in under 10 hours?

**Comment by AumCoin** [comment] 2018-04-06 01:51
Sorry I don't want to spend another several hours reproducing what I did to get error messages that seem to be already linked to known issues.  It would be really cool if someone could just say, "download such and such version/flavor of Linux and install these versions of Firefox, GeckoDriver, etc."  Because this product actually worked perfectly for years, but now between the Linux -> Selenium -> Gecko/ChromeDriver -> Firefox chain, things simply do not work.  It seems like Selenium is all you guys do, and lots of businesses use it, so I'm trying to understand how IT professionals like myself are getting by after you broke what was working for so many years.  I still need this product but I can't even restore the functionality that was available years ago.

**Comment by AumCoin** [comment] 2018-04-06 01:54
Or if you are aware of the crazy issues with Selenium right now, are you doing anything to fix them?  Are you considering reverting to an older version to fix all of the newly-introduced bugs, or do you plan on releasing a stable Docker container (one that is tested to work with the software versions it is packaged with)?

**Comment by diemol** [comment] 2018-04-06 13:13
Hi @AumCoin,

I understand the frustration that can be caused by having something working and after a while or updating it, it does not work as expected anymore. Selenium and the drivers are going through a series of changes towards the proposed [W3C WebDriver standard](https://www.w3.org/TR/webdriver/), and these changes brought some issues to Firefox, most of them should be by now in theory fixed.

However, I would appreciate that we keep a friendly tone when reporting issues, this just makes things easier and more pleasant.

Now, we are here to help and improve things in any way we can. To help you, we would actually need more specific information about the issue(s) you are running into (which is the purpose of the issue template). So, whenever you can, please let us know what docker commands were used to start the image, what Selenium bindings are you using, and if possible a small test to reproduce the issue.

I also invite you to contribute, whenever you see an issue or something that can be improved (documentation or code), don't doubt to create an issue here or sent a pull request. You can also join us in the [Selenium IRC/Slack Channel](https://seleniumhq.herokuapp.com), where lots of people are present and can help in different ways.

**Comment by diemol** [comment] 2018-04-16 19:52
I'll close this issue since we didn't get more information about it. Feel free to reopen if more details are provided.

**Closed by diemol** 2018-04-16 19:52 UTC
Labels: R-awaiting-answer
