### ISSUE TITLE
Run test with seleniu hub in Neokylin Linux get error messages.

### ISSUE THREAD

**Issue by clobob** [SeleniumHQ/docker-selenium#1046] opened 2020-05-19 09:07 UTC
## 🐛 Bug Report

OS： Neokylin Linux Desktop Operating System [introduce](http://www.cs2c.com.cn/index.php?id=108)
docker: 17.06.0-ce

start hub: # docker run -d -p 4444:4444 --name selehub selenium/hub
start node: # docker run -d -p 15555:5555 -e HUB_HOST=10.0.2.15 -e HUB_PORT=4444 -e REMOTE_HOST="http://10.0.2.15:15555" selenium/node-firefox

try to run a test script:
python testSeleniumGrid.py -v

content in testSeleniumGrid.py -->>

```
from selenium.webdriver import Remote

driver = Remote(command_executor='http://10.0.2.15:4444/wd/hub/',desired_capabilities={'browserName':'firefox'})

driver.get("http://www.baidu.com")
print(driver.title)
driver.close()

```
actual result in bash output:

> Traceback (most recent call last):
  File "testSeleniumGrid.py", line 3, in <module>
    driver = Remote(command_executor='http://10.0.2.15:4444/wd/hub/',desired_capabilities={'browserName':'firefox'})
  File "/home/work/.virtualenvs/seleniumbase_env/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/work/.virtualenvs/seleniumbase_env/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/work/.virtualenvs/seleniumbase_env/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/work/.virtualenvs/seleniumbase_env/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Session [(null externalkey)] not available and is not among the last 1000 terminated sessions.
Active sessions are[]
Stacktrace:
    at org.openqa.grid.internal.ActiveTestSessions.getExistingSession (ActiveTestSessions.java:120)
    at org.openqa.grid.internal.DefaultGridRegistry.getExistingSession (DefaultGridRegistry.java:387)
    at org.openqa.grid.web.servlet.handler.RequestHandler.getSession (RequestHandler.java:241)
    at org.openqa.grid.web.servlet.handler.RequestHandler.process (RequestHandler.java:123)
    at org.openqa.grid.web.servlet.DriverServlet.process (DriverServlet.java:85)
    at org.openqa.grid.web.servlet.DriverServlet.doPost (DriverServlet.java:69)
    at javax.servlet.http.HttpServlet.service (HttpServlet.java:707)
    at javax.servlet.http.HttpServlet.service (HttpServlet.java:790)
    at org.seleniumhq.jetty9.servlet.ServletHolder.handle (ServletHolder.java:865)
    at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle (ServletHandler.java:535)
    at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle (ScopedHandler.java:146)
    at org.seleniumhq.jetty9.security.SecurityHandler.handle (SecurityHandler.java:548)
    at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle (HandlerWrapper.java:132)
    at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle (ScopedHandler.java:257)
    at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle (SessionHandler.java:1595)
    at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle (ScopedHandler.java:255)
    at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle (ContextHandler.java:1340)
    at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope (ScopedHandler.java:203)
    at org.seleniumhq.jetty9.servlet.ServletHandler.doScope (ServletHandler.java:473)
    at org.seleniumhq.jetty9.server.session.SessionHandler.doScope (SessionHandler.java:1564)
    at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope (ScopedHandler.java:201)
    at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope (ContextHandler.java:1242)
    at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle (ScopedHandler.java:144)
    at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle (HandlerWrapper.java:132)
    at org.seleniumhq.jetty9.server.Server.handle (Server.java:503)
    at org.seleniumhq.jetty9.server.HttpChannel.handle (HttpChannel.java:364)
    at org.seleniumhq.jetty9.server.HttpConnection.onFillable (HttpConnection.java:260)
    at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded (AbstractConnection.java:305)
    at org.seleniumhq.jetty9.io.FillInterest.fillable (FillInterest.java:103)
    at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run (ChannelEndPoint.java:118)
    at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.runTask (EatWhatYouKill.java:333)
    at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce (EatWhatYouKill.java:310)
    at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.tryProduce (EatWhatYouKill.java:168)
    at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run (EatWhatYouKill.java:126)
    at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run (ReservedThreadExecutor.java:366)
    at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob (QueuedThreadPool.java:765)
    at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run (QueuedThreadPool.java:683)
    at java.lang.Thread.run (Thread.java:748)

**Comment by diemol** [comment] 2020-05-19 10:07
@clobob Can you please fill out the complete template, many sections of it were deleted 😢 
We don't know how to reproduce the issue, could you please help us by providing all the required information?

**Comment by clobob** [comment] 2020-05-19 13:56
> @clobob Can you please fill out the complete template, many sections of it were deleted 😢
> We don't know how to reproduce the issue, could you please help us by providing all the required information?

Ok.
**A clear and concise description of what the bug is.**
   _Test can not run with the hub and node which started in a Linux OS(Neokylin Linux Desktop Operating System)._

**Steps to reproduce the behavior (including the command to start the containers):**
 _1. start hub by using selenium docker. here is the command ==>>docker run -d -p 4444:4444 --name selehub selenium/hub _
_2. start node by using selenium docker. here is the command ==>> docker run -d -p 15555:5555 -e HUB_HOST=10.0.2.15 -e HUB_PORT=4444 -e REMOTE_HOST="http://10.0.2.15:15555" selenium/node-firefox _
_3. run a test in a terminal. here is the command ==>> python testSeleniumGrid.py -v _

## Expected behavior
test can run and output can be displayed.

## Test script reproducing this issue
`from selenium.webdriver import Remote

driver = Remote(command_executor='http://10.0.2.15:4444/wd/hub/',desired_capabilities={'browserName':'firefox'})

driver.get("http://www.baidu.com")
print(driver.title)
driver.close()`

## Environment
OS: <!-Neokylin Linux Desktop Operating System->
Docker-Selenium image version: latest
selenium/hub
selenium/node-firefox

docker version:  17.06.0-ce
python version: 3.7.5

**Comment by diemol** [comment] 2020-05-19 14:20
What Selenium version in the bindings, which docker images? 
What is the error in the docker containers?
What happens if you try in a different operating system?

**Comment by clobob** [comment] 2020-05-20 14:01
Selenium version 3.141.0.
docker images I used default tag, so they are latest version.

> selenium/hub:latest
> selenium/node-firefox:latest

nothing happens in docker containers.
For other operating system, i'll have a try. i need some time.

**Comment by clobob** [comment] 2020-05-22 01:15
@diemol 
it works on CentOS 7 + python 3.6.8 + selenium 3.141.0 + docker  19.03.9 + selenium/hub:latest + selenium/node-firefox:latest

**Comment by diemol** [comment] 2020-06-14 22:00
Thanks for the reply @clobob. Then I'd recommend using that OS or Ubuntu (which is normally the most reliable one), it has happened that other variants of Linux present problems. 
We don't really have enough resources, and in some cases expertise, to test and provide support to the images in OS that are not commonly used.

I will close this since you were able to make it work on CentOS.

**Closed by diemol** 2020-06-14 22:00 UTC
Labels: R-awaiting-answer
