### ISSUE TITLE
New docker images 2.53 and 2.52 fail to start

### ISSUE THREAD

**Issue by cehoffman** [SeleniumHQ/docker-selenium#208] opened 2016-04-18 19:55 UTC
The image 2.52 (9f528a33bb6f) and 2.53/latest (727a50d14683) for standalone-chrome-debug fail to start with the following error.

~~~
/opt/bin/entry_point.sh: line 4: /opt/bin/functions.sh: No such file or directory
/opt/bin/entry_point.sh: line 17: get_server_num: command not found
~~~

**Comment by sixinli** [comment] 2016-04-18 21:01
same with the firefox one :( 
```
/opt/bin/entry_point.sh: line 3: /opt/bin/functions.sh: No such file or directory
/opt/bin/entry_point.sh: line 16: get_server_num: command not found
```

**Comment by capoferro** [comment] 2016-04-18 22:07
Looks like an untested commit:
https://github.com/SeleniumHQ/docker-selenium/commit/1b2786e6090dbda785d5869db2ef73c3f20ad923

It refactors the entrypoint.sh, but doesn't update the Dockerfile or provide the functions.sh that the new entrypoint.sh needs.

**Comment by capoferro** [comment] 2016-04-18 22:08
@kayabendroth ^

**Comment by 4alldigital** [comment] 2016-04-20 15:04
Tested and confirmed only seems to be an issue with the -debug drivers. non-debug driver for both chrome and firefox work fine.

**Comment by pda** [comment] 2016-04-20 23:47
> Tested and confirmed only seems to be an issue with the -debug drivers. non-debug driver for both chrome and firefox work fine.

The source code of the non-debug standalone-chrome also has an `entry_point.sh` (actually used as `CMD` not `ENTRYPOINT`) [sourcing non-existent `/opt/bin/functions.sh`](https://github.com/SeleniumHQ/docker-selenium/blob/d63d666efe3b16cde2fcf288b56d8ca5ac79629a/StandaloneChrome/entry_point.sh#L3). However that code doesn't seem to have landed in the recent `2.52.0` or `2.53.0` image tags, but is broken in the `:latest` tag:

```
pda@paulbook ~ ❯ docker run --rm -it selenium/standalone-chrome:latest
/opt/bin/entry_point.sh: line 3: /opt/bin/functions.sh: No such file or directory
/opt/bin/entry_point.sh: line 16: get_server_num: command not found
```

**Comment by capoferro** [comment] 2016-04-20 23:54
An easy way to demonstrate the problem:

```
$ docker run selenium/standalone-chrome:latest ls /opt/bin
entry_point.sh
$ docker run selenium/standalone-chrome:latest cat /opt/bin/entry_point.sh
#!/bin/bash

source /opt/bin/functions.sh

# ...etc
```

**Comment by 4alldigital** [comment] 2016-04-20 23:57
Is this the file thats missing from the build : https://github.com/SeleniumHQ/docker-selenium/blob/master/NodeBase/functions.sh

**Comment by Spy-Seth** [comment] 2016-04-21 08:05
I confirm I have an issue the `node-chrome` one:

```
$ dc up selenium_node_chrome
myproject_selenium_hub_1 is up-to-date
Starting myproject_selenium_node_chrome_1
Attaching to myproject_selenium_node_chrome_1
selenium_node_chrome_1                 | xvfb-run: error: Xvfb failed to start
myproject_selenium_node_chrome_1 exited with code 1
```

**Comment by andrerom** [comment] 2016-04-21 16:03
`selenium/standalone-firefox:latest` broken here as well..

**Comment by kayabendroth** [comment] 2016-04-24 09:48
I checked the ```2.53.0``` tagged images and did not get the error. But can reproduce with ```latest```

**Comment by kayabendroth** [comment] 2016-04-24 12:31
Please check, if this is fixed for you with the images from today.

Latest changes from ```master``` have been merged into ```2.53.0``` branch, thus triggering a rebuild of ```2.53.0``` and ```latest``` images.

**Comment by 4alldigital** [comment] 2016-04-24 12:34
@kayabendroth is it not the debug versions doing this : https://github.com/SeleniumHQ/docker-selenium/blob/master/NodeFirefoxDebug/entry_point.sh#L3

&& the Dockerfile missing the COPY command to bring in the functions.sh file : https://github.com/SeleniumHQ/docker-selenium/blob/master/NodeFirefoxDebug/Dockerfile#L52

as the NodeBase Dockerfile currently does : https://github.com/SeleniumHQ/docker-selenium/blob/master/NodeBase/Dockerfile#L28

?

**Comment by kayabendroth** [comment] 2016-04-24 12:45
@4alldigital The _node*debug_ images are build off of their _node_ counterparts, which are based on _node-base_. And _node-base_ already has ```/opt/bin/functions.sh```. Have a look at https://hub.docker.com/r/selenium/node-firefox-debug/builds/bauzaguyjczuwpkscy3yarb/.

**Comment by 4alldigital** [comment] 2016-04-24 12:46
yeah, I was wondering if thats how it was supposed to work.. but looked like it didn't need fixing if that were the case. I'll pull and build from latest and let you know how I get on. 

Thanks for the fixes.

**Comment by 4alldigital** [comment] 2016-04-24 14:10
@kayabendroth confirmed pulled and working locally here with :latest *-debug containers. nice work! 
thanks

**Closed** 2016-04-29 12:45 UTC
Labels: bug

**Comment by park9140** [comment] 2016-05-05 21:03
@kayabendroth, I seem to still have this problem with the debug builds even using `2.53.0` I am on docker version `1.9.1` is there a dependency or something that needs to be cleared out if you had it before this fix?

**Comment by vikramvi** [comment] 2016-09-29 15:35
I got this working with command

docker run -d -P -e no_proxy=localhost -e HUB_ENV_no_proxy=localhost --link selenium-hub:hub selenium/node-chrome-debug
