### ISSUE TITLE
selenium-grid-node-docker sends registration event to selenium-hub but not registered.

### ISSUE THREAD

**Issue by namilkimfree** [SeleniumHQ/docker-selenium#1408] opened 2021-09-28 02:19 UTC
## 🐛 Bug Report

selenium-grid-node-docker log:
![image](https://user-images.githubusercontent.com/44854923/134838059-07130e33-d66c-4cd1-9f06-391af7764112.png)
02:09:10.892 INFO [NodeServer$1.lambda$start$1] - Sending registration event...

selenium-hub log:
![image](https://user-images.githubusercontent.com/44854923/134838106-beab2d62-7da2-427a-8c00-28824ac80230.png)

## To Reproduce
`
VM1: $ docker run -p 4442-4444:4442-4444 --name selenium-hub selenium/hub:4.0.0-rc-2-prerelease-20210923
`
```
VM2: $ docker run \
    -e SE_EVENT_BUS_HOST=<VM1-IP> \
    -e SE_EVENT_BUS_PUBLISH_PORT=4442 \
    -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 \
    -v /NodeDocker/config.toml:/opt/bin/config.toml \
    -v /assets:/opt/selenium/assets \
    selenium/node-docker:4.0.0-rc-2-prerelease-20210923
```

## Expected behavior

selenium-grid-node-docker must be registered on selenium-hub.

## Environment

OS: ubuntu
Docker-Selenium image version: 
selenium hub: selenium/hub:4.0.0-rc-2-prerelease-20210923
selenium grid node docker:  selenium/node-docker:4.0.0-rc-2-prerelease-20210923
Also provide the docker image id 
-->
Docker version: 
Docker-Compose version (if applicable):
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):

**Comment by moeniebdavids** [comment] 2021-09-29 08:49
Hi, Is this not due to the fact that the network on the hub and the network on the node is different?
When the node send registration request, it looks like it sends it with the an ip that is specific to the local VM and docker. This of course is not known by the hub?

**Comment by mborejdo** [comment] 2021-09-29 09:18
we seem to be running into this issue as well, but we are starting the services with docker-compose, which generates some common default network. So I guess its not related to network-setup

**Comment by moeniebdavids** [comment] 2021-09-29 09:19
well, if you running compose across two different physical machines, then the network will be different, at least on a docker level?

**Comment by mborejdo** [comment] 2021-09-29 09:25
yes, of course :-) We run all services on the same machine though. As I am upgrading from 3 to 4, there might be other config-problems I run into. But I tried different combinations with `SE_EVENT_BUS_PUBLISH_PORT`, `SE_EVENT_BUS_SUBSCRIBE_PORT`, `SE_EVENT_BUS_HOST`, `SE_NODE_GRID_URL`, `SE_NODE_PORT` and `SE_NODE_HOST` and cannot get the grid to see my nodes.

**Comment by namilkimfree** [comment] 2021-09-30 03:54
@moeniebdavids  @mborejo

Yes. It's on a different network.
Hub is VM 1
NodeDocker is on VM2.

i'm not use docker-compose , And Diemol said.
It can be done on different networks too. 

but not connected register .

dynamic docker: 
`This can be expanded to a full Grid deployment, all components deployed individually. The overall idea is to have the Hub in one virtual machine, and each of the Nodes in separate and more powerful virtual machines. `

**Comment by namilkimfree** [comment] 2021-09-30 04:02
@diemol  
can you try this issue?

**Comment by moeniebdavids** [comment] 2021-10-16 13:23
@namilkimfree 
Have you had any success?

**Comment by namilkimfree** [comment] 2021-10-21 07:54
@moeniebdavids 

I've tried the new version too, but it doesn't work.


@diemol can you help us?

thank you.

**Comment by wikingwei** [comment] 2021-10-29 10:03
We also run into the exact same issue, using 4.0.0 release version(use docker hub and chrome, both vers are: 4.0.0-20211013) 
our VM env info: 
       Ubuntu 18.04.4 LTS
       Kernel: Linux 4.15.0-115-generic
      Architecture: x86-64
And we got the same issue when we run hub docker and chrome-node dockers on the same VM or different VMs!

BTW: The way of docker network is OK without any issue about registration .

**Comment by aisebastian** [comment] 2021-10-30 05:07
I can reproduce the issue as well, it works well under one docker-compose setup

LE: I cannot reproduce the issue, turns out i was missing SE_NODE_HOST on the node, and proper firewall configuration from hub towards the node.

**Comment by namilkimfree** [comment] 2021-11-03 13:52
@aisebastian 
NodeDocker need to Env SE_NODE_HOST ?? 

did you complete multiple vm??

**Comment by diemol** [comment] 2021-11-03 14:04
This is a duplicate of #1403, please check this [comment](https://github.com/SeleniumHQ/docker-selenium/issues/1403#issuecomment-959134307) for the solution.

**Closed as completed by diemol** 2021-11-03 14:04 UTC
Labels: needs-triaging

**Comment by aisebastian** [comment] 2021-11-04 06:24
@namilkimfree yes, here is my node docker-compose configuration:

> 
>   environment:
>       - SE_EVENT_BUS_HOST=172.17.1.10
>       - SE_EVENT_BUS_PUBLISH_PORT=4442
>       - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
>       - SE_NODE_MAX_SESSIONS=1
>       - SE_NODE_HOST=172.17.1.11
>       - START_XVFB=false

172.17.1.10 is the machine running grid, 172.17.1.11 is the machine running the node

For this configuration, you definitely need ports 4442 and 4443 of the selenium grid to be exposed both through the container running it, and between the two machines.
