### ISSUE TITLE
SELENIUM HUB mismatching versions of Chrome Browser

### ISSUE THREAD

**Issue by zatekoja** [SeleniumHQ/docker-selenium#1392] opened 2021-09-13 18:26 UTC
## 🐛 Bug Report

Selenium hub mismatches versions of chrome. 
I specified using DesiredCapabilities.CHROME.copy() [Python] to start a remote webdriver with chrome version "93.0...", 
however, Selenium hub is starting a new session with "92.0...". 

This is happening after chaining multiple python files together in a shell script. For example, one file could ask the hub to run a selenium test with version 92 and the next test would ask for version 93. For some reason this causes a mis-match. 

## To Reproduce

1. Create multiple python files [A-test.py, B-test.py, C-test.py]
2. Write selenium tests using remote web-driver
3.  Let A-test.py connect using version 92.0 & let B-test connect using version 93.0 & let C-test.py connect using version 92.0

**_A-TEST.PY & C-TEST.PY Can look like this_** 
`
_**capabilities = DesiredCapabilities.CHROME.copy()
version_chrome = '92.0.4515.131' **# SWAP TO '93.0.4577.63' FOR B-TEST.PY**
capabilities['version'] = version_chrome

browser = webdriver.Remote(
            command_executor='{0}'.format(host_ip),
            desired_capabilities=capabilities)`**_

SCRIPT TO RUN A-TEST.PY B-TEST.PY C-TEST.PY
`
#!/bin/bash

set -e

echo "SELENIUM_HUB_ADD is $SELENIUM_HUB_ADD ";

while ! curl -sSL "$SELENIUM_HUB_ADD/status" 2>&1 \
        | jq -r '.value.ready' 2>&1 | grep "true" >/dev/null; do
    echo 'Waiting for the Grid'
    sleep 1
done

>&2 echo "Selenium Grid is up - executing tests"

python3 A-test.py;
python3 B-test.py;
python3 C-test.py
`
Check the logs of **selenium hub**: 
You should see something like this :

- Session request received by the distributor: [Capabilities {browserName: chrome, browserVersion: 93.0.4577.63,  ....
- Session created by the distributor. Id: 9e1045fbc82e39964deb72ab9cfe024d, Caps: Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 92.0.4515.131 ...

Notice the session **request** and what was actually made are totally **different** 

## Expected behavior

What is expected is that selenium hub creates the session that is requested. 

## Environment

OS: Mac OS big sur 11.5.2
Docker-Selenium image version: 4.0.0-rc-2 ID:sha256:d151ccdb6702c301b7412d5b6eca2e0f21f3dc88ebe91223d2b01ed987a72009
Chrome versions : selenium/node-chrome:92.0-20210804, selenium/node-chrome:93.0

Docker version: Docker version 20.10.0, build 7287ab3
Docker-Compose version (if applicable): 3
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):
docker-compose up

**Comment by diemol** [comment] 2021-09-14 21:33
What docker compose file are you using? Can you provide the complete logs of the running Grid?

**Comment by zatekoja** [comment] 2021-09-14 21:38
Hi @diemol thank you for replying my docker compose file looks like this :
version: "3"

services:
  ces_selenium_tests:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: selenium_tests
    expose:
      - 4444
    depends_on:
      - selenium-hub
      - chrome_no_proxy
      - chrome_proxy
    networks:
      host:

  selenium-hub:
    image: selenium/hub:4.0
    container_name: selenium-hub
    environment:
      - GRID_TIMEOUT=90
    ports:
      - "4444:4444"
      - "4442:4442"
      - "4443:4443"
    expose:
      - 4444
    networks:
      host:

  chrome_no_proxy:
    image: selenium/node-chrome:92.0-20210804
    container_name: chrome_no_proxy
    shm_size: 2gb
    #deploy:
      #replicas:
    ports:
      - "5800:5900"
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      host:

  chrome_proxy:
    image: selenium/node-chrome:93.0
    container_name: chrome_proxy
    shm_size: 2gb
    #deploy:
    #replicas:
    ports:
      - "5900:5900"
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - HTTPS_PROXY=$PROXY
      - HTTP_PROXY=$PROXY
    networks:
      host:

networks:
  host:

Asper the grid logs I unfortunately do not have them anymore.

**Comment by zatekoja** [comment] 2021-09-14 21:44
the ces_selenium_tests container has some python scripts that run selenium tests against corporate internal sites and some external sites. 

I have logic in my code that tells the tests to go to a specific version of chrome depending on if the test is internal [chrome_no_proxy] or external [chrome_proxy]. 
this is where i noticed that hub does not do version swapping well.

**Comment by diemol** [comment] 2021-09-14 22:25
I am not sure if I understand correctly. You have a Grid with one Hub and two Nodes. One of the Nodes has Chrome 92 and the other one has Chrome 93. Somehow a test requesting Chrome 93 starts with Chrome 92? Are you running tests in parallel or sequentially?

To troubleshoot this, I would need a complete way to reproduce it, so I can either copy & paste or clone a GitHub repo and run to analyse the logs.

**Comment by zatekoja** [comment] 2021-09-15 13:17
Sorry for the confusion, I cant share the repo its private, The best I can do is give an example. You're reallly close to understanding the issue. 

I run a test and specifically identify to go to Chrome 93 using **desired capabilities** , however, the hub ignores the request for that version and goes to 92 instead.

**Comment by diemol** [comment] 2021-09-23 09:54
Sure, you can give us an example script that allows us to reproduce the issue. It does not need to be the exact same code you are using internally, just anything that can be used on our side. This is important because I tried to reproduce it with a simple test I created and it worked, so to avoid ambiguity, it is better if you provide a way to reproduce the issue.

**Comment by diemol** [comment] 2021-10-17 19:44
Closing as we did not get more information.

**Closed as completed by diemol** 2021-10-17 19:44 UTC
Labels: R-awaiting-answer
