### ISSUE TITLE
Firefox webdriver gives "Insecure Connection" using HTTPS

### ISSUE THREAD

**Issue by Chaoste** [SeleniumHQ/docker-selenium#313] opened 2016-10-19 09:58 UTC
## Meta - Images and versions

Docker-compose file:

```
...
selenium-hub:
  image: selenium/hub:3.0.0-dubnium
  ports:
    - "4444:4444"
  links:
    - superserver:mytargeturl.com

nodefirefox:
  image: selenium/node-firefox:3.0.0-dubnium
  ports:
    - 5900
  links:
    - selenium-hub:hub
    - superserver:mytargeturl.com

test:
  build: ./..
  dockerfile: dockerfiles/images/test
  links:
    - selenium-hub
    - nodefirefox
    - superserver:mytargeturl.com
```

Docker Version:  

```
docker-compose version 1.8.0, build f3628c7
```

Testing:
I'm having a node container ("test") and several other node containers running. I have a container "superserver" which is a nginx instance allowing only https access. In my integration tests I'm using nightwatch to execute tests using selenium.
## Expected Behavior

Example test:

```
client
  .url('https://mytargeturl.com')
  .waitForElementVisible('body', 5000)
  .getTitle((title) => {
    client.assert.equal(title, 'Expected title')
  })
```

If the site loads successfully it will be the expected title.
## Actual Behavior

I'll get the page title "Insecure Connection".

[This](http://stackoverflow.com/questions/38122777/firefox-insecure-channel-warning#comment63677967_38122777) comment on SO pointed out that I require a HTTPS access but the webpage itself is actually served via HTTP and firefox gives a warning for security reasons.
I wanted firefox to ignore this alert, so I found [this](http://stackoverflow.com/a/25063706/4816930) answer on SO which mentions the firefox option "accept_untrusted_certs". I've added this option to my nightwatch.json (test_settings.default.desiredCapabilitied.accept_untrusted_certs = true) - I tried camel case, too.
When I still got the "Insecure Connection" error I found out that it might be a problem of the firefox version (mentioned [here](http://stackoverflow.com/a/37868534/4816930)).
To achieve an older firefox version (currently its firefox 49 in node-firefox:3.0.0-dubnium) I switched to node-firefox:2.50.0 which uses firefox 44.

Is there anything I did wrong and the solution is easier than mine or is this the right way to open a webpage via HTTPS which serves content via HTTP .

I know this might be a problem with firefox and not selenium or webdriver but this problem was so hard to solve and maybe someone else runs into the some problem.

**Comment by kaplich** [comment] 2016-10-20 02:25
+1
We are experiencing the same issue with the latest Selenium Docker image.

**Comment by davehunt** [comment] 2016-10-20 09:12
See https://github.com/mozilla/geckodriver/issues/93 - if you need to run against sites with self-signed certificates then you may need to use the previous release until support for ignoring such security warnings lands in Marionette/GeckoDriver.

**Comment by kaplich** [comment] 2016-10-20 18:48
@davehunt 
Thank you for the reply.
Rolling back to 2.53.1-beryllium helped.

**Comment by sixinli** [comment] 2017-01-05 06:37
+1, have to be back on 2.53.1 because of self cert issue in firefox too :(

**Comment by ddavison** [comment] 2017-01-08 06:55
so it looks like Firefox 52 and 53 have this enabled?  am i correct by what i read from that bugzilla issue, @davehunt ?

**Comment by davehunt** [comment] 2017-01-09 10:26
@ddavison that's correct, from Firefox 52, users are able to set an additional [capability](https://github.com/mozilla/geckodriver#webdriver-capabilities) to accept insecure certificates.

**Comment by diemol** [comment] 2017-06-25 17:51
@sixinli @kaplich @Chaoste, the most recent image already has Firefox 53. 

Could you please try again to use the additional capability and report back to see how it went?

**Comment by sixinli** [comment] 2017-06-27 17:58
confirmed that it works! thanks!

**Comment by sixinli** [comment] 2017-06-27 17:58
confirmed that it works! thanks!

**Comment by ddavison** [comment] 2017-06-27 18:12
great news!  closing

**Closed by ddavison** 2017-06-27 18:12 UTC

**Comment by joaquimpedrooliveira** [comment] 2017-06-29 14:39
@sixinli @diemol, could you please share how to correctly set these capabilities in `docker run` command?

**Comment by ddavison** [comment] 2017-06-29 16:23
@joaoluizjoaquim no specific command to run to fix this.. it's just using the correct version.  if you use latest, you're certainly covered.  [the commit](https://github.com/SeleniumHQ/docker-selenium/commit/30b3c9160aabe32c6932d1ec7d19497f7fd6ebdd#diff-79a170fb54c3005e51ce1510022006be) was introduced in 3.4.0-bismuth.   therefore,

versions >= 3.4.0-bismuth will work.

**Comment by joaquimpedrooliveira** [comment] 2017-06-29 19:16
I still get `"error": "insecure certificate",` using `3.4.0-bismuth`. Maybe I'm missing something else.

**Comment by ddavison** [comment] 2017-06-29 19:47
try the latest image (dysprosium)

**Comment by joaquimpedrooliveira** [comment] 2017-06-29 20:07
@ddavison , with the latest it seems to work. I've got another error message, but I think it's related to a geckodriver bug. After `driver.quit()` I get:
```console
org.openqa.selenium.WebDriverException: Tried to run command without establishing a connection
```
Thank you anyway :+1:

**Comment by Krzysiaczek-at-theFoundry** [comment] 2017-07-10 14:56
I've got exactly the same problem with the recent version which was released 10 days ago. I will try dysprosium.

**Comment by Krzysiaczek-at-theFoundry** [comment] 2017-07-10 15:11
I've just tried earlier version:
REPOSITORY                                        TAG                          CREATED              SIZE
selenium/standalone-firefox-debug   3.4.0-dysprosium   4 weeks ago         685MB

Results from the Behat:
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
      System info: host: '84aaa2dfcb3c', ip: '172.18.0.5', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.31-moby', java.version: '1.8.0_131'
      Driver info: org.openqa.selenium.firefox.FirefoxDriver
      Capabilities [{moz:profile=/tmp/rust_mozprofile.BjRAApBCv8HQ, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=53.0, platformVersion=4.9.31-moby, moz:processID=87.0, browserName=firefox, javascriptEnabled=true, platformName=linux}]

Is it possible to setup this option either in Behat or Docker file - ideally in docker-compose.yml?
