### ISSUE TITLE
No active session with ID [session ID]

### ISSUE THREAD

**Issue by yippeykeiyay** [SeleniumHQ/docker-selenium#781] opened 2018-09-10 09:57 UTC
## Meta -
Image(s):  
standalone-chrome

Docker-Selenium Image Version(s):  
3.14.0-dubnium

Docker Version:  
18.06.1-ce, build e68fc7a

OS: 
Ubuntu 16.04

## Expected Behavior -
When running a test we expect Selenium to interact with a website over a number of pages and report on the success/failure of the interactions as we go. We have written a 'wrapper' application that handles running and reporting on the tests which uses WebDriver to communicate with Selenium as it goes. The Docker container is stopped, started and 'cleaned' at the start and end of every test.

## Actual Behaviour -
On the latest version (3.14.0-dubium) we were encountering an error where we believe Selenium was 'loosing' its current session and therefore wasn't able to be communicated with from WebDriver. We were receiving this error when running WebDriver commands:
`No active session with ID [session ID]`

## Steps to reproduce -
In our use case we run roughly 60-70 tests per hour per server (roughly 20 servers) almost 24/7/365. Some of the tests just hit one page and others navigate around the target website running many actions per page. 

When we upgraded to the latest release we started receiving the mentioned error very frequently, usually on longer tests that were navigating over more than one page. It effected all servers and after rebooting we wouldn't see the error for around 10-20 minutes and then it would start occurring again. Because of this and the high-use of our use case its very difficult to reproduce this issue.

I know this is vague and doesn't give much info into how to reproduce the issue but I thought it worth reporting as its quite a damaging problem that I would expect other people to run into too if they run the latest version of the container. We've not seen the error on any previous versions and it stopped occurring as soon as we rolled back to 3.14.0-arsenic.

I can't say for certain if the versions between 3.14.0-arsenic and 3.14.0-dubnium also contain the issue but I _can_ say that arsenic *isn't* effected and dubnium *is*.

**Comment by diemol** [comment] 2018-09-14 16:51
Hi @yippeykeiyay,

Well, as you say, this is quite vague, and it is even more since the major changes between 3.14.0-arsenic and 3.14.0-dubnium are not related to Selenium at all, check https://github.com/SeleniumHQ/docker-selenium/releases. The changes are related to a Chrome update (upgraded to 69) and a change how Xvfb is handled. 

We would really appreciate if more details are provided, logs, and ideally a way to reproduce this.

**Comment by yippeykeiyay** [comment] 2018-09-17 13:44
Hi @diemol,

Yep, I appreciate that the changes aren't in Selenium so I wondered if the new Chrome version might be the problem?

I'll try and get some logs for you but unfortunately this might be tricky for me to do. Again, I fully realise how unhelpful I'm being! If nobody else is reporting this then I'm happy for this issue to be closed, I just thought it worthwhile documenting incase it crops up for others.

**Comment by diemol** [comment] 2018-09-20 11:04
@yippeykeiyay I cannot really say what the issue could be without having more data.

To be honest, I haven't seen anything similar yet, so I will close this issue. But if you find more detailed information and a way to reproduce it, please don't doubt to create a new issue or reopen this one. Thanks.

**Closed by diemol** 2018-09-20 11:04 UTC
Labels: R-awaiting-answer
