### ISSUE TITLE
Error "KeyError: 'value'" when executing over 'opera' and 'edge' containers

### ISSUE THREAD

**Issue by diegoquirino** [SeleniumHQ/docker-selenium#1219] opened 2021-02-23 12:59 UTC
## 🐛 Bug Report

When I execute robotframework script to 'opera' or 'edge' runing containers, error "KeyError: 'value'" is shown. With the same script, 'firefox' and 'chrome' runing containers works perfectly.

## To Reproduce

1. Create grid: `docker network create 20210223092457_grid`
2. Run container (edge or opera): `docker run -d -p 4444:4444 -p 6900:5900 --net 20210223092457_grid --name selenium -v /dev/shm:/dev/shm selenium/standalone-opera:4.0.0-beta-1-20210215`
3. Run robot test script: `robot --outputdir output *.robot`

## Expected behavior

It is expected test runs and pass by opening google.com website in the browser.

## Test script reproducing this issue (when applicable)

GitHub project: https://gitlab.com/diegoquirino/robot-edge.git
**Change browser using *locators.py* BROWSER variable and run *main.py* file.**

## Environment

OS: Windows 10
Docker-Selenium image version: 4.0.0-beta-1-20210215
Docker version: 20.10.2
Exact Docker command to start the containers:

- docker run -d -p 4444:4444 -p 6900:5900 --net 20210223092457_grid --name selenium -v /dev/shm:/dev/shm selenium/standalone-opera:4.0.0-beta-1-20210215

**Comment by PuppetA17** [comment] 2021-02-26 08:10
I have the same problem, have you found the solution？

**Comment by diegoquirino** [comment] 2021-02-26 20:40
> I have the same problem, have you found the solution？

Not yet. sorry!

**Comment by diemol** [comment] 2021-03-01 22:23
Could you please provide a way to reproduce this with Selenium WebDriver? I am not a robotframework user so I cannot dig into it.

In the meantime, also providing the docker containers logs can be useful to diagnose the issue.

**Comment by domibarton** [comment] 2021-03-12 23:58
> Could you please provide a way to reproduce this with Selenium WebDriver? I am not a robotframework user so I cannot dig into it.
> 
> In the meantime, also providing the docker containers logs can be useful to diagnose the issue.

There you go:

```python
from selenium.webdriver import Remote
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


driver = Remote(desired_capabilities=DesiredCapabilities.OPERA)
driver.get('https://www.selenium.dev/')
driver.close()
```

It results in (only for `DesiredCapabilities.OPERA` & `DesiredCapabilities.EDGE`:

```
Traceback (most recent call last):
  File "/tmp/selenium-error/tests/test.py", line 52, in <module>
    driver = Remote(desired_capabilities=DesiredCapabilities.OPERA)
  File "/tmp/selenium-error/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/tmp/selenium-error/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/tmp/selenium-error/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/tmp/selenium-error/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 127, in check_response
    value = value['value']
```

**Comment by diemol** [comment] 2021-03-13 00:01
What version of the Python bindings are you using? Could you please share the logs of the docker containers as well?

**Comment by domibarton** [comment] 2021-03-13 00:01
Btw I'm using the official grid/node Docker images. Here's my docker compose:

```yaml
---
version: '3.8'

services:

  chrome:
    image: selenium/node-chrome:4.0.0-beta-2-prerelease-20210312
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - '5901:5900'

  firefox:
    image: selenium/node-firefox:4.0.0-beta-2-prerelease-20210312
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - '5902:5900'

  edge:
    image: selenium/node-edge:4.0.0-beta-2-prerelease-20210312
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - '5903:5900'

  opera:
    image: selenium/node-opera:4.0.0-beta-2-prerelease-20210312
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - '5904:5900'

  selenium-hub:
    image: selenium/hub:4.0.0-beta-2-prerelease-20210312
    container_name: selenium-hub
    ports:
      - '4442:4442'
      - '4443:4443'
      - '4444:4444'
```

**Comment by domibarton** [comment] 2021-03-13 00:02
Logs after running the Python code above:

```
selenium-hub    | 00:02:08.829 INFO [Distributor.newSession] - Session request received by the distributor:
selenium-hub    |  {
selenium-hub    |   "desiredCapabilities": {
selenium-hub    |     "browserName": "opera",
selenium-hub    |     "version": "",
selenium-hub    |     "platform": "ANY"
selenium-hub    |   },
selenium-hub    |   "capabilities": {
selenium-hub    |     "firstMatch": [
selenium-hub    |       {
selenium-hub    |         "browserName": "opera"
selenium-hub    |       },
selenium-hub    |       {
selenium-hub    |         "browserName": "opera",
selenium-hub    |         "platformName": "any"
selenium-hub    |       }
selenium-hub    |     ]
selenium-hub    |   }
selenium-hub    | }
selenium-hub    | 00:02:08.847 WARN [SeleniumSpanExporter$1.lambda$export$0] - {"traceId": "d09159b35ffb9ad6b1ffae03236be45b","spanId": "38eab0691ce3fd1e","spanKind": "INTERNAL","eventTime": 1615593728826504100,"eventName": "Session request received by the distributor","attributes": {"logger": "org.openqa.selenium.grid.distributor.local.LocalDistributor","request.payload": "{\n  \"desiredCapabilities\": {\n    \"browserName\": \"opera\",\n    \"version\": \"\",\n    \"platform\": \"ANY\"\n  },\n  \"capabilities\": {\n    \"firstMatch\": [\n      {\n        \"browserName\": \"opera\"\n      },\n      {\n        \"browserName\": \"opera\",\n        \"platformName\": \"any\"\n      }\n    ]\n  }\n}"}}
selenium-hub    |
selenium-hub    | 00:02:08.848 WARN [SeleniumSpanExporter$1.lambda$export$0] - {"traceId": "d09159b35ffb9ad6b1ffae03236be45b","spanId": "38eab0691ce3fd1e","spanKind": "INTERNAL","eventTime": 1615593728845762000,"eventName": "exception","attributes": {"exception.message": "Unable to create session: Could not start a new session. No Node supports the required capabilities: Capabilities {browserName: opera, version: }, Capabilities {browserName: opera}\nBuild info: version: '4.0.0-beta-2', revision: '9c138bc189'\nSystem info: host: '98ab1a410800', ip: '172.30.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.19.121-linuxkit', java.version: '1.8.0_282'\nDriver info: driver.version: unknown","exception.stacktrace": "org.openqa.selenium.SessionNotCreatedException: Could not start a new session. No Node supports the required capabilities: Capabilities {browserName: opera, version: }, Capabilities {browserName: opera}\nBuild info: version: '4.0.0-beta-2', revision: '9c138bc189'\nSystem info: host: '98ab1a410800', ip: '172.30.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.19.121-linuxkit', java.version: '1.8.0_282'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.grid.distributor.Distributor.newSession(Distributor.java:215)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest(LocalDistributor.java:416)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.run(LocalDistributor.java:389)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n","exception.type": "org.openqa.selenium.SessionNotCreatedException","logger": "org.openqa.selenium.grid.distributor.local.LocalDistributor","request.payload": "{\n  \"desiredCapabilities\": {\n    \"browserName\": \"opera\",\n    \"version\": \"\",\n    \"platform\": \"ANY\"\n  },\n  \"capabilities\": {\n    \"firstMatch\": [\n      {\n        \"browserName\": \"opera\"\n      },\n      {\n        \"browserName\": \"opera\",\n        \"platformName\": \"any\"\n      }\n    ]\n  }\n}"}}
selenium-hub    |
selenium-hub    | 00:02:08.951 WARN [SeleniumSpanExporter$1.lambda$export$0] - {"traceId": "d09159b35ffb9ad6b1ffae03236be45b","spanId": "15ddebd475b3ec14","spanKind": "INTERNAL","eventTime": 1615593728949358600,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueuer","http.host": "127.0.0.1:4444","http.method": "POST","http.request_content_length": "185","http.scheme": "HTTP","http.status_code": 500,"http.target": "\u002fsession","http.user_agent": "selenium\u002f3.141.0 (python mac)"}}
selenium-hub    |
```

**Comment by diemol** [comment] 2021-03-13 00:04
The browser name is `operablink`, not `opera`. I think there is an issue to change it but I am not sure when that will happen.

**Comment by domibarton** [comment] 2021-03-13 00:07
> The browser name is `operablink`, not `opera`. I think there is an issue to change it but I am not sure when that will happen.

Using `{'browserName': 'operablink'}` instead of `DesiredCapabilities.OPERA` works. Shouldn't `DesiredCapabilities.OPERA` be updated then?

What about `EDGE`?

**Comment by diemol** [comment] 2021-03-13 00:09
I don't know what version of the Python bindings you are using, so I am not sure if it has been updated or not. Maybe you need to create an issue in the Selenium repo for that.
About Edge, I think it is the same, you can check `http://localhost:4444/status` to see the Grid stereotype and double check the browser name for Edge.

**Comment by domibarton** [comment] 2021-03-13 00:10
I'm using `selenium==3.141.0` which is the latest version I think.

Checked the capabilities:

```
Help on class DesiredCapabilities in module selenium.webdriver.common.desired_capabilities:

class DesiredCapabilities(builtins.object)
 |  Set of default supported desired capabilities.
 |
 |  Use this as a starting point for creating a desired capabilities object for
 |  requesting remote webdrivers for connecting to selenium server or selenium grid.
 |
 |  Usage Example::
 |
 |      from selenium import webdriver
 |
 |      selenium_grid_url = "http://198.0.0.1:4444/wd/hub"
 |
 |      # Create a desired capabilities object as a starting point.
 |      capabilities = DesiredCapabilities.FIREFOX.copy()
 |      capabilities['platform'] = "WINDOWS"
 |      capabilities['version'] = "10"
 |
 |      # Instantiate an instance of Remote WebDriver with the desired capabilities.
 |      driver = webdriver.Remote(desired_capabilities=capabilities,
 |                                command_executor=selenium_grid_url)
 |
 |  Note: Always use '.copy()' on the DesiredCapabilities object to avoid the side
 |  effects of altering the Global class instance.
 |
 |  Data descriptors defined here:
 |
 |  __dict__
 |      dictionary for instance variables (if defined)
 |
 |  __weakref__
 |      list of weak references to the object (if defined)
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  ANDROID = {'browserName': 'android', 'platform': 'ANDROID', 'version':...
 |
 |  CHROME = {'browserName': 'chrome', 'platform': 'ANY', 'version': ''}
 |
 |  EDGE = {'browserName': 'MicrosoftEdge', 'platform': 'WINDOWS', 'versio...
 |
 |  FIREFOX = {'acceptInsecureCerts': True, 'browserName': 'firefox', 'mar...
 |
 |  HTMLUNIT = {'browserName': 'htmlunit', 'platform': 'ANY', 'version': '...
 |
 |  HTMLUNITWITHJS = {'browserName': 'htmlunit', 'javascriptEnabled': True...
 |
 |  INTERNETEXPLORER = {'browserName': 'internet explorer', 'platform': 'W...
 |
 |  IPAD = {'browserName': 'iPad', 'platform': 'MAC', 'version': ''}
 |
 |  IPHONE = {'browserName': 'iPhone', 'platform': 'MAC', 'version': ''}
 |
 |  OPERA = {'browserName': 'opera', 'platform': 'ANY', 'version': ''}
 |
 |  PHANTOMJS = {'browserName': 'phantomjs', 'javascriptEnabled': True, 'p...
 |
 |  SAFARI = {'browserName': 'safari', 'platform': 'MAC', 'version': ''}
 |
 |  WEBKITGTK = {'browserName': 'MiniBrowser', 'platform': 'ANY', 'version...
```

**Comment by diemol** [comment] 2021-03-13 00:14
Seems that the Python bindings need to update the browser names. Could you please create an issue in the Selenium repo? I will close this one since it is an issue in the bindings and not in the docker images. Thank you for providing the logs to identify the issue.

**Closed as completed by diemol** 2021-03-13 00:14 UTC
Labels: R-awaiting-answer

**Comment by domibarton** [comment] 2021-03-13 00:16
# WORKAROUND

## Problem

As @diemol helped to point out, the browser names of the Selenium grid node Docker images / containers don't match the browser names of the `selenium.webdriver.common.desired_capabilities` module (at least for `EDGE` & `OPERA`).

## Workaround

Instead of using `selenium.webdriver.common.desired_capabilities.EDGE` & `selenium.webdriver.common.desired_capabilities.OPERA`, use the following desired capabilities:

```python
edge = {'browserName': 'MicrosoftEdge'}
opera = {'browserName': 'operablink'}
```

Or use the existing desired capabilties constants and update the browser names:

```python
edge = selenium.webdriver.common.desired_capabilities.EDGE
edge['browserName'] = 'MicrosoftEdge'

opera = selenium.webdriver.common.desired_capabilities.OPERA
opera['browserName'] = 'operablink'
```

**Comment by diemol** [comment] 2021-03-15 20:46
If you use Selenium 4, those workarounds are not needed.

**Comment by sathish804** [comment] 2021-07-05 10:36
Hi,

I am also getting the similar error as below for Chrome container.

Selenium Test Case                                                    | FAIL |
KeyError: 'status'

I am using Selenium4 docker compose file and python selenium==4.0.0.a7.

below is my docker compose.

`version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.0.0-rc-1-prerelease-20210618
    volumes:
      - C:\Users\C39619\docker-videos:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6900:5900"

  chrome_video:
    image: selenium/video:ffmpeg-4.3.1-20210618
    volumes:
      - C:\Users\C39619\docker-videos:/videos
    depends_on:
      - chrome
    environment:
      - DISPLAY_CONTAINER_NAME=chrome
      - FILE_NAME=chrome_video.mp4

  selenium-hub:
    image: selenium/hub:4.0.0-rc-1-prerelease-20210618
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
`

Thanks and Regards,
Sathish.
