### ISSUE TITLE
How can i create kubernetes cluster of 4 windows VMs? What tool I need to achieve this task? 

### ISSUE THREAD

**Issue by kishan0001** [SeleniumHQ/docker-selenium#827] opened 2018-11-01 10:31 UTC

**Comment by diemol** [comment] 2018-11-01 10:36
Duplicate of #826 

This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), or join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com) where the community can help you as well.

**Closed by diemol** 2018-11-01 10:36 UTC
