### ISSUE TITLE
There is no selenium/standalone-chrome: 2.53.1

### ISSUE THREAD

**Issue by msvrtan** [SeleniumHQ/docker-selenium#273] opened 2016-09-14 14:42 UTC
Even readme suggests it: 

![screen shot 2016-09-14 at 16 39 29](https://cloud.githubusercontent.com/assets/1780572/18516678/2d225c7a-7a9a-11e6-8a8f-08db989e23f0.png)

but there is none in docker:

![screen shot 2016-09-14 at 16 41 03](https://cloud.githubusercontent.com/assets/1780572/18516680/2efc493e-7a9a-11e6-80c8-da5750cd9add.png)

**Comment by bhaku** [comment] 2016-09-16 09:53
Duplicate of https://github.com/SeleniumHQ/docker-selenium/issues/272

**Comment by ddavison** [comment] 2016-09-30 06:17
this image was published today

**Closed by ddavison** 2016-09-30 06:17 UTC
