### ISSUE TITLE
Dynamic Grid can be passed in the max number of managed sessions

### ISSUE THREAD

**Issue by theddub** [SeleniumHQ/docker-selenium#1340] opened 2021-07-16 17:41 UTC
## 🚀 Feature Proposal

A clear and concise description of what the feature is.

So the Dynamic Grid spins up a number of sessions dynamically based on the number of available processors:

For example, using Docker Desktop with WSL2 on my local machine I get:
IE: "[NodeOptions.getSessionFactories] - Detected 4 available processors" thus spins up 4 sessions
It would be nice if we could pass in a max number of sessions in case we don't want to use *all* available processors for the dynamic grid for the selenium "hub". 

## Motivation

So the Dynamic Grid spins up a number of sessions dynamically based on the number of available processors:

IE: "[NodeOptions.getSessionFactories] - Detected 4 available processors" thus spins up 4 sessions
It would be nice if we could pass in a max number of sessions in case we don't want to use *all* available processors for the dynamic grid for the selenium "hub". 

This is in case we want to limit the number of processors used as a resource. This is because besides the dynamic allocation, the Dynamic Grid feature is nice to manage the hub and sessions sent to be requested especially for a "standalone", or otherwise, scenario that could be used in a CI/CD sense. As the Dynamic Grid also reuses the sessions allocated in a nice managed way.

## Example

Example command from your tutorial or GitHub repo:

docker run --rm --name selenium-docker -p 4444:4444 \
    -v ${PWD}/config.toml:/opt/bin/config.toml \
    -v /path/on/your/host/machine:/opt/selenium/assets \
    selenium/standalone-docker:4.0.0-rc-1-prerelease-20210713

I would just put the max number of sessions and the manual override number of sessions in the config.toml configuration like:

[docker]
max-number-of-sessions = 2

**Comment by diemol** [comment] 2021-07-28 21:03
This is fixed by the linked PR and I will close this because it is a duplicate of https://github.com/SeleniumHQ/selenium/issues/9660. 

When the PR is merged, we will do a pre-release a few days after.

**Closed as completed by diemol** 2021-07-28 21:03 UTC
