### ISSUE TITLE
selenium/standalone-chrome:3.7.1-beryllium inconsistent start

### ISSUE THREAD

**Issue by phuongnd08** [SeleniumHQ/docker-selenium#618] opened 2017-11-24 00:32 UTC
We use selenium/standalone-chrome:3.7.1-beryllium on Circle to run some test. The container starts most of the time but randomly failed the other time. Please advice on how to debug this issue (or advice about a version that consistently starts. We don't mind an outdated browser)

## Meta -
Image(s):  
<img width="605" alt="screen shot 2017-11-24 at 7 29 36 am" src="https://user-images.githubusercontent.com/184037/33191201-531cdfbc-d0e9-11e7-8bf4-48aa88f649c7.png">

Docker-Selenium Image Version(s):  
selenium/standalone-chrome:3.7.1-beryllium
Docker Version:  
Not sure, default Circle CI provided version
OS: 
Linux

## Expected Behavior -
The container launch consistently
## Actual Behavior -
The container fail randomly (1 out of 10 times)

**Comment by diemol** [comment] 2017-11-24 08:13
Hi @phuongnd08,

Can you please share the command you used to start the containers?

**Comment by phuongnd08** [comment] 2017-11-24 11:25
We are using default command (the entry)

**Comment by diemol** [comment] 2017-11-24 13:18
Oh, I was looking for something more specific, to see the `docker run...` command being used.

Also, taking the [comment](https://github.com/SeleniumHQ/docker-selenium/pull/619#issuecomment-346807718) from #619
>I already did this. Though I would like to think having such change will make it easier for people to report and diagnose the issue (which can come in a variety of forms)

I understand that you created an image based on the Standalone and modified it to look like:
```sh
xvfb-run -e /dev/stdout -n $SERVERNUM --server-args="-screen 0 $GEOMETRY -ac +extension RANDR" \
    java ${JAVA_OPTS} -jar /opt/selenium/selenium-server-standalone.jar \		    java ${JAVA_OPTS} -jar /opt/selenium/selenium-server-standalone.jar \
    ${SE_OPTS} &		    ${SE_OPTS} &
```

Did you get enough output that helps to find the cause why the `Xvfb failed to start` happens?

**Comment by phuongnd08** [comment] 2017-11-25 02:42
After adding such params we have yet to observe the issue again. Will report if it happen.

**Comment by phuongnd08** [comment] 2017-11-25 03:47
Okay, with that command all we get is this: 
```
xvfb-run: error: Xvfb failed to start

Exited with code 1
```
Do you have recommend on a flag that would dump more the error?
The command to run is `docker run -it standalone-chrome:3.7.1-beryllium` (just a guess because we declare the image and CircleCI 2.0 execute it).

**Comment by diemol** [comment] 2017-11-28 07:53
I think the flag `-e` should give you the information you need. But keep in mind that the output is sent to a file, not to console. Check http://manpages.ubuntu.com/manpages/xenial/man1/xvfb-run.1.html

Most of the time, that error means that the display was not available. But in the end we can only know it when you analyse the output in the error file after adding `-e`.

I have never used CircleCI 2.0, so I cannot really advise there.

**Comment by diemol** [comment] 2017-12-06 21:09
I'll close this issue since there is not really an action item to do. If you still have problems, feel free to reopen and please provide more detailed information so we can help to solve them.

**Closed by diemol** 2017-12-06 21:09 UTC
Labels: R-awaiting-answer

**Comment by yasaichi** [comment] 2018-04-06 07:18
@phuongnd08
Perhaps you use `-browsers` image for the primary container?
If so, you use the image without `-browsers`, for instance `circleci/ruby:2.4.2-node`.
