### ISSUE TITLE
get(URL ) and getCurrentUrl() timing out in 5 milliseconds

### ISSUE THREAD

**Issue by vikramvi** [SeleniumHQ/docker-selenium#111] opened 2015-10-15 07:21 UTC
get(URL ) and getCurrentUrl() works perfectly on local setup but on docker node it gets timed out in < 8 milliseconds , consistently

org.openqa.selenium.WebDriverException: Build info: version: '2.48.1', revision: 'd80083d', time: '2015-10-08 21:11:00'
System info: host: '5eadacfb1db0', ip: '172.17.0.78', os.name: 'Linux', os.arch: 'amd64', os.version: '4.0.9-boot2docker', java.version: '1.8.0_45-internal'
Driver info: driver.version: unknown
Command duration or timeout: 7 milliseconds
Build info: version: '2.47.1', revision: 'unknown', time: '2015-07-30 11:02:44'
System info: host: '6wbuildbot.local', ip: '10.40.6.185', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.5', java.version: '1.8.0_05'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={userDataDir=/tmp/.com.google.Chrome.vPoQzj}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=45.0.2454.101, platform=LINUX, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, webdriver.remote.sessionid=6df2a63d-df8c-42f9-9189-c2ca40a479a8, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 6df2a63d-df8c-42f9-9189-c2ca40a479a8  
at sun.reflect.GeneratedConstructorAccessor39.newInstance(Unknown Source)  
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) 
at java.lang.reflect.Constructor.newInstance(Constructor.java:408)  
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)  
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158) 
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:595) 
at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:306) 
at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source) 
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  
at java.lang.reflect.Method.invoke(Method.java:483) 
at org.openqa.selenium.remote.Augmenter$CompoundHandler.intercept(Augmenter.java:191)  
at org.openqa.selenium.remote.RemoteWebDriver$$EnhancerByCGLIB$$fa84a442.get(<generated>)   

org.openqa.selenium.WebDriverException: Build info: version: '2.48.1', revision: 'd80083d', time: '2015-10-08 21:11:00'
System info: host: '5eadacfb1db0', ip: '172.17.0.78', os.name: 'Linux', os.arch: 'amd64', os.version: '4.0.9-boot2docker', java.version: '1.8.0_45-internal'
Driver info: driver.version: unknown
Command duration or timeout: 7 milliseconds
Build info: version: '2.47.1', revision: 'unknown', time: '2015-07-30 11:02:44'
System info: host: '6wbuildbot.local', ip: '10.40.6.185', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.5', java.version: '1.8.0_05'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={userDataDir=/tmp/.com.google.Chrome.vPoQzj}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=45.0.2454.101, platform=LINUX, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, webdriver.remote.sessionid=6df2a63d-df8c-42f9-9189-c2ca40a479a8, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 6df2a63d-df8c-42f9-9189-c2ca40a479a8  
at sun.reflect.GeneratedConstructorAccessor39.newInstance(Unknown Source)  
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) 
at java.lang.reflect.Constructor.newInstance(Constructor.java:408)  
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)  
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158) 
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:595) 
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:618) 
at org.openqa.selenium.remote.RemoteWebDriver.getCurrentUrl(RemoteWebDriver.java:316)  
at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)  
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  
at java.lang.reflect.Method.invoke(Method.java:483) at org.openqa.selenium.remote.Augmenter$CompoundHandler.intercept(Augmenter.java:191)

**Comment by vikramvi** [comment] 2015-10-16 14:39
https://code.google.com/p/selenium/issues/detail?id=4566

**Comment by diemol** [comment] 2017-05-09 12:04
Hi @vikramvi!

Is this still an issue? If so, can you please provide some environment details and code to reproduce it?

Thank!

**Comment by diemol** [comment] 2017-07-09 17:28
I'll close this issue since we didn't get feedback from the OP. Feel free to reopen when more accurate info is provided.

**Closed by diemol** 2017-07-09 17:28 UTC
