### ISSUE TITLE
[🐛 Bug]: org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException during parallel running

### ISSUE THREAD

**Issue by MartinBruska** [SeleniumHQ/docker-selenium#1632] opened 2022-07-14 06:20 UTC
### What happened?

We are getting exception `java.util.concurrent.TimeoutException` during parallel execution. The exception is thrown randomly on different tests scenarios each execution, we did not find any pattern for that. The exception is thrown on different selenium actions(findElement, click, select, webdriverWait). We did not have any issues with the same setup with selenium/selenium grid 3

### Command used to start Selenium Grid with Docker

```shell
docker-compose -f docker-compose-execution.yml up --scale chrome-node=10 --exit-code-from specifications-execution

version: '3.0'
services:

  specifications-execution:
    image: gauge image from our nexus server
    command: bash gauge_execution.sh
    working_dir: /specs
    volumes:
      - .:/specs
    depends_on:
      - chrome-node
#        condition: service_healthy
    env_file:
      - secret-environmental-vars.env
    environment:
      - GAUGE_DIRECTORY
      - GAUGE_ENV
      - GAUGE_SPECS_DIR
      - GAUGE_TAGS
      - GAUGE_PARALLEL_NODES
      - TELEPHONY_BOT_ENABLED
      - FIVE9_CHROME_EXT_UPDATE_URL
      - STACK
      - TZ="America/New_York"

  chrome-node:
    image: selenium/node-chrome:4.3.0-20220706
    shm_size: 2gb
    depends_on:
      "selenium-hub":
        condition: service_healthy
      "mock-server":
        condition: service_healthy
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=false
      - SE_NODE_MAX_SESSIONS=10
      - TZ="America/New_York"
      - JAVA_OPTS=-Dselenium.LOGGER.level=SEVERE -Dwebdriver.chrome.whitelistedIps=

  selenium-hub:
    image: selenium/hub:4.3.0-20220706
    depends_on:
      - mock-server
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    environment:
      - TZ="America/New_York"
      - JAVA_OPTS=-Dselenium.LOGGER.level=SEVERE
    healthcheck:
      test: [ "CMD", "wget", "-O", "-", "http://localhost:4444/status" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mock-server:
    image: mockserver image from our nexus server
    ports:
      - "1080"
    environment:
      - MOCKSERVER_LIVENESS_HTTP_GET_PATH=/healthcheck
      - LOG_LEVEL=WARN
    healthcheck:
      test: [ "CMD", "wget", "-O", "-", "http://localhost:1080/healthcheck" ]
      interval: 10s
      timeout: 5s
```

### Relevant log output

```shell
org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException
Build info: version: '4.3.0', revision: 'a4995e2c09*'
System info: host: '0e2d7e030e43', ip: '172.17.43.5', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1080-aws', java.version: '11.0.14.1'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [1a55d275336d23295f03435a940db1cd, clickElement {id=f72f93d0-5a30-472b-a66f-eb44146cb5ac}]
Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 103.0.5060.114, chrome: {chromedriverVersion: 103.0.5060.53 (a1711811edd7..., userDataDir: /tmp/.com.google.Chrome.HobzoG}, goog:chromeOptions: {debuggerAddress: localhost:37863}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: LINUX, proxy: Proxy(), se:cdp: ws://172.17.43.4:4444/sessi..., se:cdpVersion: 103.0.5060.114, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: ignore, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Element: [[RemoteWebDriver: chrome on LINUX (1a55d275336d23295f03435a940db1cd)] -> id: oneOrMoreLeads1]
Session ID: 1a55d275336d23295f03435a940db1cd

org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:65)
org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:49)
org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:98)
org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55)
org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:181)
org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)
org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:569)
org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:257)
org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:78)
com.norvax.specifications.utils.elements.ElementAction.checkOrUncheckCheckbox(ElementAction.kt:118)
com.norvax.specifications.affiliatesmanagement.AffiliatesManagement.selectAffiliate(AffiliatesManagement.kt:797)
com.norvax.specifications.affiliatesmanagement.AffiliatesManagement.selectAffiliateFromReport(AffiliatesManagement.kt:242)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:566)
com.thoughtworks.gauge.execution.MethodExecutor.execute(MethodExecutor.java:28)
com.thoughtworks.gauge.execution.StepExecutionStage.executeStepMethod(StepExecutionStage.java:66)
com.thoughtworks.gauge.execution.StepExecutionStage.executeStep(StepExecutionStage.java:59)
com.thoughtworks.gauge.execution.StepExecutionStage.execute(StepExecutionStage.java:41)
com.thoughtworks.gauge.execution.AbstractExecutionStage.executeNext(AbstractExecutionStage.java:14)
com.thoughtworks.gauge.execution.HookExecutionStage.execute(HookExecutionStage.java:33)
com.thoughtworks.gauge.execution.ExecutionPipeline.start(ExecutionPipeline.java:19)
com.thoughtworks.gauge.processor.ExecuteStepProcessor.process(ExecuteStepProcessor.java:44)
com.thoughtworks.gauge.RunnerServiceHandler.lambda$executeStep$7(RunnerServiceHandler.java:166)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
java.base/java.lang.Thread.run(Thread.java:829)
```

### Operating System

os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1080-aws'

### Docker Selenium version (tag)

4.3.0

**Comment by HemanthRajaSudhakar** [comment] 2022-07-15 15:18
Even I am facing the same issue, fix for this asap will be appreciated

**Comment by diemol** [comment] 2022-08-01 08:57
Do you have tests I can use to reproduce this issue?

**Comment by HemanthRajaSudhakar** [comment] 2022-08-02 15:35
@diemol 
This java.util.concurrent.TimeoutException, seems to be happening for a long run (>4 versions are exhibiting this behavior I guess)
Please have a look over this issue thread still which is open
[https://github.com/SeleniumHQ/selenium/issues/9528] where peoples have mentioned the simple test cases to reproduce the issue

**Comment by diemol** [comment] 2022-08-03 07:53
OK, then I will close this and at some point we will get to solve the linked issue.

**Closed as completed by diemol** 2022-08-03 07:53 UTC
Labels: R-awaiting-answer
