### ISSUE TITLE
[🚀 Feature]: Provide SE_EVENT_BUS_HOST DNS name instead of only IP

### ISSUE THREAD

**Issue by jkostrhun** [SeleniumHQ/docker-selenium#1510] opened 2022-02-15 10:53 UTC
### Feature and motivation

When running Selenium Grid 4 in AWS ECS Fargate will be better if SE_EVENT_BUS_HOST on browser node can consume DNS name of HUB (load balancer) instead of IP, like in previous version of Grid (3) using HUB_PORT_4444_TCP_ADDR environment variable (which can consume DNS name).

Main purpose is creating task definitions in CDK (we don't have IP available in that step, only DNS name of load balancer), also now we have to change IP address in SE_EVENT_BUS_HOST everytime we reset HUB service, with DNS name we don't need to change it, because DNS name of LB is still same.

### Usage example

Currently we have to set: SE_EVENT_BUS_HOST=10.0.167.224

Will be better to set it with DNS name: SE_EVENT_BUS_HOST=selenium-hub-1234.us-east-1.elb.amazonaws.com

**Comment by diemol** [comment] 2022-02-15 10:56
You are free to do it, the `HOST` can be either an IP or the DNS name.

**Comment by jkostrhun** [comment] 2022-02-15 11:05
Thanks for answering! Then it looks like it's something wrong (maybe in networking on my side), when I provide DNS name of hub to browser node, then browser node is trying to send registration events to hub, but it's not registred (only when I provide IP).

Is there something extra that I need to provide to browser node? I'm setting:
SE_EVENT_BUS_HOST
SE_EVENT_BUS_PUBLISH_PORT
SE_EVENT_BUS_SUBSCRIBE_PORT

**Comment by jkostrhun** [comment] 2022-02-15 11:11
It's strange because when I tried to run 3.141.59 on same cluster (only with variable for that version) providing DNS name in HUB_PORT_4444_TCP_ADDR was OK and browser node was correctly registred to hub.

**Comment by diemol** [comment] 2022-02-20 00:32
If it works with an IP and not with the DNS name there should be a configuration missing in the DNS.

In Grid 4, the Node registers to the Hub via the Event Bus, which is why the publish and subscribe port need to be accessible from the Node.

Grid 3 is a bit more straightforward because there is no Event Bus.

**Comment by diemol** [comment] 2022-03-12 01:00
Closing as there was no more activity.

**Closed as completed by diemol** 2022-03-12 01:00 UTC
Labels: R-awaiting-answer

**Comment by rpcarleto** [comment] 2022-03-29 17:53
Happen to me the same. I'm sure that loadbalance working as expected. 

![image](https://user-images.githubusercontent.com/8861070/160673995-89e98170-d13e-4a20-b4b7-bccbe559bef3.png)

I open ports 4442-4445

SE_EVENT_BUS_HOST: internal-lb- ....

If I set IP works fine.

**Comment by illusive-ch** [comment] 2022-05-27 22:39
@rpcarleto @jkostrhun were you ever able to get this working? It works fine if I use the fargate task private IP address however the when i use the dns hostname of the load balancer it fails to register.

**Comment by rpcarleto** [comment] 2022-08-27 19:58
> 

Hey @illusive-ch same to me. I tried set a loadbalancer internal, but the problem is the same. I'm sure that loadbalancer do its job on port 4444, Maybe in two week I will come back on this subject.

**Comment by 0xhitesh-91** [comment] 2022-08-30 07:39
I am also having the same problem in AWS Fargate, kindly drop information if anybody found any workaround.

Thank you

**Comment by melnikoved** [comment] 2023-03-01 21:52
I have the same issue, tried several configurations and could not find a solution. It works only with IP address
