### ISSUE TITLE
[🐛 Bug]: Firefox Blank or White Screen in OpenShift Container Platform [devsandbox]

### ISSUE THREAD

**Issue by jayaraj007007** [SeleniumHQ/docker-selenium#1786] opened 2023-02-09 11:24 UTC
### What happened?

I'm trying to deploy seleniumgrid 4 in Openshift Container Platform using devSandbox account. I created application using standalone firefox image and tried to open firefox browser using vnc, but the firefox is not showing default home screen or any response. even I tried to open any url its not loading.
 
I'm not facing the same issue in Chrome or Edge Browsers.

![Screenshot_20230209_011235](https://user-images.githubusercontent.com/24728032/217753380-6ce623dd-ada3-49f2-b14e-f4f57ac77f37.png)

Tried with VNC:.
Open Bash Terminal --> Firefox --> White page is opening [If I tried to access any website its not responding still its black]

![image](https://user-images.githubusercontent.com/24728032/217803646-d11aaaaf-7371-45f8-92e4-dd376b29d338.png)

Pod logs : 
[standalone-firefox-3-5xrbd-standalone-firefox.log](https://github.com/SeleniumHQ/docker-selenium/files/10694773/standalone-firefox-3-5xrbd-standalone-firefox.log)

### Command used to start Selenium Grid with Docker

```shell
Used following deployment config to create Standalone Firefox.
kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: standalone-firefox
  labels:
    app: standalone-firefox
spec:
  replicas: 1
  selector:
    app: standalone-firefox
  template:
    metadata:
      labels:
        app: standalone-firefox
        deploymentconfig: standalone-firefox
    spec:
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: standalone-firefox
          env:
            - name: SE_OPTS
              value: '--log-level FINE'
          ports:
            - containerPort: 4444
              protocol: TCP
            - containerPort: 5900
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
          terminationMessagePolicy: File
          image: selenium/standalone-firefox
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
```

### Relevant log output

```shell
Error from webclient : 
C:\Users\###############\Documents\MyPrograms\OpenShift-Files\test-py.py:10: DeprecationWarning: desired_capabilities has been deprecated, please pass in an Options object with options kwarg
  driver = webdriver.Remote(
Traceback (most recent call last):
  File "C:\Users\###############\Documents\MyPrograms\OpenShift-Files\test-py.py", line 23, in <module>
    print(driver.title)
  File "C:\Program Files\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 453, in title
    resp = self.execute(Command.GET_TITLE)
  File "C:\Program Files\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Failed to decode response from marionette


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\###############\Documents\MyPrograms\OpenShift-Files\test-py.py", line 25, in <module>
    driver.quit()
  File "C:\Program Files\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 955, in quit
    self.execute(Command.QUIT)
  File "C:\Program Files\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: Tried to run command without establishing a connection
```

### Operating System

OpenShift - Kubernetes Environement

### Docker Selenium version (tag)

109.0-20230202

**Comment by diemol** [comment] 2023-02-11 21:30
I do not understand how you are opening Firefox. What do you mean by "tried to open firefox browser using vnc"?

**Comment by jayaraj007007** [comment] 2023-02-12 02:48
> I do not understand how you are opening Firefox. What do you mean by "tried to open firefox browser using vnc"?

Please find the steps below.
- Expose 7900 port 
- Connect through VNC 
- Mouse right click --> Applications --> Shells -> Bash 
-  type firefox 

![Screenshot_2023-02-12-08-16-37-607-edit_com.android.chrome.jpg](https://user-images.githubusercontent.com/24728032/218290086-84617e73-7fb4-40ad-b8fa-b21f072d366c.jpg)

![217803646-d11aaaaf-7371-45f8-92e4-dd376b29d338.png](https://user-images.githubusercontent.com/24728032/218290166-9412814c-bd97-4163-876e-6e74d7284adb.png)

**Comment by diemol** [comment] 2023-02-12 09:41
I see in the image it works as expected, Firefox is opening. Not sure what the issue is?

**Comment by jayaraj007007** [comment] 2023-02-12 10:26
firefox only showing blank/white screen. Its not showing the default home page, If I tried to open web pages it showing only blank screen only white screen its showing.


Here I attached some screenshots.
**Running In OpenShift:** NOT WORKING 
Default page is showing as blank, and after hit URL also its same.
![image](https://user-images.githubusercontent.com/24728032/218305565-ca4a6015-2335-4eb5-a58f-b89f675f513d.png)
![image](https://user-images.githubusercontent.com/24728032/218305668-816ffed8-085c-4f1d-8108-c25674212abb.png)

**Running In EKS/Docker:**
Showing Default home page and Webpages opening as expeted.
![image](https://user-images.githubusercontent.com/24728032/218305448-5144ad73-02d1-4f27-b438-37cb7f04f2c1.png)
![image](https://user-images.githubusercontent.com/24728032/218305454-bc3180e7-d159-4bc9-ae32-b6a317fda3ce.png)

**Comment by diemol** [comment] 2023-02-12 10:30
I do not have an OpenShift environment to check this. Not sure why it works with Chrome and Edge but not Firefox. Would need to wait and see if someone can help.

**Comment by refaeli-io** [comment] 2023-02-19 17:36
@jayaraj007007 
I in the past used deployment object and not deployment config object on an OpenShift environment.
Also, looks at [selenium-helm-chart](https://github.com/SeleniumHQ/docker-selenium/blob/trunk/charts/selenium-grid/README.md) and try see if you can use it, maybe a little somethin his missing.

**Comment by frgithubaccount** [comment] 2023-03-20 11:11
I had the same issue in other circumstances.
seems to be a new security feature in openshift 4.11 or so:
in my case, it was resolved by adding following lines to the container definition in the yaml:
<code>
securityContext:
&nbsp;&nbsp;&nbsp;&nbsp; allowPrivilegeEscalation: true
 </code>
But i was warned, it might not help for future openshift versions...

**Comment by vytasra** [comment] 2023-05-23 12:17
In openshift 4.12 it goes a little bit further.

I had to create a service account which is using restricted scc (by default now it used restricted-v2):

```
oc create serviceaccount selenium -n ${NAMESPACE}
oc adm policy add-scc-to-user restricted -z selenium --as system:admin
```

In values.yaml for firefox i had to modify securityContext:


```
  securityContext:
    allowPrivilegeEscalation: true
```

and since chart does not have serviceAccount default value i had to modify **firefox-node-deployment.yaml** to use newly created service account:


```
spec:
  template:
    spec:
      serviceAccountName: selenium 
```

Hopefully it helps.

**Comment by diemol** [comment] 2023-05-25 08:35
Thanks for the hints @ShaharM7 @frgithubaccount @vytasra , then it seems to be something extra needed in OpenShift. Closing this then.

**Closed as completed by diemol** 2023-05-25 08:35 UTC
Labels: help wanted
