### ISSUE TITLE
entry_point.sh for StandaloneFirefoxDebug/Dockerfile?

### ISSUE THREAD

**Issue by dezoito** [SeleniumHQ/docker-selenium#621] opened 2017-11-27 20:35 UTC
Image(s):  
StandaloneFirefoxDebug

The Dockerfile for StandaloneFirefoxDebug references an `entry_point.sh` (to be copied to `/opt/bin/` on the guest, but no such file is present in the repo (as of commit e85be62):

```

#====================================
# Scripts to run Selenium Standalone
#====================================
COPY entry_point.sh /opt/bin/entry_point.sh
```

Am I missing something?

**Comment by barahate90** [comment] 2017-11-28 06:40
@dezoito  : this script is to run Selenium Standalone as mentioned in comment .

Please check this https://github.com/SeleniumHQ/docker-selenium/tree/master/StandaloneFirefox

here they are trying to run same "selenium Standalone ", entry point.sh is also present .

try copying this  entry_point.sh to StandaloneFirefoxDebug  ,It will give you desired result .

**Comment by diemol** [comment] 2017-11-28 15:20
Hi @dezoito,

The file is placed there before the image is built, since we use a Makefile to build all the images, you can see how it is generated [here](https://github.com/SeleniumHQ/docker-selenium/blob/master/Makefile#L66). 

So, if you do `VERSION=your_local_version make standalone_firefox_debug`, you will get an image build on your machine. 

I'll close this one since it was more a question than a real issue. If you find any problems, feel free to reopen the issue (please provide enough information to reproduce it if you need to reopen).

**Closed by diemol** 2017-11-28 15:20 UTC
