### ISSUE TITLE
Selenium Screenshots Bug

### ISSUE THREAD

**Issue by eranshahar** [SeleniumHQ/docker-selenium#749] opened 2018-06-28 15:18 UTC
Reproducing lethal selenium bug.

https://github.com/eranshahar/selenium-bug

The bug causes wrong screenshot made by the selenium. 

When you request concurrently from selenium,
to take a screenshot of different screens (different url navigated),
same screenshot returns from both urls instead of 2 unique screenshots.

This code reproduce the issue.

It sends concurrently 20 screenshots requests for 20 different urls,
And validate the output it's 20 unique screenshot,
Its run in a loop until bug occurrence.

The bug reproduces on versions 3.6.0 and above.

Please advise.

**Comment by krmahadevan** [comment] 2018-07-01 17:52
cc @diemol 

@eranshahar - That was an interesting sample for sure :)

I directly tried reproducing this issue on Selenium `3.13.0` (which is the latest released version of selenium) on a standalone hub and node (Not a docker setup since its not yet available)

I continued to run for around 18 iterations (each iteration spinning off 15 concurrent browsers) and I wasn't able to reproduce the problem. But I did crash my execution from `mvn clean test` command line though (I guess my Mac couldn't take it.. I dont blame it either.. its an old one... and there's only so much that the old guy could take.. 😄 )

Docker selenium and regular selenium are literally the same. So can you please try using Selenium standalone and see if you can reproduce the problem. My guess is that in one of the iterations, either the html page that you are constructing doesn't open up and then after that when you snap a screenshot on it, its going to be a blank which could be the reason why the test conks. Just an educated guess though!

Here's the sample that I used (an altered variant of what you used)

```java
import static org.assertj.core.api.Java6Assertions.assertThat;
import static org.assertj.core.api.Java6Assertions.fail;

import com.google.common.base.Charsets;
import java.io.File;
import java.net.URL;
import java.nio.file.Path;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.LongAdder;
import java.util.stream.IntStream;
import java.util.zip.CRC32;
import java.util.zip.Checksum;
import org.apache.commons.io.FileUtils;
import org.apache.commons.lang3.RandomStringUtils;
import org.junit.Test;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class SeleniumBugWithoutDocker {

  private static final Logger logger = LoggerFactory.getLogger(SeleniumBug.class);

  @Test
  public void reproduceSeleniumBug() throws InterruptedException {
    int cycleCounter = 1;
    while (true) {
      logger.info("Cycle number: {}", cycleCounter++);
      Map<Long, String> images = new ConcurrentHashMap<>();
      LongAdder nThreads = new LongAdder();
      String currentDir = System.getProperty("user.dir") + File.separator + "images";
      File imagesDir = new File(currentDir);
      nThreads.add(15);
      CountDownLatch countDownLatch = new CountDownLatch(nThreads.intValue());
      ExecutorService executorService = Executors.newFixedThreadPool(nThreads.intValue());
      IntStream.range(1, nThreads.intValue() + 1).forEach(i ->
          executorService.execute(() -> {
            URL htmlUrl = createHtml(i, imagesDir.toPath(), countDownLatch);
            if (htmlUrl != null) {
              try {
                URL imgUrl = createImage(htmlUrl, i, imagesDir.toPath(), images);
              }
              catch (Throwable t) {
                if (!images.values().contains(i)) {
                  logger.info("decrementing, account: {}", i);
                  nThreads.decrement();
                }
                else {
                  logger.error("Not decrementing, account: {}", i);
                }
                logger.error("Failed to create image for account: {}. images: {}", i, t, images);
              }
              finally {
                countDownLatch.countDown();
              }
            }
          }));
      if (!countDownLatch.await(40, TimeUnit.SECONDS)) {
        fail("fail");
      }
      assertThat(images).hasSize(nThreads.intValue());
    }
  }

  URL createHtml(int accountId, Path path, CountDownLatch countDownLatch) {
    try {
      String html = "<!DOCTYPE html>\n" +
          "<html lang=\"en\">\n" +
          "<head>\n" +
          "    <meta charset=\"UTF-8\">\n" +
          "    <title>Eran Shahar</title>\n" +
          "</head>\n" +
          "<body>\n" +
          "Eran Shahar %s\n" +
          "</body>\n" +
          "</html>";
      String fileName = "/" + accountId + "." + "html";
      String filePath = path.toAbsolutePath() + fileName;
      File htmlFile = new File(filePath);
      FileUtils.write(htmlFile, String.format(html, accountId + "-" + RandomStringUtils.randomAlphanumeric(accountId)), Charsets.UTF_8);
      URL urlToHtml = new File(path.toAbsolutePath() + fileName).toURI().toURL();
      logger.info("urlToHtml: {}", urlToHtml);
      return urlToHtml;
    }
    catch (Throwable e) {
      logger.error("Failed to create html.", e);
      countDownLatch.countDown();
      return null;
    }
  }

  URL createImage(URL htmlUrl, int accountId, Path path, Map images) throws Exception {
    RemoteWebDriver webDriver = null;
    try {
      String imgPath = path.toAbsolutePath() + "/" + "Image" + accountId + "." + "png";
      webDriver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), new ChromeOptions());
      webDriver.manage().timeouts().setScriptTimeout(20, TimeUnit.SECONDS)
          .pageLoadTimeout(20, TimeUnit.SECONDS).implicitlyWait(30, TimeUnit.SECONDS);
      webDriver.manage().window().setSize(new Dimension(500, 500));
      webDriver.navigate().to(htmlUrl);
      webDriver.switchTo().defaultContent();
      webDriver.manage().window().setSize(new Dimension(500, 500));
      Actions builder = new Actions(webDriver);
      builder.moveByOffset(500, 500);
      builder.perform();
      byte[] screenshotAs = webDriver.getScreenshotAs(OutputType.BYTES);
      FileUtils.writeByteArrayToFile(new File(imgPath), screenshotAs);
      URL urlToImage = new File(imgPath).toURI().toURL();
      Checksum checksum = new CRC32();
      checksum.update(screenshotAs, 0, screenshotAs.length);
      long checksumValue = checksum.getValue();
      Integer previousAccountId = (Integer) images.putIfAbsent(checksumValue, accountId);
      if (previousAccountId != null) {
        logger.info("Found the bug !!! snapshot duplication!!! previous account id: {}, accountId: {}, image path: {}, duplication image path: {}, checksum value: {}",
            previousAccountId, accountId, path.toAbsolutePath() + "/" + "Image" + previousAccountId + "." + "png", imgPath, checksumValue);
        TimeUnit.SECONDS.sleep(5);
        System.exit(1);
      }
      logger.info("Finish to generate image and copy to {}, url: {}", imgPath, urlToImage);
      return urlToImage;
    }
    finally {
      if (webDriver != null) {
        webDriver.quit();
      }
    }
  }
}
```

**Comment by ddavison** [comment] 2018-07-02 17:32
if this is reproducible on the selenium side - please migrate this issue there to the overarching project https://github.com/seleniumhq/selenium .  

closing this one.  please feel free to reference this issue when that issue has been created.

**Closed by ddavison** 2018-07-02 17:32 UTC
