### ISSUE TITLE
[🐛 Bug]: can't start sessions on standalone-firefox when using RemoteWebDriver.builder()

### ISSUE THREAD

**Issue by ObjectiveTester** [SeleniumHQ/docker-selenium#1452] opened 2021-11-16 22:33 UTC
### What happened?

I can't start a session on a standalone firefox image  when using the new Selenium 4 RemoteWebDriver.builder():

`driver = RemoteWebDriver.builder().oneOf(options).address(gridAddress).build();`

However, it launches fine when using:

`driver = new RemoteWebDriver(gridAddress, options);`

and either options work when using a docker grid such as:

 `https://github.com/SeleniumHQ/docker-selenium/blob/trunk/docker-compose-v3.yml`

### Command used to start Selenium Grid with Docker

```shell
docker run -d -p 4444:4444 --shm-size="2g" selenium/standalone-firefox:4.1.0-prerelease-20211105 

and

docker-compose up
```

### Relevant log output

```shell
Nov 16, 2021 10:29:56 PM org.openqa.selenium.remote.http.netty.NettyWebSocket lambda$new$0
WARNING: connection timed out: /172.17.0.2:4444
java.net.ConnectException: connection timed out: /172.17.0.2:4444
	at org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:179)
	at org.asynchttpclient.netty.channel.NettyChannelConnector$1.onFailure(NettyChannelConnector.java:108)
	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:28)
	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:262)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: /172.17.0.2:4444
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261)
	... 9 more

Nov 16, 2021 10:29:56 PM org.openqa.selenium.remote.http.WebSocket$Listener onError
WARNING: connection timed out: /172.17.0.2:4444
java.net.ConnectException: connection timed out: /172.17.0.2:4444
	at org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:179)
	at org.asynchttpclient.netty.channel.NettyChannelConnector$1.onFailure(NettyChannelConnector.java:108)
	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:28)
	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:262)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: /172.17.0.2:4444
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261)
	... 9 more
```

### Operating System

MacOS X 12.0.1

### Docker Selenium version (tag)

4.1.0-prerelease-20211105

**Comment by ObjectiveTester** [comment] 2021-11-17 21:57
after the initial stack trace (above), the following was displayed (sorry for not including earlier)

org.openqa.selenium.remote.http.ConnectionFailedException: 
Unable to establish websocket connection to http://172.17.0.2:4444/session/310178a0-9289-45b9-b8f3-e7d9786ab6d4/se/cdp
Build info: version: '4.0.0', revision: '3a21814679'
System info: host: 'MacBook.local', ip: 'fe80:0:0:0:45d:528d:3223:6d97%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '12.0.1', java.version: '15.0.2'
Driver info: driver.version: unknown


It appears that despite using firefox, an attempt is being made to access cdp

**Comment by diemol** [comment] 2021-12-14 15:41
This is a duplicate of #1451, and added a [note about this in the README](https://github.com/SeleniumHQ/docker-selenium#grid-url-and-session-timeout).

**Closed as completed by diemol** 2021-12-14 15:41 UTC
