### ISSUE TITLE
Selenium 2.46

### ISSUE THREAD

**Issue by chris-orchard** [SeleniumHQ/docker-selenium#66] opened 2015-06-08 08:58 UTC
Are you updating the image to 2.46 now it's out?

**Comment by elgalu** [comment] 2015-06-08 09:01
Closing as duplicate of https://github.com/SeleniumHQ/docker-selenium/pull/65

**Closed by elgalu** 2015-06-08 09:01 UTC

**Comment by chris-orchard** [comment] 2015-06-08 09:03
Sorry I searched for '2.46' not '2.46.0' so the existing issue didn't come up

**Comment by elgalu** [comment] 2015-06-08 09:05
No problem ;)
