### ISSUE TITLE
Error forwarding the request Read timed out [chrome #11-12] at WebDriverError ONLY on the last browser instance on selenium grid

### ISSUE THREAD

**Issue by jahnavi310** [SeleniumHQ/docker-selenium#298] opened 2016-10-09 19:46 UTC
I keep on running into this issue whenever the last test is being run.
We run our protractor tests on a selenium grid that is fired up via docker and kicked off whenever a commit is made.

But this is the super weird thing:
Sometimes all the tests pass flawlessly and sometimes any test that is being run on the last firefox or chrome instance just hangs and sits there and eventually throws the following error:

```
WebDriverError: Error forwarding the new session Error forwarding the request Read timed out [chrome #11-12]     at WebDriverError
```

The test is random because we have `shardTestFiles: true,` and we have `max instances` set to `10`

Also due the fact that this is being run on the grid it is impossible to figure out whether there is something wrong with the test or not, because the same test would pass if it is not the one randomly picked to run on the last browser instance. 
I am also not too sure if this is a protractor issue or a docker-selenium issue.
Is anyone else experiencing the same issue?

**Comment by ddavison** [comment] 2016-10-10 16:22
are your nodes docker containers as well?

**Comment by jahnavi310** [comment] 2016-10-10 17:13
@ddavison : yes they are

**Comment by ddavison** [comment] 2016-10-10 17:18
ok, this is most likely because you are running 10 maxinstances.. the performance of the nodes is very dependent on performance.  every time you launch a chrome browser, it takes memory.  the docker containers are very minimal, and are usually only stable for 1 max instance.

Have you tried the [step in the README.md file](https://github.com/SeleniumHQ/docker-selenium/blob/master/README.md#running-the-images) where it says you should mount shared memory?

**Comment by jahnavi310** [comment] 2016-10-10 18:03
ok, so for the time being i just changed that to one, but now this is the weird thing:
The same passes on firefox, but fails on chrome with the same error message as above, only difference being that now it isn't the last browser instance as there is only one instance and also not the last test.

**Comment by ddavison** [comment] 2016-10-12 20:13
any way that i can try and reproduce this on my end?  or can this issue be closed

**Comment by diemol** [comment] 2017-06-16 15:55
Closing this issue since we didn't get any feedback from the original poster.

**Closed by diemol** 2017-06-16 15:55 UTC
