### ISSUE TITLE
I can't load chrome user profile.

### ISSUE THREAD

**Issue by osvald0** [SeleniumHQ/docker-selenium#790] opened 2018-09-20 10:59 UTC
## Meta -

Image(s):  
selenium/hub and selenium/node-chrome

Docker-Selenium Image Version(s):  
latest

Docker Version:  
17.09.0-ce

OS: 
Debian Stretch 

## Expected Behavior -

Load chrome custom profile when running a test.

## Actual Behavior -

The execution open a new empty profile each time.

## Steps to reproduce -

1- Run grid, nodes, etc:

```
docker network create grid
docker run -d -p 4444:4444 --net grid --name selenium-hub selenium/hub
docker run --privileged -d --net grid -e HUB_HOST=selenium-hub -e NODE_MAX_INSTANCES=5 -e NODE_MAX_SESSION=5 -v /dev/shm:/dev/shm  -v /home/tbm/Profiles:/home/seluser/Profiles selenium/node-chrome
```

2- Check I can see the host folder mapped to /home/seluser/Profiles

```
docker exec b46e9fef4a61 ls /home/seluser/Profiles
```

3-Run test with the following parameters:

```javascript
 options = new chrome.Options();
 options.addArguments(`user-data-dir=/home/seluser/Profiles /myCustomProfile`);
 options.addArguments("disable-popup-blocking");
 options.addArguments("screenshot");

 driver = new webdriver.Builder()
            .forBrowser('chrome')
            .setChromeOptions(options)
            .usingServer('http://localhost:4444/wd/hub')
            .build();
```

Note:

I can load the profile using the same javascript code but running the test from the host machine.

Thanks.

**Comment by diemol** [comment] 2018-09-20 11:09
Hi @osvald0,

Could you please fill up the issue template? Without it we don't have enough information on how to reproduce and find out if it is an issue or not. Otherwise this looks more like an question rather than an issue.

**Comment by osvald0** [comment] 2018-09-20 12:46
> Hi @osvald0,
> 
> Could you please fill up the issue template? Without it we don't have enough information on how to reproduce and find out if it is an issue or not. Otherwise this looks more like an question rather than an issue.

OK, Sorry. I just updated the first message using the template. Thanks!

**Comment by diemol** [comment] 2018-09-23 13:02
@osvald0 

How did you create the profile? I just created one following the instructions they mention here:
http://chromedriver.chromium.org/capabilities
>You can create your own custom profile by just running Chrome (on the command-line or through ChromeDriver) with the user-data-dir switch set to some new directory.

For example, I am using OSX:
```
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --user-data-dir=/tmp/chrome_profiles
```
then I changed some things in the profile, like setting a home page, and the directory looks like this:

```
 diemol@Diegos-MBP  /tmp/chrome_profiles  ll                                                                                                                                                                                                                                                         ✔  10199  14:54:36
total 16512
-rw-------@  1 diemol  wheel   8.0M Sep 23 14:52 BrowserMetrics-spare.pma
drwx------@  2 diemol  wheel    64B Sep 23 14:51 CertificateRevocation
drwx------@  2 diemol  wheel    64B Sep 23 14:51 CertificateTransparency
-rw-r--r--@  1 diemol  wheel    36B Sep 23 14:51 Consent To Send Stats
drwx------@ 53 diemol  wheel   1.7K Sep 23 14:54 Default
drwx------@  2 diemol  wheel    64B Sep 23 14:51 FileTypePolicies
-rw-r--r--@  1 diemol  wheel     0B Sep 23 14:51 First Run
drwx------@  2 diemol  wheel    64B Sep 23 14:51 InterventionPolicyDatabase
-rw-------@  1 diemol  wheel    58K Sep 23 14:54 Local State
drwx------@  2 diemol  wheel    64B Sep 23 14:51 MEIPreload
drwx------@  2 diemol  wheel    64B Sep 23 14:51 NativeMessagingHosts
drwx------@  2 diemol  wheel    64B Sep 23 14:51 OriginTrials
drwx------@  2 diemol  wheel    64B Sep 23 14:51 PepperFlash
drwx------@  2 diemol  wheel    64B Sep 23 14:51 SSLErrorAssistant
drwx------@  2 diemol  wheel    64B Sep 23 14:51 Safe Browsing
drwx------@  3 diemol  wheel    96B Sep 23 14:51 ShaderCache
drwx------@  3 diemol  wheel    96B Sep 23 14:51 Subresource Filter
drwx------@  2 diemol  wheel    64B Sep 23 14:51 WidevineCdm
drwx------@  2 diemol  wheel    64B Sep 23 14:51 pnacl
```

Afterwards, I started the containers with this docker-compose file:
```
# To execute this docker-compose yml file use `docker-compose -f <file_name> up`
# Add the `-d` flag at the end for detached execution
version: '2'
services:
  chrome:
    image: selenium/node-chrome-debug:latest
    volumes:
      - /dev/shm:/dev/shm
      - /tmp/chrome_profiles:/tmp/chrome_profiles
    ports:
      - "5900:5900"
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  hub:
    image: selenium/hub:latest
    ports:
      - "4444:4444"
```

executed a simple test:

```
    @Test
    public void chromeProfile() throws Exception {
        ChromeOptions chromeOptions = new ChromeOptions();
        chromeOptions.addArguments("user-data-dir=/tmp/chrome_profiles");

        WebDriver driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), chromeOptions);

        // 10 seconds to see the default page loading
        Thread.sleep(1000 * 10);

        driver.get("http://the-internet.herokuapp.com");

        Assert.assertEquals(driver.getTitle(), "The Internet");

        driver.quit();
    }
```

and it worked as expected.

Please check that your profile is the only one in that directory and that it is the default one.

I'll close this issue since there is no problem with docker-selenium and Chrome profiles, in case that there is an error, feel free to reopen and provide detailed steps showing how to reproduce the error.

**Closed by diemol** 2018-09-23 13:02 UTC
Labels: S-investigating

**Comment by diemol** [comment] 2018-09-24 17:32
Technically it is not the profile path what needs to be passed, it is the user data directory, which contains the profile.

If you check my comment above, `/tmp/chrome_profiles` is what contains the whole user data directory, and `Profile` is contained in it.

**Comment by osvald0** [comment] 2018-09-24 19:27
What do you see on chrome://version?
