### ISSUE TITLE
Can not maximize standalone-chrome browser window

### ISSUE THREAD

**Issue by pavelpp** [SeleniumHQ/docker-selenium#396] opened 2017-02-22 08:05 UTC
## Meta -
**Image(s):**  
-   _standalone-chrome_

**Docker Version:**  
- _3.0.1-germanium_

**OS:** 
- _OSX Yosemite_ 

**Env variables set:**
-   _SCREEN_WIDTH=1280_
-   _SCREEN_HEIGHT=720_

When I maximize browser size in test setup: ```driver.manage().window().maximize();``` it has no effect. However, setting size with ```driver.manage().window().setSize(new Dimension(width, height));``` works perfectly. The problem is only with _standalone-chrome_, as _standalone-chrome-debug_ with the same tag works with maximize().

## Expected Behavior -
maximize() should maximize browser window to the full screen size.
## Actual Behavior -
browser window width after maximize() is 1050x700
browser window after setSize(new Dimension(1280,720)) is 1279x719

**Comment by vikramvi** [comment] 2017-04-28 11:37
With mac 10.12.3 + Docker 17.03.1-ce-mac5 + selenium/node-chrome-debug:3.4.0

I've below method for maximizing browser
`public boolean maximizeBrowserWindow(){
		try{
		         getDriver().manage().window().maximize();
		         //Below solution not working in case of Chrome container
			 /*Toolkit toolkit = Toolkit.getDefaultToolkit();
				
			 Dimension screenResolution = new Dimension((int) toolkit.getScreenSize().getWidth(), (int) toolkit.getScreenSize().getHeight());
		         getDriver().manage().window().setSize(screenResolution);*/
		         return true;
		}catch(Exception e){
			e.printStackTrace();
			return false;
		}
	}`

But this always throws **false** and without any exception

Is there any workaround for this ?

**Comment by vikramvi** [comment] 2017-04-28 13:17
@ddavison can you please review this issue ?

**Comment by rdbaron** [comment] 2017-07-31 13:30
I am seeing the same behaviour.  Furthermore, as of Chrome v60, `driver.manage().window().maximize()` throws a Webdriver error.

**Comment by diemol** [comment] 2017-10-05 23:06
This is now a duplicate of #559, please follow up in that issue. 
I'll close this one.

**Closed by diemol** 2017-10-05 23:06 UTC
