### ISSUE TITLE
Selenium-Node hangs

### ISSUE THREAD

**Issue by nirav1911** [SeleniumHQ/docker-selenium#82] opened 2015-07-29 02:29 UTC
I have tried 2.44.0, 2.45.0 and 2.46.0 version for Docker hub and nodes with firefox. I am getting the same error with all the version. I am trying to run these docker images on Linux Host. I am trying to run test cases from another docker image.
  20:08:59.134 INFO - Launching a standalone server
  20:08:59.175 INFO - Java: Oracle Corporation 25.45-b02 
  20:08:59.176 INFO - OS: Linux 3.13.0-52-generic amd64
  20:08:59.186 INFO - v2.45.0, with Core v2.45.0. Built from revision 5017cb8
  20:08:59.247 INFO - Default driver org.openqa.selenium.ie.InternetExplorerDriver registration is skipped: registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match with current platform: LINUX
  20:08:59.300 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
  20:08:59.301 INFO - Version Jetty/5.1.x
  20:08:59.303 INFO - Started HttpContext[/selenium-server,/selenium-server]
  20:08:59.328 INFO - Started org.openqa.jetty.jetty.servlet.ServletHandler@256216b3
  20:08:59.328 INFO - Started HttpContext[/wd,/wd]
  20:08:59.329 INFO - Started HttpContext[/selenium-server/driver,/selenium-server/driver]
  20:08:59.329 INFO - Started HttpContext[/,/]
  20:08:59.332 INFO - Started SocketListener on 0.0.0.0:4444
  20:08:59.332 INFO - Started org.openqa.jetty.jetty.Server@133314b
  jar:file:/var/lib/selenium/selenium-server.jar!/customProfileDirCUSTFFCHROME
  20:08:59.465 INFO - Preparing Firefox profile...

**Comment by elgalu** [comment] 2015-07-29 07:14
This issue looks like a duplicate of https://github.com/SeleniumHQ/docker-selenium/issues/14#issuecomment-125685468

**Comment by nirav1911** [comment] 2015-07-29 12:51
It is not the similar issue as in my case, nodes are started and I can see
the grid. It is not able to open firefox.

On Wed, Jul 29, 2015 at 3:14 AM, Leo Gallucci <notifications@github.com>
wrote:

> This issue looks like a duplicate of #14 (comment)
> <https://github.com/SeleniumHQ/docker-selenium/issues/14#issuecomment-125685468>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SeleniumHQ/docker-selenium/issues/82#issuecomment-125866686>
> .
>



-- 
Thanks,

Nirav Shah
(C) (610) 306-9617

**Comment by rubytester** [comment] 2015-08-28 21:21
This could be an issue of visibility of containers one to another. If you run tests in a container you may need to link to hub or node. I am not familiar withi this way of doing things. 

However we do something like this when we run tests and link to a standalone-chrome-node for example using --link switch in docker run so my tests can see the ip and port of a container that servers the browser.

**Comment by ddavison** [comment] 2016-10-12 21:05
are you still having this issue @nirav1911 ?  

there's really not much i can go on to help you out. maybe share the way that you are running the containers

**Comment by diemol** [comment] 2017-06-16 15:36
Closing this issue since we didn't get any feedback from the original poster.

**Closed by diemol** 2017-06-16 15:36 UTC
