### ISSUE TITLE
Unable to launch the ChromeDriver 2.39 in user-Driectory

### ISSUE THREAD

**Issue by ShibiKP** [SeleniumHQ/docker-selenium#743] opened 2018-06-08 10:40 UTC
Hi,

When I have try to launch the Chrome browser from chromedriver using selenium webdriver as User define location it have throws the exception as:- 
Error message:- 
"Exception has occurejava.lang.IllegalStateException: The driver executable does not exist: E:\D file\Working\File\Demo\‪E:\Webdriver\chromedriver.exe"
But i have Pass chromeDriver Dir in same project location the chrome browser have launched properly.
 
Version:-
Webdriver version 3.12.0
ChromeDriver 2.39
java Version 1.8
OS:- windows 10

**Comment by cgoldberg** [comment] 2018-06-08 13:54
> But i have Pass chromeDriver Dir in same project location

Please show a reproducible test case containing the code where you are specifying location of chromedriver and how you are instantiating the driver.  also show a complete stacktrace with the error.   We are not all mind readers.

**Comment by ddavison** [comment] 2018-06-09 04:09
hi @ShibiKP 3 things.

1. Please follow the template that is provided by GitHub.  
2. You have not provided any details on how you ran.  Nothing in your stacktrace mentions using Docker at all, so it looks like you needed to open this in SeleniumHQ/selenium. Not the docker-selenium repository.
3.  I'm closing this issue as it looks like it's not an issue with selenium.  It's an issue of your personal setup.

Please consult the [selenium-users google group](https://groups.google.com/forum/#!forum/selenium-users) for general help.

**Closed by ddavison** 2018-06-09 04:09 UTC
