### ISSUE TITLE
[🐛 Bug]: Problem starting session-queue on Kubernetes in 4.5.0-20220929

### ISSUE THREAD

**Issue by dironel** [SeleniumHQ/docker-selenium#1687] opened 2022-09-30 13:37 UTC
### What happened?

When i changed version to 4.5.0-20220929 for my grid, session queue is not starting.

### Command used to start Selenium Grid with Docker

```shell
sudo kubectl apply -f 00_selenium-grid.yaml
```

### Relevant log output

```shell
2022-09-30 13:29:09,637 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-session-queue.conf" during parsing
2022-09-30 13:29:09,660 INFO RPC interface 'supervisor' initialized
2022-09-30 13:29:09,661 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2022-09-30 13:29:09,663 INFO supervisord started with pid 8
2022-09-30 13:29:10,664 INFO spawned: 'selenium-grid-session-queue' with pid 10
Starting Selenium Grid SessionQueue...
2022-09-30 13:29:10,672 INFO success: selenium-grid-session-queue entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
Was passed main parameter '--publish-events' but no main parameter was defined in your arg class
Usage: sessionqueue [options]
  Options:
    --allow-cors
      Whether the Selenium server should allow web browser connections from
      any host
      Default: false
    --bind-host
      Whether the server should bind to the host address/name, or only use it
      to report its reachable url. Helpful in complex network topologies where
      the server cannot report itself with the current IP/hostname but rather
      an external IP or hostname (e.g. inside a Docker container).
      Default: true
    --config
      Config file to read from (may be specified more than once)
    --config-help
      Output detailed information about config options
      Default: false
    --host
      Server IP or hostname: usually determined automatically.
    --http-logs
      Enable http logging. Tracing should be enabled to log http logs.
      Default: false
    --https-certificate
      Server certificate for https. Get more detailed information by running
      "java -jar selenium-server.jar info security"
    --https-private-key
      Private key for https. Get more detailed information by running "java
      -jar selenium-server.jar info security"
    --log
      File to write out logs. Ensure the file path is compatible with the
      operating system's file path. Windows path example:
      \\path\to\file\gridlog.log OR C:\path\path\to\file\gridlog.log
      Linux/Unix/MacOS path example: /path/to/file/gridlog.log
    --log-encoding
      Log encoding
    --log-level
      Log level. Default logging level is INFO. Log levels are described here
      https://docs.oracle.com/javase/7/docs/api/java/util/logging/Level.html
      Default: INFO
    --log-timestamp-format
      Format of the timestamp in log output
    --max-threads
      Maximum number of listener threads. Default value is: (available
      processors) * 3.
      Default: 3
    --plain-logs
      Use plain log lines
      Default: true
    -p, --port
      Port to listen on. There is no default as this parameter is used by
      different components, for example Router/Hub/Standalone will use 4444
      and Node will use 5555.
    --registration-secret
      Node registration secret
    --session-request-timeout
      Timeout in seconds. New incoming session request is added to the queue.
      Requests sitting in the queue for longer than the configured time will
      timeout.
      Default: 300
    --session-retry-interval
      Retry interval in seconds. If all slots are busy, new session request
      will be retried after the given interval.
      Default: 15
    --sq, --sessionqueue
      Address of the session queue server.
    --sessionqueue-host
      Host on which the session queue server is listening.
    --sessionqueue-port
      Port on which the session queue server is listening.
    --structured-logs
      Use structured logs
      Default: false
    --tracing
      Enable trace collection
      Default: true
    --version
      Displays the version and exits.
      Default: false

2022-09-30 13:29:11,241 INFO exited: selenium-grid-session-queue (exit status 0; expected)
```

### Operating System

Red Hat Enterprise Linux 8.6 (Ootpa)

### Docker Selenium version (tag)

4.5.0-20220929

**Comment by efranken** [comment] 2022-10-01 03:58
Options for --publish-events and --subscribe-events were removed, commit message says "It is not using the bus since a few releases ago" in reference to the session queue.

I had this issue too and just removed the publish-events and subscribe-events flags and was back in business.

https://github.com/seleniumhq/selenium/commit/4b19fa416be02542c994bf839ca3c3408ded4b16

**Comment by jamesmortensen** [comment] 2022-10-01 07:44
@efranken Thanks for jumping in.  Do you think we need to update the docs for the Helm charts or any of the yaml files to reflect this change?  If so, would you be willing to open a pull request? 

https://github.com/SeleniumHQ/docker-selenium/tree/trunk/charts/selenium-grid

**Comment by efranken** [comment] 2022-10-03 19:20
@jamesmortensen I'll say that my issue was with running a custom deployment - not using the Helm charts or YAML files, which is probably why I had this issue pop up.  Each component on a separate ec2 instance running the selenium .jar.

I'll definitely double check through the Helm charts/yaml files tomorrow and see if there's anything that could cause this, though!

**Comment by dironel** [comment] 2022-10-04 12:39
forgot to add my yaml. we are not using helm.
apiVersion: v1
kind: Service
metadata:
  name: selenium-event-bus
  namespace: automated-test
  labels:
    name: selenium-event-bus
    component: "selenium-grid-4"
spec:
  selector:
    app: selenium-event-bus
  ports:
    - name: port1
      protocol: TCP
      port: 4442
      targetPort: 4442
    - name: port2
      protocol: TCP
      port: 4443
      targetPort: 4443
    - name: port3
      protocol: TCP
      port: 5557
      targetPort: 5557
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-event-bus-deployment
  namespace: automated-test
  labels:
    app: selenium-event-bus
    name: selenium-event-bus
    component: "selenium-grid-4"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-event-bus
  template:
    metadata:
      labels:
        app: selenium-event-bus
        name: selenium-event-bus
        component: "selenium-grid-4"
    spec:
      containers:
        - name: selenium-event-bus
          image: selenium/event-bus:4.5.0-20220929
          ports:
            - containerPort: 4442
              protocol: TCP
            - containerPort: 4443
              protocol: TCP
            - containerPort: 5557
              protocol: TCP
      nodeSelector:
        purpose/application: "true"
---
#***************************************
#SELENIUM SESSIONS MAP
#***************************************
apiVersion: v1
kind: Service
metadata:
  name: selenium-sessions
  namespace: automated-test
  labels:
    name: selenium-sessions
    component: "selenium-grid-4"
spec:
  selector:
    app: selenium-sessions
  ports:
    - name: port1
      protocol: TCP
      port: 5556
      targetPort: 5556

apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-sessions-deployment
  namespace: automated-test
  labels:
    app: selenium-sessions
    name: selenium-sessions
    component: "selenium-grid-4"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-sessions
  template:
    metadata:
      labels:
        app: selenium-sessions
        name: selenium-sessions
        component: "selenium-grid-4"
    spec:
      containers:
        - name: selenium-sessions
          image: selenium/sessions:4.5.0-20220929
          env:
            - name: SE_EVENT_BUS_HOST
              value: "selenium-event-bus"
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
          ports:
            - containerPort: 5556
              protocol: TCP
      nodeSelector:
        purpose/application: "true"

#***************************************
#SELENIUM SESSION QUEUER
#***************************************
apiVersion: v1
kind: Service
metadata:
  name: selenium-session-queue
  namespace: automated-test
  labels:
    name: selenium-session-queue
    component: "selenium-grid-4"
spec:
  selector:
    app: selenium-session-queue
  ports:
    - name: port1
      protocol: TCP
      port: 5559
      targetPort: 5559
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-session-queue-deployment
  namespace: automated-test
  labels:
    app: selenium-session-queue
    name: selenium-session-queue
    component: "selenium-grid-4"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-session-queue
  template:
    metadata:
      labels:
        app: selenium-session-queue
        name: selenium-session-queue
        component: "selenium-grid-4"
    spec:
      containers:
        - name: selenium-session-queue
          image: selenium/session-queue:4.4.0-20220831
          env:
            - name: SE_EVENT_BUS_HOST
              value: "selenium-event-bus"
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
          ports:
            - containerPort: 5556
              protocol: TCP
      nodeSelector:
        purpose/application: "true"
---
#***************************************
#SELENIUM DISTRIBUTOR
#***************************************
apiVersion: v1
kind: Service
metadata:
  name: selenium-distributor
  namespace: automated-test
  labels:
    name: selenium-distributor
    component: "selenium-grid-4"
spec:
  selector:
    app: selenium-distributor
  ports:
    - name: port1
      protocol: TCP
      port: 5553
      targetPort: 5553

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-distributor-deployment
  namespace: automated-test
  labels:
    app: selenium-distributor
    name: selenium-distributor
    component: "selenium-grid-4"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-distributor
  template:
    metadata:
      labels:
        app: selenium-distributor
        name: selenium-distributor
        component: "selenium-grid-4"
    spec:
      containers:
        - name: selenium-distributor
          image: selenium/distributor:4.5.0-20220929
          env:
            - name: SE_EVENT_BUS_HOST
              value: "selenium-event-bus"
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
            - name: SE_SESSIONS_MAP_HOST
              value: "selenium-sessions"
            - name: SE_SESSIONS_MAP_PORT
              value: "5556"
            - name: SE_SESSION_QUEUE_HOST
              value: "selenium-session-queue"
            - name: SE_SESSION_QUEUE_PORT
              value: "5559"
          ports:
            - containerPort: 5553
              protocol: TCP
      nodeSelector:
        purpose/application: "true"
---
#***************************************
#SELENIUM ROUTER
#***************************************
apiVersion: v1
kind: Service
metadata:
  name: selenium-router
  namespace: automated-test
  labels:
    name: selenium-router
    component: "selenium-grid-4"
spec:
  selector:
    app: selenium-router
  ports:
    - name: web
      protocol: TCP
      port: 4444
      targetPort: 4444

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-router-deployment
  namespace: automated-test
  labels:
    app: selenium-router
    name: selenium-router
    component: "selenium-grid-4"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-router
  template:
    metadata:
      labels:
        app: selenium-router
        name: selenium-router
        component: "selenium-grid-4"
    spec:
      containers:
        - name: selenium-router
          image: selenium/router:4.5.0-20220929
          env:
            - name: SE_DISTRIBUTOR_HOST
              value: "selenium-distributor"
            - name: SE_DISTRIBUTOR_PORT
              value: "5553"
            - name: SE_SESSIONS_MAP_HOST
              value: "selenium-sessions"
            - name: SE_SESSIONS_MAP_PORT
              value: "5556"
            - name: SE_SESSION_QUEUE_HOST
              value: "selenium-session-queue"
            - name: SE_SESSION_QUEUE_PORT
              value: "5559"
          ports:
            - containerPort: 4444
              protocol: TCP
      nodeSelector:
        purpose/application: "true"
---
#***************************************
#SELENIUM CHROME NODE
#***************************************
apiVersion: v1
kind: Service
metadata:
  name: selenium-chrome-node
  namespace: automated-test
  labels:
    name: selenium-chrome-node
    component: "selenium-grid-4"
spec:
  selector:
    app: selenium-chrome-node
  ports:
    - name: port1
      protocol: TCP
      port: 6900
      targetPort: 5900


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-chrome-node-deployment
  namespace: automated-test
  labels:
    app: selenium-chrome-node
    name: selenium-chrome-node
    component: "selenium-grid-4"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: selenium-chrome-node
  template:
    metadata:
      labels:
        app: selenium-chrome-node
        name: selenium-chrome-node
        component: "selenium-grid-4"
    spec:
      containers:
        - name: selenium-chrome-node
          image: nexus.pmb.cz:5001/ppfbanka/selenium/node-chrome:4.0.0-v35
          env:
            - name: SE_EVENT_BUS_HOST
              value: "selenium-event-bus"
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
            - name: VNC_NO_PASSWORD
              value: "1"
            - name: SE_NODE_GRID_URL
              value: "https://selenium-router:443"
            - name: SCREEN_WIDTH
              value: "1920"
            - name: SCREEN_HEIGHT
              value: "1080"
          ports:
            - containerPort: 5553
              protocol: TCP
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
              readOnly: false
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "2"

      volumes:
        - name: dshm
          emptyDir: { "medium": "Memory" }
      imagePullSecrets:
        - name: registry-secret
      nodeSelector:
        purpose/application: "true"
---
#***************************************
#SELENIUM EDGE NODE
#***************************************
apiVersion: v1
kind: Service
metadata:
  name: selenium-edge-node
  namespace: automated-test
  labels:
    name: selenium-edge-node
    component: "selenium-grid-4"
spec:
  selector:
    app: selenium-edge-node
  ports:
    - name: port1
      protocol: TCP
      port: 6901
      targetPort: 5900

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-edge-node-deployment
  namespace: automated-test
  labels:
    app: selenium-edge-node
    name: selenium-edge-node
    component: "selenium-grid-4"
spec:
  replicas: 0
  selector:
    matchLabels:
      app: selenium-edge-node
  template:
    metadata:
      labels:
        app: selenium-edge-node
        name: selenium-edge-node
        component: "selenium-grid-4"
    spec:
      containers:
        - name: selenium-edge-node
          image: selenium/node-edge:4.5.0-20220929
          env:
            - name: SE_EVENT_BUS_HOST
              value: "selenium-event-bus"
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
          ports:
            - containerPort: 5553
              protocol: TCP
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
          resources:
            requests:
              memory: "100Mi"
              cpu: ".1"
            limits:
              memory: "1Gi"
              cpu: "1"
      volumes:
        - name: dshm
          emptyDir: { "medium": "Memory" }
      nodeSelector:
        purpose/application: "true"
---
#***************************************
#SELENIUM FIREFOX NODE
#***************************************
apiVersion: v1
kind: Service
metadata:
  name: selenium-ff-node
  namespace: automated-test
  labels:
    name: selenium-ff-node
    component: "selenium-grid-4"
spec:
  selector:
    app: selenium-ff-node
  ports:
    - name: port1
      protocol: TCP
      port: 6902
      targetPort: 5900

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-ff-node-deployment
  namespace: automated-test
  labels:
    app: selenium-ff-node
    name: selenium-ff-node
    component: "selenium-grid-4"
spec:
  replicas: 0
  selector:
    matchLabels:
      app: selenium-ff-node
  template:
    metadata:
      labels:
        app: selenium-ff-node
        name: selenium-ff-node
        component: "selenium-grid-4"
    spec:
      containers:
        - name: selenium-ff-node
          image: selenium/node-firefox:4.5.0-20220929
          env:
            - name: SE_EVENT_BUS_HOST
              value: "selenium-event-bus"
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
          ports:
            - containerPort: 5553
              protocol: TCP
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
          resources:
            requests:
              memory: "100Mi"
              cpu: ".5"
            limits:
              memory: "1Gi"
              cpu: "1"
      volumes:
        - name: dshm
          emptyDir: { "medium": "Memory" }
      nodeSelector:
        purpose/application: "true"

**Comment by DGCarramona** [comment] 2022-10-04 14:23
Hello, getting this issue also, just starting docker image of session-queue, tagged with version 4.5.0-20220929

**Comment by efranken** [comment] 2022-10-04 14:42
@jamesmortensen The main "bug" is that the [start-selenium-session-queue.sh](https://github.com/SeleniumHQ/docker-selenium/blob/trunk/SessionQueue/start-selenium-grid-session-queue.sh) still allows `--publish-events` and `--subscribe-events` to be set as flags, which fail when passed to the .jar.  

I will have a PR up in the next couple hours to fix this. 

As far as the docs go, there is one reference to the event bus from the session queue in one spot - 

components.sessionQueue.resources | {} | Resources for event-bus container
-- | -- | --

but it looks like the text `Resources for event-bus container` may be copy pasted from another line, I don't think that's pointing the sessionqueue to eventbus.  I don't think the helm charts need updated.

The helm charts don't look like they reference `SE_EVENT_BUS_HOST` or the launch flags anywhere.  I think that's all user-specified?


@DGCarramona if you remove either the env vars `SE_EVENT_BUS_SUBSCRIBE_PORT`, `SE_EVENT_BUS_PUBLISH_PORT` and `SE_EVENT_BUS_HOST`, or the `--publish-events` and `--subscribe-events` flags from however you launch the sessionqueue, it will allow it to run again.

**Comment by jamesmortensen** [comment] 2022-10-04 19:17
Thanks to @efranken it looks like we have a fix to this issue.  Please change your docker-compose yaml tags to 4.5.0-20221005 to try it out.  Please help us close this issue by confirming it also works for you, @dironel @DGCarramona 

https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.5.0-20221004

**Comment by DGCarramona** [comment] 2022-10-05 04:30
Hello, I'll try it ASAP and share the result. Thanks for the PR

**Comment by DGCarramona** [comment] 2022-10-05 09:35
I confirm it works for me @jamesmortensen

**Comment by efranken** [comment] 2022-10-05 15:49
I just put a PR up to clean up the environment variables.  As mentioned in the PR I don't have knowledge of Helm or an environment to test k8s deployment in, if someone could help test.  It's only a small modification and I copied the structure from another helm chart in the repo, but I don't have a way to verify it.

**Comment by jamesmortensen** [comment] 2022-10-06 04:09
@efranken Thanks again.  I can confirm whether or not the docker-compose changes work, but at this time, I don't feel I'm  fully qualified to check the Kubernetes stuff.  Since those changes aren't urgent, we can leave the pull request open until we get someone who can help review it.

**Comment by dironel** [comment] 2022-10-13 09:01
Hello it working well now.
Regards

**Comment by diemol** [comment] 2022-10-13 09:07
Thanks for the feedback. Closing this.

**Closed as completed by diemol** 2022-10-13 09:07 UTC
Labels: help wanted, R-awaiting-answer
