### ISSUE TITLE
Failed: java.lang.String cannot be cast to java.lang.Number - firefox 2.45.0

### ISSUE THREAD

**Issue by bitliner** [SeleniumHQ/docker-selenium#105] opened 2015-10-08 19:47 UTC
It occurs with `selenium/standalone-firefox:2.46.0` and `selenium/standalone-firefox:2.45.0` as described [here](https://github.com/angular/protractor/issues/2546).

If I run it with `selenium/standalone-firefox:2.47.1` then - because my app open an alert - it throws error saying "Unexpected alert".

:-(

PS: of course, if I run the webdriver directly on the machine, the error does not occur - aka it is related to docker-selenium, no to selenium itself.

**Comment by rubytester** [comment] 2015-10-10 16:26
Hi, how could I reproduce this issue? not sure if I understand

**Comment by diemol** [comment] 2017-06-16 15:45
Closing this issue since we didn't get any feedback from the original poster.

**Closed by diemol** 2017-06-16 15:45 UTC
