### ISSUE TITLE
[🚀 Feature]: Dynamic Grid in Kubernetes

### ISSUE THREAD

**Issue by chuongnguyen5397** [SeleniumHQ/docker-selenium#1590] opened 2022-06-02 15:34 UTC
### Feature and motivation

I'm trying to deploy and Selenium Dynamic Grid in my EKS cluster. 
Images I used are: `selenium/hub:4.2.1-20220531` and `selenium/node-docker:4.2.1-20220531`
For the `Dynamic-node-deployment`, I added some volumes as below:
```
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - name: config-volume
              mountPath: /opt/bin/config.toml
              subPath: config.toml
            - name: docker
              mountPath: /var/run/docker.sock
        {{- with .Values.dynamicNode.resources }}
          resources: {{- toYaml . | nindent 12 }}
        {{- end }}
    {{- with .Values.dynamicNode.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.dynamicNode.tolerations }}
      tolerations:
        {{ toYaml . | nindent 6 }}
    {{- end }}
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: {{ default "1Gi" .Values.dynamicNode.dshmVolumeSizeLimit }}
        - name: config-volume
          configMap:
            name: {{ .Chart.Name }}-configmap
        - name: docker
          hostPath:
            path: /var/run/docker.sock
```
The diagram is simple. I use the helm chart in this repo, but I write 1 more deployment and service for the dynamic and disable Chrome, Firefox and Edge browser. 
After deployment, the `kubectl get all` look like this:
```
kubectl get all -n selenium-grid                                                 
NAME                                         READY   STATUS    RESTARTS   AGE
pod/selenium-dynamic-node-667476fcfd-bnjzh   1/1     Running   0          26s
pod/selenium-dynamic-node-667476fcfd-srfzw   1/1     Running   0          26s
pod/selenium-hub-56fc498d57-cpf49            1/1     Running   0          26s

NAME                            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                        AGE
service/selenium-dynamic-node   ClusterIP   172.20.207.226   <none>        6900/TCP                                       29s
service/selenium-hub            NodePort    172.20.16.164    <none>        4444:30444/TCP,4442:30650/TCP,4443:32738/TCP   29s

NAME                                    READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/selenium-dynamic-node   2/2     2            2           29s
deployment.apps/selenium-hub            1/1     1            1           29s

NAME                                               DESIRED   CURRENT   READY   AGE
replicaset.apps/selenium-dynamic-node-667476fcfd   2         2         2       30s
replicaset.apps/selenium-hub-56fc498d57            1         1         1       30s
```

And here is the `config.toml` content in the configmap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
  namespace: {{ .Chart.Name }}
data:
  config.toml: |
    [docker]
    # Configs have a mapping between the Docker image to use and the capabilities that need to be matched to
    # start a container with the given image.
    configs = [
        "selenium/standalone-firefox:4.2.1-20220531", '{"browserName": "firefox", "platformName": "linux"}',
        "selenium/standalone-chrome:4.2.1-20220531", '{"browserName": "chrome", "platformName": "linux"}',
        "selenium/standalone-edge:4.2.1-20220531", '{"browserName": "MicrosoftEdge", "platformName": "linux"}'
        ]

    # URL for connecting to the docker daemon
    # host.docker.internal works for macOS and Windows.
    # Linux could use --net=host in the `docker run` instruction or 172.17.0.1 in the URI below.
    # To have Docker listening through tcp on macOS, install socat and run the following command
    # socat -4 TCP-LISTEN:2375,fork UNIX-CONNECT:/var/run/docker.sock
    url = "http://127.0.0.1:2375"
    # Docker image used for video recording
    video-image = "selenium/video:ffmpeg-4.3.1-20220531"

    # Uncomment the following section if you are running the node on a separate VM
    # Fill out the placeholders with appropriate values
    [server]
    host = "selenium-dynamic-node.selenium-grid.svc.cluster.local"
    port = 5555
```

I also added `SE_EVENT_BUS_HOST` for the dynamic node:
```
  extraEnvironmentVariables:
    - name: SE_EVENT_BUS_HOST
      value: selenium-hub.selenium-grid.svc.cluster.local
```

After I deployed using Helm, here is the log from dynamic-node:
```
2022-06-02 15:17:44,639 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-docker.conf" during parsing
2022-06-02 15:17:44,641 INFO supervisord started with pid 8
2022-06-02 15:17:45,643 INFO spawned: 'socat' with pid 10
2022-06-02 15:17:45,645 INFO spawned: 'selenium-grid-docker' with pid 11
Starting Selenium Grid Node Docker...
2022-06-02 15:17:45,651 INFO success: socat entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2022-06-02 15:17:45,651 INFO success: selenium-grid-docker entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
15:17:46.258 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
15:17:46.264 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
15:17:46.461 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://selenium-hub.selenium-grid.svc.cluster.local:4442 and tcp://selenium-hub.selenium-grid.svc.cluster.local:4443
15:17:46.561 INFO [UnboundZmqEventBus.<init>] - Sockets created
15:17:47.563 INFO [UnboundZmqEventBus.<init>] - Event bus ready
15:17:47.712 INFO [NodeServer.createHandlers] - Reporting self as: http://selenium-dynamic-node.selenium-grid.svc.cluster.local:5555
15:17:47.740 INFO [NodeOptions.getSessionFactories] - Detected 3 available processors
15:17:48.432 INFO [V141Docker.isContainerPresent] - Checking if container is present: selenium-dynamic-node-667476fcfd-bnjzh
15:17:48.446 INFO [Docker.getImage] - Obtaining image: selenium/standalone-chrome:4.2.1-20220531
15:17:48.446 INFO [Docker.getImage] - Obtaining image: selenium/standalone-edge:4.2.1-20220531
15:17:48.452 INFO [V141Docker.getImage] - Listing local images: Reference{domain='docker.io', name='selenium/standalone-edge', tag='4.2.1-20220531', digest='null'}
15:17:48.452 INFO [V141Docker.getImage] - Listing local images: Reference{domain='docker.io', name='selenium/standalone-chrome', tag='4.2.1-20220531', digest='null'}
15:17:48.477 INFO [Docker.getImage] - Obtaining image: selenium/standalone-firefox:4.2.1-20220531
15:17:48.478 INFO [V141Docker.getImage] - Listing local images: Reference{domain='docker.io', name='selenium/standalone-firefox', tag='4.2.1-20220531', digest='null'}
15:17:48.529 INFO [Docker.getImage] - Obtaining image: selenium/video:ffmpeg-4.3.1-20220531
15:17:48.529 INFO [V141Docker.getImage] - Listing local images: Reference{domain='docker.io', name='selenium/video', tag='ffmpeg-4.3.1-20220531', digest='null'}
15:17:48.553 INFO [Docker.getImage] - Obtaining image: selenium/video:ffmpeg-4.3.1-20220531
15:17:48.553 INFO [V141Docker.getImage] - Listing local images: Reference{domain='docker.io', name='selenium/video', tag='ffmpeg-4.3.1-20220531', digest='null'}
15:17:48.575 INFO [Docker.getImage] - Obtaining image: selenium/standalone-edge:4.2.1-20220531
15:17:48.576 INFO [V141Docker.getImage] - Listing local images: Reference{domain='docker.io', name='selenium/standalone-edge', tag='4.2.1-20220531', digest='null'}
15:17:48.610 INFO [DockerOptions.lambda$getDockerSessionFactories$1] - Mapping Capabilities {browserName: MicrosoftEdge, platformName: LINUX} to docker image selenium/standalone-edge:4.2.1-20220531 3 times
15:17:48.610 INFO [Docker.getImage] - Obtaining image: selenium/standalone-chrome:4.2.1-20220531
15:17:48.611 INFO [V141Docker.getImage] - Listing local images: Reference{domain='docker.io', name='selenium/standalone-chrome', tag='4.2.1-20220531', digest='null'}
15:17:48.639 INFO [DockerOptions.lambda$getDockerSessionFactories$1] - Mapping Capabilities {browserName: chrome, platformName: LINUX} to docker image selenium/standalone-chrome:4.2.1-20220531 3 times
15:17:48.640 INFO [Docker.getImage] - Obtaining image: selenium/standalone-firefox:4.2.1-20220531
15:17:48.640 INFO [V141Docker.getImage] - Listing local images: Reference{domain='docker.io', name='selenium/standalone-firefox', tag='4.2.1-20220531', digest='null'}
15:17:48.664 INFO [DockerOptions.lambda$getDockerSessionFactories$1] - Mapping Capabilities {browserName: firefox, platformName: LINUX} to docker image selenium/standalone-firefox:4.2.1-20220531 3 times
15:17:48.692 INFO [Node.<init>] - Binding additional locator mechanisms: name, id, relative
15:17:48.797 INFO [NodeServer$1.start] - Starting registration process for Node http://selenium-dynamic-node.selenium-grid.svc.cluster.local:5555
15:17:48.801 INFO [NodeServer.execute] - Started Selenium node 4.2.1 (revision ac4d0fdd4a): http://selenium-dynamic-node.selenium-grid.svc.cluster.local:5555
15:17:48.836 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
15:17:58.846 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
15:18:08.852 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
15:18:18.862 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
15:18:28.868 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
15:18:38.873 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
15:18:48.878 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
15:18:58.882 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
15:19:08.888 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
```

and here is the log from the hub:
```
2022-06-02 15:17:44,634 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-hub.conf" during parsing
2022-06-02 15:17:44,637 INFO supervisord started with pid 8
2022-06-02 15:17:45,639 INFO spawned: 'selenium-grid-hub' with pid 10
15:17:46.594 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
2022-06-02 15:17:46,598 INFO success: selenium-grid-hub entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
15:17:46.601 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
15:17:46.911 INFO [BoundZmqEventBus.<init>] - XPUB binding to [binding to tcp://*:4442, advertising as tcp://10.5.5.38:4442], XSUB binding to [binding to tcp://*:4443, advertising as tcp://10.5.5.38:4443]
15:17:47.023 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://10.5.5.38:4442 and tcp://10.5.5.38:4443
15:17:47.102 INFO [UnboundZmqEventBus.<init>] - Sockets created
15:17:48.105 INFO [UnboundZmqEventBus.<init>] - Event bus ready
15:17:49.790 INFO [Hub.execute] - Started Selenium Hub 4.2.1 (revision ac4d0fdd4a): http://10.5.5.38:4444
15:18:08.913 INFO [Node.<init>] - Binding additional locator mechanisms: relative, id, name
15:18:19.710 INFO [Node.<init>] - Binding additional locator mechanisms: id, relative, name
15:18:29.735 INFO [Node.<init>] - Binding additional locator mechanisms: name, relative, id
15:18:39.757 INFO [Node.<init>] - Binding additional locator mechanisms: name, id, relative
15:18:49.780 INFO [Node.<init>] - Binding additional locator mechanisms: name, id, relative
15:18:59.802 INFO [Node.<init>] - Binding additional locator mechanisms: name, id, relative
15:19:09.820 INFO [Node.<init>] - Binding additional locator mechanisms: relative, id, name
15:19:19.848 INFO [Node.<init>] - Binding additional locator mechanisms: name, id, relative
15:19:29.865 INFO [Node.<init>] - Binding additional locator mechanisms: id, name, relative
15:19:39.879 INFO [Node.<init>] - Binding additional locator mechanisms: id, relative, name
15:19:49.904 INFO [Node.<init>] - Binding additional locator mechanisms: id, relative, name
```

Why do the dynamic nodes can not register to the hub? Any help will be very appreciated

### Usage example

I will use it to deploy dynamic grid to EKS cluster

**Comment by diemol** [comment] 2022-06-02 15:36
Duplicate of https://github.com/SeleniumHQ/selenium/issues/9845

**Closed as completed by diemol** 2022-06-02 15:36 UTC
