### ISSUE TITLE
failed Using selenium/node-firefox  to test 

### ISSUE THREAD

**Issue by william5065** [SeleniumHQ/docker-selenium#558] opened 2017-09-07 01:14 UTC
## Meta -
Image(s):  
node-firefox
Docker-Selenium Image Version(s):  
3.5.3-astatine
OS: 
Centos7

**node-firefox container logs:**
2017-09-07 01:01:41.106:INFO:osjs.Server:main: Started @1249ms
01:01:41.106 INFO - Selenium Grid node is up and ready to register to the hub
01:01:41.116 INFO - Starting auto registration thread. Will try to register every 5000 ms.
01:01:41.116 INFO - Registering the node to the hub: http://172.17.0.3:4444/grid/register
01:01:41.160 INFO - The node is registered to the hub and ready to use
2017-09-07 01:08:14.841:INFO:osjshC.ROOT:qtp1979313356-14: org.openqa.selenium.remote.server.WebDriverServlet-6eda5c9: Initialising WebDriverServlet
01:08:14.874 INFO - Binding default provider to: org.openqa.selenium.chrome.ChromeDriverService
01:08:14.875 INFO - Found handler: org.openqa.selenium.remote.server.BeginSession@96b2a99
01:08:14.878 INFO - /session: Executing POST on /session (handler: BeginSession)
01:08:14.897 INFO - Capabilities are: Capabilities {marionette=true, acceptInsecureCerts=true, browserName=firefox, javascriptEnabled=true, platformName=ANY, version=, platform=ANY, firefox_profile=UEsDBBQAAAAIAKIKCEnOFgm64wI..., }
01:08:14.899 INFO - Capabilities {marionette=true, acceptInsecureCerts=true, browserName=firefox, javascriptEnabled=true, platformName=ANY, version=, platform=ANY, firefox_profile=UEsDBBQAAAAIAKIKCEnOFgm64wI..., } matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
01:08:14.899 INFO - Capabilities {marionette=true, acceptInsecureCerts=true, browserName=firefox, javascriptEnabled=true, platformName=ANY, version=, platform=ANY, firefox_profile=UEsDBBQAAAAIAKIKCEnOFgm64wI..., } matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
1504746494942	geckodriver	INFO	geckodriver 0.18.0
1504746494945	geckodriver	INFO	Listening on 127.0.0.1:12311
1504746495077	geckodriver::marionette	INFO	Starting browser /usr/bin/firefox with args ["-marionette"]
1504746495783	addons.xpi	WARN	Error parsing extensions state: [Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [amIAddonManagerStartup.readStartupData]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm :: loadExtensionState :: line 1596"  data: no] Stack trace: loadExtensionState()@resource://gre/modules/addons/XPIProvider.jsm:1596 < getInstallState()@resource://gre/modules/addons/XPIProvider.jsm:1631 < checkForChanges()@resource://gre/modules/addons/XPIProvider.jsm:3152 < startup()@resource://gre/modules/addons/XPIProvider.jsm:2246 < callProvider()@resource://gre/modules/AddonManager.jsm:271 < _startProvider()@resource://gre/modules/AddonManager.jsm:741 < startup()@resource://gre/modules/AddonManager.jsm:908 < startup()@resource://gre/modules/AddonManager.jsm:3122 < observe()@jar:file:///opt/firefox-55.0.3/omni.ja!/components/addonManager.js:65
1504746496148	Marionette	INFO	Enabled via --marionette
1504746503246	Marionette	INFO	Listening on port 44824
JavaScript error: chrome://marionette/content/server.js, line 337: NS_ERROR_SOCKET_ADDRESS_IN_USE: Component returned failure code: 0x804b0036 (NS_ERROR_SOCKET_ADDRESS_IN_USE) [nsIServerSocket.initSpecialConnection]
1504746503294	Marionette	WARN	TLS certificate errors will be ignored for this session
1504746503343	Marionette	DEBUG	loaded listener.js
01:08:23.561 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@c79af64
01:08:23.561 INFO - Handler thread for session e61a44f2-b67d-4540-a4d9-189ad4a7976e (firefox): Executing POST on /session/e61a44f2-b67d-4540-a4d9-189ad4a7976e/timeouts/async_script (handler: ServicedSession)
01:08:56.238 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@c79af64
01:08:56.239 INFO - Handler thread for session e61a44f2-b67d-4540-a4d9-189ad4a7976e (firefox): Executing DELETE on /session/e61a44f2-b67d-4540-a4d9-189ad4a7976e (handler: ServicedSession)
1504746536253	Marionette	INFO	New connections will no longer be accepted
01:08:56.398 INFO - Removing session org.openqa.selenium.remote.server.ServicedSession@c79af64

**test logs**

==============================================================================
[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: No browser is open
测试一下                                                              | FAIL |
WebDriverException: Message: POST /session/e61a44f2-b67d-4540-a4d9-189ad4a7976e/timeouts/async_script did not match a known command
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:54:15.039Z'
System info: host: '6653703a3853', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.26.2.el7.x86_64', java.version: '1.8.0_131'
Driver info: driver.version: unknown

## Expected Behavior -
open firefox browser
## Actual Behavior -
cannot open firefox  browser

**Comment by diemol** [comment] 2017-09-28 12:38
Hi @william5065,

I think this is the same as #577, please check this specific [comment](https://github.com/SeleniumHQ/docker-selenium/issues/577#issuecomment-332184020), maybe you can give us feedback a report where exactly this command is being triggered.

**Comment by william5065** [comment] 2017-09-29 02:08
Thanks

**Comment by diemol** [comment] 2017-10-03 19:19
OK, so I will close this issue for now, but please don't doubt to reopen if you need help to identify the problem and if you have detailed information on how that command is triggered.

**Closed by diemol** 2017-10-03 19:19 UTC

**Comment by suryavir** [comment] 2018-07-12 21:15
Hi @kormbrek-rally  I am running on selenium 3.12.0 and facing the issue. Which selenium version did you use to fix this?

**Comment by suryavir** [comment] 2018-07-17 11:57
@kormbrek-what does that exactly mean? selenium/standalone-chrome:3.11.0-dysprosium is a docker container containing selenium standalone and chrome I presume, but what is the python bindings you mentioned? Are you using some python framework for your web application which needs to be tested with selenium+chrome?  Thanks a lot in advance!

**Comment by kormbrek-rally** [comment] 2018-07-17 14:59
With Selenium, could be using [bindings for different languages](https://www.seleniumhq.org/download/). The bindings provide the client side of Selenium whereas selenium-docker provides the server. This has nothing to do with the application under test. I am using robotframework-seleniumlibrary on top of Selenium as well.

The below was caused by a mismatch between the client/bindings version and the version of Selenium used by the server. The protocol for the communication between the client and server has changed.

> WebDriverException: Message: POST /session/e61a44f2-b67d-4540-a4d9-189ad4a7976e/timeouts/async_script did not match a known command

**Comment by suryavir** [comment] 2018-07-17 17:14
@kormbrek-rally interesting. I am new to this, so just to clarify then- My framework ie the client (protractor which is running tests of my angular app) is speaking to the client of selenium which in turn talks to the server of selenium which then talks to the marionette driver of firefox to allow firefox to run and run our tests. Is this correct? So in that case the issue is due to the client of selenium and selenium server having a mismatch?

**Comment by kormbrek-rally** [comment] 2018-07-17 17:37
@suryavir you may just need to upgrade protractor. protractor has selenium-webdriver as a dependency and older versions of protractor came with older bindings.
