### ISSUE TITLE
Chrome sessions hang randomly with node-chrome due to DBUS issue

### ISSUE THREAD

**Issue by testphreak** [SeleniumHQ/docker-selenium#465] opened 2017-04-22 22:19 UTC
## Meta -
Image(s):
node-chrome. May affect other chrome and firefox images as well.

Image Version:
3.3.1-cesium

Docker version:
17.04.0-ce, build 4845c56

OS:
Ubuntu 16.04.2 LTS

## Expected Behavior -
Tests execute as usual without hanging.

## Actual Behavior -
@diemol, @ddavison spent a good deal of time last night trying to get to the bottom of the issue. It's related to this change https://github.com/SeleniumHQ/docker-selenium/commit/88584def77585863a226ca72bbce0f9dce561242 made by @a-k-g to resolve #358. 

Due to this change, none of the node-chrome images after 3.0.1 are working for me and the timeline of the commit confirms that. Would it be possible to add a fix that would work for all images - node-chrome, node-chrome-debug, standalone-chrome and standalone-chrome-debug images?

I passed in `DBUS_SESSION_BUS_ADDRESS=/dev/null` as an environment variable to node-chrome when starting the containers and all my tests now execute without random hangs with 3.4.0-actinium. It would be better if this variable is set in the image rather than us having to pass it in every time. 

I also found out that I am not alone in this issue and several including @pwaller and others have run into this issue recently https://github.com/SeleniumHQ/docker-selenium/issues/87#issuecomment-284238845.

**Comment by diemol** [comment] 2017-04-23 18:13
I was able to reproduce it with the Chrome images from the 3.4.0-bismuth release. Summarising, under this use case (open and closing Chrome many times, at least 50):

* node-chrome -> Does not work
* node-chrome-debug -> Works
* standalone-chrome -> Does not work
* standalone-chrome-debug -> Does not work

I am building locally the Dockerfiles now with some changes to see if it works. I'll keep you updated.

**Comment by testphreak** [comment] 2017-04-23 18:15
Awesome! Thanks @diemol!

**Comment by diemol** [comment] 2017-04-23 21:02
@testphreak Firefox images seem to work fine. By fine I mean that the test does not hang, it either fails or passes (I am just clarifying it because I am not 100% sure if the latest version of Geckodriver - 0.16 and Firefox 53 are working well, so nothing related to the DBUS_SESSION_BUS_ADDRESS).

**Comment by diemol** [comment] 2017-04-23 21:57
@testphreak, I just created a PR for this. Please check it, any help with checking it with your local tests would be great.

**Comment by testphreak** [comment] 2017-04-24 04:32
@diemol, your change looks good. Verified your change locally. Thanks for reverting the change back to #182.

**Closed** 2017-04-26 16:52 UTC

**Comment by derinbay** [comment] 2017-04-28 09:51
@testphreak is this fixed your problem, have you tested after chromium update?
Probably from a different reason than DBUS but #456 problem is still exist.
