### ISSUE TITLE
Fail to use test grid with wdio

### ISSUE THREAD

**Issue by egut** [SeleniumHQ/docker-selenium#892] opened 2019-04-01 13:49 UTC
## 🐛 Bug Report

First run: The test fails almost immediately,
The rest: The test just hangs, nothing happens.

Sorry that I can't be more clear, but all log files are included below.
 
I have  the latest Chrome-version (the same with debug and not) and the latest Hub version. (Have tried server version actual like 3.14.0-krypton and 3.141.59-gold same issue ) 

## To Reproduce

I first start the grid with docker-compose: 

```
version: "3"
services:

  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    environment:
      - GRID_DEBUG=true
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome-debug
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    ports:
      - "5900:5900"
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - GRID_DEBUG=true
```

Sometime it fails on first start, with error 143 (but that can be related to corporate proxy. )

Log output from selenium-hub (with my comments ):

```
selenium-hub    | 2019-04-01 13:10:19,444 INFO Included extra file "/etc/supervisor/conf.d/selenium-hub.conf" during parsing
selenium-hub    | 2019-04-01 13:10:19,445 INFO supervisord started with pid 7
selenium-hub    | 2019-04-01 13:10:20,449 INFO spawned: 'selenium-hub' with pid 10
selenium-hub    | Starting Selenium Hub with configuration:
selenium-hub    | 2019-04-01 13:10:20,472 INFO success: selenium-hub entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
selenium-hub    | {
selenium-hub    |   "host": "0.0.0.0",
selenium-hub    |   "port": 4444,
selenium-hub    |   "role": "hub",
selenium-hub    |   "maxSession": 5,
selenium-hub    |   "newSessionWaitTimeout": -1,
selenium-hub    |   "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
selenium-hub    |   "throwOnCapabilityNotPresent": true,
selenium-hub    |   "jettyMaxThreads": -1,
selenium-hub    |   "cleanUpCycle": 5000,
selenium-hub    |   "browserTimeout": 0,
selenium-hub    |   "timeout": 1800,
selenium-hub    |   "debug": true
selenium-hub    | }
selenium-hub    | 13:10:20.620 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
selenium-hub    | 13:10:20.676 INFO [GridLauncherV3.lambda$buildLaunchers$5] - Launching Selenium Grid hub on port 4444
selenium-hub    | 2019-04-01 13:10:21.030:INFO::main: Logging initialized @555ms to org.seleniumhq.jetty9.util.log.StdErrLog
selenium-hub    | 13:10:21.139 INFO [Hub.start] - Selenium Grid hub is up and running
selenium-hub    | 13:10:21.140 INFO [Hub.start] - Nodes should register to http://172.21.0.2:4444/grid/register/
selenium-hub    | 13:10:21.140 INFO [Hub.start] - Clients should connect to http://172.21.0.2:4444/wd/hub
selenium-hub    | 13:10:21.830 INFO [DefaultGridRegistry.add] - Registered a node http://172.21.0.3:5555
selenium-hub    | Trapped SIGTERM/SIGINT/x so shutting down supervisord...
selenium-hub    | 2019-04-01 13:10:23,972 WARN received SIGTERM indicating exit request
selenium-hub    | 2019-04-01 13:10:23,972 INFO waiting for selenium-hub to die
selenium-hub    | 2019-04-01 13:10:23,972 INFO stopped: selenium-hub (terminated by SIGTERM)
selenium-hub    | Shutdown complete              # <-- first run docker-compose ended with Error 143 for this process
selenium-hub    | 2019-04-01 13:10:42,358 INFO Included extra file "/etc/supervisor/conf.d/selenium-hub.conf" during parsing
selenium-hub    | 2019-04-01 13:10:42,359 INFO supervisord started with pid 7
selenium-hub    | 2019-04-01 13:10:43,363 INFO spawned: 'selenium-hub' with pid 10
selenium-hub    | Starting Selenium Hub with configuration:
selenium-hub    | 2019-04-01 13:10:43,373 INFO success: selenium-hub entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
selenium-hub    | {
selenium-hub    |   "host": "0.0.0.0",
selenium-hub    |   "port": 4444,
selenium-hub    |   "role": "hub",
selenium-hub    |   "maxSession": 5,
selenium-hub    |   "newSessionWaitTimeout": -1,
selenium-hub    |   "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
selenium-hub    |   "throwOnCapabilityNotPresent": true,
selenium-hub    |   "jettyMaxThreads": -1,
selenium-hub    |   "cleanUpCycle": 5000,
selenium-hub    |   "browserTimeout": 0,
selenium-hub    |   "timeout": 1800,
selenium-hub    |   "debug": true
selenium-hub    | }
selenium-hub    | 13:10:43.517 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
selenium-hub    | 13:10:43.572 INFO [GridLauncherV3.lambda$buildLaunchers$5] - Launching Selenium Grid hub on port 4444
selenium-hub    | 2019-04-01 13:10:43.942:INFO::main: Logging initialized @566ms to org.seleniumhq.jetty9.util.log.StdErrLog
selenium-hub    | 13:10:44.104 INFO [Hub.start] - Selenium Grid hub is up and running
selenium-hub    | 13:10:44.105 INFO [Hub.start] - Nodes should register to http://172.21.0.2:4444/grid/register/
selenium-hub    | 13:10:44.105 INFO [Hub.start] - Clients should connect to http://172.21.0.2:4444/wd/hub
selenium-hub    | 13:10:44.800 INFO [DefaultGridRegistry.add] - Registered a node http://172.21.0.3:5555             #  Boot ended here

selenium-hub    | 13:12:26.966 INFO [RequestHandler.process] - Got a request to create a new session: Capabilities {browserName: chrome, goog:chromeOptions: {}}
selenium-hub    | 13:12:26.969 INFO [TestSlot.getNewSession] - Trying to create a new session on test slot {server:CONFIG_UUID=48723485-be45-418e-8704-5646d0385d52, seleniumProtocol=WebDriver, browserName=chrome, maxInstances=1, platformName=LINUX, version=73.0.3683.86, applicationName=, platform=LINUX}             # First test run ended here

selenium-hub    | 13:14:19.228 INFO [RequestHandler.process] - Got a request to create a new session: Capabilities {browserName: chrome, goog:chromeOptions: {}}             # Second test run ended here

```

Log output from chrome:

```
chrome_1        | 2019-04-01 13:10:20,100 INFO Included extra file "/etc/supervisor/conf.d/selenium-debug.conf" during parsing
chrome_1        | 2019-04-01 13:10:20,100 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
chrome_1        | 2019-04-01 13:10:20,101 INFO supervisord started with pid 7
chrome_1        | 2019-04-01 13:10:21,103 INFO spawned: 'xvfb' with pid 10
chrome_1        | 2019-04-01 13:10:21,104 INFO spawned: 'fluxbox' with pid 11
chrome_1        | 2019-04-01 13:10:21,105 INFO spawned: 'vnc' with pid 12
chrome_1        | 2019-04-01 13:10:21,106 INFO spawned: 'selenium-node' with pid 13
chrome_1        | Connecting to the Hub using the host selenium-hub and port 4444
chrome_1        | 2019-04-01 13:10:21,141 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
chrome_1        | 2019-04-01 13:10:21,141 INFO success: fluxbox entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
chrome_1        | 2019-04-01 13:10:21,141 INFO success: vnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
chrome_1        | 2019-04-01 13:10:21,141 INFO success: selenium-node entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
chrome_1        | 13:10:21.291 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
chrome_1        | 13:10:21.353 INFO [GridLauncherV3.lambda$buildLaunchers$7] - Launching a Selenium Grid node on port 5555
chrome_1        | 2019-04-01 13:10:21.410:INFO::main: Logging initialized @266ms to org.seleniumhq.jetty9.util.log.StdErrLog
chrome_1        | 13:10:21.530 INFO [WebDriverServlet.<init>] - Initialising WebDriverServlet
chrome_1        | 13:10:21.577 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 5555
chrome_1        | 13:10:21.577 INFO [GridLauncherV3.lambda$buildLaunchers$7] - Selenium Grid node is up and ready to register to the hub
chrome_1        | 13:10:21.598 INFO [SelfRegisteringRemote$1.run] - Starting auto registration thread. Will try to register every 5000 ms.
chrome_1        | 13:10:21.799 INFO [SelfRegisteringRemote.registerToHub] - Registering the node to the hub: http://selenium-hub:4444/grid/register
chrome_1        | 13:10:21.830 INFO [SelfRegisteringRemote.registerToHub] - The node is registered to the hub and ready to use
chrome_1        | Trapped SIGTERM/SIGINT/x so shutting down supervisord...
chrome_1        | 2019-04-01 13:10:23,972 WARN received SIGTERM indicating exit request
chrome_1        | 2019-04-01 13:10:23,972 INFO waiting for selenium-node, xvfb, vnc, fluxbox to die
chrome_1        | 2019-04-01 13:10:23,972 INFO stopped: selenium-node (terminated by SIGTERM)
chrome_1        | 2019-04-01 13:10:23,972 INFO stopped: vnc (terminated by SIGTERM)
chrome_1        | 2019-04-01 13:10:24,974 INFO stopped: fluxbox (terminated by SIGTERM)
chrome_1        | 2019-04-01 13:10:24,976 INFO stopped: xvfb (terminated by SIGTERM)
chrome_1        | Shutdown complete             # <-- first run docker-compose ended with Error 143 for this process 
chrome_1        | 2019-04-01 13:10:42,875 INFO Included extra file "/etc/supervisor/conf.d/selenium-debug.conf" during parsing
chrome_1        | 2019-04-01 13:10:42,875 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
chrome_1        | 2019-04-01 13:10:42,876 INFO supervisord started with pid 7
chrome_1        | 2019-04-01 13:10:43,879 INFO spawned: 'xvfb' with pid 10
chrome_1        | 2019-04-01 13:10:43,880 INFO spawned: 'fluxbox' with pid 11
chrome_1        | 2019-04-01 13:10:43,882 INFO spawned: 'vnc' with pid 12
chrome_1        | 2019-04-01 13:10:43,883 INFO spawned: 'selenium-node' with pid 13
chrome_1        | Connecting to the Hub using the host selenium-hub and port 4444
chrome_1        | 2019-04-01 13:10:43,927 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
chrome_1        | 2019-04-01 13:10:43,928 INFO success: fluxbox entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
chrome_1        | 2019-04-01 13:10:43,928 INFO success: vnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
chrome_1        | 2019-04-01 13:10:43,928 INFO success: selenium-node entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
chrome_1        | 13:10:44.152 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
chrome_1        | 13:10:44.229 INFO [GridLauncherV3.lambda$buildLaunchers$7] - Launching a Selenium Grid node on port 5555
chrome_1        | 2019-04-01 13:10:44.303:INFO::main: Logging initialized @367ms to org.seleniumhq.jetty9.util.log.StdErrLog
chrome_1        | 13:10:44.454 INFO [WebDriverServlet.<init>] - Initialising WebDriverServlet
chrome_1        | 13:10:44.515 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 5555
chrome_1        | 13:10:44.515 INFO [GridLauncherV3.lambda$buildLaunchers$7] - Selenium Grid node is up and ready to register to the hub
chrome_1        | 13:10:44.545 INFO [SelfRegisteringRemote$1.run] - Starting auto registration thread. Will try to register every 5000 ms.
chrome_1        | 13:10:44.766 INFO [SelfRegisteringRemote.registerToHub] - Registering the node to the hub: http://selenium-hub:4444/grid/register
chrome_1        | 13:10:44.800 INFO [SelfRegisteringRemote.registerToHub] - The node is registered to the hub and ready to use             # <-- Boot end here

chrome_1        | 13:12:27.010 INFO [ActiveSessionFactory.apply] - Capabilities are: {
chrome_1        |   "browserName": "chrome",
chrome_1        |   "goog:chromeOptions": {
chrome_1        |   }
chrome_1        | }
chrome_1        | 13:12:27.011 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
chrome_1        | Starting ChromeDriver 73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72) on port 28270
chrome_1        | Only local connections are allowed.
chrome_1        | Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
chrome_1        | [1554124347.033][SEVERE]: bind() failed: Cannot assign requested address (99)
chrome_1        | 13:12:27.347 INFO [ProtocolHandshake.createSession] - Detected dialect: OSS
chrome_1        | 13:12:27.522 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session ebed1a987a284fcf14c98aa52da4691a (org.openqa.selenium.chrome.ChromeDriverService)             # <--First test ends here, no lines for the second test...
```

VNC First show a empty desktop, when the first test starts the chrome starts and show "data: ;" in the navbar. This the last life sign. After the test I did some quick test the chrome via VNC and is seams to work as expected.

wdio command: `node node_modules/.bin/wdio --baseUrl=https://our.online.dev.server -l trace ./test/config/suite.mocha.conf.js`

wdio output first run: 

```
Stdout:
2019-04-01T13:12:25.173Z DEBUG @wdio/utils:initialiseServices: initialise wdio service "selenium-standalone"
**** let's go ****
2019-04-01T13:12:25.215Z INFO @wdio/cli:Launcher: Run onPrepare hook
2019-04-01T13:12:26.534Z INFO @wdio/local-runner: Start worker 0-0 with arg: --baseUrl=https://our.online.dev.server,-l,trace,./test/config/suite.mocha.conf.js
[0-0] 2019-04-01T13:12:26.716Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2019-04-01T13:12:26.722Z DEBUG @wdio/utils:initialiseServices: initialise wdio service "selenium-standalone"
[0-0] 2019-04-01T13:12:26.905Z DEBUG @wdio/local-runner:utils: init remote session
2019-04-01T13:12:27.592Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
2019-04-01T13:12:27.593Z INFO @wdio/cli:Launcher: Run onComplete hook
**** that's it ****

Test Suites:	 0 passed, 1 failed, 1 total (100% completed)
Time:		 🕑  2.42s

```

wdio output second run:

```
 RUNNING  0-0 in chrome - /test/specs/user-login.spec.js

Stdout:
2019-04-01T13:14:17.638Z INFO @wdio/cli:Launcher: Run onPrepare hook
2019-04-01T13:14:18.841Z INFO @wdio/local-runner: Start worker 0-0 with arg: --baseUrl=https://our.online.dev.server,-l,trace,./test/config/suite.mocha.conf.js
[0-0] 2019-04-01T13:14:19.011Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2019-04-01T13:14:19.017Z DEBUG @wdio/utils:initialiseServices: initialise wdio service "selenium-standalone"
[0-0] 2019-04-01T13:14:19.192Z DEBUG @wdio/local-runner:utils: init remote session

Test Suites:	 0 passed, 1 total (0% completed)
Time:            🕑  36.22s^C

Ending WebDriver sessions gracefully ...
(press ctrl+c again to hard kill the runner)

```

## Expected behavior

The test running in the browser, the site do work and manually running them do work and "before" (sorry can't specify more than this year) the -gold driver did work.

## Test script reproducing this issue (when applicable)

The setup and test is based on WebdriverIO-v5 boilerplate some minor changes and adding of our test are done. 

## Environment

OS:  Linux, Ubuntu 18.04 and 16.04 (different machines)
Docker-Selenium image version: 3.141.59-gold and latest debug.
Also provide the docker image id 
-->
Docker version: 
Docker-Compose version (if applicable): 18.09.4
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well): Its above.

**Comment by egut** [comment] 2019-04-08 11:58
Any suggestion on what can be wrong?

**Comment by egut** [comment] 2019-04-10 08:16
Apparently I wasn't clear on what is failing. The failing part is that no test is executed at all and what I can tell this has nothing to to with the test, we event tried several different tests and the behavior is the same. The browser only show data:; in the navbar and nothing more happens.

No I haven't tried the webdriverIO chat,  I will try that too.

**Comment by diemol** [comment] 2019-04-24 08:47
Ok, I will close this for now since we do not have a reproduction scenario. Feel free to reopen when more information on how to reproduce is provided.

**Closed by diemol** 2019-04-24 08:47 UTC
Labels: R-awaiting-answer

**Comment by chenrui333** [comment] 2019-06-06 16:14
I am actually having similar issue:
`Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.`

It was working fine two days back.

```
16:02:11.274 INFO [SelfRegisteringRemote.registerToHub] - Registering the node to the hub: http://172.20.213.204:4444/grid/register
16:02:11.342 INFO [SelfRegisteringRemote.registerToHub] - The node is registered to the hub and ready to use
16:04:47.709 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "chrome",
  "chromeOptions": {
    "prefs": {
      "credentials_enable_service": false
    },
    "extensions": [
    ],
    "args": [
      "--disable-notifications"
    ]
  },
  "goog:chromeOptions": {
  },
  "javascriptEnabled": "True",
  "loggingPrefs": {
    "browser": "ALL",
    "performance": "ALL"
  },
  "screenResolution": "1280x1024",
  "version": "ANY"
}
16:04:47.711 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
Starting ChromeDriver 75.0.3770.8 (681f24ea911fe754973dda2fdc6d2a2e159dd300-refs/branch-heads/3770@{#40}) on port 23540
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
[1559837087.755][SEVERE]: bind() failed: Cannot assign requested address (99)
16:04:50.287 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
16:04:50.344 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session bcf79cec9225ac375c33d286b94ea424 (org.openqa.selenium.chrome.ChromeDriverService)
```

**Comment by diemol** [comment] 2019-06-06 20:09
and what changed since then @chenrui333 ?

**Comment by chenrui333** [comment] 2019-06-07 01:23
After I revert the docker-selenium image version, it works for me now. The error log is like above.

**Comment by diemol** [comment] 2019-06-14 06:07
The difference is that Chrome 75 works in W3C now, please double check your client to have it working properly in W3C mode.

If you have more questions, please send them to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
