### ISSUE TITLE
Selenium-hub: supervisor: couldn't setuid to 1000: Can't drop privilege as nonroot user

### ISSUE THREAD

**Issue by XerdosLoreskull** [SeleniumHQ/docker-selenium#807] opened 2018-10-10 06:39 UTC
Image(s):  
!> selenium/hub
Docker-Selenium Image Version(s):  
!> latest (3.14?)
Docker Version / OpenShift 
!> openshift v3.6.173.0.129
!> kubernetes v1.6.1+5115d708d7
OS: 
!> RHEL 7x

## Expected Behavior -
Image: selenium/hub:3.13
/opt/bin/entry_point.sh: line 6: /opt/selenium/config.json: Permission denied
starting selenium hub with configuration:
{
"host": "0.0.0.0",
"port": 4444,
"role": "hub",
"maxSession": 5,
"newSessionWaitTimeout": -1,
"capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
"throwOnCapabilityNotPresent": true,
"jettyMaxThreads": -1,
"cleanUpCycle": 5000,
"browserTimeout": 0,
"timeout": 30,
"debug": false
}
06:35:12.947 INFO [GridLauncherV3.launch] - Selenium build info: version: '3.13.0', revision: '2f0d292'
06:35:12.951 INFO [GridLauncherV3$2.launch] - Launching Selenium Grid hub on port 4444
2018-10-10 06:35:14.218:INFO::main: Logging initialized @2805ms to org.seleniumhq.jetty9.util.log.StdErrLog
06:35:15.081 INFO [Hub.start] - Selenium Grid hub is up and running
06:35:15.082 INFO [Hub.start] - Nodes should register to http://10.221.41.143:4444/grid/register/
06:35:15.082 INFO [Hub.start] - Clients should connect to http://10.221.41.143:4444/wd/hub

## Actual Behavior -
**From OpenShift log:**
2018-10-10 06:25:43,062 WARN Included extra file "/etc/supervisor/conf.d/selenium-hub.conf" during parsing
2018-10-10 06:25:43,067 INFO supervisord started with pid 7
2018-10-10 06:25:44,069 INFO spawned: 'selenium-hub' with pid 10
supervisor: couldn't setuid to 1000: Can't drop privilege as nonroot user
supervisor: child process was not spawned
2018-10-10 06:25:44,071 INFO success: selenium-hub entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2018-10-10 06:25:44,072 INFO exited: selenium-hub (exit status 127; not expected)

## Steps to reproduce -
Run selenium hub onOpenShift according to : https://github.com/ddavison/selenium-openshift-templates

**Comment by diemol** [comment] 2018-10-10 07:10
Duplicate of #802

**Closed by diemol** 2018-10-10 07:10 UTC
