### ISSUE TITLE
[🐛 Bug]: Unable to parse: 400 Bad Request; org.openqa.selenium.json.JsonException: Expected to read a START_MAP but instead have: NUMBER. Last 0 characters read:

### ISSUE THREAD

**Issue by 95nagyd** [SeleniumHQ/docker-selenium#1662] opened 2022-08-22 21:56 UTC
### What happened?

I am running punning parallel test classes with maven surefire-testng (3.0.0-M7)
```
<threadCount>5</threadCount>
<parallel>classes</parallel>
```
I am using selenium 4.4.0; selenium/hub:4.4.0, selenium/node-chrome:4.4.0
When I run test cases on selenium grid (since 4.1.4 it is happening on 4.4.0 too), I receive random 
`org.openqa.selenium.json.JsonException: Unable to parse: 400 Bad Request
`
`Caused by: org.openqa.selenium.json.JsonException: Expected to read a START_MAP but instead have: NUMBER. Last 0 characters read: `

It happens completely random, from 50 test cases about 1-4 usually fails because of this.
I saw a similar github issue(https://github.com/SeleniumHQ/docker-selenium/issues/1507), but I believe that is something different (or not?) than this.

The exception occurs when test runs a javascript command with `JavascriptExecutor`. This function checks if there are any pending xhr. I tried to handle it by retrying if `org.openqa.selenium.json.JsonException` thrown.
The retry handles the javascript execution part, but then the first `RemoteWebElement ` 
`org.openqa.selenium.remote.RemoteWebElement.isDisplayed(RemoteWebElement.java:313)`

or `RemoteWebDriver` reference will throw the same exception with exactly the same messages.
`at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:380)`
`at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:372)`

Sadly I can not give any steps to reproduce. I never faces such issue on any other projects, only with this one.
Even tried similar steps test case on Youtube, but 3 hours of running 5 parallel nodes didn't gave this exception.
I hope it is just some misconfiguration or I messed up something and someone can help me out with this.

### Command used to start Selenium Grid with Docker

```shell
version: "3"
services:

  selenium-hub:
    image: selenium/hub:4.4.0
    container_name: selenium-hub
    environment:
      - GRID_MAX_SESSIONS=30
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 4G
      
  chrome:
    image: selenium/node-chrome:4.4.0
    shm_size: 1gb
    depends_on:
      - selenium-hub
    environment:
      - SE_NODE_MAX_SESSIONS=1
      - TZ=Europe/Budapest
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_OPTS=--log-level FINE
      - SE_NODE_SESSION_TIMEOUT=1800
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - VNC_NO_PASSWORD=1
      - VNC_VIEW_ONLY=1
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
```

### Relevant log output

```shell
org.openqa.selenium.json.JsonException: Unable to parse: 400 Bad Request
	at org.openqa.selenium.json.Json.toType(Json.java:57)
	at org.openqa.selenium.json.Json.toType(Json.java:50)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:99)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
	at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:547)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:481)
	at helpers.CustomWaitConditions$2.apply(CustomWaitConditions.java:61)
	at helpers.CustomWaitConditions$2.apply(CustomWaitConditions.java:55)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
	at helpers.global.Functions.waitUntilLoadingSpinnerIsNotPresent(Functions.java:89)
	at pages.MenuPage.chooseMenu(MenuPage.java:36)
	at testCases.JsonExceptionTest.badRequest(JsonExceptionTest.java:593)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.openqa.selenium.json.JsonException: Expected to read a START_MAP but instead have: NUMBER. Last 0 characters read: 
Build info: version: '4.4.0', revision: 'e5c75ed026a'
System info: host: 'jenkins-masterautotest-chrome', ip: '**.**.*.**', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-122-generic', java.version: '1.8.0_302'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.json.JsonInput.expect(JsonInput.java:307)
	at org.openqa.selenium.json.JsonInput.beginObject(JsonInput.java:229)
	at org.openqa.selenium.json.MapCoercer.lambda$apply$1(MapCoercer.java:64)
	at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:145)
	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:127)
	at org.openqa.selenium.json.Json.toType(Json.java:71)
	at org.openqa.selenium.json.Json.toType(Json.java:55)
	... 28 more
... Removed 12 stack frames
```

### Operating System

It has happened on both Win10 and Ubuntu

### Docker Selenium version (tag)

4.4.0-20220812

**Comment by diemol** [comment] 2022-08-31 08:15
Duplicate of #1507

**Closed as completed by diemol** 2022-08-31 08:15 UTC

**Comment by kislov99** [comment] 2022-09-12 01:48
Same problem on selenium/standalone-chrome:4.4.0-20220831

```
Expected to read a START_MAP but instead have: END. Last 0 characters read: 
Build info: version: '4.4.0', revision: 'e5c75ed026a'
System info: host: '396543fbb8a1', ip: '172.17.0.7', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-957.el7.x86_64', java.version: '11.0.16'
Driver info: driver.version: unknown
