### ISSUE TITLE
Chrome-node: supervisor: couldn't setuid to 1000: Can't drop privilege as nonroot user

### ISSUE THREAD

**Issue by XerdosLoreskull** [SeleniumHQ/docker-selenium#808] opened 2018-10-10 07:09 UTC
Image(s):  
!> selenium/node-chrome-debug:latest
Docker-Selenium Image Version(s):
!> latest (3.14?)
Docker Version / OpenShift
!> openshift v3.6.173.0.129
!> kubernetes v1.6.1+5115d708d7
OS:
!> RHEL 7x

## Expected Behavior -
selenium/node-chrome-debug:3.13
/opt/bin/entry_point.sh: line 6: /opt/selenium/config.json: Permission denied
appending selenium options: -debug
Waiting xvfb...
Can't create directory //.fluxbox
Failed to load database: //.fluxbox/init
Failed to load database://.fluxbox/init
Retrying with: /etc/X11/fluxbox/init
Failed to read: session.ignoreBorder
Setting default value
Failed to read: session.forcePseudoTransparency
Setting default value
Failed to read: session.colorsPerChannel
Setting default value
Failed to read: session.doubleClickInterval
Setting default value
Failed to read: session.tabPadding
Setting default value
Failed to read: session.styleOverlay
Setting default value
Failed to read: session.slitlistFile
Setting default value
Failed to read: session.appsFile
Setting default value
Failed to read: session.tabsAttachArea
Setting default value
Failed to read: session.cacheLife
Setting default value
Failed to read: session.cacheMax
Setting default value
Failed to read: session.autoRaiseDelay
Setting default value
10/10/2018 07:06:44 passing arg to libvncserver: -rfbport
10/10/2018 07:06:44 passing arg to libvncserver: 5900
Enter VNC password: stty: 'standard input': Inappropriate ioctl for device
fgets: No such file or directory
stty: 'standard input': Inappropriate ioctl for device
x11vnc -usepw: could not find a password to use.
Failed to read: session.screen0.opaqueMove
Setting default value
Failed to read: session.screen0.fullMaximization
Setting default value
Failed to read: session.screen0.maxIgnoreIncrement
Setting default value
Failed to read: session.screen0.maxDisableMove
Setting default value
Failed to read: session.screen0.maxDisableResize
Setting default value
Failed to read: session.screen0.workspacewarping
Setting default value
Failed to read: session.screen0.showwindowposition
Setting default value
Failed to read: session.screen0.autoRaise
Setting default value
Failed to read: session.screen0.clickRaises
Setting default value
Failed to read: session.screen0.defaultDeco
Setting default value
Failed to read: session.screen0.tab.placement
Setting default value
Failed to read: session.screen0.windowMenu
Setting default value
Failed to read: session.screen0.noFocusWhileTypingDelay
Setting default value
Failed to read: session.screen0.workspaces
Setting default value
Failed to read: session.screen0.edgeSnapThreshold
Setting default value
Failed to read: session.screen0.window.focus.alpha
Setting default value
Failed to read: session.screen0.window.unfocus.alpha
Setting default value
Failed to read: session.screen0.menu.alpha
Setting default value
Failed to read: session.screen0.menuDelay
Setting default value
Failed to read: session.screen0.tab.width
Setting default value
Failed to read: session.screen0.tooltipDelay
Setting default value
Failed to read: session.screen0.allowRemoteActions
Setting default value
Failed to read: session.screen0.clientMenu.usePixmap
Setting default value
Failed to read: session.screen0.tabs.usePixmap
Setting default value
Failed to read: session.screen0.tabs.maxOver
Setting default value
Failed to read: session.screen0.tabs.intitlebar
Setting default value
Failed to read: session.screen0.focusModel
Setting default value
Failed to read: session.screen0.tabFocusModel
Setting default value
Failed to read: session.screen0.focusNewWindows
Setting default value
Failed to read: session.screen0.focusSameHead
Setting default value
Failed to read: session.screen0.rowPlacementDirection
Setting default value
Failed to read: session.screen0.colPlacementDirection
Setting default value
Failed to read: session.screen0.windowPlacement
Setting default value
Failed to load database://.fluxbox/init
Retrying with: /etc/X11/fluxbox/init
Failed to read: session.ignoreBorder
Setting default value
Failed to read: session.forcePseudoTransparency
Setting default value
Failed to read: session.colorsPerChannel
Setting default value
Failed to read: session.doubleClickInterval
Setting default value
Failed to read: session.tabPadding
Setting default value
Failed to read: session.styleOverlay
Setting default value
Failed to read: session.slitlistFile
Setting default value
Failed to read: session.appsFile
Setting default value
Failed to read: session.tabsAttachArea
Setting default value
Failed to read: session.cacheLife
Setting default value
Failed to read: session.cacheMax
Setting default value
Failed to read: session.autoRaiseDelay
Setting default value
Failed to read: session.screen0.opaqueMove
Setting default value
Failed to read: session.screen0.fullMaximization
Setting default value
Failed to read: session.screen0.maxIgnoreIncrement
Setting default value
Failed to read: session.screen0.maxDisableMove
Setting default value
Failed to read: session.screen0.maxDisableResize
Setting default value
Failed to read: session.screen0.workspacewarping
Setting default value
Failed to read: session.screen0.showwindowposition
Setting default value
Failed to read: session.screen0.autoRaise
Setting default value
Failed to read: session.screen0.clickRaises
Setting default value
Failed to read: session.screen0.defaultDeco
Setting default value
Failed to read: session.screen0.tab.placement
Setting default value
Failed to read: session.screen0.windowMenu
Setting default value
Failed to read: session.screen0.noFocusWhileTypingDelay
Setting default value
Failed to read: session.screen0.workspaces
Setting default value
Failed to read: session.screen0.edgeSnapThreshold
Setting default value
Failed to read: session.screen0.window.focus.alpha
Setting default value
Failed to read: session.screen0.window.unfocus.alpha
Setting default value
Failed to read: session.screen0.menu.alpha
Setting default value
Failed to read: session.screen0.menuDelay
Setting default value
Failed to read: session.screen0.tab.width
Setting default value
Failed to read: session.screen0.tooltipDelay
Setting default value
Failed to read: session.screen0.allowRemoteActions
Setting default value
Failed to read: session.screen0.clientMenu.usePixmap
Setting default value
Failed to read: session.screen0.tabs.usePixmap
Setting default value
Failed to read: session.screen0.tabs.maxOver
Setting default value
Failed to read: session.screen0.tabs.intitlebar
Setting default value
Failed to read: session.screen0.focusModel
Setting default value
Failed to read: session.screen0.tabFocusModel
Setting default value
Failed to read: session.screen0.focusNewWindows
Setting default value
Failed to read: session.screen0.focusSameHead
Setting default value
Failed to read: session.screen0.rowPlacementDirection
Setting default value
Failed to read: session.screen0.colPlacementDirection
Setting default value
Failed to read: session.screen0.windowPlacement
Setting default value
Failed to read: session.screen0.slit.acceptKdeDockapps
Setting default value
Failed to read: session.screen0.slit.autoHide
Setting default value
Failed to read: session.screen0.slit.maxOver
Setting default value
Failed to read: session.screen0.slit.placement
Setting default value
Failed to read: session.screen0.slit.alpha
Setting default value
Failed to read: session.screen0.slit.onhead
Setting default value
Failed to read: session.screen0.slit.layer
Setting default value
failed to open apps file
whoami: cannot find name for user ID 1130310000
mkdir: cannot create directory ‘//.fluxbox’Failed to read: session.screen0.toolbar.autoHide
Setting default value
Failed to read: session.screen0.toolbar.maxOver
Setting default value
Failed to read: session.screen0.toolbar.visible
Setting default value
Failed to read: session.screen0.toolbar.alpha
Setting default value
Failed to read: session.screen0.toolbar.layer
Setting default value
Failed to read: session.screen0.toolbar.onhead
Setting default value
Failed to read: session.screen0.toolbar.placement
Setting default value
Failed to read: session.screen0.toolbar.height
Setting default value: Permission denied

Failed to read: session.screen0.iconbar.mode
Setting default value
Failed to read: session.screen0.iconbar.alignment
Setting default value
Failed to read: session.screen0.iconbar.iconWidth
Setting default value
Failed to read: session.screen0.iconbar.iconTextPadding
Setting default value
Failed to read: session.screen0.iconbar.usePixmap
Setting default value
touch: cannot touch '//.fluxbox/lastwallpaper': No such file or directory
feh WARNING: Can't write to //.fehbg
/usr/bin/fbsetbg: 159: /usr/bin/fbsetbg: cannot create //.fluxbox/lastwallpaper.tmp: Directory nonexistent
mv: cannot stat '//.fluxbox/lastwallpaper.tmp': No such file or directory
/usr/bin/fbsetbg: 168: /usr/bin/fbsetbg: cannot create //.fluxbox/lastwallpaper: Directory nonexistent
07:06:45.841 INFO [GridLauncherV3.launch] - Selenium build info: version: '3.13.0', revision: '2f0d292'
07:06:45.845 INFO [GridLauncherV3$3.launch] - Launching a Selenium Grid node on port 5555
2018-10-10 07:06:46.184:INFO::main: Logging initialized @1779ms to org.seleniumhq.jetty9.util.log.StdErrLog
07:06:46.501 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 5555
07:06:46.501 INFO [GridLauncherV3$3.launch] - Selenium Grid node is up and ready to register to the hub
07:06:46.595 DEBUG [SelfRegisteringRemote.startRegistrationProcess] - Using the json request : {
  "class": "org.openqa.grid.common.RegistrationRequest",
  "configuration": {
    "browserTimeout": 0,
    "capabilities": [
      {
        "applicationName": "",
        "browserName": "chrome",
        "maxInstances": 1,
        "platform": "LINUX",
        "platformName": "LINUX",
        "seleniumProtocol": "WebDriver",
        "server:CONFIG_UUID": "d2ec7b79-6352-49dc-942d-b5f58ca2a807",
        "version": "68.0.3440.84"
      }
    ],
    "custom": {
    },
    "debug": false,
    "downPollingLimit": 2,
    "enablePlatformVerification": true,
    "host": "10.221.41.44",
    "hub": "http:\u002f\u002fselenium-hub:4444\u002fgrid\u002fregister",
    "id": "http:\u002f\u002f10.221.41.44:5555",
    "maxSession": 1,
    "nodePolling": 5000,
    "nodeStatusCheckTimeout": 5000,
    "port": 5555,
    "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
    "register": true,
    "registerCycle": 5000,
    "remoteHost": "http:\u002f\u002f10.221.41.44:5555",
    "role": "node",
    "servlets": [
    ],
    "timeout": 1800,
    "unregisterIfStillDownAfter": 60000,
    "withoutServlets": [
    ]
  },
  "description": null,
  "name": null
}
07:06:46.596 INFO [SelfRegisteringRemote$1.run] - Starting auto registration thread. Will try to register every 5000 ms.
07:06:46.596 INFO [SelfRegisteringRemote.registerToHub] - Registering the node to the hub: http://selenium-hub:4444/grid/register
07:06:47.073 DEBUG [SelfRegisteringRemote.registerToHub] - Updating the node configuration from the hub
07:06:47.127 DEBUG [SelfRegisteringRemote.registerToHub] - Hub configuration: {
  "browserTimeout": 0,
  "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
  "cleanUpCycle": 5000,
  "custom": {
  },
  "debug": false,
  "host": "10.221.41.143",
  "jettyMaxThreads": -1,
  "maxSession": 5,
  "newSessionWaitTimeout": -1,
  "port": 4444,
  "registry": "org.openqa.grid.internal.DefaultGridRegistry",
  "role": "hub",
  "servlets": [
  ],
  "throwOnCapabilityNotPresent": true,
  "timeout": 30,
  "withoutServlets": [
  ]
}
07:06:47.128 DEBUG [SelfRegisteringRemote.registerToHub] - Updated node configuration: {
  "browserTimeout": 0,
  "capabilities": [
    {
      "applicationName": "",
      "browserName": "chrome",
      "maxInstances": 1,
      "platform": "LINUX",
      "platformName": "LINUX",
      "seleniumProtocol": "WebDriver",
      "server:CONFIG_UUID": "d2ec7b79-6352-49dc-942d-b5f58ca2a807",
      "version": "68.0.3440.84"
    }
  ],
  "custom": {
  },
  "debug": false,
  "downPollingLimit": 2,
  "enablePlatformVerification": true,
  "host": "10.221.41.44",
  "hub": "http:\u002f\u002fselenium-hub:4444\u002fgrid\u002fregister",
  "id": "http:\u002f\u002f10.221.41.44:5555",
  "maxSession": 1,
  "nodePolling": 5000,
  "nodeStatusCheckTimeout": 5000,
  "port": 5555,
  "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
  "register": true,
  "registerCycle": 5000,
  "remoteHost": "http:\u002f\u002f10.221.41.44:5555",
  "role": "node",
  "servlets": [
  ],
  "timeout": 30,
  "unregisterIfStillDownAfter": 60000,
  "withoutServlets": [
  ]
}
07:06:47.128 INFO [SelfRegisteringRemote.registerToHub] - The node is registered to the hub and ready to us

## Actual Behavior -
**From OpenShift log:**
2018-10-10 06:43:11,048 WARN Included extra file "/etc/supervisor/conf.d/selenium-debug.conf" during parsing
2018-10-10 06:43:11,048 WARN Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
2018-10-10 06:43:11,055 INFO supervisord started with pid 7
2018-10-10 06:43:12,057 INFO spawned: 'xvfb' with pid 10
2018-10-10 06:43:12,059 INFO spawned: 'fluxbox' with pid 11
2018-10-10 06:43:12,060 INFO spawned: 'vnc' with pid 12
2018-10-10 06:43:12,061 INFO spawned: 'selenium-node' with pid 13
2018-10-10 06:43:12,062 INFO exited: xvfb (exit status 127; not expected)
2018-10-10 06:43:12,062 INFO exited: fluxbox (exit status 127; not expected)
2018-10-10 06:43:12,062 INFO success: vnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2018-10-10 06:43:12,062 INFO success: selenium-node entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2018-10-10 06:43:12,063 INFO exited: vnc (exit status 127; not expected)
supervisor: couldn't setuid to 1000: Can't drop privilege as nonroot user
supervisor: child process was not spawned
2018-10-10 06:43:12,064 INFO exited: selenium-node (exit status 127; not expected)

## Steps to reproduce -
Run selenium hub onOpenShift according to : https://github.com/ddavison/selenium-openshift-templates

**Comment by diemol** [comment] 2018-10-10 07:11
Duplicate of #802

**Closed by diemol** 2018-10-10 07:11 UTC
