### ISSUE TITLE
Grid 4 Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500

### ISSUE THREAD

**Issue by rajgopalrajesh** [SeleniumHQ/docker-selenium#1305] opened 2021-06-01 18:03 UTC
## 🐛 Bug Report

running docker docker-compose-v3.yml
 while connecting to hub and running scripts getting error

Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: unknown error: MSEdge failed to start: crashed.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from msedge location \u002fusr\u002fbin\u002fmicrosoft-edge is no longer running, so MSEdgeDriver is assuming that MSEdge has crashed.)

## To Reproduce

Steps to reproduce the behavior (including the command to start the containers):

## Expected behavior

scripts has to run on docker

## Test script reproducing this issue (when applicable)

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links are also OK.
public WebDriver remoteEdgeDriver(){
        EdgeOptions options = new EdgeOptions();
        options.setCapability("platform", Platform.ANY);
        return new RemoteWebDriver(this.url, options);
    }

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS:  win 10
Docker-Selenium image version: 
Docker version: version: "3"
Docker-Compose version (if applicable):version: "3"
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well): docker-compose  docker-compose-v3.yml up
![error](https://user-images.githubusercontent.com/16475965/120370001-b1478400-c331-11eb-9b51-73d170e09340.PNG)
docker-compose-v3.yml

**Comment by diemol** [comment] 2021-06-01 18:07
What command are you using to start the containers? What operating system are you using? (All these were questions in the template 😢)

**Comment by rajgopalrajesh** [comment] 2021-06-01 18:10
> What command are you using to start the containers? What operating system are you using? (All these were questions in the template 😢)

added in the issue

**Comment by diemol** [comment] 2021-06-01 18:13
Then it is a duplicate of this [issue](https://github.com/SeleniumHQ/docker-selenium/issues/1267#issuecomment-830448417), please check the comment (replace `/dev/shm` for `shm_size: '2gb'`)

**Closed as completed by diemol** 2021-06-01 18:13 UTC
Labels: R-awaiting-answer

**Comment by rajgopalrajesh** [comment] 2021-06-01 18:46
> Then it is a duplicate of this [issue](https://github.com/SeleniumHQ/docker-selenium/issues/1267#issuecomment-830448417), please check the comment (replace `/dev/shm` for `shm_size: '2gb'`)
below is compose file stil getting same error

# To execute this docker-compose yml file use `docker-compose -f docker-compose-v3-full-grid.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v3-full-grid.yml down`
version: "3"
services:
  selenium-event-bus:
    image: selenium/event-bus:4.0.0-beta-4-prerelease-20210527
    container_name: selenium-event-bus
    ports:
      - "4442:4442"
      - "4443:4443"
      - "5557:5557"

  selenium-sessions:
    image: selenium/sessions:4.0.0-beta-4-prerelease-20210527
    container_name: selenium-sessions
    ports:
      - "5556:5556"
    depends_on:
      - selenium-event-bus
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-session-queue:
    image: selenium/session-queue:4.0.0-beta-4-prerelease-20210527
    container_name: selenium-session-queue
    ports:
      - "5559:5559"
    depends_on:
      - selenium-event-bus
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-distributor:
    image: selenium/distributor:4.0.0-beta-4-prerelease-20210527
    container_name: selenium-distributor
    ports:
      - "5553:5553"
    depends_on:
      - selenium-event-bus
      - selenium-sessions
      - selenium-session-queue
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_SESSIONS_MAP_HOST=selenium-sessions
      - SE_SESSIONS_MAP_PORT=5556
      - SE_SESSION_QUEUE_HOST=selenium-session-queue
      - SE_SESSION_QUEUE_PORT=5559

  selenium-router:
    image: selenium/router:4.0.0-beta-4-prerelease-20210527
    container_name: selenium-router
    ports:
      - "4444:4444"
    depends_on:
      - selenium-distributor
      - selenium-sessions
      - selenium-session-queue
    environment:
      - SE_DISTRIBUTOR_HOST=selenium-distributor
      - SE_DISTRIBUTOR_PORT=5553
      - SE_SESSIONS_MAP_HOST=selenium-sessions
      - SE_SESSIONS_MAP_PORT=5556
      - SE_SESSION_QUEUE_HOST=selenium-session-queue
      - SE_SESSION_QUEUE_PORT=5559

  chrome:
    image: selenium/node-chrome:4.0.0-beta-4-prerelease-20210527
    depends_on:
      - selenium-event-bus
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    shm_size: '2gb'   
    ports:
      - "6900:5900"

  edge:
    image: selenium/node-edge:4.0.0-beta-4-prerelease-20210527
    depends_on:
      - selenium-event-bus
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    shm_size: '2gb'  
    ports:
      - "6901:5900"

  firefox:
    image: selenium/node-firefox:4.0.0-beta-4-prerelease-20210527
    depends_on:
      - selenium-event-bus
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    shm_size: '2gb'  
    ports:
      - "6902:5900"
